### ISSUE TITLE
Porting Invisimail problem

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#100]
I have made a start on porting Invisimail because I need to provide obfustication of email addresses.

However, I have hit a problem because of changes in the core filters module.
In Backdrop filter.admin.inc at line 255 has
``
$settings_form = $function($form, $form_state, $filters[$name], $format);
``

Whereas in Drupal the equivalent line 274 has two extra parameters
``
$settings_form = $function($form, $form_state, $filters[$name], $format, $defaults, $filters);
``

I have also tried porting the Spamspan module and hit exactly the same issue.

**Comment by docwilmot** [comment]
https://github.com/backdrop/backdrop-issues/issues/172#issuecomment-64295199 might be some help. As noted there, I hit the same issue.

Post what exactly the problem you're facing if this doesn't help.

**Comment by quicksketch** [comment]
Thanks @docwilmot! Right on the button. $defaults are merged into the $format->settings and $filters are now in $format->filters. Looks like we don't have a changelog for that one yet, let's continue in https://github.com/backdrop/backdrop-issues/issues/172.

**Comment by Graham-72** [comment]
Thanks @docwilmot and @quicksketch .
Port now completed.

**Comment by quicksketch** [comment]
Woot!
