### ISSUE TITLE
Port of Views Send

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#102]
I am porting 'Views Send' in order to be able to do mass mailing with Views.

At the moment my repo is at https://github.com/Graham-72/views_send.

**Comment by quicksketch** [comment]
Excellent, thanks again @Graham-72!

**Comment by Graham-72** [comment]
After diverting my attention to the Date and the Feed Import modules, I am now back looking at Views Send, which I hope to get working in the next two or three weeks, because I need it.

**Comment by jenlampton** [comment]
Not sure why this issue was opened here? Closing issue.
