### ISSUE TITLE
Best practices for READMEs

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#106]
A couple of issues arose last few days:
- In [this issue](https://github.com/backdrop-ops/backdropcms.org/pull/88) in [the video](https://drive.google.com/file/d/0BzY54DXqV6bNdGxhcW1FZmFNX00/view?usp=sharing) (at the 2:00 minute mark) @wesruv recommends best practices since we use READMEs to pull info from GitHUb to build our module displays on BAckdropCMS.org. Ugly READMEs therefore cause ugly module page, we cant have that.
- In Project Browser, which we hope to get into core one day, I'm finding the same issue, that displying summaries of projects from truncated READMEs give very variable results.
- And [in another discussion](https://github.com/backdrop-ops/contrib/issues/104#issuecomment-134503694) @Graham-72 just reminded me that we had originally suggested that more detailed project help etc should go in the GitHub wikis per repo.

So I suggest we do the following
- Agree on a modified README format that includes a word-limit-recommended summary as the first item, say 300 words for example, for consumption by both the module page and the Project Browser.
- Agree to limit the detail in READMEs to the minimum required for installation and getting started and move all really complex stuff to wikis.Like this epistle here https://github.com/backdrop-contrib/setup (by me :disappointed: )

**Comment by quicksketch** [comment]
I think that all sounds good. Here's our current example README.md:

https://github.com/backdrop-ops/contrib/blob/master/examples/README.md

I have a feeling that once we make project pages public on BackdropCMS.org, authors will pay more attention to the parsed version of their READMEs than they do currently.

In addition to the README, we also have project descriptions on GitHub that we're not utilizing effectively. Take a look at https://github.com/backdrop-contrib/ and read through the summaries. Some are effective like the one for API module, "Generates HTML-formatted pages of documentation from PHPdoc." However, many just use the description to say they are a port of another module, e.g. " BackdropCMS port of the Webform Remote Post module for Drupal 7"

If we got our summaries cleaned up, that could be an additional data item we could store on BackdropCMS.org and use for summaries there as well. But I'm not sure that is going to be more or less effective than the first paragraph of the READMEs.

**Comment by jenlampton** [comment]
I think it would be useful if someone were to create issues for the contrib projects that don't have a readme that conforms to standards, since I expect most of them were ported directly from Drupal and may not even know there is a problem.  This could be a great novice task for a sprint!

**Comment by jenlampton** [comment]
I think we should stick with using the first paragraph of the readme's and try to enforce keeping those clean. I created a handful of issues against the worst offenders I could see on the Backdrop CMS [modules page](https://backdropcms.org/modules) and it looks like we're in a lot better shape than we were before.

**Comment by jenlampton** [comment]
I just pushed a commit to the example readme that satisfies @docwilmot's suggestions. Sorry it took so long to get this resolved :)
