### ISSUE TITLE
Updating ported modules

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#108]
Have we any guidance on how a Backdrop contributed module should be updated when its Drupal source is updated? I am wondering about preserving the history of the changes.

**Comment by Graham-72** [comment]
An answer to my own question, I have found this article 
"How to Maintain Contrib Modules for Drupal and Backdrop at the Same Time - Part 3" at
https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-3

**Comment by quicksketch** [comment]
Yep! It's one of the reasons why we maintain the D7 history. As long as the base source is the same, you can add the drupal.org source code as a remote and then do a git pull to merge in the new changes. Though if the parent source is drastically changed, it can be tough to merge. But for small things and bug fixes, it actually works really well. Be sure to do a replacement "drupal" with "backdrop" after any merges of new code though. Thanks as always @Graham-72!
