### ISSUE TITLE
working on backup_migrate module port

### ISSUE THREAD

**Issue by quackers8me** [backdrop-ops/contrib#11]
There was a comment somewhere suggesting to check the backdrop-issues to find out if someone was working on a port but I couldn't find any. I would suggest rather that it is more appropriate to post here. Would that be ok?

I would like to post that I am working on the backup_migrate module and will submit for review once complete.

**Comment by quicksketch** [comment]
Hi @quackers8me! I think this is a great place to start. :smile:

I'll communicate this to anyone else I see who's porting modules. This is a good place to announce it.

**Comment by quicksketch** [comment]
Hi @quackers8me, I was looking through your repo and it looks like a great start! Would you like to get it transferred over to the central repo?

- [x] README.md (with maintainers and license)
- [x] LICENSE.txt
- [x] Maintained Drupal 7 history

Nice job! I'd like to get it over to guarantee nobody starts overlapping work. Thanks!

**Comment by quackers8me** [comment]
Hi @quicksketch, sure that would be great. I've been bogged down with other things so I haven't gotten back to it yet. 
Things that aren't done yet are:
- stdClass items have been moved to entity_create but they had not been tested to see if it worked (may not be declared properly).
- system_settings_form conversion: from your suggestion I found that yes indeed the 4 functions all call items that can be saved separately to the config file. I created a scratchpad of those functions here that need to be saved:
https://github.com/quackers8me/my-php-scratchpad/blob/master/nodesquirrel_working_file.php
- fix an issue with saving your private files directory. It didn't seem to be pulling from the config file for some reason. If you manually put in a full path you can run a backup successfully.
- full suite of testing to be done.

How do I go about and transferring it?

Thanks,
Jason

**Comment by quicksketch** [comment]
If you agree to the contrib author agreement for the record, I'll send you an invite. Then you can transfer the repository using the Settings tab in the right sidebar on your repository to transfer it (under the "Danger zone") to `backdrop-contrib`. Thanks!

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must agree to license your contributions as GPLv2 or later.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.  The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explaination.    

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later. 

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc) 
  1. A list of the current maintainers for the Backdrop project
  1. A list of the past maintainers for the Backdrop or Drupal project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by quackers8me** [comment]
I agree to the agreement. 
Thanks again

**Comment by quicksketch** [comment]
Super! Invite sent. :smile:

**Comment by quackers8me** [comment]
It says that it added access to the Owner's team but gives an option to add access to the Author team too. Do I enable that option?

**Comment by quicksketch** [comment]
Huh, that's weird. You should be a member of the "Author" team. The Owner team is responsible for billing and such, so you shouldn't be a member of that group. Perhaps it's listing you as an Owner of your own account but an Author of the Backdrop Contrib group?

**Comment by quackers8me** [comment]
The option is: Authors - Developers who can push to all contrib module repositories.

**Comment by quicksketch** [comment]
Yes, that's the one you want. :+1:

**Comment by quackers8me** [comment]
Oh poop! I accidentally unchecked it before transfer. I assume the owners group can re-check that option? Sorry about that.

**Comment by quicksketch** [comment]
I think you're good. You're still in the listing of Authors that I can see. Can you try transferring your repository and see if you're allowed to move it into the backdrop-contrib group?

**Comment by quackers8me** [comment]
Yes, I moved it now

**Comment by quicksketch** [comment]
woot!
