### ISSUE TITLE
Backdrop Contrib Group Application

### ISSUE THREAD

**Issue by danielrose28** [backdrop-ops/contrib#111]
Hi, I am applying in order to help co-maintain the YouTube and Socialfield projects with Jen. I really enjoy the Backdrop project and would love to start trying to help out and learn. Thanks for your time. I look forward to hopefully start helping out soon and become part of the Backdrop community. :)

Thanks,
Dan

**Comment by jenlampton** [comment]
I'd also like to be @danielrose28's recommendation. I would love to have some help maintaining YouTube and Socialfield modules!

**Comment by quicksketch** [comment]
Great, thanks @jenlampton. Welcome @danielrose28! Our policy for contributing-only (and not new projects) is that you "reapply" when you create your first module (whether entirely new or ported from D7). Then we can go through the normal review process that contributors normally go through. But in the mean time, getting more contributors on existing projects is greatly appreciated! I've sent an invite to you. As the first order of business, please commit to the README.md for YouTube and Socialfield projects to add yourself as a maintainer to those projects. Thanks!

**Comment by danielrose28** [comment]
Awesome! Thank you. I'm happy to help out.

**Comment by quicksketch** [comment]
@danielrose28++
