### ISSUE TITLE
Porting of Google Calendar API and Google Auth

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#113]
I would like to be able to use the Google Calendar API from within Backdrop and I am proposing to try porting the GCal module. This needs the Google Auth (GAuth) module and I have made a start with that, now available for testing at https://github.com/backdrop-contrib/gauth. 

If all goes well (it sometimes does :smile:) GCal will follow shortly.

**Comment by docwilmot** [comment]
For a brief moment I thought you were porting [Calendar module](https://www.drupal.org/project/calendar). Any plans for that, seeing as you did most of Date already? Think I might need it soon.

**Comment by Graham-72** [comment]
@docwilmot yes, we ought to have a BD port of Calendar but I have not planned to tackle it in the near future, perhaps in January 2016. Please feel free to go ahead if you need it. I expect it will need a fully-working version of Date Repeat and I have not yet managed to clear all the issues with my port of that - I hit a problem and moved on to other priorities.

**Comment by klonos** [comment]
@Graham-72 can you please confirm that you agree to make @bugfolder the maintainer of https://github.com/backdrop-contrib/gauth?

**Comment by jenlampton** [comment]
@klonos from the readme it looks like this project is abandoned. @Graham-72  isn't listed as maintainer, but should appear in the credits section for porting the module. If that's the case then @bugfolder can request maintainer access by creating [an issue in this queue](https://github.com/backdrop-ops/contrib/issues/new?assignees=klonos&labels=Maintainer+change+request&template=maintainer-change-request.md&title=Maintainer+change+request)

**Comment by bugfolder** [comment]
[Issue created.](https://github.com/backdrop-ops/contrib/issues/472)

**Comment by jenlampton** [comment]
Since both gauth and calendar modules have projects in backdrop-contrib now, I'm going to close this issue :) Thank you all for helping get these projects going for Backdrop CMS!
