### ISSUE TITLE
Porting EU Cookie Compliance module

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#118]
In response to a suggestion by @klonos at https://github.com/backdrop/backdrop-issues/issues/1354 I have made a start on porting this module which provides a function needed in the European Union. I have hit a problem because the Drupal module uses hook_page_build and I do not yet know how to replace this in Backdrop and can find no mention on api.backdropcms.org

My work-in-progress is currently at https://github.com/Graham-72/eu-cookie-compliance.

**Comment by klonos** [comment]
Thanx for doing this @Graham-72

**Comment by BWPanda** [comment]
I think we can close this as I'm sure the module has progressed past the issue @Graham-72 had back in 2015, and the module is part of the backdrop-contrib repo now.

**Comment by BWPanda** [comment]
But I lack the permissions to close issues here...

**Comment by Graham-72** [comment]
It seems I can close this. The ported module is at https://github.com/backdrop-contrib/eu_cookie_compliance.
