### ISSUE TITLE
Porting Beautytips

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#120]
I have started work on porting beautytips.

**Comment by Graham-72** [comment]
There would seem to be a big question regarding support for the jQuery plug-in so maybe I should consider other possibilities e.g. the Tips module.

**Comment by quicksketch** [comment]
Yeah, I would do the same. BeautyTips was written a long time ago and I don't think it's particularly well supported at this point.

**Comment by Graham-72** [comment]
I have now spent time on porting Tips but have put it to one side for the moment because the module has a very small uptake in Drupal and I feel needs quite a bit more explanation for the user.

I am now looking at Tipsy which has better usage but still only 7309 sites. I am currently trying to port some code I have not met before and am a bit puzzled:
`$form['#theme'] = 'system_settings_form';`
 `$form['#submit'][] = 'tipsy_admin_submit';`
 `return $form;`

What should I do with `system_settings_form ` in this circumstance?

**Comment by quicksketch** [comment]
Looks like theme_system_settings_form() doesn't do anything by default: https://api.drupal.org/api/drupal/modules!system!system.module/function/theme_system_settings_form/7

So I think you can safely just delete that `$form['#theme'] = 'system_settings_form';`.

**Comment by BWPanda** [comment]
@Graham-72 What's the status here? I see a few modules in backdrop-contrib now, and more in your personal repos...

**Comment by olafgrabienski** [comment]
@BWPanda The [Beautytips](https://github.com/backdrop-contrib/beautytips) module was ported by @Graham-72 and it has already a second release.

I'm using Beautytips on a production site, together with [Beautytips Node](https://github.com/backdrop-contrib/beautytips_node). Both modules have still some issues but the basics work fine.

**Comment by Graham-72** [comment]
The module's repository is at https://github.com/backdrop-contrib/beautytips.
