### ISSUE TITLE
Module Contributor

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop-ops/contrib#121]
I would like to join as a module contributor. I have extensive Drupal 7 experience, profile:
http://www.thedreamchest.com/portfolio (90% of those sites in D7)
and have a module I built for D7 and completed porting to Backdrop.
The module is a "another" CAPTCHA but very unique, simple to use and very strong.  Users can create their own challenges/answers or use an online CDN.
Example sites using the D7 version:
http://www.cloudbrat.com/form/contact-us
http://www.albanylodge.com/contact-us
http://www.florencecoloradochamber.com/contact
and many more.
The ported module can be downloaded from this page:
http://spambotblocker.com/
(there is a link right on the page)
I have tested it extensively with a live site.

**Comment by klonos** [comment]
Hey there @JugglingCoder have you had a look at https://github.com/backdrop-ops/contrib/blob/master/README.md?

Not sure what our policy about this is, but you are not hosting your module on GitHub and you only have links to .zip files from your website. The point is for us to have a quick look at the code and make sure that the basic requirements are met. Not that we cannot download the module .zip and check the code, it's just that hosting them on GitHub makes it easier and also, people can file issues that can be tracked here. Another thing is that AFAIK, we do not support checking for updated/new versions against anything other than backdropcms.org and that pulls releases of contrib modules from GitHub only.

Not sure how you feel about all this and whether you'd be willing to get your code in a repository in GitHub. I see that you just recently created you GitHub account, so I understand you might have questions about how it all works.

The ["Contributing code"](https://backdropcms.org/develop/code) section of the Backdrop CMS main website is a good start.

**Comment by klonos** [comment]
> Not sure what our policy about this is...

Here it is, at the end of https://api.backdropcms.org/modules there's this part:

> Submitting a contrib module

The Backdrop development community uses GitHub to manage contrib modules. If you are not familiar with GitHub, you can read through [some excellent documentation available on GitHub and other sites](https://help.github.com/articles/good-resources-for-learning-git-and-github/).

also, on https://github.com/backdrop-ops/contrib/blob/master/README.md the 7th point states this:

> Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

This implies that you should be using GitHub. Perhaps we should state this more clearly @quicksketch??

**Comment by klonos** [comment]
@JugglingCoder I hope that all this does not put you off from contributing. Please lets us know if you need any help or clarification and thanx for joining our community. We're clad to have you on board.

**Comment by JugglingCoder** [comment]
Thanks for the info kionos. I guess I misunderstood... on this page https://github.com/backdrop-ops/contrib/blob/master/README.md it says, "If you have started writing or porting a project for Backdrop, please include a link to the module, theme, or layout you have written. If you have posted the code under your... "  So I got the impression I could "include a link".  I guess I'll try to get some time to learn GitHub... yes, your right I'm new and with actually trying to build websites, learn Totally Re-learn D8, and learn Wordpress (because considering totally dropping Drupal anyways because of the D8 complete change and direction of becoming even more complicated) and Backdrop... LOL... time is thin!

**Comment by JugglingCoder** [comment]
kionos, I have created a depository and successfully uploaded the module into it:
https://github.com/JugglingCoder/spam_bot_blocker.git

**Comment by quicksketch** [comment]
Hi @JugglingCoder! Welcome! And thanks for porting your module!

Overall the new module looks great. Thanks for adding the README.md and LICENSE.txt file. It also looks like this module has been effectively ported to Backdrop with Config Management support.

There are a few issues:

- I filed an issue at https://github.com/JugglingCoder/spam_bot_blocker/issues/1, the implementation of hook_config_info() isn't quite right.
- There are a mix of tabs and spaces for indentation in places rather than using 2 spaces everywhere.
- We don't often see the use of `ob_start()` and `ob_flush()` within modules. Usually long strings are either concatenated or output with PHP's [heredoc format](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc).

However, we only require the following for module ports. While the above is optional, we do require at least:

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

So you only really need to do the last item. You may need to delete the repository off GitHub and post it again with the history from the D7 version. I don't think Git allows you to retroactively add history to an existing repository.

**Comment by JugglingCoder** [comment]
Hello quicksketch,

This module is not a "port" (as there is not official module for D7) and would be classified maybe... as a "new" module for Backdrop? So... there is no "Git history from Drupal 7" as this module is not an official D7 module.  I finished it about 6 months ago and seeing that D7 will be going the way of the dinosaur saw no reason to "apply" and go through the D7 process (which can take up to half a year) when D7 is going to be depreciated anyways.

So... can this proceed? Am I going to have to have this module "accepted" as a D7 module on Drupal before it can be accepted in Backdrop?  If people start building new modules specifically for Backdrop... "Maintain the Git history from Drupal 7"... is not really viable.  Will we always have to build an "official" D7 module first, then "port" it?

**Comment by quicksketch** [comment]
Ah! I hadn't realized that there wasn't a D7 version. When you said you had written it months ago, I had assumed that it was in the D7 repository as well.

All the better! New blood and new modules are excellent for the project. We're thrilled to have your module for Backdrop.

The only thing I forgot to mention earlier was that you should rename the branch of your module to `1.x-1.x`, matching the Drupal versioning paradigm.

---

But this is a great start and you've met all the major requirements. Would you agree to the following agreement for the contrib group officially? Then I can add you to the group and you can transfer your module over. Thanks!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by JugglingCoder** [comment]
Cool, thanks quicksketch

1.) "Backdrop Contributed Project Agreement"
yes, I agree

2.)
"you should rename the branch of your module..."

Do you mean the name here:
https://github.com/JugglingCoder/spam_bot_blocker
from "master" to "1.x-1.x"?

I am assuming so... on that page I looked around to
change branch name but can't find anything... sorry,
I'm new to git and still learning.

or maybe... I have to change it through the git 
command line?

**Comment by JugglingCoder** [comment]
I just went in and "tried" some things and managed to change the branch name to:
1.x-1.x
at: https://github.com/JugglingCoder/spam_bot_blocker
Hope this is correct.

**Comment by quicksketch** [comment]
Awesome! Looks good on the branch name.

I've added you to the contrib group. You should get an invite in your e-mail. You can transfer the project to the "backdrop-contrib" group by editing the settings on your project. Let me know if you have any trouble!

**Comment by JugglingCoder** [comment]
quicksketch, I transferred the module successfully but since I am no longer the "owner" I cannot change the "description" of the depository.  Would you please change it,
From:
"Spam Bot Blocker" Module for Backdrop CMS
To:
A "Strong" CAPTCHA that is easy to use for Site Visitors and Site Admins.

**Comment by klonos** [comment]
Just made that change for you :wink:

**Comment by quicksketch** [comment]
Sure @JugglingCoder! Yeah transferring a project isn't as nice as it should be, as you are a member of the "Authors" group but GitHub doesn't default to checking that box when you transfer the project. :stuck_out_tongue: Fixed now and the authors group permissions are set.
