### ISSUE TITLE
Group Membership Application

### ISSUE THREAD

**Issue by dboulet** [backdrop-ops/contrib#123]
I’d like to contribute some ported modules — the first of which is the Unsubscribe module:

https://github.com/dboulet/unsubscribe

I have a few more modules which I maintain on drupal.org that I will be porting in the future.

**Comment by quicksketch** [comment]
Hi @dboulet! Excellent! A very well-ported module!

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

---

You've done all the required items, and a basic check over the code looks great. We just need to have you state that you agree to the contrib agreement and then I'll grant you access!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

---

One minor item, we usually name the branches in Drupal-fashion, that is `1.x-1.x`. But that can be remedied at any time.

**Comment by dboulet** [comment]
Thanks @quicksketch!

>  We just need to have you state that you agree to the contrib agreement and then I'll grant you access!

I agree!

> we usually name the branches in Drupal-fashion, that is `1.x-1.x`

Good to know, I wasn’t sure about this and a quick glance at the existing contrib modules revealed inconsistent naming conventions in use. I’ll create a new branch in the repo.

**Comment by quicksketch** [comment]
Invite sent! Note when you transfer projects make sure that you grant the "Authors" team access (as that is the team you are a member of). Thanks so much @dboulet!

**Comment by dboulet** [comment]
Great! Thanks, @quicksketch.
