### ISSUE TITLE
Porting fancybox

### ISSUE THREAD

**Issue by gifad** [backdrop-ops/contrib#127]
I did an initial port of drupal fancybow module.
Why fancybox when colorbox is already here ?
1 - it's fancy ;-)
2 - it has a very powerfull, yet simple, javascript API, which makes it a good candidate to CTools modal replacement...
It's at https://github.com/gifad/backdrop-fancybox

**Comment by jenlampton** [comment]
Since this module is ported, I'm going to close this issue :)  Thanks @glfad!
