### ISSUE TITLE
Porting urllogin

### ISSUE THREAD

**Issue by gifad** [backdrop-ops/contrib#128]
urllogin allows generation of autologin URL
It's at https://github.com/gifad/backdrop-urllogin
It's also usefull to build demo sites, you can see it at work at : 

http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/

enjoy !

**Comment by jenlampton** [comment]
Since this module is ported, I'm going to close this issue :)  Thanks @glfad!
