### ISSUE TITLE
Porting  Page Theme module

### ISSUE THREAD

**Issue by rstamm** [backdrop-ops/contrib#130]
You can find it here:
https://github.com/rstamm/backdrop-page_theme

d.o. project page:
https://www.drupal.org/project/page_theme

**Comment by quicksketch** [comment]
Hi @rstamm! Excellent! Welcome to Backdrop!

This port looks really good! We require a few basics from all new projects:

New project checklist
---------------------

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

However, this last item is **optional** if you are the original author of the project. It might be a good idea to maintain the Git history just for the purposes of seeing when changes were last made to what line of code. I'll leave it to you if you decide to maintain the Git history.

The one thing I noticed in the code was that you were using a database table (`page_theme`) to store your configuration. In Backdrop, it'd probably be more appropriate to store that information in Configuration. See the "Updating your module to use configuration" section in https://api.backdropcms.org/converting-modules-from-drupal.

But this and your other project are both in great shape for initial inclusion in the Backdrop Contrib repository.

If you would agree to the following agreement for the record, we can invite you to the group so you can transfer the project and make an official release. Thanks!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by rstamm** [comment]
thanks. currently work on to use cmi.

**Comment by rstamm** [comment]
I agree to the Backdrop Contributed Project Agreement.

**Comment by quicksketch** [comment]
Thanks @rstamm! Sorry for the delay! I've sent you an invite. You can transfer the project to the `backdrop-contrib` group at any time. Once you're ready, you can list the modules on backdropcms.org by [making a release](https://api.backdropcms.org/creating-official-contrib-releases), which will automatically create a node on backdropcms.org based on the README.md file. Thanks!
