### ISSUE TITLE
Permissions differ due transferred repositories to and new created in backdrop-contrib

### ISSUE THREAD

**Issue by rstamm** [backdrop-ops/contrib#135]
After I transferred repositories to backdrop-contrib I lost administration access to my own repos.
I cannot edit the repo description nor have access to the repo settings, https://github.com/backdrop-contrib/copyright_notice/settings creates a 404, but i can still push to the repo.

But if I create a new repository in backdrop-contrib I administration access, like https://github.com/backdrop-contrib/tweaks/settings

To the most repositories in backdrop-contrib I have administration access. There are only a few like calendar, drush, eu-cookie-compliance, I don't have admin access.

I think transferred repositories have different permissions by default than new created in backdrop-contrib.

At https://github.com/orgs/backdrop-contrib/teams/authors/repositories you can see what permissions you have.

**Comment by klonos** [comment]
@quicksketch I want to help with issues like this but I do not know how to...

I cross-checked and compared @rstamm's [settings for copyright_notice](https://github.com/orgs/backdrop-contrib/people/rstamm/repositories/backdrop-contrib/copyright_notice) to that (for example) of @serundeputy's [settings for the same repo](https://github.com/orgs/backdrop-contrib/people/serundeputy/repositories/backdrop-contrib/copyright_notice). The only difference I see is that @rstamm has also "collaborator access" (additionally to "membership privilege" that @serundeputy has). ???

**Comment by klonos** [comment]
...if you end up fixing this, please describe the steps you follow so that next time I can help out by taking some of the burden off of you.

**Comment by quicksketch** [comment]
GitHub permissions can be set per user or per project. I think you'd been looking at the user-level permissions rather than the project-level one. Projects should allow the "Authors" group admin level access. When transferring a project, you're asked which groups should get access. Oddly it's entirely possible to lock yourself out after doing a transfer by not including the group of which you are a member. :stuck_out_tongue: 

To fix this, I went to the settings page for copyright_notice (https://github.com/backdrop-contrib/copyright_notice/settings/collaboration), and granted the "Authors" group Admin access.

![selection_063](https://cloud.githubusercontent.com/assets/100206/12988306/ef58cc7e-d0b4-11e5-837c-4777f04c36f2.png)

**Comment by jenlampton** [comment]
Thanks @quicksketch, I was unable to figure that out too!  Good to have it documented here for furure reference, as I expect there may be others who also fall into this situation.

**Comment by rstamm** [comment]
Thanks. Now I have access to the admin pages for copyright_notice
![github com_backdrop-contrib_copyright_notice_settings_collaboration_-_2016-02-11_23 33 27](https://cloud.githubusercontent.com/assets/6431849/12993256/4fab9c78-d119-11e5-91fd-dd48174e6b87.png)

but for tweaks it looks like this, just wondering because the Teams field is empty
![github com_backdrop-contrib_tweaks_settings_collaboration_-_2016-02-11_23 34 00](https://cloud.githubusercontent.com/assets/6431849/12993293/84c90df0-d119-11e5-9f11-d9d0150ab82f.png)

team Authors repositories page
![github com_orgs_backdrop-contrib_teams_authors_repositories_-_2016-02-11_23 38 05](https://cloud.githubusercontent.com/assets/6431849/12993334/ebbc0a8a-d119-11e5-8d9b-a4ee35a5352b.png)
![github com_orgs_backdrop-contrib_teams_authors_repositories_repo_page 2_-_2016-02-11_23 40 38](https://cloud.githubusercontent.com/assets/6431849/12993505/d49206f6-d11a-11e5-9d1b-9fb4fcaecb4e.png)

**Comment by rstamm** [comment]
Now I only need admin access to 
https://github.com/backdrop-contrib/content_theme
https://github.com/backdrop-contrib/page_theme

Thanks

**Comment by jenlampton** [comment]
@rstamm Thanks for pointing those out as well, I have updated your access.

**Comment by rstamm** [comment]
@jenlampton thanks.

**Comment by klonos** [comment]
Thanx for taking the time to explain how it's done @quicksketch. Next time I'll know how to do it :wink:
