### ISSUE TITLE
[DX] Synchronize core and contrib labels for a common vocabulary.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/contrib#136]
I believe that having the same labels in the Backdrop core and Backdrop contrib repos will allow us to communicate and solve issues more efficiently.

I have not tested this, but I found this while thinking about this issue: https://github.com/matomo-org/github-sync

**Comment by jenlampton** [comment]
I couldn't find this issue so I made https://github.com/backdrop-ops/backdropcms.org/issues/181 :)
