### ISSUE TITLE
Let's add attribution to past Backdrop/Drupal maintainers in the README.md

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#14]
It's important that we be respectful to Drupal developers who may have poured their heart, soul, and time into a Drupal module before it was ported to Backdrop.  As a hat-tip, I think it would be nice if we gave credit where credit is due.  Let's add another section in the README.md file for past maintainers, and make sure new Bakcdrop projects list the maintainers of the Drupal projects from which they evolved.

**Comment by quicksketch** [comment]
Sounds good to me! Merged your PR to update the example.
