### ISSUE TITLE
I would like to join the Backdrop Contrib community!

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop-ops/contrib#142]
I have a port of Multiple Selects (D7) ready, and I'm a (co)maintainer of a couple of Drupal projects which I can port, and maintain in the (near) future.

-tnx!-

Harold

**Comment by quicksketch** [comment]
Hi @MrHaroldA! It's great to see you in the contrib group! Thanks for the work you've done already in the core queue. :smile:

Could you push up your repository of Multiple Selects to your personal GitHub account so we could review it? All projects have to have these minimum requirements met.

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by MrHaroldA** [comment]
Well, after the discussion in #1676 I no longer want to publish Multiple Selects as it only fixes a single UX issue. ;)

I'll have a look at some of my maintained D7 modules, like Field Element Acces, Node Embed, Webform Encrypt, Functional Content, and some others ...

**Comment by klonos** [comment]
> Well, after the discussion in https://github.com/backdrop/backdrop-issues/issues/1676 I no longer want to publish Multiple Selects as it only fixes a single UX issue. ;)

Some people might still find it useful in Backdrop contrib land and besides, we have not settled on any decision over in that issue yet :wink:

**Comment by MrHaroldA** [comment]
True, but I don't want to push any unmaintained code into the wild. In case of the Multiple Selects module, the port is only a change in the info file, and commenting the commerce widget line, since that yields a notice in Backdrop.

**Comment by klonos** [comment]
Fair enough then.

**Comment by klonos** [comment]
Hello @MrHaroldA 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
