### ISSUE TITLE
MathJax for BackdropCMS

### ISSUE THREAD

**Issue by rhoscalas** [backdrop-ops/contrib#144]
I would you like to share with Backdrop community a module named [MathJax](https://github.com/rhoscalas/MathJax-BackdropCMS). Thanks!

**Comment by klonos** [comment]
Hello there @rhoscalas and welcome to the Backdrop contrib group. Thank you taking the time to port this very useful module over to Backdrop. Would you care to move it over to the official contrib repository so that its releases are automatically available in the list of modules in backdropcms.org?

All projects have to have these minimum requirements met.

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
I see you already include a GPL v2 LICENSE.txt. The README.md could use some love. Not sure how to check the Git history to see if the D7 part was transferred over (@quickscetch how do I check this??).

Last thing: I know this is done in good intentions, but when porting a module, out of courtesy we usually try to contact the original creators or the current maintainers over in d.org and ask them for permission or at least give them a heads-up of our intention to port their module and also offer (co)maintainership if they'd like. Can you go ahead and do that please?

**Comment by docwilmot** [comment]
> Not sure how to check the Git history to see if the D7 part was transferred over

On the module's Git repo (e.g. https://github.com/rhoscalas/MathJax-BackdropCMS) click "commits" under the "code" tab. If its a port, there should be commits in there from Drupal devs. (Usually obvious, old issues, like "Issue #823748782").

**Comment by rhoscalas** [comment]
Sorry, but I'm not an expert. I will follow the instructions of the article. Should I remove the module for now? I should first contact the creator and maintainer of MathJax for Drupal. Thanks for your patience!

**Comment by klonos** [comment]
>Sorry, but I'm not an expert.

Don't worry about that. I'm no expert in Git and GitHub either.

> Should I remove the module for now?

I think you should be fine. But do try to contact the maintainer (file an issue in the module queue over in d.org and perhaps wait for a week or so for any reply.).

**Comment by klonos** [comment]
@docwilmot tahnx :wink:

**Comment by rhoscalas** [comment]
Ok, perfect! Today I will try to contact the maintainer. Thanks!

**Comment by quicksketch** [comment]
Hi @rhoscalas! Welcome to the Backdrop community! Thanks so much for porting this module and we're thrilled you're sharing it with us! I'm looking forward to working with you. :smile:

**Comment by rhoscalas** [comment]
Thanks so much for your work! :) I'm still trying to figure out how to contact the author and maintainer of the Drupal module, but I can't find any email or any other way to contact him. Any idea?

**Comment by klonos** [comment]
Yes, sorry for not mentioning this beforehand. You can file a new issue in the project queue in drupal.org: https://www.drupal.org/node/add/project-issue/mathjax

...you'll have to have a valid d.org user account in order to be able to create issues. If you do not have an account and do not want to create one, then I can file an issue on your behalf to let the maintainers know of our intention to have their module ported to Backdrop. Let me know.

**Comment by rhoscalas** [comment]
Ok, perfect! You can file an issue on my behalf. Thanks so much @klonos

**Comment by klonos** [comment]
Done!: https://www.drupal.org/node/2685717

**Comment by rhoscalas** [comment]
I reiterate my thanks for your help @klonos :)

**Comment by cilefen** [comment]
Hi.

**Comment by rhoscalas** [comment]
Hi @cilefen! Are you interested to port MathJax from Drupal to Backdrop?

**Comment by cilefen** [comment]
@rhoscalas Does it not work as it is?
I see you need to fix the git history.

**Comment by rhoscalas** [comment]
Yes, it works perfectly. If you want to port the module with your name it is ok for me (In that case I will remove the code from my github). Otherwise I can maintain MathJax for Backdrop. Regarding of fixing the git history I think that I'll need help. I'm sorry for my english!

**Comment by cilefen** [comment]
Start over with the github import, as documented: https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2

**Comment by rhoscalas** [comment]
I think that now is ok! https://github.com/rhoscalas/mathjax @klonos @cilefen

**Comment by cilefen** [comment]
I think you took the 7.x-1.x branch, but the 7.x-2.x branch is the supported one.

**Comment by rhoscalas** [comment]
Yes, it is the 7.x-1.x because the 7.x-2.x doesn't work.. The code of the branch 7.x-2.x is here: https://github.com/rhoscalas/mathjax-backdrop/tree/mathjax. Next Tuesday I will try to understand what is the problem.. Thanks so much for your patience @cilefen

**Comment by gifad** [comment]
> what is the problem.. 

`hook_page_alter()` does not exist any more in backdrop : Google just found "we've also removed the infamous hook_page_alter() function" in http://www.jenlampton.com/blog/great-cleanse-removing-features-backdrop-cms

Since it seems to be just about javascript injection, use `backdrop_add_js()` in a `hook_init()`, or try `hook_prepreprocess_layout()`, if `script type="text/x-mathjax-config"` is mandatory.

related issues : https://github.com/backdrop/backdrop-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+hook_page_alter

**Comment by rhoscalas** [comment]
The problem is solved thanks to @gifad Today I will upload the module!

**Comment by rhoscalas** [comment]
Ok, all done! https://github.com/rhoscalas/mathjax-backdrop tested on my website.

**Comment by gifad** [comment]
@rhoscalas : Are you interested in CKEditor plugin integration ?
I committed a micro module at https://github.com/gifad/backdrop-ckeditor_mathjax
Feel free to merge the two integration functions in your project !

Note: the CKEditor plugin has been applied the "Button" fix, as per the [d.o issue](https://www.drupal.org/node/2215409).

**Comment by rhoscalas** [comment]
@gifad I'm interested! Next week I'll try your module to see how it works. Thanks so much!

**Comment by klonos** [comment]
Sorry for the late reply @rhoscalas...

From the [commit history](https://github.com/rhoscalas/mathjax-backdrop/commits/) it seems that the history from d.org was preserved this time. Also, there is also a [README.md](https://github.com/rhoscalas/mathjax-backdrop/blob/1.x-1.x/README.md) now, so the last two checkboxes on the requirements list are ticked!!

Before I send you an official invitation to join the contrib group, for the record I will have you agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

Additional notes for non-coders
-------------------------------

1. If an applicant is not (yet) a coder but would still like access to the
   contrib group (for example, for updating documentation or managing issue
   queues) the applicant must get at least one recommendation from another
   person who already has commit access to the contrib group.

1. Any non-coder applicant still agrees to the same contributed project author
   agreement as coders (above).

1. Any non-coder applicant needs to additionally promise that should they ever
   wish to author new code in the Backdrop contrib group, they will also undergo
   the same code spot-check process a new contributor needs to undergo at the
   time they add the code.

Abandoned Projects
------------------

You may apply to adopt an abandoned project. The procedure is as follows:

1. If you haven't already, please join the Backdrop Contrib group by submitting
   an application (see above).

1. File an issue with the current project requesting to help maintain the
   project.

  - If written permission is granted by a current maintainer, create a PR that
    adds your name to the README.md file in the list of maintainers.
  - If a current maintainer does not respond within 2 weeks [create an issue in this repository](https://github.com/backdrop-ops/contrib/issues/new) to take
    over the project. Please include a link to the issue you filed with the
    abandoned project.

1. After confirming the project has been abandoned, a Backdrop Contrib
   administrator will add your name to the list of maintainers in that project's
   README.md file.

1. You may now maintain the project directly as though given permission by the
   project maintainers, and likewise now grant permission to others to maintain
   the project.

**Comment by rhoscalas** [comment]
@klonos Don't worry about the late response. 
I agree to all points of the Backdrop Contributed Project Agreement!

**Comment by klonos** [comment]
Great! The invite is on its way and you should receive an email about it soon.

One thing you might need to do is to delete the D7 and D8 releases that were automatically created for the module when you transferred it from d.org. You can transfer the project to the `backdrop-contrib` group at any time. Once you're ready, you can list the modules on backdropcms.org by [making a release](https://api.backdropcms.org/creating-official-contrib-releases), which will automatically create a node on backdropcms.org based on the README.md file.

It's great to have you on-board :tada: ...please let us know if you have any issues with permissions or anything else.
