### ISSUE TITLE
Put together an official non-code contrib membership agreement.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#145]
For people like myself and the more recent case of @goldmantx in #143

Here's what @jenlampton had suggested back in https://github.com/backdrop-ops/backdropcms.org/issues/44#issuecomment-71571133

> 1) Add stipulations around how a non-coder gets commit access to the contrib group. @quicksketch proposed that the applicant needs to get one recommendation from another person who already has commit access to the contrib group.

>2) Applicant needs to agree to the same contributed project author agreement as coders.

>3) Applicant needs to additionally promise that should they ever want to author new code in the Backdrop contrib group, they will also undergo the same code spot-check process a new contributor needs to undergo at the time they add the code.

**Comment by quicksketch** [comment]
It still sounds like a good idea to me. Let's file a PR against the README.md to document this.

**Comment by jenlampton** [comment]
I'm working in that file now (was just adding line breaks) but I'll be happy to submit a PR.

**Comment by quicksketch** [comment]
Great, yeah when you save just make it a PR. :smile:

**Comment by quicksketch** [comment]
Thanks, I merged the changes.
