### ISSUE TITLE
Ported services

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#148]
Didnt intend to, but after working on Feeds, was in the mood to figure out how to purge CTools properly, and this module was up to the challenge. Tests not checked yet, so errors likely. 

Plans to convert to using config for storing endpoints, eventually, to maintain exportability (which went away with CTools)

**Comment by serundeputy** [comment]
@docwilmot closing as we have services in contrib w/ releases.

feel free to reopen it if needed
