### ISSUE TITLE
Port select2 integration.

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/contrib#149]
Select2 plugin is due to core integration, but is tagged 1.x future.
see [ Replace jQuery UI autocomplete with Select2 #459 ](https://github.com/backdrop/backdrop-issues/issues/459)
In the meantime, [this project](https://github.com/backdrop-contrib/select2) can help test/evaluation…

**Comment by quicksketch** [comment]
Thanks @gifad! Closing this issue as the port is complete.
