### ISSUE TITLE
Porting Custom Publishing Options

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/contrib#154]
Initial port of custom_pub, at https://github.com/backdrop-contrib/custom_pub, which has been referenced (requested ?) recently in various issues…
My intent is to extend it with node permissions, to have a "workflow lite" module (targeted at node "visibility")
More if affinities :)

Note : for use by real users on real sites, [Override Node Options](https://github.com/backdrop-contrib/override_node_options) is almost a prerequisite…

**Comment by quicksketch** [comment]
Thanks @gifad! I'm going to close this issue. I'm not sure what happened to your account (now marked as @ghost), but we hope to see you again!
