### ISSUE TITLE
First contrib module: simple EU cookies

### ISSUE THREAD

**Issue by davidvina** [backdrop-ops/contrib#158]
I wrote my first module for backdrop. Displays a warning about the use of cookies.
It is simply an implementation of jquery module: cookiebar.
I would like other people to take advantage of this work. I would appreciate it got in the repository modules backdrop.

The link to the module: https://github.com/davidvina/simple_EU_cookies

best regards,
and excuse me for my poor English.

**Comment by quicksketch** [comment]
Hi @davidvina! Welcome to the Backdrop Contrib group!

Could you make a few adjustments to your code for consistency and cleanup?

- You're missing `hook_config_info()`. That will prevent importing/exporting in the configuration management interface.
- Rename `LICENSE` to `LICENSE.txt`
- Remove this inaccurate documentation:
```
/**
 * @defgroup block_example Example: Block
 * @ingroup examples
 * @{
 * Demonstrates code creation of blocks.
 *
 * This is an example outlining how a module can define blocks that can be
 * displayed on various pages of a site, or how to alter blocks provided by
 * other modules.
 */
```
- And update this to be the name of your module:
```
/**
 * @file
 * Module file for block_example.
 */
```

Overall it looks like a nice and simple module! It doesn't seem to have been a port of an existing module, so you don't need to keep the D7 history.

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Overall though you've completed the major points. I'd love to see the module cleaned up further, but it is not our policy to do a complete review at this point.

**Comment by quicksketch** [comment]
If you would agree to this, then we can move in the repository into the backdrop-contrib group:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

**Comment by davidvina** [comment]
Hello,

thanks you too much for your advices.

I just upload the changes.

I hope it will published like a backdrop contrib module soon.

best regards!

2016-04-16 3:05 GMT+02:00 Nate Haug <notifications@github.com>:

**Comment by klonos** [comment]
Hello @davidvina 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
