### ISSUE TITLE
Porting Fivestar module

### ISSUE THREAD

**Issue by whiteph** [backdrop-ops/contrib#159]
I'm a co-maintainer for Fivestar on Drupal.

**Comment by quicksketch** [comment]
Hi @whiteph! Welcome to the Backdrop contrib community! We chatted by email but I'll post it here as well. For new projects, push up your port to your personal GitHub account. Then when it's ready we can give it a basic review. We check for the following things:

New project checklist
---------------------

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Again I'm really excited to see you brining over Fivestar module to Backdrop. Feel free to ping me on [Gitter](https://gitter.im/backdrop/backdrop-issues) if you have any questions.

**Comment by quicksketch** [comment]
I closed https://github.com/backdrop-ops/contrib/issues/160 and we'll use this issue to get you access to the contrib group once you've got something to review. You can start with just VotingAPI if you prefer. Perhaps a simpler one to start and then Fivestar afterward. Excited to see the work either way. :smile:

**Comment by whiteph** [comment]
Thanks. I'm doing final testing now. Seems to be working fine. I want to run a few more tests before handing it over.

**Comment by whiteph** [comment]
This is ready for review, together with Voting API.

**Comment by klonos** [comment]
Just checked both repositories and they seem to have retained commit history from d.org and they also include a LICENSE.txt and a README.md. All boxes ticked! @whiteph can I please have you agree to the following for the record?:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

**Comment by whiteph** [comment]
I agree.

**Comment by klonos** [comment]
Perfect! Invite is on its way. Welcome to the Backdrop Contrib group.

I can't wait for Fivestar to be some day deployed on backdropcms.org. I have always envisioned allowing users to vote for features they want to see in upcoming versions and/or give priority to bugs that they need fixed (https://github.com/backdrop-ops/backdropcms.org/issues/211), vote on requests for projects that they want to see ported (https://github.com/backdrop-ops/contrib/issues/110) and we can also use the Voting API for things like PMC voting, having users like blog posts or mark documentation or Q&A as useful or not and even track customer satisfaction by ...I mean once [Vote Up/Down](https://www.drupal.org/project/vote_up_down), [Is Useful](https://www.drupal.org/project/is_useful), [Plus 1](https://www.drupal.org/project/plus1) and [Fivestar Smiley](https://www.drupal.org/project/fivestar_smiley) are also ported or perhaps implemented as submodules/features of Fivestar.

Thank you for joining our community @whiteph. We are thrilled to have you on-board!

**Comment by quicksketch** [comment]
Welcome @whiteph!
