### ISSUE TITLE
Porting Voting API module

### ISSUE THREAD

**Issue by whiteph** [backdrop-ops/contrib#160]
Fivestar depends on this. I'm not a co-maintainer of Voting API, so I've left a request on the Voting API issue list to see if one of the maintainers would be happy to do the port: <a href="https://www.drupal.org/node/2711001">Backdrop Port of Voting API</a>.

**Comment by quicksketch** [comment]
Let's close this issue and use https://github.com/backdrop-ops/contrib/issues/159 as your application. Can't wait to see it!
