### ISSUE TITLE
Sign me up for backdrop-contrib!

### ISSUE THREAD

**Issue by deekayen** [backdrop-ops/contrib#162]
I started porting the modules I wrote or used for the [Guardr](https://www.drupal.org/project/guardr) Drupal distro to Backdrop. I plan to do a bunch more and break up some other Drupal security modules into smaller Backdrop parts. Seems like I ought to join up and get these moved to a place where people can find them easily:

https://github.com/deekayen/clear_password_field
https://github.com/deekayen/diskfree
https://github.com/deekayen/hide_php_fatal_error
https://github.com/deekayen/markdownextra
https://github.com/deekayen/paranoia
https://github.com/deekayen/remove_generator
https://github.com/deekayen/x_originating_ip

I've got the routine down enough that I scripted a big chunk of the upgrade process into a bash script that downloads the Drupal git repo, branches to 1.x-1.x, and then does some scripted updates. In case anyone else is also interested in that: https://gist.github.com/deekayen/14d48f1fadec49039a79.

I after 15 years with Drupal, I'm slowly shedding big things like my [d.o elevated privileges](https://www.drupal.org/node/2575695), so I hope you'll take me over here.

**Comment by quicksketch** [comment]
Hi @deekayen! Wow, awesome! This looks great! I read through several of the modules and they look nicely ported. Well done!

Thanks for putting those up publicly. You're right that having them in the central contrib group would also be helpful. Right now, the only way to list modules on backdropcms.org is through the contrib group. Long-term we might work out distributed modules, but centralizing them has other benefits for group maintainership, security updates, consistent tools, and other reasons. So `backdrop-contrib` is definitely the place to be!

So for all our new projects, we require the following:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

---

Yay, you've done all the required parts. That's a nice shell script too! I wonder if we could formalize that somewhere. Perhaps put it into the Drush project?

Anyway, you're good to go if you would accept the official contrib agreement:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

**Comment by deekayen** [comment]
The agreement sounds alright to me.

**Comment by quicksketch** [comment]
Great, thanks @deekayen! You're now invited to the https://github.com/backdrop-contrib group. You can transfer your repositories and make new releases at your leisure. Be sure to grant access to the "Authors" group when you transfer the repositories, as that's the group you are a member of. 

When you make a tag, you also have to make it an official release on GitHub. Official releases will automatically create a node and download available from BackdropCMS.org.

Because contrib authors can currently commit to any repository in the group (see https://github.com/backdrop-ops/contrib/issues/150), you might also want to change your email notification settings if you have not already so that you don't receive mail for every issue from every module.

Please let me know if you have any troubles or questions! The best place to catch us in real time is on Gitter: https://gitter.im/backdrop/backdrop-issues Welcome again!
