### ISSUE TITLE
Social SimpleSharer

### ISSUE THREAD

**Issue by ElliotChristenson** [backdrop-ops/contrib#168]
non-Javascript social (Facebook, Twitter, etc.) sharing module is ported to Backdrop 1.x

https://github.com/ElliotChristenson/backdrop-simplesharer

**Comment by klonos** [comment]
Welcome to the Backdrop CMS Contrib queue @ElliotChristenson. Would you be interested in becoming a member of the Team? This is a relatively simple process (we review some basic things in your project repo like the README and LICENSE files) and then have you agree to some terms.

Becoming a member will allow you to transfer your projects to the official backdrop/contrib repo and that in turn will allow any release you make on GitHub to be shown in the Project Installer so that people can install your project from the convenience for their website admin UI.

**Comment by ElliotChristenson** [comment]
Sure thing, Gregory. I'm very excited for the Backdrop project.

**Comment by klonos** [comment]
Great. ...and all of us here in Backdrop are excited to have people excited about the project 😄 

Lets make this an official contrib project maintainer application. These are our current requirements:

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Going through your repo now...

**Comment by klonos** [comment]
LICENSE.txt and README.md: both check. In the README, you could make the mention of the Foundation Icon Font Set a link to http://zurb.com/playground/foundation-icon-fonts-3, but that can be done at any point.

With the Git commit history, I see that on [the d.org side](https://www.drupal.org/node/2579481/commits) there are commits that go as far back as October 2015, but on GitHub, the commits are only as far back as a few hours ago. Can you please look into that? Please use the article I link to in the remaining check in my previous comment.

**Comment by ElliotChristenson** [comment]
Sent from my iPhone

> On Jun 26, 2016, at 7:07 AM, Gregory Netsas <notifications@github.com> wrote:
> 
> LICENSE.txt and README.md: both check. In the README, you could make the mention of the Foundation Icon Font Set a link to http://zurb.com/playground/foundation-icon-fonts-3, but that can be done at any point.
> 
Good point. I thought I had that in there. But thanks for the catch!


> With the Git commit history, I see that on the d.org side there are commits that go as far back as October 2015, but on GitHub, the commits are only as far back as a few hours ago. Can you please look into that? Please use the article I link to in the remaining check in my previous comment.
> 
Should I create a new repo importing that in then make the BD specific changes?

I was a little fuzzy on that since it's my module and is so simple whether I needed the history or not.

I'll see what I can do.

Thanks for all the help!

**Comment by klonos** [comment]
> Should I create a new repo importing that in then make the BD specific changes?

Yeah, sounds like that's the way to go. Let us know when you're ready.

**Comment by klonos** [comment]
Hello @ElliotChristenson 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
