### ISSUE TITLE
Token: Undefined property: stdClass::$language

### ISSUE THREAD

**Issue by yamlfd** [backdrop-ops/contrib#17]
Undefined property: stdClass::$language	Notice	token.module	509	token_get_info()

**Comment by quicksketch** [comment]
Hiya @yamlfd, please file this against the Token module, not the Contrib Ops repository: https://github.com/backdrop-contrib/token/issues

**Comment by yamlfd** [comment]
Are you able to move the case? Gitbub is usability nightmare for me. No idea how to find the project queues

**Comment by quicksketch** [comment]
Unfortunately moving issues is not possible in Github. :(

It's definitely a pain.
