### ISSUE TITLE
Port of Getlocations project

### ISSUE THREAD

**Issue by bobhutch** [backdrop-ops/contrib#170]
I have made a start at porting my mapping module Getlocations from Drupal to Backdrop. The configuration pages are working, maps can be added to content-types using Getlocations_fields and Google maps, Openstreet maps and numerous others can be displayed in content or in Views. There is more to be done, there may still be some features that need tweaking, some minor modules have yet to be ported and README files need editing.

This project can currently be obtained on
https://github.com/bobhutch/getlocations
set branch to bd-1.x-1.x to get the Backdrop version

Getlocations required the Libraries module and you will need some markers, there are links on the main project page

The Drupal 7 version can be seen at http://test.arwystli.net/
I will get a Backdrop demo site going in due course.

**Comment by klonos** [comment]
Hello @bobhutch and thanx for taking the time to port your module to Backdrop. There are a few things that we need to check before you can move your project to the official contrib repository:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

...you can read more about the process [here](https://github.com/backdrop-ops/contrib)

Let us know when you are ready for n initial review.

**Comment by bobhutch** [comment]
There is a Backdrop compatible version at https://github.com/bobhutch/getlocations/tree/bd-1.x-1.x
It has a LICENSE.txt and a README.md as well as a README.txt containing more instructions. The above repo was branched from Drupal-7 and includes the full history right from the initial commit of the Getlocations project, There is a CHANGELOG.txt included as well. As far as I know I have complied with the above requirements.

**Comment by klonos** [comment]
Hi @bobhutch I don't mean to make this hard for you. Just some minor details that I am not sure of:

1. I don't think we've had project maintainers that maintain both Backdrop and Drupal code in the same GitHub repo. This has made another possible issue to emerge: the backdrop branch is bd-1.x-1.x instead of plain 1.x-1.x. I realize that this is in order to be future-proof (for when Backdrop reaches 6.x and 7.x eventually), but I don't know what the policy is for that specific issue. @quicksketch ??

2. The Backdrop branch contains both a README.**md** as well as a README.**txt** (which states at its start "for Backdrop 7???"). I think that this needs to be removed once any relative info from it is transferred over to the README.md

3. The LICENSE.txt seems to be GPL v3, just double-checking that this is compatible with the recommended GPL v2 (@quicksketch again??)

The commit history seems to be right though. I've ticked that off the list 😉

**Comment by bobhutch** [comment]
In order to avoid future namespace clashes I have created a new github account for the Backdrop version, see https://github.com/arwystli/getlocations/tree/1.x-1.x
The LICENSE.txt has been updated there.
The README.txt contains a lot of information that site developers may need, eventually it can go into The Wiki pages as the README.md has a rather limited remit. It has been moved to README2.txt to avoid confusion.

**Comment by bobhutch** [comment]
The code at https://github.com/arwystli/getlocations/tree/1.x-1.x has been updated and a number of bugfixes applied, there is now a basic demo site at

http://bd.arwystli.net/

**Comment by arwystli** [comment]
The port of Getlocations to Backdrop is now quite stable IMHO, any chance of getting this listed sometime soon?
TIA

**Comment by docwilmot** [comment]
Looks great to me. @klonos should be along in just a few seconds to give you access to the Backdrop contrib group.

**Comment by klonos** [comment]
Yep, invitation on its way. Sorry for taking too long with this @arwystli and thanx @docwilmot for doing the review 👍

**Comment by klonos** [comment]
@arwystli once you accept the invite, you'll be able to transfer your project to https://github.com/backdrop-contrib and then tag a release. That should trigger a project node being created over in backdropcms.org and that in turn would have that version picked up by the Project Installer module 😉 

Let us know if you have any problems that we can help with.

**Comment by arwystli** [comment]
Thanks, I'm happy to accept, let me know what I need to do to transfer the project.

**Comment by klonos** [comment]
Oh, yeah. The agreement. For the record, I must have you agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

**Comment by arwystli** [comment]
OK, I have read the Backdrop Contributed Project Agreement and I agree to abide by it.
Thanks.

**Comment by klonos** [comment]
Thank you and welcome to the Backdrop contrib group @arwystli

**Comment by quicksketch** [comment]
Welcome @arwystli! Thanks @klonos for the great feedback and process here.
