### ISSUE TITLE
Port Privatemsg (private messaging)

### ISSUE THREAD

**Issue by bd0bd** [backdrop-ops/contrib#171]
Hi all!

I offer somebody to port [Privatemsg](https://www.drupal.org/project/privatemsg) module.
Or may be similar one.
:smile: 

Thank you!

**Comment by Graham-72** [comment]
I have made a start on porting Privatemsg and put the repository at https://github.com/backdrop-contrib/privatemsg. There is still much testing and debugging to be done.

**Comment by bd0bd** [comment]
@Graham-72, thank you very much!

**Comment by klonos** [comment]
I guess all comments and issues can be directed to that repository then.
