### ISSUE TITLE
Theme - Sora

### ISSUE THREAD

**Issue by Scoppettuolo** [backdrop-ops/contrib#175]
Theme Sora based in Seven but with features for the front end utilization.

https://github.com/Scoppettuolo/Sora

**Comment by quicksketch** [comment]
Hi @Scoppettuolo! I saw this post but I didn't realize you weren't a member of the contrib group yet. Sometimes we use this issue queue just to announce the ports or release of new modules/themes.

Are you interested in moving this to the contrib group? We can do the basic review and get you access if you would like to move this to http://github.com/backdrop-contrib, which would be great as that will make the theme available for download from BackdropCMS.org and through the Installer UI.

**Comment by Scoppettuolo** [comment]
Sure, if it Sora Theme is ok.

**Comment by Scoppettuolo** [comment]
Sure, if it Sora Theme is ok.

Update: Some update?

**Comment by Scoppettuolo** [comment]
Sure, if it Sora Theme is ok.

Update: Some update?

**Comment by jenlampton** [comment]
@klonos can you please present @Scoppettuolo with a maintainers agreement?

**Comment by klonos** [comment]
@jenlampton before proceeding with the agreement, the minimum requirements are to be met:

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] ~~Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).~~

We are good on the LICENSE.txt and retaining the Git history from D7 does not apply in this specific case because this is a new theme developed only for Backdrop. With the README.md though, I'm not sure because most of it is in Spanish (??).

**Comment by jenlampton** [comment]
Ah!  Maybe we should stipulate that the README.md should be written in English?

**Comment by klonos** [comment]
Yes, I think so.

**Comment by Scoppettuolo** [comment]
I added the necessary Info, I think

In English ..., my English is not good., You can translate the Info, so I add it below.

**Comment by klonos** [comment]
Thanx @Scoppettuolo. I'll help with the English ...as best I can.

**Comment by klonos** [comment]
@jenlampton instead of mixing multiple languages in a single README, should we be reserving README.md for English and have other languages be README.%langcode%.md (README.es.md in this case)?

**Comment by jenlampton** [comment]
The README.md should be in English. I'd like to avoid shipping each contrib project with more than one readme, (for the same reason that we no longer ship contrib projects with multiple translations) but I do like the idea of having alternate versions. 

@klonos Can you see what Drupal does about translating the readmes?

**Comment by Scoppettuolo** [comment]
Any update?

**Comment by jenlampton** [comment]
Hi @Scoppettuolo, it looks like we need to do a few things here:

* remove the README.en.md file
* Update the README.md 

I usually copy the README.md file from the example, found here: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md

**Comment by jenlampton** [comment]
I have created a pull request to update the readme file: https://github.com/Scoppettuolo/Sora/pull/1

This is a close enough starting point that we can get you into the contrib project, and include your theme in the contrib group!

When transferring the repository, please change the project name from "Sora" to "sora" with a lowercase S. :)

**Comment by Scoppettuolo** [comment]
Now is ok?

**Comment by klonos** [comment]
@Scoppettuolo yes, all boxes ticked 👍 ...can I please have you agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to an issue to grant
   a new maintainer within 2 weeks, your project may be modified by a Backdrop
   Contrib Administrator to add a new maintainer, without your explicit consent.

**Comment by klonos** [comment]
- If a current maintainer does not respond within 2 weeks, [create an issue in
this repository](https://github.com/backdrop-ops/contrib/issues/new)
    to take over the project. Please include a link to the issue you filed with
    the abandoned project.

**Comment by klonos** [comment]
- If a current maintainer does not respond within 2 weeks, [create an issue in
    this repository](https://github.com/backdrop-ops/contrib/issues/new)
    to take over the project. Please include a link to the issue you filed with
    the abandoned project.

**Comment by Scoppettuolo** [comment]
it is fine for me.

**Comment by klonos** [comment]
Great to have you on board @Scoppettuolo!! ...invite underway:

> You've invited Scoppettuolo to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation. 

PS: as @jenlampton pointed, please remeber to rename the project to `sora` (use a lower-case "s") when you transfer the project over to backdrop-contrib.

**Comment by klonos** [comment]
...also sorry this took so long. Please let us know if there is anything we can help you with.

**Comment by Scoppettuolo** [comment]
Ok, but now...

- Settings

- Transfer ownership
Transfer this repository to another user or to an organization where you have the ability to create repositories.

- Type the name of the repository to confirm
- New owner’s GitHub username or organization name
¿? - ¿What I write here? ¿Backdrop? ¿contrib? ¿backdrop-ops?

**Comment by jenlampton** [comment]
backdrop-contrib

**Comment by klonos** [comment]
Hello @Scoppettuolo 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
