### ISSUE TITLE
Application to join contrib team - for View mode selector

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop-ops/contrib#177]
I would like to apply to join the Backdrop contrib team.

Here is a module I ported: https://github.com/Al-Rozhkov/view_mode_selector

Since issue queue for [this module](https://www.drupal.org/project/view_mode_selector) on drupal.org is disabled I asked maintainers about port in their issue queue on github: https://github.com/drupal-fancy/view_mode_selector/issues/14

The port process was simple (changes in .info file and "drupal" to "backdrop" changes). I removed Display Suite and Migrate integration because DS wasn't ported yet and probably no needed in BD ecosystem. And Migrate is in early stage of porting. That kind of functionality can be added later.

I'm not very skilled coder but going to port more complex modules if I did everything right with this one. And I'm very excited to join Backdrop community :)

**Comment by klonos** [comment]
Hello @Al-Rozhkov and welcome to the Backdrop Contrib issue queues. Before you get approval for joining the Group, lets go through the checklist for the project you ported...

New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
...all points tick, so if I could just have you agree to the following for the record:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

Additional notes for non-coders
-------------------------------

1. If an applicant is not (yet) a coder but would still like access to the
   contrib group (for example, for updating documentation or managing issue
   queues) the applicant must get at least one recommendation from another
   person who already has commit access to the contrib group.

1. Any non-coder applicant still agrees to the same contributed project author
   agreement as coders (above).

1. Any non-coder applicant needs to additionally promise that should they ever
   wish to author new code in the Backdrop contrib group, they will also undergo
   the same code spot-check process a new contributor needs to undergo at the
   time they add the code.

Abandoned Projects
------------------

You may apply to adopt an abandoned project. The procedure is as follows:

1. If you haven't already, please join the Backdrop Contrib group by submitting
   an application (see above).

1. File an issue with the current project requesting to help maintain the
   project.

  - If written permission is granted by a current maintainer, create a PR that
    adds your name to the README.md file in the list of maintainers.
  - If a current maintainer does not respond within 2 weeks [create an issue in this repository](https://github.com/backdrop-ops/contrib/issues/new) to take
    over the project. Please include a link to the issue you filed with the
    abandoned project.

1. After confirming the project has been abandoned, a Backdrop Contrib
   administrator will add your name to the list of maintainers in that project's
   README.md file.

1. You may now maintain the project directly as though given permission by the
   project maintainers, and likewise now grant permission to others to maintain
   the project.

**Comment by Al-Rozhkov** [comment]
Thank you @klonos.
I have read the Agreement and confirm that I agree to it.

**Comment by klonos** [comment]
Welcome to the Backdrop Contrib Group @Al-Rozhkov!

You can now move your project to https://github.com/backdrop-contrib and soon as you make a release, it should be at the same time published on BackdropCMS.org and also available through the Project Installer.

**Comment by klonos** [comment]
Let us know if you are having any problems by re-opening this issue.
