### ISSUE TITLE
Application to join: rszrama (Contributing my Backdrop theme "Starch")

### ISSUE THREAD

**Issue by rszrama** [backdrop-ops/contrib#178]
This is a Backdrop implementation of the Apex WordPress theme that I've been tweaking over time. It's still not "1.0.0" ready, but I'll begin using it on sites in its current state and will continue to clean out the cruft / update it for the latest developments in Backdrop core.

Repository: https://github.com/codewombat/starch
Demo site: http://ryanszrama.com/starch/

(That's a temporary demo site; will move it when I have time to fool with DNS.)

**Comment by rszrama** [comment]
Definitely open to feedback! Bugs I know about are form elements exceeding mobile screen widths (contact form on iPhone 5), pinch zoom still enabled on mobile (might be a feature?), the "Featured post" tag screwing up on taxonomy pages, and the same tag being weird when logged in as a non-administrator.

**Comment by jenlampton** [comment]
@rszrama this looks fantastic!  I'll take it for a spin on one of my sites and see if I can get you some more constructive feedback, but so far 👍

**Comment by klonos** [comment]
Hey @rszrama 👋 ...are you still interested to move this theme to Backdrop Contrib?

**Comment by olafgrabienski** [comment]
The theme looks cool at first sight. Would be nice to have it in Backdrop contrib!

**Comment by rszrama** [comment]
Happy to push it over the hump with a little support. I haven't touched it in a few years, so I can't be certain it doesn't need a little work before it's officially contributed. : )

**Comment by olafgrabienski** [comment]
> Happy to push it over the hump with a little support.

Great, @rszrama! Which kind of support would help?

**Comment by klonos** [comment]
@rszrama if you moved the project under https://github.com/backdrop-contrib and asked for co-maintainers, I'm sure people would offer to help 😉

**Comment by klonos** [comment]
Hey @rszrama 👋🏼 ...it's been a while since we've heard from you, so I will go ahead and close this issue here.

Please feel free to reopen if you are still interested.
