### ISSUE TITLE
Application to join contrib team - for OAuth

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#18]
I am making a start on porting OAuth with an aim of then working on Twitter and then Rules. I have viewed Nate's video and read the guidelines - so here goes.

**Comment by quicksketch** [comment]
Hi @Graham-72, awesome!

Could you push up a copy of the module to your own account initially, so we can make sure you're headed in the right direction? We like to check that you do a few things:

- Maintain the entire Git history (from the D7 version)
- Include a LICENSE.txt
- Update the README.md to list maintainers and credits, preferably following [the example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md).

After the basic review and you get access, you can transfer the repository over to the `backdrop-contrib` group. Thanks!

**Comment by Graham-72** [comment]
Please kindly check what I have done so far in my repository Oauth. I have tried to follow the guidance but I am a bit stuck with system_settings_form which is not picking up default values from my oauth_common.settings.json
I am struggling a bit as a complete newbie to Git!

**Comment by docwilmot** [comment]
I must say if this is your first time, you've chosen a real beast of a module to convert! Will you be up to maintaining this, given the security implications? Just curious here.
As far as system_settings_form() see this here: https://api.backdropcms.org/node/28621
You need to replace the call to system_settings_form() completely as it saves values to variables, but your form is pulling defaults from config, so your defaults will never change!
Good luck!

**Comment by quicksketch** [comment]
For reference (to myself and others) the in-progress OAuth module is at https://github.com/Graham-72/oauth. Thanks @Graham-72!

**Comment by Graham-72** [comment]
Thanks for your comment @docwilmot - the short answer is that I will not be up to maintaining it, other than porting across from Drupal any changes made to the 7.x release. But what if there are any special security issues introduced by Backdrop CMS? Hopefully someone much more knowledgable than me will help.

**Comment by quicksketch** [comment]
I think it's great to put forth the effort to port the module even if not maintaining it. For large/popular modules we may need multiple maintainers anyway. Let's just make sure that when we include it in the repository that we make it clear in the README.md that it doesn't have any active maintainers and needs some. I did that for Code Filter (https://github.com/backdrop-contrib/codefilter), just crediting myself with the port but marked it as needing maintainers.

@Graham-72, let us know here when the module is ready for a basic review (or if it is already). Thanks!

**Comment by Graham-72** [comment]
@quicksketch I think it is ready for basic review but, having worked through the changes needed for CMI, I cannot reinstall the module on my trial site. So probably I have not done something right. I get this error message on screen
![backdroperror](https://cloud.githubusercontent.com/assets/10559274/5871141/8b1b8c3c-a2d0-11e4-9ee8-038d0facbd66.png)

I am not sure how to debug this. I have looked in my server log and there is no record of an attempt to access my ...modules/oauth/config/oauth_common.settings.json file, but maybe I have missed doing something in my rework

**Comment by Graham-72** [comment]
I am no longer getting this settings file error but I have still to find out why the settings form is not saving properly.

**Comment by docwilmot** [comment]
Hi @Graham-72 

Its because your submit function is named `my_settings_form_submit()`

It should be `_oauth_common_admin_submit()` since your form is `_oauth_common_admin()`

incidentally:
You could also rename your validate function `_oauth_common_admin_validate()` and remove the custom validate function line (`  $form['#validate'][] = '_oauth_common_admin_settings_validate';`) left over from when it used system_settings_form(). Or you could leave it, it should still work as is, but just looks inconsistent with the naming convention.

**Comment by Graham-72** [comment]
Thanks very much for your help. That has fixed it.

**Comment by Graham-72** [comment]
Hi @quicksketch 

I have now completed (I think!) all the changes needed for Content Management in Backdrop CMS and the ported module does seem to be working OK. I would like now to produce a tidier repository with just a single transition from the Drupal 7 version of each file to the Backdrop version. Is this OK? Also, I started from the Drupal 7.x-3.x repo rather than the latest 7.x-4.x, because the 7.x-3.x seems to correspond with the current D7 release of OAuth. Was I right or should I work from 7.x-4.x ?

**Comment by quicksketch** [comment]
> I would like now to produce a tidier repository with just a single transition from the Drupal 7 version of each file to the Backdrop version. Is this OK?

Yes, that's great. :smile: You can make a new repo or you could probably do it on your current one with enough git-foo. It'll probably be easier making a new one, so go with that approach.

> Also, I started from the Drupal 7.x-3.x repo rather than the latest 7.x-4.x, because the 7.x-3.x seems to correspond with the current D7 release of OAuth.

That looks correct to me, based on the current release page on drupal.org. Because there are multiple releases of OAuth on Drupal.org, I'd recommend that you match your version number with the version you forked. That is, the Backdrop version branch should be `1.x-3.x`, indicating it's for Backdrop 1.x and version 3.x of OAuth module.

I also filed a small PR at https://github.com/Graham-72/oauth/pull/1.

I think with your current warning in the README.md file, you've met all the requirements that we have for joining the contrib repo:

- [x] Added a README.md with maintainers and license.
- [x] Added a LICENSE.txt file
- [x] Maintained history from Drupal 7.

There's still a bit of work to be done. Just searching the codebase I could find several references to Drupal in functions and classes, as well as a few variable_get() calls still in place. However, I think it would be more beneficial for this code to be in the contrib repository where we can work on it together rather than in an individual account. Otherwise we might end up with duplicated work.

**Comment by quicksketch** [comment]
Would you agree to the following for the record? Thanks!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by Graham-72** [comment]
I agree, with pleasure.

**Comment by quicksketch** [comment]
Invite sent! Thanks so much for your patience and effort!
