### ISSUE TITLE
Joining the contrib group

### ISSUE THREAD

**Issue by jackaponte** [backdrop-ops/contrib#180]
I'd like to join! I'm working on a few Backdrop contrib projects, most notably https://github.com/jackaponte/webform_civicrm which I'm hoping will be ready for showtime soon! I agree to the Backdrop Contributed Project Agreement, though webform_civicrm is not yet polished WRT to all of the requirements therein.

Please let me know what's next!

**Comment by klonos** [comment]
New project checklist
---------------------

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
Great to see you in the contrib queue @jackaponte! Your repo already ticks one of the 3 prerequisites. Just rename the README.txt to a .md file and make sure it includes some of the things from the linked example file like credits to the Drupal creators/maintainers and also include the LICENSE.txt file and you'll be good to go 😉

**Comment by klonos** [comment]
...just took a look to your recent commits. In https://github.com/jackaponte/webform_civicrm/commit/61de4629c12b824a271ed0ac16f0e6fc2ce838c2 you seem to have done a simple search and replace which changed a few URLs from drupal.org issues and the api subdomain to backdropcms.org, but the respective node numbers are either not present or not the same in backdropcms.org. Also quite a few instances where lower case "backdrop" should be capitalized. Would be great to have another "manual" pass at the changes if you have the time.

**Comment by jackaponte** [comment]
Thanks for the feedback, @klonos; I'm digging back into this work at long last!

I've just taken care of the LICENSE.txt and README.md tasks; I'll next work on the manual pass at changes that you noted above.

**Comment by jackaponte** [comment]
Alright, that manual pass is complete as of my [last few commits](https://github.com/jackaponte/webform_civicrm/commits/1.x-1.x-backdrop). Please give that a look when you get a chance, @klonos; thanks!

**Comment by klonos** [comment]
The two remaining checkboxes for README.md and LICENSE.txt are ticked, so you're good to go! I have not gone through all of the code to verify that you have got *all* the "Backdrop" capitalization and reverting of backdrop.org links to drupal.org, but if you missed some I'm sure they will eventually surface and be fixed.

Invite underway... 😉

**Comment by klonos** [comment]
...ooh ooh, for posterity sake, can I get you to first agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you
agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later.  See
   for the [Backdrop License FAQ](https://backdropcms.org/license) for a more
   detailed explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the
   issue tracker within 2 weeks, your project may be modified by a Backdrop
   Contrib administrator without your explicit consent.

Additional notes for non-coders
-------------------------------

1. If an applicant is not (yet) a coder but would still like access to the
   contrib group (for example, for updating documentation or managing issue
   queues) the applicant must get at least one recommendation from another
   person who already has commit access to the contrib group.

1. Any non-coder applicant still agrees to the same contributed project author
   agreement as coders (above).

1. Any non-coder applicant needs to additionally promise that should they ever
   wish to author new code in the Backdrop contrib group, they will also undergo
   the same code spot-check process a new contributor needs to undergo at the
   time they add the code.

Abandoned Projects
------------------

You may apply to adopt an abandoned project. The procedure is as follows:

1. If you haven't already, please join the Backdrop Contrib group by submitting
   an application (see above).

1. File an issue with the current project requesting to help maintain the
   project.

  - If written permission is granted by a current maintainer, create a PR that
    adds your name to the README.md file in the list of maintainers.
  - If a current maintainer does not respond within 2 weeks [create an issue in this repository](https://github.com/backdrop-ops/contrib/issues/new) to take
    over the project. Please include a link to the issue you filed with the
    abandoned project.

1. After confirming the project has been abandoned, a Backdrop Contrib
   administrator will add your name to the list of maintainers in that project's
   README.md file.

1. You may now maintain the project directly as though given permission by the
   project maintainers, and likewise now grant permission to others to maintain
   the project.

**Comment by jackaponte** [comment]
I agree wholeheartedly!

**Comment by klonos** [comment]
Invite underway! Please check to see if you can successfully transfer your port repo over to backdrop/contrib and lets us know if you have any issues. Closing this issue 😉

**Comment by jackaponte** [comment]
Many thanks, @klonos -- I'll try to transfer the port repo soon!

**Comment by jackaponte** [comment]
Oops more questions!

I transferred the repo over, yay:

https://github.com/backdrop-contrib/webform_civicrm

However, when presented with the option of giving everyone in the Authors group push permissions, I got nervous that wasn't what I was supposed to do, so I skipped it and only gave the Security group push permissions. I then found #150 where this is discussed a bit, but not settled completely. I can't figure out any way to change this now that I've transferred the repo already.

Thoughts on whether I've mucked up and what I should do to fix it, if anything?

**Comment by jackaponte** [comment]
Ah, from [this comment from @quicksketch on someone else's contrib application](https://github.com/backdrop-ops/contrib/issues/162#issuecomment-214909461) it looks like I should have granted access to the Authors group. Serves me right for being stingy! ;) Hopefully one of you will be able to change that?

**Comment by klonos** [comment]
@jackaponte, I forgot to mention that I've made some changes to the repo yesterday. Can you please check if everything works now?

**Comment by jackaponte** [comment]
Yup, the changes you made allow me to push to the webform_civicrm repo, access its settings, etc. Looks like I'm all set; thanks @klonos!
