### ISSUE TITLE
Joining the contrib group (darol100)

### ISSUE THREAD

**Issue by darol100** [backdrop-ops/contrib#181]
Hey Backdrop Community, I will like to join the contrib group. I have build a module that allows Backdrop websites to get entities data into JSON (https://github.com/darol100/json_api). This module is not been ported (or copied) by an existing project in Drupal.org. I build this project base on inspiration of a close Drupal 7 project that I work on. 

This project still under-development there are many improvements that I will like to do before an stable release. 

The [`json_api`](https://github.com/darol100/json_api) module meets all minimum requirements
- LICENSE.txt: https://github.com/darol100/json_api/blob/master/LICENSE.txt
- README.md: https://github.com/darol100/json_api/blob/master/README.md
- Maintain the Git history from Drupal 7: No applicable because I have not build it yet for D7.

 I agree on Backdrop Contributed Project Agreement.

**Comment by klonos** [comment]
Hello there @darol100!! ...you make my life easy by those links to the things we need to check. All things ticked (besides the Git history that does not apply to this case of course):

All projects must meet these minimum requirements.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

 so for posterity,

**Comment by darol100** [comment]
@klonos , I agree on Backdrop Contributed Project Agreement.

**Comment by darol100** [comment]
I just transfer this project to backdrop-contrib. https://github.com/backdrop-contrib/json_api

**Comment by klonos** [comment]
Great! Whenever you feel the module is production-ready, you can create a new release and that will show up as available for users to install it: https://github.com/backdrop-contrib/json_api/releases

**Comment by darol100** [comment]
@klonos , I will like to get some feedback from other devs, how helpful is this project for a Backdrop website and which new features might be nice to have.

I have notice that Headless project only have 1 active install -https://backdropcms.org/project/headless , which makes me think how much time and effort I should put into json_api project.

So any feedback will be appreciated.

**Comment by klonos** [comment]
@darol100 I personally do not have any need for it currently, but you never know what the future holds. Now it's out there for people to install and test. Once people start using it, you'll see issues filed in the issue queue (most likely bugs). Feedback is I am afraid inevitable and it's coming your way weather you want it or not 😄
