### ISSUE TITLE
Diff Module

### ISSUE THREAD

**Issue by tomgrandy** [backdrop-ops/contrib#182]
Is anyone currently working on porting the diff module over to Backdrop so we can track the content of revisions without making manual notations in Revision Information?

**Comment by Graham-72** [comment]
I have made a start on porting the diff module and have added it to backdrop-contrib/diff in its unfinished state. I hope to do some more work on it tomorrow (UK time). I guess there are quite a few problems to find and resolve.

**Comment by jenlampton** [comment]
I believe the diff engine is now in Backdrop core, since we are using that for the config diffs. Not sure if/what will need to be reworked b/c of that. Hopefully it will mean less work for you two! :)

**Comment by Graham-72** [comment]
At long last I have returned to working on this module and have now published a revised release 1.x-3.4.0.

I haven't used the diff engine in Backdrop core. Where would that be?

**Comment by quicksketch** [comment]
Closing this as Diff is ported: https://github.com/backdrop-contrib/diff

However, now it seems needs a new maintainer, see https://github.com/backdrop-ops/contrib/issues/680

If you're around @Graham-72, it's be wonderful to have your help. If not, still thank you for porting this module!
