### ISSUE TITLE
Create a bug-squad, and add info + process to README.txt

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#185]
It would be great to establish a more group-centric contrib environment for our maintainers. We've already taken the first step by moving all contrib projects into a GitHub "organization" where we can have teams who have various levels of access.

Should we also set up a group of trustworthy people who have permission to do things on behalf of overworked contrib maintainers? It was proposed in #169 that we set up a bug-squad who is empowered to merge bug-fix PRs that have been marked RTBC for a period of 2 weeks or more. 

We should establish Rules around who / what / when, and perhaps also process for how. Once we know these things, we should add all pertinent info into the README so that new maintainers know exactly what they are signing on for (and about all the perks of joining!)

---
PR from @jenlampton to add Bug Squad info https://github.com/backdrop-ops/contrib/pull/184

**Comment by alexfinnarn** [comment]
I like the idea of this issue as part of the discussion of changing around permissions and how contrib projects are maintained.
