### ISSUE TITLE
Backdrop Contributed Project Group Application - XML Sitemap

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-ops/contrib#186]
I would like to join the Backdrop contrib group via a port of the Drupal XML sitemap module: [https://github.com/alexfinnarn/backdrop-xml-sitemap](https://github.com/alexfinnarn/backdrop-xml-sitemap)

I think the following check boxes have all been accounted for:
- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use this copy.
- [x] Include a README.md file that includes license and maintainer information. You can use this example.
- [x] Maintain the Git history from Drupal 7. See this article.

I have also read and agreed to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement) while taking off my cap and placing my hand over my heart. 

For the good of the land, can I join your group?

**Comment by klonos** [comment]
> I think the following check boxes have all been accounted for:

Yep, they have 👍 

> ...while taking off my cap and placing my hand over my heart.

😆 

Invite underway @alexfinnarn and welcome to the Backdrop Contrib group!

PS: Sorry for taking long to respond. Been trying to sort as many things before leaving on holiday and have no time.

**Comment by klonos** [comment]
...when you get a change, you can transfer the project to the backdrop/contrib repo and soon as you make an official release, it will become available on BackdropCMS.org and then in the Project Installer. Let us know if you have any problems or need any help/pointers.

**Comment by alexfinnarn** [comment]
Thanks @klonos! and no worries on the time delay. I thought it was super quick :) It took me 11 months, 33 comments, and several "bonus" reviews to get through Drupal's Project Application Review process :/

Maybe I'm not seeing it, but how should I go about transferring the repo? I see this guide:[https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/). Do I follow that process?

**Comment by jenlampton** [comment]
Yep, that is the process.  Please note that you can also change the name of the repository (to remove the word "backdrop") as part of the transfer process.

**Comment by alexfinnarn** [comment]
okay, it is transferring now and seems to have worked...closing issue now.

**Comment by alexfinnarn** [comment]
okay, I don't know if I did the "make an official release" part right. There is an error file on the release page: [https://github.com/backdrop-contrib/xmlsitemap/releases](https://github.com/backdrop-contrib/xmlsitemap/releases)

I did have a "core = 7.x" line in the info file, but other than that it looks like other info files I see...

[https://github.com/backdrop-contrib/xmlsitemap/blob/master/xmlsitemap.info](https://github.com/backdrop-contrib/xmlsitemap/blob/master/xmlsitemap.info)
[https://github.com/backdrop-contrib/xmlsitemap/blob/master/xmlsitemap.info](https://github.com/backdrop-contrib/elysia_cron/blob/1.x-2.x/elysia_cron.info)

What is my issue here?

**Comment by alexfinnarn** [comment]
okay...I think this happened because I wasn't using semantic versioning. I tagged a new release so I'll see if that publishes the node.

**Comment by alexfinnarn** [comment]
Nevermind, I got the same error. I don't know how to fix.

**Comment by jenlampton** [comment]
What is the error message?

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by docwilmot** [comment]
Your release tag should be in the format 1.x-1.0.0

**Comment by alexfinnarn** [comment]
Thanks @docwilmot! It's showing up now.
