### ISSUE TITLE
Request for account change

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-ops/contrib#189]
I'd like to convert my @sentaidigital account to an organization, but to do so I need to leave any organizations on that account.  Would it be possible to have @sentaidigital "leave" backdrop, and  @jlfranklin join (this account) in its place?

**Comment by klonos** [comment]
I started doing this, but after I removed the @sentaidigital account I realized that this might hide a security risk (account hijack or faking another person's ID). For the sake of security and posterity, can you please post another comment here from the @sentaidigital account stating that you endorse this request and that these are indeed both accounts held by the same person?

**Comment by jenlampton** [comment]
Good Idea @klonos, great catch and I think that should be part of our policy :)

**Comment by sentaidigital** [comment]
Both @jlfranklin and @sentaidigital accounts are held by John Franklin.  The change is endorsed.  Thanks, @klonos.  The confirmation step is good security.

**Comment by klonos** [comment]
Thanx @sentaidigital / @jlfranklin ...invite underway. Let us know if you are having any issues.

@jenlampton not sure if it needs to be part of some policy. It is not that often that we get such requests.

**Comment by jlfranklin** [comment]
I've received the invite for backdrop-contrib, but not yet for backdrop.

**Comment by klonos** [comment]
That's because I have permission to do the removes/invites only on backdrop-contrib. I guess it'll take either one of @quicksketch or @jenlampton that have the "owner" role for backdrop to do the rest. Sorry about that.

**Comment by jenlampton** [comment]
> not sure if it needs to be part of some policy. It is not that often that we get such requests.

I just meant that what you are doing is exactly right!  👍  If we want to document it somewhere we can (but it may also not be necessary).

> I've received the invite for backdrop-contrib, but not yet for backdrop.

It's not my place to authorize new core committers, that needs to come from the PMC, and be executed by @quicksketch or @serundeputy.  I can give you access to the backdrop-issues repo though, was that what you meant?

**Comment by jlfranklin** [comment]
> I can give you access to the backdrop-issues repo though, was that what you meant?

Whatever access @sentaidigital currently enjoys in that group.  I don't (shouldn't!) have core commit access, so it is probably just access to backdrop-issues.

**Comment by jenlampton** [comment]
Okay, I granted @jlfranklin access to access to backdrop-issues, though @klonos you should be able to do that too. I'm setting up a "docs admin" team and adding you to it,  @klonos, feel free to add other trustworthy people as docs admins as needed.

**Comment by jenlampton** [comment]
Also closing this issue!  @jlfranklin if you find you don't have the access to do something you used to do, please re-open and let us know what that is. I can't see all the access @sentaidigital had in one place, but I don't *think* we are missing anything else.

**Comment by jlfranklin** [comment]
Thanks!
