### ISSUE TITLE
config_set defaults question

### ISSUE THREAD

**Issue by quackers8me** [backdrop-ops/contrib#19]
Not sure if this issue should be posted here but I have a couple questions about setting the defaults in hook_install.

- when a module does a config_get for site variables eg: site_name, should that be set in hook install to 'Backdrop Site' or is there a better way? And is using ini_get() recommended here?
- when a module does this: config->get('VARIABLE_NAME_' . $this->get('id'), 0); 
 is there a way to to set defaults for this in hook_install? If not what would be recommended?

Thanks.

**Comment by quicksketch** [comment]
Here is fine for now. :smile: 

There isn't a second parameter to `$config->get('foo')` to provide a default. Instead, if your module provides a set of configuration, it should include a `config` directory in its root that contains all the JSON files of default configuration. When the module is installed, the entire contents of the `config` directory within the module are copied to the active configuration directory. Likewise, when the module is uninstalled, it's automatically deleted. See the modules that come with core for examples, such as `user` or `book`. You can also bundle entire sets of functionality, such as image styles or views, by including configuration files from those modules in your module's `config` directory.

If you need to set a dynamic value upon installation, it'd be best to use hook_install(), load the config file, then use `$config->set()` to save the default value so it's available later for `$config->get()` calls.

**Comment by quackers8me** [comment]
Hi @quicksketch, I am referring to the JSON files but I was asking about site defaults. I see the answer in your reference to #621 in using the system.core settings. 
That will work for the dynamic variables.
Thank-you.
