### ISSUE TITLE
Intending to port the Site map module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#197]
Hi all, I will  likely be porting the site_map module to Backdrop shorty.  Posting here so that we don't accidentally end up duplicating efforts :)  d.o issue: https://www.drupal.org/node/2845775

**Comment by fluxsauce** [comment]
Starting on this.

**Comment by bd0bd** [comment]
> porting ... shorty

+ 5 more months?

**Comment by jenlampton** [comment]
Or so! :)

**Comment by jenlampton** [comment]
Port is up, with a release, so closing this issue.
https://github.com/backdrop-contrib/site_map
