### ISSUE TITLE
Application to join the contributed module developer team

### ISSUE THREAD

**Issue by oadaeh** [backdrop-ops/contrib#2]
I am doing this:
> To apply simply create a request as an issue at https://github.com/backdrop-ops/contrib/issues/new

I have not yet ported a module or theme to Backdrop, but I have started work on it.  I do not guarantee anything will be ready any time soon.  :)

**Comment by quicksketch** [comment]
Hi @oadaeh! Thanks so much for the work you've put in this far to Backdrop! We really appreciate it!

I also apologize for the extreme delay in responding here. I set up this repo but didn't turn on notifications. :frowning:

We drafted up an [agreement for managing contrib projects](https://github.com/backdrop-ops/contrib/blob/master/README.md#backdrop-contributed-project-author-agreement). Would you agree to the following?

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by oadaeh** [comment]
> Would you agree to the following?

Yes.

**Comment by oadaeh** [comment]
FYI, these are the Drupal projects I'm considering porting to Backdrop:

I'm the primary maintainer:
* Basic webmail
* Bluemarine (because I like it)
* Checkmail
* Courier MTA (this one might not fit with the Backdrop model)
* Mass Contact
* Plastic Theme

I'm a co-maintainer:
* Audit Files (I'm still thinkng about it)
* Email Verification
* Views Summarize

I'm not a maintainer:
* Drupal-to-Drupal data migration (except that it would be called Drupal-to-Backdrop data migration)
* Migrate
* PHPMailer (my preference over SMTP Authentication Support, although PHPMailer depends on Libraries)

**Comment by quicksketch** [comment]
Awesome @oadaeh! Sorry I got buried by e-mail yesterday and it took me a while to get to this one. Invite is on its way. Thanks!

**Comment by oadaeh** [comment]
My Git foo is not quite up to snuff, and I've spent far too long looking, how do I take an existing Drupal & project and copy it into GitHub, retaining the existing history?  Is there some doc on this somewhere, because nothing I have found sounds like the correct solution?

**Comment by quicksketch** [comment]
This would be for a module that had a 2.x release:

```
# Checkout from drupal.org:
git clone --branch 7.x-2.x http://git.drupal.org/project/[project_name].git
cd [project_name]

# Rename the branch.
git branch -m 7.x-2.x 1.x-2.x

# Remove the old origin and point at Github instead.
git remote remove origin
git remote add origin git@github.com:backdrop-contrib/[project_name].git

# Push to the new repository.
git push origin 1.x-2.x
```

I don't think we have process documented currently, that's on us. We should probably add this to the converting modules section in https://api.backdropcms.org/node/28621.

**Comment by oadaeh** [comment]
Cool.  Thanks.  Now I know what I was finding on the Interwebs was not right.  :)
