### ISSUE TITLE
Maintaining contrib module updates

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#200]
There is a useful article by David Rothstein at https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-3 however it doesn't seem to cover all issues.

Suppose a module has been ported to Backdrop and installed in a Backdrop site. The Drupal version is then updated for Drupal and includes a new update function. Suppose the fix then needs to be applied to any existing Backdrop installation, so the new release of the Backdrop module must handle both the possible migration from Drupal (from the latest release of the module) and the updating of the previous Backdrop release.

What I am wondering about is the coding of the contrib module update function so that it suits both the migration from Drupal to Backdrop as well as the update of a Backdrop installation. I am currently faced with this situation for the OAuth module and the Views Slideshow module.

To be specific, the OAuth module in Drupal now has a new function oauth_common_update_7100(). The Backdrop port already has oauth_common_update_1000() and I can add the new update to the Backdrop port as oauth_common_update_1001() but this update will already been applied if someone now wants to migrate from a Drupal installation. How can this work and what should the new Backdrop release have for oauth_common_update_last_removed ?

I'm probably missing something basic, or explained elsewhere. If so, my apologies.
@quicksketch @jenlampton or anyone, please advise me.

**Comment by jenlampton** [comment]
One thing that would be safe would be to check the value of whatever you are changing, and if it's already where you need it, don't change it again. Or, if that's too complicated, add a variable that denotes its state the first time it's changed, then check the variable the second time. I've seen that done in Drupal contrib commonly.

**Comment by Graham-72** [comment]
@jenlampton thanks for the answer.
I have added to the update in Backdrop the test
`if (!db_field_exists('oauth_common_token', 'callback_url')) {`
so that it will not attempt to add the field 'callback_url' if already added in Drupal.
