### ISSUE TITLE
Porting EqualHeights (and/or converting to matchHeight library)

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/contrib#205]
I am planning to port the [Equalheights module](https://www.drupal.org/project/equalheights). Was going to use it as a base and implement the jQuery matchHeight library instead (since it seems newer and better) but don't have time at the moment and plan to just do a simple port as is.

**Comment by klonos** [comment]
I have not examined the differences between matchHeight.js and the EqualHeights, but why not create a separate "matchHeight" module for Backdrop based on the code of https://www.drupal.org/project/equalheights ?

**Comment by laryn** [comment]
That was my initial plan, and maybe I will do that after all if I have a little extra time when I finally get to it. I started it and then realized maybe it wasn't as simple as swapping out the .js. :)

https://github.com/laryn/jquery_matchheight

**Comment by laryn** [comment]
Update: I've been learning more about `flexbox` and I doubt I will come back to this as it is working pretty well to use `display: flex;` and `flex-flow: row wrap;` on the container element. Closing the issue for now.
