### ISSUE TITLE
Porting Iframe Filter module to Backdrop

### ISSUE THREAD

**Issue by fluxsauce** [backdrop-ops/contrib#207]
Howdy, working on a D6 to Backdrop CMS upgrade and need to port https://www.drupal.org/project/iframe_filter - working on it in https://github.com/fluxsauce/iframe_filter

Notification - https://www.drupal.org/node/2864012

**Comment by fluxsauce** [comment]
Ready! https://github.com/fluxsauce/iframe_filter

**Comment by serundeputy** [comment]
@fluxsauce awesome!

Are you already a member of the contrib group?

If not please file an application, https://github.com/backdrop-ops/contrib/blob/master/README.md, and then you can transfer your port to https://github.com/backdrop-contrib and cut a release.

If you already are a member you can transfer your port at any time.

**Comment by fluxsauce** [comment]
@serundeputy sorry, I honestly thought this was my application :-) I'll explicitly file an issue for that.

**Comment by jenlampton** [comment]
Thanks @fluxsauce !  I'm going to close this issue because https://github.com/backdrop-contrib/iframe_filter exists :)
