### ISSUE TITLE
Port Draggable Views Module to Backdrop

### ISSUE THREAD

**Issue by tomgrandy** [backdrop-ops/contrib#209]
Would like to help get Draggable Views ported over to Backdrop.

@behindthepage

**Comment by behindthepage** [comment]
Hi Tom,

I see you have created a repository here
https://github.com/tomgrandy/dvport

Lets continue our discussion there.

Regards Geoff

**Comment by tomgrandy** [comment]
Sounds good.  Thanks Geoff!

**Comment by klonos** [comment]
For posterity... Draggable Views has been moved to contrib: https://github.com/backdrop-contrib/draggableviews
