### ISSUE TITLE
Backdrop Contributed Project Group Application

### ISSUE THREAD

**Issue by targoo** [backdrop-ops/contrib#21]
I would like to port a few of my modules to backdrop.

Thanks

**Comment by quicksketch** [comment]
Hi @targoo! Awesome! We like to guide the initial project to you port along, and make sure some basics are completed before we let you loose on the contrib repository. Could you push up a copy of your module to your personal Github account (or elsewhere) so we could give it a basic check? We like to ensure at least the following:

- The Git history is maintained from D7 (i.e. checkout the D7 branch, rename it to 1.x-1.x and push up to Github).
- You add a LICENSE.txt file ([GPL vs](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)).
- You include a list of maintainers in the README.md file ([example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)).

We'd also like all modules in the contrib group to be fully ported to Backdrop (e.g. no references to "drupal_" functions, variable_get(), etc) but that comes with time. Thanks!

**Comment by klonos** [comment]
Hello @targoo 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
