### ISSUE TITLE
Join Backdrop Contrib Community

### ISSUE THREAD

**Issue by jacksinn** [backdrop-ops/contrib#211]
Hey there, I'd like to join the Backdrop contrib community. I have a few modules I can port over the simplest one I just ported is https://github.com/jacksinn/backdrop-wolframAlpha which creates wolframAlpha search blocks that can be placed on a page. Im also interested in helping to port other modules or helping where I can.

**Comment by serundeputy** [comment]
@jacksinn Excellent!

Great to have your contributions.  Here is a checklist of things your port must contain:

New project checklist
----

All projects must meet these minimum requirements.

 - [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use this copy.
 - [x] Include a README.md file that includes license and maintainer information. You can use this example.
 - [ ] Maintain the Git history from Drupal 7. See this article.

---
Looks like you did not maintain the git history.  If you clone down your repo and merge your backdrop work into it that should maintain the history and get us where we need to be.  Let me know if I can help.

thanks!
~Geoff

**Comment by jacksinn** [comment]
Will do, thanks!

**Comment by jacksinn** [comment]
Updated, finally got off the road!

**Comment by serundeputy** [comment]
oh; only 3 commits!

**Comment by serundeputy** [comment]
@jacksinn for the record need you to agree to the terms here in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md

If you can give that a read and for the record here in this issue thread state if you agree or disagree (of course agreeing is required for admittance to contrib group) :) 

thanks,
~Geoff

**Comment by jacksinn** [comment]
I agree to those terms. Is there a list of modules that the community would like ported? If I port it and I'm not a maintainer how does that work if I don't have the commit history ( I mean, if I clone I'll have history)? Can I just clone the repo and still commit or can I start from scratch? Or can I be pointed somewhere that I can educate myself?

**Comment by jacksinn** [comment]
Yeah this commits are for d7. I had a d6 one that I started with and it was a simple upgrade to d7. Def not the largest project in the world - one I show people how easy it is to get started.

**Comment by serundeputy** [comment]
> Is there a list of modules that the community would like ported?

* https://github.com/backdrop-ops/contrib/issues/34
  * I'd say any module is welcome though; for example I like the `paragraphs` module and that is not on that list

> If I port it and I'm not a maintainer how does that work if I don't have the commit history ( I mean, if I clone I'll have history)? Can I just clone the repo and still commit or can I start from scratch?

* You should also file an issue in the Drupal Module's issue queue tag with backdrop port

* Using `paragraphs` as an example, here is what I do:
  * Go to this part of the project page: https://www.drupal.org/project/paragraphs/git-instructions
  * Change the drop down to the branch you want, generally 7.x-y.x
  * Copy the git clone command: `git clone --branch 7.x-1.x https://git.drupal.org/project/paragraphs.git`
  * Add your github upstream:
    * `git remote add {remote_name_you_like} git@github.com:jacksinn/paragraphs.git`

> Or can I be pointed somewhere that I can educate myself?

* https://api.backdropcms.org/converting-modules-from-drupal

**Comment by serundeputy** [comment]
also we hang out here oft: https://gitter.im/backdrop/backdrop-issues
if you are looking for more real time interaction/questions.

**Comment by serundeputy** [comment]
@klonos I gave it a code review. Everything looks great!

**Comment by klonos** [comment]
@serundeputy 👍 ...

@jacksinn there is a way to maintain both Drupal and Backdrop versions of a single module: https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time

I only have an objection there with the namespace. The original module is https://www.drupal.org/project/wolframalpha, so the respective module for backdrop (the .info and .module files, the repo name and any function names and mentions) should also be `wolframalpha` (it currently is `wolframAlpha`).

Related to that, when you transfer the project over to backdrop-contrib, please remember to remove the `backdrop-` prefix so that the end repo URL is `https://github.com/backdrop-contrib/wolframalpha`

The other two people listed as maintainers of the Drupal version (https://www.drupal.org/u/phubear and https://www.drupal.org/u/rootedlogics) are not listed in the credits section of the README.md. Can you please add them?

PS: ...you could also consider changing the text of that slide on your site to include Backdrop 😄:

> We Support Your CMS
> Whether you use Drupal 6, 7, 8 or Wordpress ...

**Comment by klonos** [comment]
...also the (human) name of the project in d.org includes the word "Search". You might wanna be consistent with that. in documentation etc.

**Comment by jacksinn** [comment]
Thanks, @klonos, for all the suggestions and I will put them into place. The naming for the repo on my end is just for sorting and I'll definitely update it for the push to backdrop-contrib. The D8 version of the wolframalpha module has a contribution from my buddy phubear and I will include him here. Rooted Logics is one of my companies and is me in a company context and I don't mind adding that either.
I'll also throw Backdrop up on the Red Sky site :)

**Comment by jenlampton** [comment]
It looks like @jacksinn is in, can we close this issue? (If it needs to stay open, please feel free to re-open again!)
