### ISSUE TITLE
Porting Paragraphs Module

### ISSUE THREAD

**Issue by jacksinn** [backdrop-ops/contrib#212]
I've created an issue on d.o https://www.drupal.org/node/2866172 letting the module maintainer(s) know of my intentions to port the module. I also saw on https://api.backdropcms.org/converting-modules-from-drupal that this is a good place to announce that as well. I chose this module because of the comment here: https://github.com/backdrop-ops/contrib/issues/211#issuecomment-290842800

The progress can be found/tracked at: https://github.com/jacksinn/backdrop-paragraphs

I've begun by updating the deprecated drupal functions. I'll likely, at first, introduce no changes/updates to the module beyond getting as much of a 1:1 comparison of the module between the two CMSs.

**Comment by PepeMty** [comment]
Any news on this issue...?
I was about to make a "port request" for paragraphs module.
Warm regards from sunny México.
José

**Comment by jacksinn** [comment]
I haven't worked on it since last year. I forget what issue I was specifically having but I think it was due to some class in core. I was talking chatting with serendeputy about it at one point. I deleted the twitter account we were chatting on so I don't have access to the prior convo. The module is here: https://github.com/jacksinn/backdrop-paragraphs

**Comment by jacksinn** [comment]
Yeah, per my commit log there was an issue with EntityAPIController https://github.com/jacksinn/backdrop-paragraphs/commits/backdropport and then a weekend or something must have happened and I totally forgot to keep working on it :/

**Comment by PepeMty** [comment]
Thanks, Jacksinn. 
I was just wondering on the fate of this module.
Best regards.

**Comment by laryn** [comment]
I see that Paragraphs has been ported and is ready for testing here:

https://github.com/backdrop-contrib/paragraphs

**Comment by herbdool** [comment]
This issue can be closed.
