### ISSUE TITLE
Porting instruction please

### ISSUE THREAD

**Issue by bd0bd** [backdrop-ops/contrib#221]
Please, can you give me a **simple** instruction how to port modules?
Step 1
Step 2
Step 3
...

These are not simple. Too much letters/words:
https://api.backdropcms.org/converting-modules-from-drupal
https://www.lullabot.com/articles/porting-drupal-7-modules-to-backdrop

**Comment by klonos** [comment]
I'm afraid there is no "easy" way to do it @bd0bd ...you can try by watching this: https://www.youtube.com/watch?v=by8mMhIpARA

**Comment by bd0bd** [comment]
Thank you! :smile: 
Video is not good solution (for me). Text is better.

I am not looking for "easy" way to do it.
I am looking for easy/simple instructions (w/o demagogy).
Step 1, step 2, step 3 ...
