### ISSUE TITLE
Group application request

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/contrib#225]
I'm porting the drupal 7 Usertabs module to backdrop and mainting it here: https://github.com/robertgarrigos/usertabs

Thus thi is my application to the contrib group.

Thanks.

**Comment by klonos** [comment]
Hey @robertgarrigos all new projects must meet these minimum requirements:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by klonos** [comment]
...the only thing I see wrong is that you don't seem to have kept the D7 commit history.

**Comment by robertgarrigos** [comment]
True. Fixed. Thanks.

**Comment by klonos** [comment]
Great @robertgarrigos!!! Now, if I can please have you agree to the following:

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib)
(Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current
   maintainer (even though joining the Backdrop Contrib group will grant you
   access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2
   `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)
   in the root of your repository. The GPLv2 license applies to all code that
   directly interacts with parts of Backdrop licensed as GPLv2 or later. See the
   [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed
   explanation.

1. You must confirm that you have the right to distribute any additional code,
   libraries, images, fonts or other assets written or created by any third
   party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing
  at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images,
     etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)
  to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities
   in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled
   for official communication.

1. If any of the above requirements are not met, your access to the Backdrop
   Contrib group -- including all projects and even those that you may have
   originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to an issue to grant
   a new maintainer within 2 weeks, your project may be modified by a Backdrop
   Contrib Administrator to add a new maintainer, without your explicit consent.

**Comment by robertgarrigos** [comment]
I agree to the Backdrop Contributed Project Agreement.

**Comment by klonos** [comment]
Thank you @robertgarrigos and welcome to the Backdrop Contrib Group!!

Invite underway:

> You've invited Robert Garrigos to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

When you feel ready, you can move the project to backdrop-contrib and soon as you make a release, it will become available for installation via the project installer.

**Comment by robertgarrigos** [comment]
Great! Thanks.
