### ISSUE TITLE
Porting 'Image Resize Filter'

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#227]
I have started porting Drupal's [Image Resize Filter](https://www.drupal.org/project/image_resize_filter) module to Backdrop.
Port request here: https://www.drupal.org/node/2874704
Repository here: https://github.com/BWPanda/image_resize_filter

**Comment by klonos** [comment]
@BWPanda you should ask permission from the original author 😄

**Comment by jenlampton** [comment]
I thought we included some/most of these features in Backdrop core?  Which pieces were missing?

**Comment by BWPanda** [comment]
@jenlampton The reason I wanted the Image Resize Filter module for Backdrop is because of this blog article: https://ilovedrupal.com/blog/drupal-tip-2-colorbox-overlay-images-ckeditor

It explains how to use that module and Colorbox (of which there's already a BD module) to automatically create lightbox-enabled images in a WYSIWYG editor.

Images have always been a struggle for me with Drupal/Backdrop; to find a solution that's flexible for clients to add images wherever they want, but to also be easy-to-use and as simple as possible.

That blog posts solution seems to be elegant, simple and ideal for me. Please do let me know if I've missed something and this is already possible with Backdrop, or if/how I should submit a pull request to core to add any missing functionality...

**Comment by BWPanda** [comment]
Maybe something like this would be better instead: https://github.com/backdrop/backdrop-issues/issues/1580...

**Comment by jenlampton** [comment]
Yeah, throwing colorbox in the mix makes it a little bit more complicated. I agree that needs to be easier but I'm not sure colorbox needs to be a core feature.

**Comment by BWPanda** [comment]
> I'm not sure colorbox needs to be a core feature

No, me either. But the ability to add 'colorbox-load' as a class to links would work I believe, and the ability to add classes to links could certainly be a core feature...

**Comment by BWPanda** [comment]
Putting this port on hold in the hopes this feature can get into core instead (see linked issue above).

**Comment by quicksketch** [comment]
I took a look at the port and it looks like it should be fairly straight-forward. It looks like it still has some calls to legacy `drupal_*` functions, but generally its coming along well!

I think we still have some issues to be resolved, especially how time has changed how we handle images. There are some useful patches on Drupal.org (e.g. https://www.drupal.org/node/2346923) but even then, things have changed a bit, such as using `srcset` to provide multiple sizes of images and then letting the browser choose the best one. It'd probably be best to start in contrib and work on a core variation afterwards.

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/image_resize_filter
