### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by sirkitree** [backdrop-ops/contrib#23]
Hi!

I've ported a module and would kindly request a review and access to move it into this organization.

https://github.com/sirkitree/codemirror

I've also submitted an issue to the original repository here:
https://www.drupal.org/node/2410485

**Comment by quicksketch** [comment]
Hi @sirkitree! This port looks great! We generally require:

- An update README.md (with maintainer list) (done!)
- Include a LICENSE.txt (done!)
- Maintain the Git history from D7 (done!)

So you're all good! Could you agree to the following for the record?

---


Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the Backdrop project
  1. A list of the past maintainers for the Backdrop or Drupal project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by sirkitree** [comment]
Agreed, fine sir!

**Comment by quicksketch** [comment]
Invite sent! So excited to have you helping on Backdrop @sirkitree!

**Comment by sirkitree** [comment]
Just an afterthought here, but in the boilerplate (I assume your first comment was a little bit of boilerplate response) you could make those first three points checkboxes that can be checked off when they're completed:

* [ ] An update README.md (with maintainer list) (done!)
* [ ] Include a LICENSE.txt (done!)
* [ ] Maintain the Git history from D7 (done!)

---
Just a thought.

**Comment by quicksketch** [comment]
Thanks, probably a good idea. ;)
