### ISSUE TITLE
Become a contributor

### ISSUE THREAD

**Issue by Steve-A-Orr** [backdrop-ops/contrib#231]
I have high hopes for using Backdrop (and convincing others to do the same). Thought I could assist with documentation first and move on to code later. Thanks for the consideration.

**Comment by jenlampton** [comment]
Thanks @Steve-A-Orr and Welcome!  We'd love to have some more help with documentation.  :) Were you hoping to help with any contrib module(s) in particular, Backdrop core, Backdropcms.org, or other places?

**Comment by klonos** [comment]
Hey @Steve-A-Orr 👋 ...I will go ahead and close this one, but please feel free to reopen and provide a link to a repository with any code for consideration.
