### ISSUE TITLE
Twilio port completed.  Shows on github, not on backdropcms/projects

### ISSUE THREAD

**Issue by mclinn** [backdrop-ops/contrib#233]
I may have missed a step somewhere.  I've imported the whole repo into backdrop-contrib; that went fine and it shows up as expected:

https://github.com/backdrop-contrib/twilio

But it's nowhere to be found on backdropcms-project, nor does it show up within my backdrop installs in the "Install modules" area.

Another quirk, don't know if it's connected but on the "Releases" tab it seems all the projects show a "Download" link with the name of the project, in addition to the .zip and tar.gz source code links.  On the twilio github page, the Release looks fine but only shows the two source code links.  I know I could zip the files and upload them but I can't imagine needing to do this, surely I've missed something?  If anyone could enlighten me I would appreciate it.

I am ready to begin the process with another small D7 module but figured I'd clear this up first.

Oh, and I am glad to be here, my first foray into "collaboration."  So far so good!

**Comment by jenlampton** [comment]
Yep, there's a packaging step too. After you add release notes on GitHub the system is supposed to automatically generate the "Download" version, and that's the version that appears on b.org and in the project browser in-app.

I checked your release on GitHub (https://github.com/backdrop-contrib/twilio/releases/tag/1.x-1.11.0) and everything looks fine to me. I'll ask at the meeting today and see if anyone has seen this before, and knows what the issue might be.

**Comment by mclinn** [comment]
Thanks @jenlampton!

**Comment by jenlampton** [comment]
@mclinn the recommended fix is to delete the release notes and add them back again, to see if that kick-starts the packager.

**Comment by mclinn** [comment]
OK, I deleted the release entirely, then redid it.  Wow, that was quick!  I just reloaded the page and it has already added the "download" link.  It's now on backdropcms.org as well.  Great suggestion, thanks!

**Comment by quicksketch** [comment]
I checked the GitHub webhook log and it doesn't look like the webhook on GitHub fired at all, so the packager on backdropcms.org never was notified the release exists. @mclinn Could you try deleting [the release](https://github.com/backdrop-contrib/twilio/releases/tag/1.x-1.11.0) (you can leave the tag itself) and then make it again?

**Comment by quicksketch** [comment]
Oh, haha. Cross-post! Yay that's great that it worked this time around. I'm not sure what caused it, other than apparently a failure on GitHub's side. Thanks @jenlampton and @mclinn!

**Comment by mclinn** [comment]
I think the old gag is "Jinx, owe you a Coke" or some such, @quicksketch!  But it worked like a charm, second try was the charm in my case.  Now I'll be more confident than ever for my next one!
