### ISSUE TITLE
Port of taxonomy_field_formatter

### ISSUE THREAD

**Issue by opi** [backdrop-ops/contrib#239]
Drupal module: https://www.drupal.org/project/taxonomy_field_formatter

Drupal issue: https://www.drupal.org/node/2915005

Work in progress: https://github.com/opi/taxonomy_field_formatter

**Comment by opi** [comment]
*My maintainer application is already done in https://github.com/backdrop-ops/contrib/issues/238#issuecomment-334390169*

**Comment by jenlampton** [comment]
Nice work! :)

**Comment by jenlampton** [comment]
I see this module is available for use now, so I'm going to close this issue :)
