### ISSUE TITLE
Versioning guide

### ISSUE THREAD

**Issue by sirkitree** [backdrop-ops/contrib#24]
Is there a versioning guide for contributors anywhere that guides us on branch names and tagging releases to indicate a contrib module's compatibility with core?

**Comment by sirkitree** [comment]
Since core is using semantic versioning (1.x and 1.0.0) and one of the first modules is using 1.x-1.x I'm assuming the following:

## Development Release Branches:
Contrib branches should reflect the core major version (1.x) followed by a hypen and then your module's major version (1.x).

## Releases:
Contrib release tags should reflect the core major version followed by a hyphen and then your module's major.minor.patch (1.x-1.0.0)

---
Does this sound right? And where is the best place to document this?

**Comment by quicksketch** [comment]
Yes! That's totally correct. We should update the page at https://backdropcms.org/develop/code, as it's our closest page currently.

**Comment by quicksketch** [comment]
I added it to the section in https://backdropcms.org/develop/code#contrib. Thanks @sirkitree!

**Comment by sirkitree** [comment]
No, no. Thank *you* sir!
