### ISSUE TITLE
Port of DP 6 Wordpress Import Module

### ISSUE THREAD

**Issue by bjoern-st** [backdrop-ops/contrib#240]
I nedded it, so I did.
I've ported the Wordpress Import Module from
https://www.drupal.org/project/wordpress_import

Issue under:
https://www.drupal.org/node/2920635

It is already working for me - I've ported my Wordpress site successfully to Backdrop, but the module needs review. So it might be a very good Idea to join the  Backdrop Contributed Project Group - so this is my official request.
You can find the ongoing work here:
https://github.com/bjoern-st/wordpress_import

Because of the Importer being able to import multilingual WP-Sites (by now only sites translated with Stella Press are supported) and to create menu entries for pages, I added a little submodule to display the language for each menu entry on the menu entry overview site .. maybe you find it useful.

Cheers Bjoern

**Comment by jenlampton** [comment]
Wow, thanks @bjoern-st, this looks fantastic! We have been discussing adding a feature like the wordpress_import module to Backdrop core, and this might be a great place for us to start! :) I really appreciate your hard work on this and your willingness to contribute back :)

> it might be a very good Idea to join the Backdrop Contributed Project Group - so this is my official request.

Fantastic! Let me just do a few checks....

New project checklist
---------------------

All projects must meet these minimum requirements.

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

It looks like the Git history may have been lost in https://github.com/bjoern-st/wordpress_import.  If you need help restoring it feel free to ask in Gitter, maybe someone in there will be able to walk you through that step: https://gitter.im/backdrop/backdrop-issues.

We'll also need an official agreement to abide by the terms here in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md

@bjoern-st If you can give that a read, and state for the record - here in this issue thread - if you agree.

**Comment by bjoern-st** [comment]
Hey @jenlampton ,

ah, yes, you're right. I missed to branch the original code . As I started this project it was just for me - so I just downloaded the compressed repo. It took a while for the awareness, that it might be useful in general. Shame on me -- I'll try to fix fix :-) 

Concerning to https://github.com/backdrop-ops/contrib/blob/master/README.md 

I agree ! :-) 

Cheers Bjoern

**Comment by jenlampton** [comment]
Fantastic, thanks @bjoern-st.  Please add a comment here when you have the Git history restored, and I'll be happy to add you to the contrib-group! :)

**Comment by bjoern-st** [comment]
@jenlampton avec plaisir :-)

**Comment by bjoern-st** [comment]
Hey @jenlampton 

I restored the git history of the master branch, but that was not that efficient as expected.

**Comment by jenlampton** [comment]
Looks great! Thanks @bjoern-st :) I've sent you an invitation to join the contrib group.

Please to use this issue if you need help transferring the repository over to the group (sometimes admin permissions are lost in the transfer - I'll be available to restore them to you afterward if that happens)
