### ISSUE TITLE
Enhance multilingual menus 

### ISSUE THREAD

**Issue by bjoern-st** [backdrop-ops/contrib#242]
Hey 
I've developed two modules to make menu items more usable for multilingual sites. 

The first one adds the ability to add a language to a menu item / menu link - see 
https://github.com/bjoern-st/language_menu_item

The other module will simply add an additional row with the language for the menu item / menu link item in the menu overview form - see 
https://github.com/bjoern-st/menu_overview_enhance

Issue : It might be a good idea to bring it as on module.
Request : To make this stuff really useful and concerning to that issue (https://github.com/backdrop/backdrop-issues/issues/1690  )it would be great to implement something like templete_preprocess_block in that module, too and to recognize menu blocks. With that facility it would be easy to filter out menu items that do not belong to the current language - so it is only one menu block per menu left.
( Please have a look at https://github.com/bjoern-st/language_menu_item/wiki/Make-language-sensitive-menu-blocks )

Any ideas and / or support to make menu blocks recognizable? 

 Cheers Bjoern.

**Comment by olafgrabienski** [comment]
@bjoern-st I just saw that the "other module" points to the same page as the "first one".

**Comment by bjoern-st** [comment]
@olafgrabienski Thank you .. I've fixed that.

**Comment by docwilmot** [comment]
@bjoern-st sorry but I didnt understand what is your request in your first post.

**Comment by bjoern-st** [comment]
Hello @docwilmot 

I came across that while porting the wordpress_import module, because I added an option to import a multilingual Wordpress site. 

I think, the usual way in backdrop would be to create one menu for each language, add them all to your layout(s) and set the visibility of each block to one language. 

I tried a different way:
You can give menu items a language like you can do for nodes. So the idea is to give menu items a language and to display only those items in the menu, that belong to the current language. So only one menu block per user menu is needed. 

But right now that is hardly supported in backdrop (please see this issue, too https://github.com/backdrop/backdrop-issues/issues/2907).

The other problem is, that even if you give menu items a language context, the core functions that build the menu tree doesn't respect that, so the menu items of all languages are displayed in the menu tree.

So the task is to filter those menu items out, that doesn't belong to the current language.
For that some preprocessing is needed. One approach is to preprocess the menu block(s) as described here: https://github.com/bjoern-st/language_menu_item/wiki/Make-language-sensitive-menu-blocks 

The disadvantage here is: if I have several menu blocks I have to name each block in the preprocess function
to make it work. 
Of course the better and more friendly way for site developers would be, that the preprocess function can recognize user menu blocks and do the work. 

So I aked for help or suggestions how to reliably recognize user menu blocks in the preprocess function

I hope,that makes it more clear ..

**Comment by quicksketch** [comment]
I think we can close this now that we support multilanguage menus directly in core: https://github.com/backdrop/backdrop-issues/issues/225

This was more effort than @bjoern-st's implementation, but it comprehensively added the language functionality to menu items, including a UI and the filtering per-language ability.
