### ISSUE TITLE
Intend to port the drupal module patchinfo

### ISSUE THREAD

**Issue by bjoern-st** [backdrop-ops/contrib#243]
Im going to port the Module Patchinfo to Backdrop.
I think it is very useful for all developers and / or operators working with backddrop before updating.
It is a still growing project, so it might be useful.
Please see https://www.drupal.org/project/patchinfo for more information.

Issue: https://www.drupal.org/project/patchinfo/issues/2924180

Ongoing work: https://github.com/bjoern-st/patchinfo

**Comment by jenlampton** [comment]
Thanks for your work on this module @bjoern-st! :)

**Comment by bjoern-st** [comment]
@jenlampton You are very welcome . I needed it and so I had to port it. And it has been developed by some colleagues of mine .. so it is by default a great module :-)

**Comment by stpaultim** [comment]
https://backdropcms.org/project/patchinfo
