### ISSUE TITLE
Easy Breadcrumb Port

### ISSUE THREAD

**Issue by deaddred** [backdrop-ops/contrib#247]
Looking for someone to port https://www.drupal.org/project/easy_breadcrumb I could throw in some $$ to get it done quicker.

edit: here's the [maintainer notification on d.o](https://www.drupal.org/project/easy_breadcrumb/issues/2938397)

**Comment by jenlampton** [comment]
@deaddred I'd be willing to take on this port for you. What's your timeline? When do you need it done?

**Comment by deaddred** [comment]
I can wait for after the holidays as I still have to add content to the site so the breadcrumbs as not that important atm.

**Comment by jenlampton** [comment]
okay, I'll take a closer look this weekend and see how much work is involved. Did you have a budget in mind?

**Comment by deaddred** [comment]
No budget set but you can let me know how much you think it would cost if its ok I'll pay it if not might haggle a little lol.

**Comment by deaddred** [comment]
Hi Jen

Can you let me know when you can start and what you would charge?

**Comment by jenlampton** [comment]
Yes, sorry for the delay. I'm hoping to have some time for it this weekend! How about I port the module, tell you what it would cost at a 50% yay-you're-supporting-backdrop discount, and then you can pay me whatever seems fair?

**Comment by deaddred** [comment]
Sure :)

**Comment by jenlampton** [comment]
Voila! https://github.com/backdrop-contrib/easy_breadcrumb 

Do you want to give it a test and let me know if it's working as expected for you?  If so, I'll make an official release!

**Comment by deaddred** [comment]
Hi Didn't forget just was busy I'll be free Sunday so will test it out and send the funds over.

**Comment by jenlampton** [comment]
Sounds great! Let me know how it goes.

On Feb 2, 2018 7:25 PM, "deaddred" <notifications@github.com> wrote:

Hi Didn't forget just was busy I'll be free Sunday so will test it out and
send the funds over.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/backdrop-ops/contrib/issues/247#issuecomment-362774269>,
or mute the thread

**Comment by deaddred** [comment]
Ok so far seems to work. A few bugs listed below. Also do you have a non paypal payment method or are you able to send me an invoice  from Paypal as I don't have an account.

Show breadcrumb separator after the final breadcrumb. This seems reveresd as you have to select this in order to hide the separator after the final breadcrumb
and
Grammar/spelling in this "Include the a link to the home page as the first breadcrumb."

**Comment by jenlampton** [comment]
> A few bugs listed below.

I've moved the issues you noted into the issue queue: https://github.com/backdrop-contrib/easy_breadcrumb/issues

> Also do you have a non paypal payment method or are you able to send me an invoice from Paypal as I don't have an account.

Do you have Venmo? https://venmo.com/jenlampton  If not I can send you an invoice, but I'll need your email address.

**Comment by deaddred** [comment]
Ok Venmo is not available in Canada. I send you a msg from your site.

**Comment by deaddred** [comment]
Hey did you get my message from your site?

**Comment by jenlampton** [comment]
No! Hm, I'll need to check on that site's ability to send mail... Can you try this one?  (I tested it, I know this one works :)

**Comment by jenlampton** [comment]
Oh no! I hope you feel better soon. No rush on my end!

**Comment by deaddred** [comment]
Hi

I just send you a message on your contact form.

Arek

**Comment by jenlampton** [comment]
I got it, thanks :)  I'm going to close this issue, and will create an official release shortly!
