### ISSUE TITLE
Requesting contrib access; porting Token Filter

### ISSUE THREAD

**Issue by jerry-hudgins** [backdrop-ops/contrib#249]
I've ported Drupal's Token Filter module to Backdrop.

Upstream issue: https://www.drupal.org/project/token_filter/issues/2928473
Port repository: https://github.com/jerry-hudgins/token_filter

I agree to the terms of the Backdrop Contributed Project Agreement.

**Comment by jenlampton** [comment]
Hi @jerry-hudgins! Thanks for your work on porting Token Filter, and welcome to Backdrop contrib! Let's see here...

New project checklist
---------------------

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [x] official agreement to abide by the terms here in the Backdrop Contributed Project Agreement section: https://github.com/backdrop-ops/contrib/blob/master/README.md

It doesn't look like [the commit history](https://github.com/jerry-hudgins/token_filter/commits/1.x-1.x) has been maintained from the Drupal project.   [Here's an example](https://github.com/backdrop-contrib/geolocation/commits/1.x-1.x) of what a project looks like when it does. You can see all the old Git commits from the Drupal project there.

Here's my usual process for maintaining git history:

* git clone drupal project
* apply/commit any patches you want from the Drupal queue
* checkout new branch for backdrop
* remove all Drupal tags & branches
* make any changes necessary for Backdrop (or in your case, copy/paste in working Backdrop version of module and commit, or merge in current branch with separate commits)
* push new branch to GitHub

Ping us in [Gitter chat](https://gitter.im/backdrop/backdrop-issues) if you need any help!

**Comment by jerry-hudgins** [comment]
Thanks for the response, @jenlampton. However, I believe that I did maintain the Drupal commit history; I see it [here](https://github.com/jerry-hudgins/token_filter/commits/1.x-1.x). I followed the process provided by [David Rothstein's video](https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2) to do so. Granted, the history is brief.

**Comment by jenlampton** [comment]
Thanks @jerry-hudgins, I must be going crazy today. Maybe the briefness was throwing me off?  I've ticked the box and granted you access to contrib :)

**Comment by jerry-hudgins** [comment]
Everything looks good, at least after I added the "type" specifier to the .info file. Thanks for your help!

**Comment by jenlampton** [comment]
My pleasure! :)
