### ISSUE TITLE
PACKAGING_ERROR_LOG.txt

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#250]
Please tell me what I did wrong: https://github.com/backdrop-contrib/auto_menu_settings/releases/tag/1.x-1.0.0-beta.1

I followed https://semver.org/ in adding/formatting the 'beta' tag, and marked it as a 'pre-release' in Github, so not sure why I got an error...

**Comment by jenlampton** [comment]
In the `PACKAGING_ERROR_LOG.txt` file it says: `The version string "1.x-1.0.0-beta.1" does not match the required format of the "project_release" node type.`

I think the tag needs to be 1.x-1.0.0-beta1, though we really *should* support numbering from https://semver.org.  @quicksketch can you confirm that the final period is what's causing the problem?

**Comment by BWPanda** [comment]
@jenlampton That appears to have worked, thanks! https://github.com/backdrop-contrib/auto_menu_settings/releases/tag/1.x-1.0.0-beta1

Yes, be good to properly support semver.org numbering/versioning.

**Comment by jenlampton** [comment]
Created https://github.com/backdrop-ops/backdropcms.org/issues/443, closing
