### ISSUE TITLE
Application to contributor community

### ISSUE THREAD

**Issue by bizmarkdev** [backdrop-ops/contrib#252]
I request joining the contributor community for Backdrop. 

My first project is a port of the [Drupal 7 Real Name module](https://www.drupal.org/project/realname). [The repository for this port is here](https://github.com/bizmarkdev/backdrop-realname). 

I agree to all items in the Backdrop Contributed Project Agreement.

Thanks for all you do.

**Comment by bizmarkdev** [comment]
Hi Jen -

I've got my github repository updated with what was missing: added
README.md, remove hook_help(), clean-up whitespace and code format in
realname.module. I think it's ready:
https://github.com/bizmarkdev/backdrop-realname  Let me know if more needs
to be done.

A few things:

I'm happy to list myself as the maintainer for this, but I don't know how
much I'll be able to troubleshoot code if something breaks. I'll do my best
to follow changes in the 7.x project on Drupal and I'll also tend to
whatever messages come up in the issue queue. I'll try and do my best. If
you can go with that, then great. I'll learn as we go. I certainly learned
a bunch this weekend!

Do I respond to this message to backdrop-ops/contrib? Does that get back to
you? How do I communicate with whoever is managing backdrop-contrib?

What is the next step to get the repository from bizmarkdev over to
backdrop-contrib?

Mark

-------------------------------------
Mark Hicks, MSTC
512-923-1031
http://www.linkedin.com/in/markhicks

**Comment by bizmarkdev** [comment]
Well, it didn't take long to find my first snag ... I missed the files in
the test subdirectory...
class RealnameEntityTest extends DrupalWebTestCase

I'll work on this early next week.

Mark

-------------------------------------
Mark Hicks, MSTC
512-923-1031
http://www.linkedin.com/in/markhicks

**Comment by jenlampton** [comment]
> I've got my github repository updated with what was missing: added README.md

Fantastic, that was all that was needed!  I've sent you an invite to join the contirb group.  Welcome!

> I'm happy to list myself as the maintainer for this, but I don't know how much I'll be able to troubleshoot code if something breaks. 

That's fine, the only reason we *require* a maintainer is so that we have someone to contact if there is a security issue. All other problems can be posted in the public queue and worked on collaboratively. You don't need to be responsible for fixing anything (though that's nice) you'll only need to be responsible for merging in fixes (fixes can be both created and tested by others!)

> I'll try and do my best.

And we'll help you!

> Does that get back to you? How do I communicate with whoever is managing backdrop-contrib?

Yes this issue queue is for the people managing backdrop-contrib. I see all these issues, though maybe not instantly :)

> Well, it didn't take long to find my first snag ... I missed the files in the test subdirectory...

That's fine. We can create an issue in the queue for your project. When you move that project into the backdrop-contrib group (and rename it) the issue queue will move along with it! :)

**Comment by docwilmot** [comment]
Hello @bizmarkdev any plans to move this to Backdrop contrib?

**Comment by herbdool** [comment]
Looks like someone else ported it in the meantime https://backdropcms.org/project/match_redirect

**Comment by klonos** [comment]
@jenlampton has already sent an invite to @bizmarkdev to join the contrib group, so I think that it is OK to close this issue.

@bizmarkdev welcome!! 🎉 😄 ...and feel free to port any other module.

**Comment by herbdool** [comment]
Looks like we need your port after all. The other one is mostly empty.

**Comment by klonos** [comment]
@bizmarkdev sorry if it's too late, but I've noticed that you have not accepted the GitHub invite that we've sent your way (it shows as failed in the admin backend). Are you still interested to contribute to Backdrop? Would you like us to resend the invite?

**Comment by bizmarkdev** [comment]
Thank you, Greg - I'm not using Backdrop so please remove me from
the mailing list. Thanks for all you folks do.
Mark

-------------------------------------
Mark Hicks
Mobile: 512-923-1031
Skype: mkhicks
Linked-in: https://www.linkedin.com/in/markhicks/

**Comment by jenlampton** [comment]
Thanks @bizmarkdev,

This should be the last email you get about this issue (since I will close it now) but you'll need to use the link in the email to unsubscribe permanently, if that's what you prefer. (We don't have that kind of access for GitHub emails, unfortunately)

Happy Holidays!
Jen
