### ISSUE TITLE
Intent to port module profile2_regpath to backdrop

### ISSUE THREAD

**Issue by bjoern-st** [backdrop-ops/contrib#253]
With this module you can give each profile created with the profile module an individual regestration path with the ability to preselect registration fields an user role.

Issue on drupal:
https://www.drupal.org/project/profile2_regpath/issues/2947783

Ongoing work found here:
https://github.com/bjoern-st/profile_regpath

**Comment by bjoern-st** [comment]
##Idea for the registration path module.
###What this module does: 
This module enables administrators to set unique registration paths per Profile profile type with the option to assign different roles to each registration path.  (see https://backdropcms.org/project/profile for infos about profile module)

I've almost finished the port of this module and by now it has a dependency to the profile module. 
But perhaps it is a good idea to make it by default a standalone module with an **option** to integrate with the profiles module.
Any suggestion or opinion is welcome.

**Comment by docwilmot** [comment]
So if not dependent on profile what would this do on its own?

**Comment by bjoern-st** [comment]
You could at least assign different user roles during registration. 
I stumbled about this point in several discussions.
