### ISSUE TITLE
Requesting access to the backdrop-contrib group (New Relic RPM module)

### ISSUE THREAD

**Issue by hosef** [backdrop-ops/contrib#255]
I would like access to the backdrop-contrib repository.

I am a maintainer for the New Relic RPM module and i have ported it to backdrop.
[Drupal module](https://www.drupal.org/project/new_relic_rpm)
[Backdrop module](https://github.com/hosef/new_relic)

I agree to all items in the Backdrop Contributed Project Agreement.

**Comment by jenlampton** [comment]
Hi @hosef!

Here's our checklist:

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. 
- [x] Include a README.md file that includes license and maintainer information. 
- [x]  Maintain the Git history from Drupal 7. See this article.
- [x]  agree to all items in the Backdrop Contributed Project Agreement.

I've sent you an invite. Welcome to Backdrop contrib!
