### ISSUE TITLE
Joining Request

### ISSUE THREAD

**Issue by iyyappanuni** [backdrop-ops/contrib#257]
Hi Team,

I am a Drupal developer and developed the drupal contrib modules. I would like to join Backdrop community. My drupal profile - https://www.drupal.org/u/iyyappangovind-0

**Comment by jenlampton** [comment]
Hello @iyyappan-unimity and welcome to the backdrop community! We'd love for you to be a part of the [Backdrop contrib group on GitHub](https://github.com/backdrop-contrib) :)

This is how the process usually works:
1) You create (or port from Drupal) a contributed module, theme or layout, and push it to GitHub as your own project.
2) We'll do a very cursory review of the project making sure it meets our [New project checklist](https://github.com/backdrop-ops/contrib#new-project-checklist)
3) You'll provide us with a written statement (here, in this issue) saying you agree to the terms in [our agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)
4) we grant you access!

If you don't have any Backdrop code ready yet, you are also welcome to join as a co-maintainer or issue-queue manager of any existing project. In that case you'll need two [existing members](https://github.com/orgs/backdrop-contrib/people) to vouch for you, one of them preferably a current maintainer of the project you would like to help with.

**Comment by klonos** [comment]
Hello @iyyappanuni 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
