### ISSUE TITLE
Port Antibot module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#260]
I've had some real luck with the Antibot module in Drupal 7 and would love to see this ported to Backdrop. I'm looking at moving a few sites to Backdrop and would like solid SPAM protection. Also open to other recommendations. 

https://www.drupal.org/project/antibot

Someone posted a request for a backdrop version of this module in the Drupal issue queue: https://www.drupal.org/project/antibot/issues/2935836

**Comment by klonos** [comment]
> Someone posted a request for a backdrop version of this module in the Drupal issue queue ...

That someone was @BWPanda :)

**Comment by BWPanda** [comment]
Ha, well there you go 😉 Might take a look at this again, would love to get away from using Recaptcha if possible...

**Comment by BWPanda** [comment]
I want better spam protection for Backdrop, but I don't know what's better. So I decided to test different methods. I've written a blog post about it here: https://panda.id.au/posts/anti-spam-test-introduction

Basically, after the test results come in in a month's time, I'll make a decision about what module I want to use in Backdrop and then use/port that.

Sorry, but I won't be porting Antibot just yet. Someone else feel free in the meantime.

**Comment by docwilmot** [comment]
Any progress on this yet? Been a month.

**Comment by BWPanda** [comment]
I've had absolutely no submissions on any of my test forms (even the control with no spam protection). Guess spambots aren't finding my site... Not sure what to do about that. Suggestions?

**Comment by stpaultim** [comment]
Need to post link to your site in some public venues. Tweet about it or post links on a page that is already well established. Spambots need to find out about it somewhere.

**Comment by BWPanda** [comment]
Can I post a link in this public venue...? :-)
http://spamtest.panda.id.au/

I've also gone ahead and added an XML sitemap, and articles that I've copied (and credited) from the internet to add more text and comment forms to the site (spambots can't resist those right?).

**Comment by jenlampton** [comment]
I'm going to take a stab at a port of antibot module. I have a client who is asking for another spam protection method, and I'd like to give it a try.

**Comment by jenlampton** [comment]
The antibot module is here: https://github.com/backdrop-contrib/antibot

**Comment by docwilmot** [comment]
Did you just port that in 27 minutes? On fiya!

**Comment by BWPanda** [comment]
Nice, thanks @jenlampton! If I ever get the results from my spam test and decide to use Antibot, I'll make sure to give it a thorough test ;-)

**Comment by docwilmot** [comment]
> conversion from variables to config 

You know the Coder Upgrade module does that right?

**Comment by jenlampton** [comment]
> You know the Coder Upgrade module does that right?

Yes, but since there were only two variables it almost wasn't worth it to set up coder upgrade ;)

**Comment by stpaultim** [comment]
Great work. I'll be installing it ASAP to give it a spin.

**Comment by jenlampton** [comment]
@stpaultim I've already found an omission, please use a git clone to test (because it has the default config values). I'll create a new release as soon as I we determine there isn't anything else that needs fixing :)
