### ISSUE TITLE
Port Menu Link Weight to Backdrop

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#261]
https://www.drupal.org/project/menu_link_weight

I have posted a ticket against Backdrop core to solve the problem that this module is trying to solve: https://github.com/backdrop/backdrop-issues/issues/3029

Getting things in core takes time, so in the meantime, porting the module over would be nice :)

**Comment by indigoxela** [comment]
FTR this module has been released for Backdrop last summer:

https://backdropcms.org/project/menu_link_weight

**Comment by olafgrabienski** [comment]
Thanks for porting this useful module, @indigoxela! (Labeled the issue as "Port complete".)
