### ISSUE TITLE
Nagios module and Application to join backdrop-contrib

### ISSUE THREAD

**Issue by MegaphoneJon** [backdrop-ops/contrib#263]
I ported the Nagios module (https://github.com/MegaphoneJon/nagios/tree/1.x-1.x) to Backdrop.  I only had a single site running it, but I shared it with Palante Tech, who confirms it works on their Backdrop sites as well.  I'd like to submit it to the contrib repo.

**Comment by jenlampton** [comment]
Welcome to Backdrop @MegaphoneJon! Thanks for porting the Nagios module :)

**Comment by klonos** [comment]
Hello @MegaphoneJon and thank you for porting the module! ...sorry for the really late response.

According our [New Project Checklist](https://github.com/backdrop-ops/contrib#new-project-checklist), all projects must meet these minimum requirements:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

- I see that you have included a LICENSE.txt file that indicates the code is GPL v2, so we are good on that 👍 
- you will need to rename your README.txt to README.md though, and also please remove any Drupal-specific references. This file will also need to mention the original D7 maintainers (for credits purposes), as well as the current maintainers. If you do not wish to maintain this module, then a "Seeking maintainers" line will do 😉 
- Unfortunately, https://github.com/MegaphoneJon/nagios/commits/7.x-1.x shows that the commit history has been maintained for each branch, but [the branches have not been cleaned up](https://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2#cleaning-up-branches-and-tags). Can you please do this? Ideally, there should be a single `1.x-1.x` branch, which should have been a rename of the 7.x branch (`git branch -m 7.x-1.x 1.x-1.x`)

Another thing is that out of courtesy, we usually open an issue in the d.org queue, letting the original module maintainers know of our intention to port the module, also asking if they are interested in either doing the port themselves, and/or if they want to help maintain the Backdrop port. I could not find [any such ticket in d.org in the Nagios module queue](https://www.drupal.org/project/issues/nagios?text=backdrop&status=All&priorities=All&categories=All&version=All&component=All) though. Here's an example such issue for another module: https://www.drupal.org/project/submitted_by/issues/2429943

**Comment by MegaphoneJon** [comment]
Thanks @klonos - I'm not ignoring this but have to prioritize some client work first.  I'll try to deal with this after my August vacation.

**Comment by klonos** [comment]
Perfectly understandable @MegaphoneJon ...it's not as if I have responded in a timely manner either. Sorry 😅...just let me know once ready (might be faster if you jumped into the Gitter channel and "pinged" me)

**Comment by klonos** [comment]
Friendly "ping" @MegaphoneJon 😄

**Comment by klonos** [comment]
I hope that 2019 has found you in great health @MegaphoneJon. Second friendly ping 😄

**Comment by klonos** [comment]
Hello @MegaphoneJon 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.

**Comment by MegaphoneJon** [comment]
Thanks @klonos - I was contacted by @jackalope just last month, and we discussed that Palante Tech would take over this port.
