### ISSUE TITLE
Menu Attributes

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#269]
The Menu Attributes module is one of the top Drupal modules that doesn't exist for Backdrop yet. 

There's an issue in the Drupal queue where two people have begun to work on the port, that contains some early code: https://www.drupal.org/project/menu_attributes/issues/2871103

@quicksketch completed the port of the Menu Attributes module during a Backdrop CMS training workshop at Twin Cities Drupal camp in June of 2018. The corresponding Backdrop issue for this port is located here: https://github.com/backdrop-ops/contrib/issues/269 and the module should be available shortly in the Backdrop contrib repo.

**Comment by jenlampton** [comment]
There's also been a recent request for the module in the Forum: https://forum.backdropcms.org/forum/advanced-menu-link-setup

**Comment by klonos** [comment]
Someone seems to be answering forum questions as the drop user 😄

**Comment by jenlampton** [comment]
The dragon is a helpful resource for people :)

**Comment by jenlampton** [comment]
Menu attributes has been posted in contrib: https://github.com/backdrop-contrib/menu_attributes
