### ISSUE TITLE
Porting Contact Forms

### ISSUE THREAD

**Issue by behindthepage** [backdrop-ops/contrib#27]
Hi Nate,

I am nearly finished the port of my Drupal Module Contact Forms over to Backdrop. I will get it up on my account for you to look it over soon.

Two Questions (no rush to answer these)
1. Will a name change from Contact Forms to Contact Plus be problematic in the context of Git or for users. Listening to myself I probably should just leave the name as is.

2. I want to create a view of Contact Form Categories and other information that is stored in the contact.categories.json and contact_forms.extras.json files. Is this possible and how would I go about it?

Regards
Geoff

**Comment by jenlampton** [comment]
Hi @behindthepage,

1. It would probably be best to keep the name the same, just so people upgrading don't run into problems.
2. You may need to add views integration to the contact forms module, or port the existing Drupal 7 integration to Backdrop, if it exists.  There are some examples of similar ports of views integration in core, check out comment, node, and search for examples.

Let us know if you have any other questions :)

**Comment by behindthepage** [comment]
Hi @jenlampton,

1. I will leave the name as is.

2. I am familiar with views integration and the examples you mentioned have the data in the database but in this case the data is in the config files. Any examples of views displaying data from config files?

Regards
Geoff

**Comment by jenlampton** [comment]
Interesting....  @quicksketch was the views integration for comment, node and search not fully ported to CMI?  I had thought that it was.

**Comment by behindthepage** [comment]
Hi @jenlampton. I am not sure we are on the same wave length. Let me 

The Node and Comment modules each have a database table called "node" and "comment" where the data for each node and comment is stored. The Admin Content view pulls the data of all the nodes from the node table. The contact module doesn't have a database table. It stores all the categories (recipients) for the site wide contact form in a config file. 

I want to create a view of contact form categories but I am starting to think this is not possible because the views system is table based. 

Regards
Geoff

**Comment by quicksketch** [comment]
>  I want to create a view of Contact Form Categories and other information that is stored in the contact.categories.json and contact_forms.extras.json files. Is this possible and how would I go about it?

If you'd just like to use this information in a view of something else, it's pretty trivial to pull in this information from config in your field handlers. However, to actually make a *listing* of contact categories in Views... I don't know. That seems like it'd be pretty tricky. You might be able to fake it by overriding the `query` method in a field handler, but this is definitely turning into making Views do things for which it wasn't intended. Depending on your situation, you may find it more practical to forgo using Views at all and build the display page by hand with a normal template to override it.

**Comment by behindthepage** [comment]
Thanks @quicksketch I will build a display page and over ride it with a template.

**Comment by quicksketch** [comment]
Great, good luck @behindthepage :smile:

I think this was intended to be closed. Reopen if you have more on this question.
