### ISSUE TITLE
Intent To Port Match Redirect

### ISSUE THREAD

**Issue by kreynen** [backdrop-ops/contrib#272]
https://www.drupal.org/project/match_redirect provides redirecting based on path patterns with wildcards. This functions much like how block page visibility works. You specify a pattern like "old-blog/*" and a target like "new-blog" and all pages under old-blog will be redirected to the page new-blog.

I've opened https://www.drupal.org/project/match_redirect/issues/2986976, but the maintainer of the Drupal project has been MIA for years so I'm not expecting a response.

The integration between redirects and 404s in admin/config/urls/redirect/404 in Backdrop is a really brilliant feature!  Unfortunately, it requires dblog.  

We've done something similar at CU altering menus and permissions so that site owners can resolve 404s based on the top 404s reported to Google Analytics.  Resolving 404s is really improves both the user experience and server performance, but running dblog would be too much of a hit for us. 

Once I finish the initial port of match_redirect, I'm going to alter it so it's UI integrates with the core redirect UI as well as adding support for path/querystring preserving redirects.

**Comment by kreynen** [comment]
Got https://github.com/kreynen/match_redirect functional in < hour.  Still working on https://github.com/kreynen/match_redirect/issues/1, but a wildcard redirect can be created and it works.

**Comment by alexfinnarn** [comment]
I can confirm that @kreynen has completed the listed checks...

- [x]  Include a LICENSE.txt file that indicates the code is GPL v2. You can use this copy.
- [x] Include a README.md file that includes license and maintainer information. You can use this example.
- [x] Maintain the Git history from Drupal 7. See this article.

**Comment by kreynen** [comment]
I agree to the CLA too

**Comment by serundeputy** [comment]
@klonos can you approve @kreynen 's maintainer app and add him to backdrop-contrib group if everything is to your satisfaction?

**Comment by klonos** [comment]
@kreynen please rename the default branch to 1.x-1.x (currently 7.x-1.x). In trust that you will do that, I have just sent an invite:

>You've invited kreynen to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by klonos** [comment]
...please let me know if you have any issues.
