### ISSUE TITLE
Maintainer Application: Port of the Google Custom Search Engine

### ISSUE THREAD

**Issue by jeor0980** [backdrop-ops/contrib#274]
Google Custom Search Engine (CSE) is a free service that can be used to search a set of one or more sites. The Google CSE uses Google's index of the site. Content changes are not immediately reflected in the results the way they are with Drupal's core search.

https://www.drupal.org/project/google_cse
https://www.drupal.org/project/google_cse/issues/2987920

**Comment by jeor0980** [comment]
Ported Bundle Repo: https://github.com/jeor0980/google_cse

**Comment by herbdool** [comment]
Looks like project meets the checklist: license, Drupal commit history and README.

**Comment by klonos** [comment]
Indeed, the project meets the requirements:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2.
- [ ] Include a README.md file that includes license and maintainer information.
- [ ] Maintain the Git history from Drupal 7.

Thank you @jeor0980 for porting the module over 👍. For the record, can I please have you state that you agree with the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)?

**Comment by klonos** [comment]
PS: this is optional, but @jeor0980 can you please also consider doing the following:

- Add a section in your readme that says the following:

    ```
The current version of this module is in parity with the 7.x-3.0-alpha1+4-dev version of the respective Drupal 7 module.
    ```

-  Add a line in the module (and any submodules) .info file with the following:

```
parity = 7.x-3.0-alpha1+4-dev
maintainers[] = jeor0980
```

I have assumed that you have started work from the latest 3.x dev version. If not, then change the lines above to match the version you branched off of.

Thanks

**Comment by klonos** [comment]
Invite underway @jeor0980:

> You've invited Jesus Ortiz to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome onboard! 🎉

**Comment by klonos** [comment]
I'm going to assume that you have received your invite @jeor0980 and that it is OK to close this now.
