### ISSUE TITLE
Intent To Port Site Verify Module

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-ops/contrib#275]
I saw the site_verification module, https://github.com/backdrop-contrib/site_verification, and looked at it hoping that it would have the features I need.

I almost filed some issues on features I'd like to add to that module, but the D7 Site Verification https://www.drupal.org/project/site_verify module already has those features...it is what we use in D7.

That D7 module also has extensible hooks for adding verification engines, a custom and file upload option, and at least one test. For these reasons, I intend to port the D7 version of Site Verification.

D7 issue: https://www.drupal.org/project/site_verify/issues/2987923

**Comment by alexfinnarn** [comment]
Read over https://github.com/backdrop-ops/contrib/blob/master/README.md

Complete the three checkboxes listed in https://github.com/backdrop-ops/contrib/blob/master/README.md

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use this copy. https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt
- [ ] Include a README.md file that includes license and maintainer information. You can use this example. https://github.com/backdrop-ops/contrib/blob/master/examples/README.md
- [ ] Maintain the Git history from Drupal 7. See this article.

Additional Optional Checks:

- [ ] Attempt to cleanup issue queue on D7
- [ ] Looked for similar Backdrop contrib modules; make crosslinks in readme for any found
- [ ] If similar modules found, file an issue with current Backdrop project to see if your functionality can be added to that project; The goal is to not have a bunch of very similar modules
- [ ] Think about what category your module fits into and add to readme; one day this might help with categorization in searching for modules
- [ ] Try to run your module on PHP 5.3 to be nice to users who may be migrating from that version of PHP...I think that is the minimum version supported for Backdrop. You can test different PHP versions  with Lando. 
- [ ] Run any tests the module may have. They will most likely be SimpleTests you can run with the Testing module enabled.
- [ ] Remove Drupal compatibilty layer
- [ ] Replace variable_get variable_set with config system
- [ ] Change info file to reflect Backdrop changes from D7
- [ ] Place module on GitHub in a repo for others to look at and link to in your issue

Then once accepted do https://github.com/backdrop-ops/contrib/blob/master/README.md#what-to-do-after-your-application-is-accepted

**Comment by alexfinnarn** [comment]
On a second look, I'm going to try working on https://github.com/backdrop-contrib/site_verification/issues to see if those will work for my needs.

site_verify is something D7 users would be used to though vs. site_verification, and migrating multiple site_verify entities doesn't work in the current version of site_verification if that were to be a replacement to site_verify in D7.

**Comment by jenlampton** [comment]
I'd love to see the two modules merged into a single one. Whichever one you choose to use, I'd be willing to help with an upgrade path from the other :)

**Comment by alexfinnarn** [comment]
cool. I'm pausing working on porting site_verify in lieu of the issues I opened in site_verification and looking at that module more. I'll wait a tad bit for comments on those issues, but I think the previous maintainer of that project is no more.

**Comment by alexfinnarn** [comment]
Based on https://github.com/backdrop-contrib/site_verification/issues/6#issuecomment-412632578 I'm gonna leave that module alone and port the d.o version. It has a one-to-one name recognition migrating from Drupal anyway.

**Comment by jenlampton** [comment]
@alexfinnarn how's it coming with site verify? I'm looking to use it on one of my backdrop projects and would be willing to help however needed!

**Comment by jenlampton** [comment]
Well, I decided to start on a port at https://github.com/backdrop-contrib/site_verify. I have added you as a co-maintainer, and would love your help, or at least eyes :)

**Comment by jenlampton** [comment]
First release is out: https://backdropcms.org/project/site_verify

**Comment by alexfinnarn** [comment]
You were right to start the port, @jenlampton . Nice jorb! I've been out of the drops lately so I commonly forget D7 101 if I work on D7/Backdrop nowadays. Hope your verifying goes well :)
