### ISSUE TITLE
Application for contrib

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/contrib#28]
Hi Nate et al, thanks for all your work! I look forward to trying it out on a real project soon. We've got lots of non-profits that don't want to undergo another major upgrade soon to Drupal 8.

I'd like to apply to add some contrib modules. I've ported http://github.com/herbdool/markdown, http://github.com/herbdool/captcha, http://github.com/herbdool/recaptcha.

I chose modules that I thought were easy to port and presumably easy to maintain.

**Comment by docwilmot** [comment]
Markdown's been done. https://github.com/backdrop-contrib/markdown, unless thats also you (you both have 'herb' in your names).

**Comment by quicksketch** [comment]
Wow, nice job @herbdool!

Sorry we duplicated the work on porting Markdown! We're trying to figure out how to prevent that problem at https://github.com/backdrop/backdrop-issues/issues/625. Right now there's just so much porting happening at the same time we're bound to overlap.

I reviewed CAPTCHA and it looked great!

- [x] README.md created and lists maintainers.
- [x] LICENSE.txt added
- [x] Git history maintained from Drupal 7

You even converted settings to config. Nice job!

**Comment by quicksketch** [comment]
Code looks great. Would you agree to this for the record?

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the Backdrop project
  1. A list of the past maintainers for the Backdrop or Drupal project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by herbdool** [comment]
I agree to the Backdrop Contributed Project Author Agreement.

No problem about the markdown, I think it was a one line change from Drupal 7.

**Comment by quicksketch** [comment]
Thanks @herbdool! Invite sent.
