### ISSUE TITLE
Add GitHub Template For Project Application

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-ops/contrib#284]
A lot of recent talk relates to the steps you need to take to when applying to port/create a module. 

https://help.github.com/articles/about-issue-and-pull-request-templates/

I haven't made extensive use of GitHub templates but all of the checkboxes in the readme could be added to a template so it is very clear to the potential contributor what they need to do in beginning the process. 

It also helps in standardizing reviews. Looking through issues in the same format should make it more efficient for application people to grok.

I ended up copying the checks into my initial application, and then I made some more checkboxes for another port. 

To start, https://github.com/backdrop-ops/contrib/blob/master/README.md#new-project-checklist can be plopped into a template. A lot of parts of that readme are fine as-is but the procedural steps should be taken out and just referenced as...

"To apply simply create a request as an issue at https://github.com/backdrop-ops/contrib/issues/new. You will see a list of steps you need to take in the issue template."

**Comment by alexfinnarn** [comment]
"Under your repository name, click  Settings..." from https://help.github.com/articles/creating-issue-templates-for-your-repository/

So I guess I can't make a PR for this, but I still think it is a good idea.

**Comment by docwilmot** [comment]
I have in past proposed this whole thing be a Webform on BackdropCMS.org.

**Comment by jenlampton** [comment]
I've added a github template, but it doesn't seem to be in effect yet. I'll need to do some more research on how to actually get those hooked up...

**Comment by alexfinnarn** [comment]
I think I did it on https://github.com/alexfinnarn/code_syntax_highlighting_bundle/issues/new/choose I had to click "Propose Changes" next to the templates I added in the UI, and then I was prompted to make a PR to my dev branch. Some files just showed up in https://github.com/alexfinnarn/code_syntax_highlighting_bundle/tree/dev/.github/ISSUE_TEMPLATE.

I think you could just commit files to that directory without using the UI, but that's how I did it.

**Comment by jenlampton** [comment]
> I think you could just commit files to that directory without using the UI

That's what I tried first, but it didn't do the trick. :(

Anywho, we have issue templates now. There is one for every reason we tell people to use the queue in the readme: https://github.com/backdrop-ops/contrib/issues/new/choose

Seeking feedback in https://github.com/backdrop-ops/contrib/issues/369 :)
