### ISSUE TITLE
Follow WordPress contrib licensing policies and allow GPL-2.0 and GPL-3.0

### ISSUE THREAD

**Issue by kreynen** [backdrop-ops/contrib#294]
I brought the idea of moving to GPL-3.0 back in https://github.com/backdrop/backdrop-issues/issues/45

It makes sense to keep Backdrop core licensed as GPL-2.0 or/and later (we actually clarified that all contributions committed to Drupal.org's git repos are required to be dual licensed by changing to "and later" in the latest version of https://www.drupal.org/git-repository-usage-policy).  This would keep it in line with the other similar PHP CMS projects (Drupal, WordPress and Joomla).  

Newer projects like https://getgrav.org/ and https://octobercms.com/ are licensed as MIT.  While not as infectious as the GPL, MIT provides more flexibility with code that is licensed at Apache-2.0 or GPL-3.0 (the other 2 licenses GitHub points developers to when starting a project in https://choosealicense.com/).  

The GPL-3.0 option for Backdrop kicks in when it is distributed with something like the AGPL-3.0 licensed CiviCRM project or any Apache-2.0 licensed PHP library, but it adds complexity and confusion when contrib projects can't distribute required libraries with the module project.

While https://wordpress.org/about/license/ still references Drupal.org's licensing policies, WordPress contributors have the freedom to distribute the projects from https://wordpress.org/plugins/ as GPL-2.0 or GPL-3.0.  

https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/ uses the unversioned form of GPL.  While the contrib plugin documentation wasn't as clear, when I opened https://wordpress.org/support/topic/apache-2-0-code-in-a-gpl-2-0-plugin/?view=all#post-10048732 it was escalated to the group that manages that project's contrib plugins.  They clarified that they allow both GPL-2.0 and GPL-3.0 and while they agreed that the Amazon Polly for WordPress project should be distributed as GPL-3.0, they only intervene if a project isn't using GPL-2.0 or GPL-3.0.  

The question about GPL-3.0 came up with https://github.com/laryn in Gitter and in 
https://github.com/backdrop-ops/contrib/issues/265

While [WordPress's AMP solution](https://wordpress.org/plugins/amp/) doesn't require Google's Apache-2.0 licensed, not being able to distribute Apache-2.0 with GPL-2.0 requires increasingly more work as Google, Amazon, Mozilla and Apereo.

Apereo isn't as well know outside of higher education, but they have a [great summary of why they prefer Apache-2.0 over GPL or AGPL](https://www.apereo.org/licensing).

It is VERY unlikely that these groups are going to move from Apache-2.0 to a GPL-2.0 compatible license.

I believe that explicitly allowing projects in backdrop-contrib to be distributed as GPL-2.0 and GPL-3.0 or just GPL-3.0 is in line with [Backdrop's principals of Easier updates, Simplicity, Extensibility and Freedom](https://backdropcms.org/philosophy) and removes what has been a limitation to Drupal being more compatible with modern open source development.

**Comment by laryn** [comment]
@kreynen  I pasted the Gitter chat we had into [an issue on Scroll Reveal](https://github.com/backdrop-contrib/scrollreveal/issues/11#issuecomment-410868684) (since that is the module that bundles a library that is currently MIT but moving to GPL3).

It [looks like contrib can already choose](https://backdropcms.org/license#gpl-version) to license itself as GPL3 if desired (according to this paragraph from the link above):

> **Can I release my work under GPL version 3 or under GPL version 2-only?**
Yes. Because users of Backdrop may choose which version of the GPL license they wish to use (version 2 or version 3), any module or theme written for Backdrop may be distributed under either license exclusively. However, if the module is packaged together with Backdrop, all the code included in the package must be under the same license. For that reason, any module or theme that integrates with Backdrop is encouraged to use the same "GPL version 2 or higher" license.

**Comment by kreynen** [comment]
https://api.backdropcms.org/contrib-application-process and https://github.com/backdrop-ops/contrib/blob/master/README.md (are these the same?)

> Include a LICENSE.txt file that indicates the code is GPL v2

> Any project you create or maintain must include a copy of the GPL v2 LICENSE.txt file in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.

> Any project you create or maintain must include a README.md file containing at the least the following... License information for the project (GPL v2)

If the intent is to allow either GPL-2.0 or GPL-3.0, that isn't clear.  The line Drupal has always walked is that you can legally distribute Drupal core or contrib as GPL-3.0, but you can't do it from Drupal.org.  This used to reduce confusion since if something was downloaded from Drupal.org you had a higher level of confidence that it was GPL-2.0 compatible as well as secure.  Now, trying to walk this line on Drupal.org just confuses people since this is not something a developer would experience on GitHub, Packagist or NPM.

**Comment by laryn** [comment]
@kreynen You're right -- those pages seem to contradict each other. Sorry. I guess we need a core team representative to chime in here after all.

**Comment by laryn** [comment]
A few notes from @kreynen in Gitter, pasted here for when the PMC looks this over:

> Once someone with the authoriy over contrib decides whether Backdrop wants its contrib to be more like Drupal.org or more like WordPress.org, I’m happy to help rewrite these.

> In 2018, all license codes need to be using https://spdx.org/license-list formatting like GPL-2.0 vs. GPLv2

> I chair the DA’s Licensing Working Group. It took almost 3 years before the DA and Dries agreed to change the Drupal.org policies to allow projects to include non-code assets in projects like fonts and CC licensed images. I’m happy to answer any questions or provide examples of how holding onto GPL-2.0 compatibility has had a negative impact on the Drupal project.

**Comment by herbdool** [comment]
I vote to make it flexible. Backdrop already encourages bundling of third party libraries (where allowed) so I suspect it should be okay to make it clearer policy that there license allows that.

**Comment by laryn** [comment]
I'd also vote to make it more flexible and allow folks to choose GPL-3.0 only licenses on modules they host in the `backdrop-contrib` space.

**Comment by jenlampton** [comment]
I've opened a PMC issue to review and clarify the licensing for contrib.

**Comment by laryn** [comment]
@jenlampton Has this been discussed by the PMC?

**Comment by laryn** [comment]
Thanks @herbdool  -- I haven't had a chance to watch yesterday's meetings yet. This is great!

**Comment by jenlampton** [comment]
Yes, @herbdool and @laryn the PMC voted to allow GPL version3 projects in contrib, when necessary. We're going to update the [new project checklist](https://github.com/backdrop-ops/contrib) shortly, with more info about how and when to use this version.

**Comment by herbdool** [comment]
What about other licenses? Apache 2.0, other common ones for libraries?

**Comment by herbdool** [comment]
I think I found my answer for Apache license 2.0 https://www.apache.org/licenses/GPL-compatibility.html. It can be included in GPL 3 projects. So I think we can update the readme to include that.

**Comment by herbdool** [comment]
Tangent: there is a font library in core that is actually Apache 2.0 https://github.com/backdrop/backdrop/blob/1.x/core/misc/opensans/FONT-LICENSE.txt which seems to be incompatible unless there's an exception for fonts that I'm unaware of.

**Comment by jenlampton** [comment]
> I think we can update the readme to include that.

Yes, good idea.

> there is a font library in core that is actually Apache 2.0 

yes, there's something funny about fonts. I think the inheritance doesn't apply?

**Comment by kreynen** [comment]
So glad to see this move forward!  

For consistency, I would recommend switching to the https://spdx.org/licenses/ format for licensing abbreviations.

So GPL-3.0 vs. GPL v3

> If your project includes a library that is GPL v3 then you must license your project as GPL v3

It isn't just GPL-3.0, but any library that uses a license that is only compatible with GPL-3.0 like Apache-2.0.  https://www.drupal.org/node/1475972#gplv2-compatible-licenses is the list of most common licenses we run into and their GPL-2.0 compatibility according to the FSF.  Backdrop contrib projects could now include GPL-3.0, LGPL-3.0, Apache-2.0 and AGPL-3.0.  The only request we often get for Drupal contrib that Backdrop developers couldn't include are for projects where the code that has no licenses or the license isn't clearly stated.  This is less common, but still happens.

I would just reference the full list of licenses that are compatible with GPL-2.0 and/or GPL-3.0 at http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses 

So maybe something like...

_If your project includes a GPL compatible library that the[ Free Software Foundation has determined to only be compatible with GPL-3.0](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses ), then you must license and distribute your project as GPL-3.0.  The GPL-3.0 license will prevent your project from being included in Backdrop core in the future, so please only use this license when necessary. You may use this text for GPL-3.0._

> yes, there's something funny about fonts. Maybe the inheritance doesn't apply? 

Because fonts are a non-code asset, the rules for compatibility are different.  Technically the common SIL-OFL isn't GPL compatible because it includes a clause stating that the fonts can only be distributed with another original work. I think this was to stop people from creating font CDs or distributing the fonts in a way the hid who the original author was, but I'm not sure how Google gets away with https://github.com/google/fonts/tree/master/ofl.  You won't find many people who recommend using a license like GPL or Apache of non-code assets like fonts or images, but it happens.

https://www.gnu.org/licenses/gpl-faq.en.html#FontException is one way to handle this.

Similar to fonts, technically a project where the PHP is licensed as GPL-2.0 can be distributed with javascript that is licensed as Apache-2.0 if the javascript is run in the browser and isn't a derivative of another project. Because of the evolving nature of javascript and Drupal's stance on all modules and themes being a derivative of Drupal core, the LWG and DA chose not to try to figure out whether each javascript could be considered a non-code asset.  

The more time I spend helping projects deal with licensing issues, the more I wish every project with just switch to using http://www.wtfpl.net/

**Comment by jenlampton** [comment]
> For consistency, I would recommend switching to the spdx.org/licenses format for licensing abbreviations. So GPL-3.0 vs. GPL v3

I agree. I've cleaned up the last few references for consistency. 

> So maybe something like...

Love it...  here's what I landed on: https://github.com/backdrop-ops/contrib#new-project-checklist

I listed some of the most common examples in our docs, to make it a little easier on our contributors, but also included the link to the complete list.

**Comment by klonos** [comment]
Our [New Project Checklist](https://github.com/backdrop-ops/contrib#new-project-checklist) includes the following:

```
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0 -- please see below). Please use [this text for GPL-2.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
  * If your project includes a library that is licensed under GPL-3.0, LGPL-3.0,
    Apache-2.0, AGPL-3, or any other license that the Free Software Foundation
    has determined to [only be compatible with GPL-3.0](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses),
    then you must license your project as GPL-3.0. Please use [this text for GPL-3.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE-GPL-3-0.txt).
  * The GPL-3.0 license will prevent your project from one day being included in
    Backdrop core, so please only use this license when necessary.
```

Anything else left to be done here?

**Comment by jenlampton** [comment]
Don't think so!

**Comment by findlabnet** [comment]
On the same page under [The Backdrop Bug Squad](https://github.com/backdrop-ops/contrib#the-backdrop-bug-squad) line with link

> The Bug Squad members can be viewed, here: https://github.com/orgs/backdrop-ops/teams/bug-squad/members

leads to 404

**Comment by jenlampton** [comment]
Hm. I wonder if that's only visible if you're on it?

**Comment by findlabnet** [comment]
Yes, I'm logged in, if not (in other browser)  - click on this (visible) link opens "Sign in to GitHub" form.

**Comment by klonos** [comment]
>>Anything else left to be done here?
> Don't think so!

Closing this one then. @findlabnet I have filed #334 for the problem with the link to the team members. Thanks for bringing that to our attention 👍
