### ISSUE TITLE
Port Request for Views Field View

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#297]
I'm just running into a situation where it would be great to use the Views Field Views module?
https://www.drupal.org/project/views_field_view

**Comment by jenlampton** [comment]
I'm surprised I haven't needed this yet, it's one of my fav projects for Drupal. I'd expect that I'll need it shortly, and when that happens I'd be happy to share the result with the community :) If you have a timeline, let's chat!

**Comment by jenlampton** [comment]
hah... Well, I need it now :) I may be working on this between now and Jan 1st...

**Comment by mrconnerton** [comment]
I have an inital port at https://github.com/mrconnerton/views_field_view folks can test. I haven't ported the actual `viewsFieldViewTestCase` yet.

**Comment by jenlampton** [comment]
That was fast! :)

**Comment by stpaultim** [comment]
I just installed this module and embedded a pretty simple view inside of another view. No problems and no error messages. This was not a very complicated test, but for a simple test case this module worked perfectly for me.

**Comment by jenlampton** [comment]
@mrconnerton would you like to become a contrib group member and maintainer for views_field_view? If not, how would you feel about me forking your project and moving it into contrib? I promise to give you all the credit!

**Comment by mrconnerton** [comment]
I would love to a contrib group member but I doubt I would have the time to
contrib much anytime soon. With that said, please absolutely fork the
project and move into contrib.

**Comment by jenlampton** [comment]
Maintainer application stuff:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [ ] Include a README.md file that includes license and maintainer information.
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0)

@mrconnerton do you agree to the [Backdrop Contributed Project Agreement
](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)? (We'll need you to state here, for the record, if you agree)

I'm going to file a PR to your repo with the LICENSE.txt file and README.md...

**Comment by jenlampton** [comment]
@mrconnerton if you can merge that PR we can tick off the two boxes above, and then you can transfer the project into the contrib group, without me needing to fork it :)

**Comment by mrconnerton** [comment]
Great. I'm turning in but can tackle this in the morning.

**Comment by mrconnerton** [comment]
Sorry for the delay, I have merged the PR and I do agree to the Backdrop Contributed Project Agreement.

**Comment by jenlampton** [comment]
- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0)

>  I do agree to the Backdrop Contributed Project Agreement.

Whoohoo!  Welcome to Backdrop contrib :)

> You've invited Matthew Connerton to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Once you accept the invitation, you should be able to transfer views_field_view into the `backdrop-contrib` group  following the steps mentioned [in this post](https://help.github.com/articles/transferring-a-repository-owned-by-your...).

After clicking 'I understand, transfer this repository', you'll be shown the 'Team Access' screen where you choose who will have access to this repo. Tick **Authors**, **Bug Squad** and **Security**, then click 'Transfer'.

And thank you again!

**Comment by BWPanda** [comment]
I was just looking for this module. Took me a while to find this. @mrconnerton Are you able to go ahead with transferring your port to the Backdrop Contrib group? @jenlampton If not, what are the side-effects of forking it...?

**Comment by jenlampton** [comment]
> I was just looking for this module. Took me a while to find this.

Hm, good point. i should have left this issue open until the repo had been transferred. Reopening. 

>  @jenlampton If not, what are the side-effects of forking it...?

I don't know, as no one has done that yet :)

**Comment by mrconnerton** [comment]
Whoops! didn't realize this wasn't transferred. @jenlampton I just tried and got "You don’t have the permission to create public repositories on backdrop-contrib"

**Comment by mrconnerton** [comment]
Ok, fixed and transferred :-)

**Comment by jenlampton** [comment]
yay! thank you @mrconnerton !!!
