### ISSUE TITLE
Porting IMCE Rename Module

### ISSUE THREAD

**Issue by aytee** [backdrop-ops/contrib#298]
In the process of porting the IMCE Rename module.
https://www.drupal.org/project/imce_rename

https://www.drupal.org/project/imce_rename/issues/2993447

**Comment by aytee** [comment]
This module is ready to submitted.  I would also like to apply as a Contributor at this point.

**Comment by herbdool** [comment]
@klonos see above. @aytee what's the link to your module?

**Comment by aytee** [comment]
@herbdool - Should I create a repo on my personal account for it?  I'm a bit perplexed on the process here.

**Comment by aytee** [comment]
Thanks @herbdool  for the clarification.  Here is the module location:
https://github.com/aytee/imce_rename

**Comment by klonos** [comment]
I have checked the repo and 

- [x] Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0/GPL-3.0.

So approved 👍 ...welcome to Backdrop CMS Contrib @aytee!! 🎉 :

> You've invited Arthur Turlak to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by herbdool** [comment]
@aytee I've only looked at the .info file. My suggested changes:

* Don't need to list `files[]` since both `.install` and `.module` get included automatically.
* Instead of `core = 7.x`, it needs to be `backdrop = 1.x`
* Need to add `type = module`

**Comment by herbdool** [comment]
Also I suggest following the instructions in https://api.backdropcms.org/converting-modules-from-drupal to convert references to Drupal functions to Backdrop, including drupal_, and variable_* and the update hooks.

**Comment by aytee** [comment]
@herbdool - Apologies for the misfire.  I hadn't actually updated the files in Git properly so you were looking at the Drupal module version with just the README.md and License.txt updated.  I've pushed all those updated files to the repo at https://github.com/aytee/imce_rename .  Thanks for your patience.

**Comment by klonos** [comment]
@aytee welcome from me too 😄 ...I think that it's OK to close this and have issues reported in https://github.com/aytee/imce_rename/issues
