### ISSUE TITLE
Backdrop page builder

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#299]
I'd love to have a system in which my clients can design, layout and build their own pages, without my needing to do it for them in a way that's hard-coded and in-flexible. It needs to be easy to use (i.e. not just give them full access to Views, Layouts, etc.), and preferably drag-and-drop and in-place editable.

Wordpress has lots of options like this, some of which are:

- [Make](https://thethemefoundry.com/wordpress-themes/make/)
- [Elementor](https://elementor.com/)
- [Gutenburg](https://wordpress.org/gutenberg/)

(Note: I've not used them, just checked out their websites/videos)
Also, other systems (from what I've seen/understand (again, not used them personally)) seem to all offer the same/similar functionality (e.g. [Wix](https://www.wix.com/), [Squarespace](https://www.squarespace.com/), [Weebly](https://www.weebly.com/), [Strikingly](https://www.strikingly.com/)).

I'd love to build/contribute to something like this for Backdrop.

What I don't like is how those types of themes for Wordpress are either for purchase, or there's a free/open-source version that's cut-down, then you need to pay for the full features. I'd prefer a fully free and open-source solution. Also, those things tend to be an all-in one solution (jack-of-all-trades), whereas I think it'd be better/easier/more manageable to have a collection of modules/themes/layouts/install profiles? that all work together to accomplish this in Backdrop (e.g. a module that provides in-place editing, a layout that provides the necessary framework to allow for these customisations, etc.).

I'm not sure of how this should work. I have different ideas; from providing simple options to change various aspects of the site (e.g. choose a header layout: logo and menu on full-screen background image, short bar across top of page, vertical 'sidebar' with logo and menu, etc.) which the user would select from, then the necessary back-end functionality would be setup programatically, to a full-fledged drag-and-drop system that allows users to change every aspect of the site themselves (e.g. drag logo to left or right or header, drag-and-drop a photo onto section to change background, etc.).

I have no idea how to even start building a system like this. If one does provide a drag-and-drop system for Backdrop, how do we make with work with Layouts, content types, fields, etc.? It seems very overwhelming and a bit pie-in-the-sky for me, so I'm putting it out there in the hope that others can contribute ideas, code, etc. and maybe one day this will become a reality.

EDIT: Added Gutenburg to list above.

**Comment by BWPanda** [comment]
For what it's worth, this idea came about mostly from my growing need to build frontpages that are comprised of 'sections' as you scroll down the page - each section has its own background (either a colour or an image/video), layout (e.g. a large centered text quote, blog teasers, portfolio thumbnails, etc.).

To build this in a way that the client can customise; add, remove and re-arrange section, change each background, etc.; proves difficult without hard-coding aspects of it (e.g. this section always shows blog teasers on a white background in a 3-column layout).

Giving the client the ability to more easily create these sorts of frontpages (and indeed the rest of the pages on their site) themselves would be great in my opinion.

**Comment by oadaeh** [comment]
I'm attempting to flag @hosef as we have discussed creating similar functionality in the past.

**Comment by jenlampton** [comment]
I believe @docwilmot worked on flexible layout (like from Panels) but I'm not sure where that ended up...

**Comment by olafgrabienski** [comment]
Strange, I believe I had added a comment referring to the [Paragraphs module](https://github.com/backdrop-contrib/paragraphs), must have forgotten to save it. It's a great approach especially for front pages and landing pages with many sections. More information on the [Drupal module page](https://www.drupal.org/project/paragraphs) and the [demo site](https://paragraphs.site-showcase.com).

Re Flexible Layout: https://github.com/backdrop-contrib/flexible_layout

**Comment by davegmk** [comment]
I've used page builders such as Beaver Builder for clients WordPress sites.  The upsides is that they make the visual updating of content very, very easy for non technical users.  People can see exactly how the changes they are making effect the content in real time.

One of the big downsides for me is that they leave a lot of nested Div's in the markup.

I've used Paragraphs for Drupal sites and while great it isn't as user friendly as a well implemented page builder.

Interestingly the massively popular WP page builder Elementor now has a release for D8:
https://blog.linnovate.net/elementor-drupal-c4d789bd706d

**Comment by BWPanda** [comment]
Wow, Elementor for Drupal looks interesting. Quick, let's do something for Backdrop before I get jealous :wink:

Regarding Paragraphs, came across this the other day: https://blog.acromedia.com/live-component-guide-with-drupal-paragraphs
It basically provides the functionality I want for my clients, but the UX could use (a lot) of work. Will try to have a play with it sometime soon and see if it's suitable for my needs.

**Comment by davegmk** [comment]
When working with Drupal 7 sites I'd often use a combination of a Bootstrap base theme, Display Suite and Paragraphs.  This worked very well, but the UX was often a little harder for users to get their heads around, especially with more complex layouts and multiple fields.

I was very much a hold out against Page Builders.  However I thought  I would give one a try for a new WordPress project.  The client was wildly enthusiastic about how easily they could now edit their content.

The other benefit was that it cut build time down substantially!

**Comment by laryn** [comment]
I've just started using Paragraphs in the last few months and it is a big improvement. I'm wondering how easy it would be to provide a module that prepopulated (or gave the option to prepopulate) some bundles very quickly and easily.

Also, although I haven't used it yet, my "to test out" list includes HAX, which may be worth mentioning here: https://backdropcms.org/project/hax

**Comment by kevincrafts** [comment]
So we've had a need for this type of page for years at CU Boulder and I'd designed/developed about 5 different versions of it before we finally settled on our current version on our Express platform.

We already had a block type that allowed you to specify a background and embed other block type content inside of it, so rather than recreate that, we made a content type that allows you to just select as many of those as you want, place them in the order that you want, and add some display options (navigation, section size, etc) - here's one of the pages that was built with it: https://www.colorado.edu/beboulder/explore

**Comment by davegmk** [comment]
Reopening this after playing with the Gutenberg module for Drupal 8.  It's not perfect but as a simple page builder it shows some initial promise. There seem to be moves towards making Gutenberg CMS agnostic, see:
https://wptavern.com/gutenberg-cloud-team-advocates-for-making-wordpress-orgs-new-block-directory-a-cms-agnostic-library

No idea how much work would be involved in building a Backdrop module for Gutenberg.  I remember seeing a YouTube video where Jen demonstrated the WordPress plugin Divi.  She mentioned how good it would be to have a page builder in Backdrop.

**Comment by docwilmot** [comment]
Curious, Does this build the entire page (like a layout)? Or does it build the node content area?

**Comment by jenlampton** [comment]
Neither, it only builds the contents of the body field.

**Comment by davegmk** [comment]
I think WordPress have plans to make Gutenberg into a fully fledged page builder which would deal with layout, sidebars and widgets.

I've certainly seen how builders have transformed how my WordPress clients use their websites.  For complex content layouts they are easier to use than something like Paragraphs.  Paragraphs is great but for complex layouts the UI is not so good.

As Jen says when using Gutenberg for Drupal it's just the contents of a body field.  This would tend to replace my old practice of using multiple fields on a node to layout complex content.

Interestingly the Drupal version also seems to be able to pull in content from Drupal blocks.

The downside is that it also takes over the whole node editing screen, which makes accessing other fields harder.  At the moment these are displayed in a more settings option in a vertical tab.   This wouldn't work if you had a lot of other fields.  I've attached a screen grab:

![drupal-gutenberg](https://user-images.githubusercontent.com/40337704/55824705-4f49b600-5afc-11e9-838c-7a8868ee0ac8.png)

**Comment by docwilmot** [comment]
We have Flexible Layouts and Node Layouts in contrib and I think we should develop them for core.

**Comment by jenlampton** [comment]
I agree, I'd love to see flexible layouts in core, as well as layouts for view-modes (so you can have a two column teaser, for example).

**Comment by docwilmot** [comment]
A thought:
- the majority of times a site builder would just want to add a new row to a layout, with or without column divisions.
- a lot of the code complexity in Flexible Layout module is because it allows complex nested colums, regions, rows, with draggable separators.
- could we in keeping with our simplicity ideal just allow core to add/remove **rows** only? Those rows could be selectable as 1 to 6 colums (to suit Bootstrap). 

Example:
![add row](https://user-images.githubusercontent.com/1042283/56471029-1e7a5280-6413-11e9-8b1f-57463def80fa.PNG)
![col select](https://user-images.githubusercontent.com/1042283/56471030-1e7a5280-6413-11e9-9293-db2a43f1e7d1.PNG)

Thoughts?

**Comment by BWPanda** [comment]
@docwilmot I think that's a good idea. If I ever get around to it, I was thinking of using the idea re. Paragraphs posted above. Its the same as what you're suggesting basically; create predefined sections consisting of one or more columns (e.g. banner image, content with right sidebar, 3 33%-wide blocks, etc.) and then the user just adds as many of these down the page as they want (i.e. rows). I know you're talking about layouts/regions/blocks, but the idea of Backdrop providing predefined sections and the user using those to create rows is very similar. I think it'll certainly account for the 80% majority of use cases.

**Comment by jenlampton** [comment]
We definitely don't need draggable separators in core, but I think adding
columns to rows is important. There's not much difference between adding a
new row with a single column, and adding another block to a single column
layout, which we can already do.

I like @docwilmot's idea of allowing people to choose a width from only the
available bootstrap options, and I think that would simplify things. But I
 don't understand why you'd set a width on a row (which should always be
all 12-columns) and not on the blocks or columns in the row (which should
always add up to 12 columns).

Is there an example of this I can see in action?

**Comment by docwilmot** [comment]
I actually don't understand what you mean @jenlampton. The idea would be to allow users to add our remove full width rows, pre-divided into columns. I'll have to pick up to demo. 

Another question I thought of: would it be best to make the block add page flexible like Flexible Layouts now fires, OR have a separate UI where you build a custom layout template, then it save it, and it shows up in the list of templates.

**Comment by jenlampton** [comment]
> The idea would be to allow users to add or remove full width rows, pre-divided into columns.

Oh, this makes more sense! So instead of allowing people to add columns at the specific widths 2/3/4/6/8/9/10/12, we'd provide a single massive list of all options for rows? Maybe something like the following:
- One column
- Two columns, 10/2
- Two columns, 9/3
- Two columns, 8/4
- Two columns, 6/6
- Two columns, 4/8
- Two columns, 3/9
- Two columns, 2/10
- Three columns, 4/4/4
- Three columns, 2/8/2
- Three columns, 2/2/8
- Three columns, 8/2/2
- Three columns, 3/6/3
- Three columns, 3/3/6
- Three columns, 6/3/3
- Three columns, 4/2/6
- Three columns, 4/6/2
- Three columns, 2/6/4
- Three columns, 2/4/6
- Three columns, 6/2/4
- Three columns, 6/4/2
- Four columns, 3/3/3/3
- Four columns, 3/3/4/2
- Four columns, 3/3/2/4
- Four columns, 4/3/3/2
- Four columns, 2/3/3/4
- Four columns, 2/4/3/3
- Four columns, 4/2/3/3
- Four columns, 2/4/4/2
- Four columns, 2/4/2/4
- Four columns, 4/2/2/4
- Four columns, 4/2/4/2

> would it be best to make the block add page flexible like Flexible Layouts now fires, OR have a separate UI ...

I think a separate UI is enough for the first pass. Making the manage blocks page flexible is something that could be done in contrib, or later on for core.

**Comment by docwilmot** [comment]
You got it.
And I also prefer a separate UI.

**Comment by docwilmot** [comment]
https://github.com/backdrop/backdrop/pull/2646

**Comment by stpaultim** [comment]
We now have flexible layouts in core. Should we close this issue. 

(I see that I don't have permission to close it if I wanted to).

**Comment by laryn** [comment]
Is this already in another follow-up issue? (From @jenlampton's [comment above](https://github.com/backdrop-ops/contrib/issues/299#issuecomment-484636749))

> ...as well as layouts for view-modes (so you can have a two column teaser, for example).

**Comment by jenlampton** [comment]
I think there might be a core issue on "mini-layouts" somewhere?
