### ISSUE TITLE
Application to join

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/contrib#3]
I have ported one theme.

**Comment by enzolutions** [comment]
What changes are required in a theme to migrate to backdrop?

**Comment by quicksketch** [comment]
Hi @docwilmot! I see that you've also ported a few modules at https://github.com/backdrop/backdrop-issues/issues/570#issuecomment-69561769!

Could you make this repository a checkout of the Drupal.org module and then push it into the Github repository? That would help maintain the entire history of the projects.

We recently drafted up an agreement for all contributors so they know what they're getting into. If it looks acceptable, would you agree to the following from the new [Backdrop Contributed Author Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-module-author-agreement)?

---

By publishing a module in the [Backdrop Contributed module group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your module becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by docwilmot** [comment]
https://github.com/docwilmot/cleanish
Do I need a separate application for each project?

**Comment by quicksketch** [comment]
>  Do I need a separate application for each project?
Nope! But you do need to agree to the agreement! If you can say for the record that you agree, we'll add you to the group and then you can port to your heart's content. :)

Thank you for adding a LICENSE.txt file! If you could update your README.txt to a .md file ([here's an example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)) then we're pretty much good to go.

**Comment by docwilmot** [comment]
I agree to the agreement. 
Updating readmes to .md shortly

**Comment by quicksketch** [comment]
Excellent, thanks @docwilmot! Invite is on its way. Thanks for all your work on Backdrop!
