### ISSUE TITLE
Maintainer change request for Back To Top

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#302]
As per https://github.com/backdrop-contrib/back_to_top/issues/5, I'd like to take over the maintainership of the [Back To Top](https://github.com/backdrop-contrib/back_to_top) module.

**Comment by klonos** [comment]
Enough time has been allowed @BWPanda. I think it is now perfectly OK to add your name to the list of maintainers and take over 😉

**Comment by BWPanda** [comment]
@klonos Thanks.
