### ISSUE TITLE
Application to join Backdrop contrib

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/contrib#303]
Here I am, Olaf Grabienski from Hamburg, Germany. I work with Backdrop for a while, mainly as a site architect, and I'd like to join the Backdrop contrib community.

I need a port of the Drupal *Footnotes* module and tried to do it by myself. I guess it worked quite well even if I'm not a coder, thanks to the help of other contributors. Here's the repository of the module: https://github.com/olafgrabienski/footnotes

(LICENSE.txt will be added soon, cf. https://github.com/olafgrabienski/footnotes/issues/27.)

I agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement).

**Comment by klonos** [comment]
Hello @olafgrabienski, as explained over Gitter, a LICENSE.txt file needs to be added to the repo:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use
[this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information.
You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See
[this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

**Comment by olafgrabienski** [comment]
@klonos Thanks for the checklist! I've added the `LICENSE.txt`.

**Comment by klonos** [comment]
Sorry for the late response @olafgrabienski. Invite underway:

> You've invited Olaf Grabienski to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome officially 😄 🎉

**Comment by klonos** [comment]
...I'm gonna go ahead and close this issue.

**Comment by olafgrabienski** [comment]
Thanks, and maybe tick the "Include a LICENSE.txt" checkbox. (I've not the permission to edit the comment.)
