### ISSUE TITLE
Porting prism module

### ISSUE THREAD

**Issue by Pepenauta** [backdrop-ops/contrib#304]
Hi, I have ported prism module. Find it here https://github.com/pepenauta/prism.

**Comment by jenlampton** [comment]
Fantastic, thanks Pepenauta!

**Comment by Pepenauta** [comment]
Yes, I would like to be a member of the contrib group.
Thanks Jen.

**Comment by klonos** [comment]
Hello @Pepenauta and sorry for the late response... I have checked and the ported module ticks all boxes re requirements 👍:

- [x] Maintain the Git history from Drupal 7. See
    [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [x] Include a README.md file that includes license and maintainer information.
    You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0).

...so I have sent you an invite to join the contrib group:

>You've invited José Espinosa to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome onboard 😄 🎉 

PS: PR to update the README file, for your consideration (not a requirement): https://github.com/Pepenauta/prism/pull/1

**Comment by Pepenauta** [comment]
Hi @klonos , thanks for the invitation!  I already made the merge and transferred the repository. Bye!

**Comment by klonos** [comment]
...closing this ticket then.

**Comment by jenlampton** [comment]
Welcome @Pepenauta! It's wonderful to have you :)
