### ISSUE TITLE
Port Request: PhotoSwipe

### ISSUE THREAD

**Issue by korontari** [backdrop-ops/contrib#311]
Provides a very good and mobile friendly lightbox functionality. IMHO one of the best lightboxes adapted for Drupal.

https://www.drupal.org/project/photoswipe

**Comment by Graham-72** [comment]
@korontari thank you for this recommendation. I have now made an initial port to Backdrop which you will find at https://github.com/backdrop-contrib/photoswipe.

**Comment by korontari** [comment]
@Graham-72 thank you for porting the module! I will test it on my sandbox BD installation and provide you with feedback.

**Comment by korontari** [comment]
My apologies for taking so much time to respond. I have tested the module recently. While it generally works well I have a couple of issues with it:

1. If added to a view with multiple images the Photoswipe module doesn't recognize it as a gallery. It displays only a single image without the ability to swipe/click to next or previous image. I could make it work by assigning CSS class 'photoswipe-gallery' in the view's 'Other' section.  If used for content with multivalue image field then it recognizes it as a gallery and works correctly.
I remember that same issue was in Drupal module so I think this is inherited bug, not module port related.

2. I noticed that the module installation process requires manual installation of a library. This is exactly like it is in Drupal and is different from what I was experiencing in Backdrop where libraries are installed automatically. I wonder if there was some policy change or is it just a temporary solution?

I wasn't sure if I should have written this here or post an issue on the module's page. So let me know please if I should move these comments somewhere else.

**Comment by Graham-72** [comment]
@korontari thanks for your feedback. I think it would be better to make these as two issues for the module, though not necessarily as bug reports. The second one certainly is a feature or enhancement request and it would be good to include the javascript library within the module provided copyright and licensing permit. I will do some tests regarding your first point which I think is more of a configuration issue which needs better explanation in the README. There is a useful guide on reporting issues at https://backdropcms.org/user-guide/how-use-issue-queue which perhaps you have already seen.

**Comment by Graham-72** [comment]
@korontari regarding your first point, I have done some more testing and, if using a view built from a group of nodes with one image in each, I cannot get Photoswipe to recognise them as a gallery either in Backdrop or D7. Please can you describe the exact settings you have used for this?

I have a feeling that it may require change to the module's javascript file to get this configuration to work.

**Comment by klonos** [comment]
Lets please close this issue and move all requests and bug reports to https://github.com/backdrop-contrib/photoswipe/issues
