### ISSUE TITLE
Port request: field_validation:

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#314]
From email:
```
Hello,
I would like to know if the Field validation module is available for backdropcms.
Cordially
```

**Comment by jenlampton** [comment]
I took a look at the field_validation module today, thinking that since it was for fields, and fields are mostly unchanged, that it wouldn't be too much work to convert to Backdrop from Drupal.

Unfortunately, it looks like the field_validation module uses ctools heavily, so the conversion is going to be more involved than I thought. I thought this might be a good opportunity to document converting ctools exports, and ctools plugins, as I expect other contrib modules would benefit from that as well.

I've started the conversion, and will post my work in a repo for others to use / test / continue working on.

**Comment by jenlampton** [comment]
I pushed a version of field-validation up to https://github.com/backdrop-contrib/field_validation. I'm not sure if it "works" or not, but I got all the ctools bits sorted out. Anyone want to give it a test?

**Comment by jenlampton** [comment]
I heard that the module wasn't working, so I took another stab at cleaning up the validator class. I can now get basic rule validation correctly throwing errors, but I could use more help testing. Please [report any issues in the queue](https://github.com/backdrop-contrib/field_validation/issues/new) and I'll take care of them.

**Comment by salahjaafar** [comment]
sorry but the module does not work

**Comment by jenlampton** [comment]
I'm sorry, but I'm not able to diagnose "does not work" without more information. 

If you could document the problem (by answering the following questions) in the issue queue, I will be able to diagnose and fix any issues: https://github.com/backdrop-contrib/field_validation/issues/new

* What are you trying to do? (please provide steps to follow)
* Is there an error message? It not, what happens?
* What appears is in the log?

**Comment by salahjaafar** [comment]
this message appears when using the field validation module for the single value: 
Fatal error:  Call to undefined function ctools_include() in /opt/lampp_5.5.19-0/htdocs/stdobp/modules/field_validation/property_validation/property_validation.module on line 43
