### ISSUE TITLE
Request to Contribute

### ISSUE THREAD

**Issue by ethanteague** [backdrop-ops/contrib#32]
Howdy.  I would like to contribute modules to Backdrop.  This is me:
https://www.drupal.org/u/ethant

Thanks!
Ethan

**Comment by quicksketch** [comment]
Hi @ethanteague! That's great! We'd love to have your help! We like to do a (very small) review of the first module you port to set you on the right track with the differences between Backdrop and Drupal. Could you push up whichever module you're porting to your personal account and link to it? Then we'll check it for the following basics:

- [ ] Include a README.md with a list of maintainers and license info (you can copy [this example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)).
- [ ] Include a LICENSE.txt file indicating it is GPL v2 (you can use [this copy](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt)).
- [ ] And if you're porting a contributed module from Drupal 7, we like to maintain the full history in Git. So do a checkout from D7, rename the branch to 1.x-1.x, then copy your ported version over the top.

We're looking forward to having your help. Thanks!

**Comment by ethanteague** [comment]
You bet, @quicksketch - looking forward to getting involved.

**Comment by quicksketch** [comment]
Thanks @ethanteague for the amazing article at http://www.civicactions.com/blog/2015/feb/02/first-look-backdrop-cms! I can't say how much we appreciate that. I think you wrote up our philosophy better than we did. :wink:

We're still looking forward to getting you in the contrib group. Just let me know when you have a module ready to spot-check against the short-list above. Thanks!

**Comment by ethanteague** [comment]
Thanks for the kind words (and great project), @quicksketch - I plan to contribute, soon!

**Comment by klonos** [comment]
@ethanteague: Hello Ethan! Just doing some issue queue clean-ups here. It's been some time now that you've filed this issue and I was wondering if you found the time to port a first module yet?

**Comment by ethanteague** [comment]
Hey @klonos - thanks for reaching out! I apologize, I just haven't had the time (yet).

**Comment by klonos** [comment]
No worries @ethanteague, just helping triage issues in the queue in order to keep it clean :wink: Please feel free to re-open this once you have had the chance to get some work done.
