### ISSUE TITLE
Maintainer change request for HTML5 Upload

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/contrib#321]
There's been some recent activity on HTML5 Upload which reminded me that there is an outstanding PR that needs to be merged. I requested a maintainership transfer but never heard back since August 2018:

https://github.com/backdrop-contrib/html5_upload/issues/7

This was a port by @biolithic who has abandoned all of his projects (is my understanding).

**Comment by klonos** [comment]
> ...who has abandoned all of his projects (is my understanding).

That is my understanding also. @jenlampton ??

**Comment by jenlampton** [comment]
@laryn yes I think he has a new job.  If he doesn't reply within the 2 week window, @klonos,  It would be good to transfer his projects to anyone who requests one.

**Comment by laryn** [comment]
@jenlampton @klonos  That sounds fine in general, thanks. In the case of this particular module I made the request linked above in August 2018 and have no reply so I think we're safe to transfer it so I can merge the PR from 2017.

**Comment by klonos** [comment]
Hey @laryn 👋 ...I believe that you're good to go. Feel free to add your name to the list of maintainers.

Lets close this one...
