### ISSUE TITLE
Request to Join for the purpose of contributing modules

### ISSUE THREAD

**Issue by ksthomas** [backdrop-ops/contrib#322]

**Comment by klonos** [comment]
Hello @ksthomas. Can you please post a link to a module repository for review?

According to our [New Project Checklist](https://github.com/backdrop-ops/contrib#new-project-checklist):

All projects must meet these minimum requirements.

- [ ] Maintain the Git history from Drupal 7. See
    [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).
- [ ] Include a README.md file that includes license and maintainer information.
    You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0). Please use [this text for GPL-2.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).

**Comment by ksthomas** [comment]
This would be a new project that does not exist in the Drupal Repository. How does that change things?

**Comment by klonos** [comment]
That's perfectly fine @ksthomas, simply start the project under your personal GitHub account, and then post a link to it here. In such cases, the requirement to maintain the Git history from Drupal 7 is of course moot.

**Comment by klonos** [comment]
Hello @ksthomas 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
