### ISSUE TITLE
Amend the Bug Squad and Abandoned projects sections of the README

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#323]
As a follow-up to https://github.com/backdrop-ops/contrib/issues/185, We should let everyone review the new contrib readme, and update with feedback and suggestions:
https://github.com/backdrop-ops/contrib

**Comment by klonos** [comment]
Thoughts/ideas:

- create a bugsquad@backdropcms.org email and forward to people that want to be part of that list.
- create a page in b.org that a) lists current members, b) provides short description of duties/purpose*, c) mentions the email above and Gitter as a form of communication with the squad, and d) links to instructions on how to become a member

* the main points here should be:

> - trying to take the burden of project maintainership from single individuals and making it a responsibility of the community to step in when needed.
> - trying to improve the overall quality of contributed projects, by reducing the amount of time it takes for bug fixes to be released as much as possible
> - ...

**Comment by stpaultim** [comment]
I approve of this message. 

Looks good. Answers my questions.

**Comment by jlfranklin** [comment]
Other than searching for your own name on https://backdropcms.org/modules, is there a way to get your current list of maintained projects?

**Comment by jenlampton** [comment]
I've created pages on backdropcms.org for
* [the bug squad](https://backdropcms.org/leadership/bug-squad) and
* [the security team](https://backdropcms.org/leadership/security-team) and
* [abandoned projects](https://backdropcms.org/user-guide/adopt-project)

I'm hoping these pages will be easier to keep up to date here than in the readme, and hopefully the information will also be easier for people to find :) 

I've also updated the readme with links to these pages.
