### ISSUE TITLE
Bug Squad team members are not visible without a GitHub account

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#334]
This was reported in https://github.com/backdrop-ops/contrib/issues/294#issuecomment-480621061 by @findlabnet:

> On the same page under [The Backdrop Bug Squad](https://github.com/backdrop-ops/contrib#the-backdrop-bug-squad) line with link
> 
> > The Bug Squad members can be viewed, here: https://github.com/orgs/backdrop-ops/teams/bug-squad/members
> 
> leads to 404

@jenlampton:
> Hm. I wonder if that's only visible if you're on it?

@findlabnet
>Yes, I'm logged in, if not (in other browser) - click on this (visible) link opens "Sign in to GitHub" form.

**Comment by klonos** [comment]
This is easily reproducible, if you visit https://github.com/orgs/backdrop-ops/teams/bug-squad/members as anonymous (not logged into any GitLab account).

These might help:

https://help.github.com/en/articles/publicizing-or-hiding-organization-membership

https://help.github.com/en/articles/changing-team-visibility

**Comment by klonos** [comment]
...worth noting that:

> **Tip**: If a team has child or parent teams, you cannot make it a secret team.

**Comment by klonos** [comment]
It seems to me that team member visibility can only be set among the members of the same organization (which implies having a GitHub account). I could not find any documentation on how to achieve showing these members publicly.

Perhaps we can pull this info somehow using the GitHub API? ...don't really know.

**Comment by klonos** [comment]
> Perhaps we can pull this info somehow using the GitHub API? ...don't really know.

I was referring to displaying that info on b.org.

**Comment by jenlampton** [comment]
Yeah, all our teams are already public, yet none are visible to anyone who is not on github. I think the API might be our best bet.

See https://github.com/backdrop-ops/backdropcms.org/issues/591
