### ISSUE TITLE
Maintainer application: Mosaic Grid module

### ISSUE THREAD

**Issue by korontari** [backdrop-ops/contrib#339]
Hello!

I have been working on a module that would provide a nice image gallery based on views. This is what I came up with: https://github.com/korontari/mosaic_grid.

I would be grateful for a code review and testing it as well as any advice for improvement (I am not a pro coder). I would also appreciate any license check. There are two jQuery libraries in this module that are covered by MIT license. While this sounds ok to me I may not be aware of some details concerning licensing and how they fit Backdrop in particular.

I have been applying in the past with [ Views Photo Grid port](https://github.com/backdrop-ops/contrib/issues/310) but I couldn't make the module work properly as it appears to have some issues in jQuery library itself that I can't fix. So in this new module I have used a completely different library wich seem to work well for me. Here is a small demo on pantheon: http://dev-copper-mountain.pantheonsite.io/mosaic.

**Comment by klonos** [comment]
Sorry for the really late response on this one @korontari 😓 

- [x] ~~If porting a Drupal project, Maintain the Git history from Drupal 7.~~ new, Backdrop-only module - not a D7 port.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0)

**Comment by klonos** [comment]
...welcome to the Backdrop Contrib Group 🎉 

> You've invited Pavel to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by korontari** [comment]
Thank you and no worries about late response. I understand it takes time to go through all the issues.
So should I now transfer my module repository to backdrop-contrib?

**Comment by klonos** [comment]
Hello again @korontari 👋 yes, you should transfer the project https://github.com/backdrop-contrib. There's instructions on how to do that here: https://github.com/backdrop-ops/contrib#what-to-do-after-your-application-is-accepted

This will allow you to create releases, which will then make the module available in b.org, and in the Project Browser 😉 

Let us know if you need any help with anything.

**Comment by korontari** [comment]
Thank you @klonos! I have transferred the repository and made a release. I wonder what is the Security release? And should be the code of the new module be checked by the Bug Squad?

**Comment by klonos** [comment]
Hey @korontari 👋 

> I wonder what is the Security release?

If you mean how you can mark a release of your project as a security release, then this is done via the release node on backdropcms.org ...once you have made a release that needs to be marked as security, please let someone [on Gitter](https://gitter.im/backdrop/backdrop-issues) know, and we'll do that for you.

> should be the code of the new module be checked by the Bug Squad?

This is not a requirement, no. But you can request help for any issue you may have, or anything specific you need someone to test; also on Gitter 😉

**Comment by stpaultim** [comment]
I went ahead and closed this issue. The module has a public release and the maintainer has been added to contrib group. 

Is there anything else?
