### ISSUE TITLE
Port Request: Block Background Color

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#341]
Here is the Drupal Module:
https://www.drupal.org/project/block_background_color

I set up a repo on backdrop-contrib:
https://github.com/backdrop-contrib/block_background_color

I have suggested that this feature might be a useful core feature. 
https://github.com/backdrop/backdrop-issues/issues/3918

I am interested in a feature like this for a contrib module I am working on:
https://github.com/backdrop-contrib/tatsu/issues/21

I posted in note in the Drupal issue queue for this module: https://www.drupal.org/project/block_background_color/issues/3066901

**Comment by klonos** [comment]
Hey @nitheesh 👋 ...let me know if you need help applying to become a Backdrop Contrib maintainer 😉

**Comment by stpaultim** [comment]
This is complete. @nitheesh responded to my request and helped port this module. He has also expressed interest in becoming the maintainer of this module. 

I've invited him to apply to become a maintainer. 

I'll close this issue.

**Comment by nitheesh** [comment]
Thanks, @stpaultim @klonos. I'm very glad to be part of the Backdrop Contrib team. Let me know the process.
