### ISSUE TITLE
Make a 'template repository'? (or three)

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#344]
I just noticed this (new?) setting in GitHub: https://help.github.com/en/articles/creating-a-template-repository

![image](https://user-images.githubusercontent.com/2385329/61856978-e714b980-aecb-11e9-8c96-6c78b4d8e396.png)

Wonder if this would be a good idea for this repo? Then module developers could [create new repositories](https://help.github.com/en/articles/creating-a-repository-from-a-template) from this template, with the README, etc. already setup and ready to go.
I know we already have an example README and LICENSE, but you still have to copy/paste them manually... Having a template would make this easier I think.

Or would it be better to have multiple template repositories; one each for a module, theme and layout? Then they could include the info file, etc. ready to go.

**Comment by BWPanda** [comment]
@jenlampton What do you think of this?

**Comment by jenlampton** [comment]
I like the multiple template repositories idea :)

**Comment by BWPanda** [comment]
@jenlampton Cool, sounds good! I'd be happy to do this if you like, though I'd need more access to the backdrop-ops group in order to create the new repos. Or can I set them up under my account, let you review them, and then transfer them to Backdrop?

**Comment by jenlampton** [comment]
We can add you to backdrop-ops.

**Comment by jenlampton** [comment]
Okay, I think you should be able to create a repo there now. Can you
give it a try?
--
Jennifer Lea Lampton
Jeneration Web Development
www.jenerationweb.com | 510-747-8230

**Comment by BWPanda** [comment]
Yep, looks good thanks. Will work on this soon 🙂

**Comment by BWPanda** [comment]
One done: https://github.com/backdrop-ops/module-template

**Comment by jenlampton** [comment]
@BWPanda this looks great!!  Thank you for working on these :)

I had been meaning to make a few changes to the example readme: I turned all the names into links, and added a sponsoring org under credits. I made the same changes to this copy as to the one in the examples dir for backdrop-ops/contrib.

I also made one small change to the .info file and moved the `type = module` line to the top, above the name. I'm not sure that's an improvement, but it's what I do in my projects (mostly so it's a clear difference from D7).

**Comment by BWPanda** [comment]
Thanks @jenlampton, I'm happy with those changes.

Here's the next one: https://github.com/backdrop-ops/layout-template

**Comment by docwilmot** [comment]
How about these other common elements?
- tests folder
- templates folder
- views folder
- includes folder
- `my_module.theme.inc`
- `my_module.admin.inc`
- `my_module.api.php`

How do we want to go, include everything and have the user delete what he doesnt need, or include only the minimum? 

And this encroaches a bit on `Examples module` territory.

**Comment by BWPanda** [comment]
I was kinda going for a similar '80%' rule that Backdrop uses elsewhere, though my idea of what constitutes 80% of common code is admittedly made up...

**Comment by serundeputy** [comment]
fwiw; `drush bp module` does this too or similar.
  * admittedly `drush bp` could use some improvements, but it is useful as it is.  

I take it these template repos are for new modules/themes/layouts not one being ported from drupal where one would want to preserve commit history etc?

**Comment by BWPanda** [comment]
> I take it these template repos are for new modules/themes/layouts

Yeah, they're basically a more detailed version of https://github.com/backdrop-ops/contrib/tree/master/examples Just a way for people to setup a new module/thtme/layout repo without writing/copying all the basic code from scratch.

**Comment by BWPanda** [comment]
Last one: https://github.com/backdrop-ops/theme-template

Going to close this issue now. All future suggestions/comments/etc. for these repos can go in their respective issue queues.
