### ISSUE TITLE
Application to join Backdrop contrib

### ISSUE THREAD

**Issue by nitheesh** [backdrop-ops/contrib#345]
The original request was made as part of the issue - https://github.com/backdrop-ops/contrib/issues/341. I've worked with @stpaultim to port the [Block Background Color](https://github.com/backdrop-contrib/block_background_color) module from [D.O](https://www.drupal.org/project/block_background_color).

I would like to become a maintainer at Backdrop contrib. Let me know if anything else I need to provide to process my request.

**I agree to the Backdrop Contributed Project Agreement.**

Thanks

**Comment by klonos** [comment]
All requirements met:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

So welcome onboard @nitheesh 🎉 🙂
