### ISSUE TITLE
Intent/Request to port Forum Access module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#346]
I'm going to help get this port started. But, please anyone feel free to jump it at anytime to help save me from this madness. :-)

https://www.drupal.org/project/forum_access

I'm going to run this through Coder Upgrader to help get started on a solution to this problem: https://forum.backdropcms.org/forum/what-modules-are-used-backdrop-forum

**Comment by VasasA** [comment]
Ported by @stpaultim :
https://github.com/backdrop-contrib/forum_access

**Comment by stpaultim** [comment]
I started the port, but it still needs lots of work. I got distracted, will try to find time to look at this but if anyone else has time to work on it I welcome the help. This was intended to be a learning project for me.

**Comment by VasasA** [comment]
I'm working on it.

**Comment by VasasA** [comment]
It was not easy to convert. :sweat_smile:  I created a PR with 32 commit: https://github.com/backdrop-contrib/forum_access/pull/10
@stpaultim Please, merge it, and test the module.
Please, close the issues, if the module works: https://github.com/backdrop-contrib/forum_access/issues
**Important**: Apply this patch in the Forum module: https://github.com/backdrop-contrib/forum/commit/77570c8d17cfdab1ffcf67578688db289507d577

**Comment by stpaultim** [comment]
Changes merged. Needs testing, but I think we can close this issue.
