### ISSUE TITLE
Module Port Request: Accordion Blocks

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#349]
https://www.drupal.org/project/accordion_blocks

I have suggested this as a possible core feature:
https://github.com/backdrop/backdrop-issues/issues/3995

**Comment by olafgrabienski** [comment]
@stpaultim Have you also considered to port https://www.drupal.org/project/collapsiblock instead? With *Accordion Block* you create a special accordion block, *Collabsiblock* provides an "collapsible" option for every block. And release-wise, the latter is more up to date.

**Comment by klonos** [comment]
https://www.drupal.org/project/accordion_blocks

> This module provides admin interface to add more Accordion widgets and for each Accordion widget we can choose set of blocks as content.

If I am reading this correctly, this sounds like collapsible "regions" ...all blocks added to an accordion "widget" will be wrapped in an accordion - so 1 single click hides multiple blocks in one go.

...whereas https://www.drupal.org/project/collapsiblock works as a setting for each individual block:

> Collapsiblock makes all Drupal blocks collapsible. To show/hide the content of a block just click on its title.
>
>Optionally, the last state of blocks is saved in a cookie for each user.

**Comment by VasasA** [comment]
Accordion Blocks module uses D7's Block module functions. There aren't these functions in Backdrop's Block module:
block_load()
_block_rehash()
_block_compare()

I couldn't port this module.

**Comment by keiserjb** [comment]
Preliminary, rought draft port of Collapsiblock. https://github.com/backdrop-contrib/collapsiblock  I think accordion blocks is a lost cause.

**Comment by stpaultim** [comment]
Based upon this feedback and progress on the collapsiblock module, I'll close this issue.
