### ISSUE TITLE
Application to join contrib team: Radix

### ISSUE THREAD

**Issue by arshad** [backdrop-ops/contrib#35]
Hi

I've ported the Radix theme to Backdrop and would like to join the contrib team.

### Checklist

- [x] Drupal version: http://drupal.org/project/radix
- [x] Drupal maintainer: Arshad (myself)
- [x] Backdrop version: https://github.com/arshad/radix_backdrop
- [x] GPL v2 License: https://github.com/arshad/radix_backdrop/blob/1.x/LICENSE.txt
- [x] README: https://github.com/arshad/radix_backdrop/blob/1.x/README.md
- [x] Demo: http://dev-radix-backdrop.pantheon.io/

Thanks
Arshad

**Comment by quicksketch** [comment]
Hi @arshad! This is excellent! I was looking over it this weekend and I'm impressed. Thanks so much for doing this port! You've definitely gone above and beyond.

Would agree to the following for the record?

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must agree to license your contributions as GPLv2 or later.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.  The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explaination.    

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later. 

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc) 
  1. A list of the current maintainers for the Backdrop project
  1. A list of the past maintainers for the Backdrop or Drupal project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by arshad** [comment]
I've read and agree to the Backdrop Contributed Project Author Agreement.

Thanks @quicksketch.

**Comment by quicksketch** [comment]
Invite sent. Thanks @arshad! Looking forward to collaborating with you. :smile:
