### ISSUE TITLE
Request to join backdrop contrib team

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/contrib#350]
I wrote a Backdrop module to export iCal feeds using views: https://github.com/indigoxela/viewsicalexport

It's not actually a port, but is a complete rewrite of Drupal [Date iCal](https://www.drupal.org/project/date_ical) with less features and no external library dependencies.

There is already a [full port](https://github.com/backdrop-contrib/date_ical) for that module, but unfortunately it has showstopper issues, which are hard to fix.

My module tries to be a lightweight alternative for people not needing the iCal import/parse feature.

I've already contributed to Backdrop core (comments, testing, code, issues).

**Comment by klonos** [comment]
Hey @indigoxela 👋 ...please bear with me as I double-check with the rest of the team re the process when the contrib module is not a port (this case is not covered in https://github.com/backdrop-ops/contrib#new-project-checklist)

In the meantime, may I suggest that you rename the module to `views_ical_export` (this is not a requirement at all - just my personal opinion that it would make the name more easily-readable).

**Comment by indigoxela** [comment]
@klonos:

> please bear with me as I double-check with the rest of the team re the process when the contrib module is not a port

No problem, no need to hurry. ;)

> ...rename the module to views_ical_export

Using underscores for module directories was always called "bad practice" in Drupal. Are underscores preferred in Backdrop? Can't seem to find the guidelines for that.

@herbdool:

> Glad to review your module!

You're welcome.

**Comment by indigoxela** [comment]
> you've got a class ViewsicalexportBlankDateFieldException that I think needs to be listed in hook_autoload_info

@herbdool that's an interesting point. I don't think, this class needs hook_autoload_info, as it is included in the .module file.
The hook is necessary, if the class is defined in an extra .inc or .php file. 
Comparable to the files[] property in Drupal info files.
class_exists() returns true. ;)

**Comment by olafgrabienski** [comment]
@klonos Have you been able to check the requirements for the contrib team application in this case? And/or are there other open questions?

(I'd like to use the Views iCal Export module, and I'd prefer to use it as an official contrib version.)

**Comment by klonos** [comment]
Yes, I have. It's basically the same as the requests when porting existing D7 projects, minus the "maintain the Git history from Drupal 7" requirement of course.

- [x] ~~If porting a Drupal project, maintain the Git history from Drupal 7.~~ new, Backdrop-only module - not a port.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0).

Invite underway @indigoxela ...welcome to Backdrop Contrib 🎉 

> You've invited indigoxela to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by indigoxela** [comment]
In the meantime I have moved my module to backdrop-contrib and added a release.
https://backdropcms.org/project/viewsicalexport
