### ISSUE TITLE
Port Request: role_delegation module

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-ops/contrib#351]
I would like to get the [Role Delegation](https://www.drupal.org/project/role_delegation) module ported. I have created [this issue](https://www.drupal.org/project/role_delegation/issues/3077306) on Drupal.org.

I have done the[ initial port](https://github.com/kelizoliva/role_delegation) which went mostly fine, but I am running into issues with how users are handled in Backdrop vs. Drupal 7. Would love to work with someone seeing this through, if anyone would like to help. I and Palante are happy to continue to maintain the module going forward, as we hope to be using it long-term in a large deployment project here at Palante.

Would also like this ticket to serve as my application to join the Backdrop Contrib group! I am generally interested in helping to move modules along where I can!

**Comment by klonos** [comment]
Hey, welcome @kelizoliva 👋 and thanks for letting the original maintainers know, by raising that d.org issue. You may want to consider to offer them to (co-)maintain the Backdrop port either now or in the future if they decide to.

...here's the list of requirements for new applications/projects, as per https://github.com/backdrop-ops/contrib#new-project-checklist:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [ ] Include a README.md file that includes license and maintainer information.
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0). Please use [this text for GPL-2.0](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).

I had a quick look, so you need to:

- rename `README.txt` to `README.md` (also make sure that lines in it do not exceed the max of 80 chars/line)
- add a LICENSE.txt

I would additionally recommend to remove the CHANGELOG.txt file, as it only creates overhead.

> ...went mostly fine, but I am running into issues with how users are handled in Backdrop vs. Drupal 7.

I have not examined the code thoroughly, but a couple of things that you should be aware are:

- Role IDs in Backdrop have changed to role (machine) names instead (see https://api.backdropcms.org/change-records/converted-user-roles-cmi). I see quite a few instances of `$rid` in the code.

- (most) Settings in Backdrop are saved in configuration. I'm sure you will find https://api.backdropcms.org/converting-modules-from-drupal of great use, and the "Update your module to use Configuration management" section specifically to what I am referring to here.

Lastly, have you tried https://github.com/backdrop-contrib/coder_upgrade and https://github.com/backdrop-contrib/coder_review ?

**Comment by kelizoliva** [comment]
> You may want to consider to offer them to (co-)maintain the Backdrop port either now or in the future if they decide to.

Noted, and I have!

I have added LICENSE.txt and renamed README, removed CHANGELOG.

> Lastly, have you tried https://github.com/backdrop-contrib/coder_upgrade and https://github.com/backdrop-contrib/coder_review ? ...thy may make your life easier 😉

I have not, but I am checking those out now!

I only quickly performed the initial port steps to see how things fared. With this additional information, I will try to get working module going. Thank you!

**Comment by kelizoliva** [comment]
I've performed a deeper dive into the code and Backdrop API, and I believe I have most everything changed correctly for Backdrop (I did run the Coder Upgrade and Coder Review modules, thank you!).

There are [two outstanding issues](https://github.com/kelizoliva/role_delegation/issues) that I am feeling pretty stuck on. They are major issues, in that the module will be non-functional until these issues are addressed. I'm feeling a little out of depth here with regard to how Backdrop handles roles, despite reading into it in the documentation.

**Comment by klonos** [comment]
Hello @kelizoliva 👋 ...sorry for the late response, but life's been busy lately (working on the latest 1.14 release 😄). I have checked the port, and all remaining checkboxes have been ticked 👍 

There is no need for any remaining issues to hold up moving the project to https://github.com/backdrop-contrib, so I have sent you an invite:

> You've invited kelizoliva to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome to Backdrop Contrib! 🎉

Perhaps you can consider joining us in [our Gitter channel](https://gitter.im/backdrop/backdrop-issues), where you can ask for help there?

PS, I have filed this PR for your consideration, to fix some minor formatting nits in the README: https://github.com/kelizoliva/role_delegation/pull/3

**Comment by kelizoliva** [comment]
Fantastic, thank you Gregory! I will close this ticket now and move the repository into  Backdrop Contrib to continue work on it. :)
