### ISSUE TITLE
Port request: Feeds Tamper

### ISSUE THREAD

**Issue by mazzech** [backdrop-ops/contrib#353]
This module would be a great addition to contrib, several import scenarios are not covered by Feeds module itself, e.g. multi field values, find & replace strings, image import. A solid import function could be a real advantage for Backdrop, i have several D7 installations where customers make CSV imports on a regular basis (which is not possible in D8 yet, unless they fiddle around with Migration framework)

**Comment by laryn** [comment]
I had started this at one point and ran stuck on some `ctools` related items, IIRC:

https://github.com/laryn/feeds_tamper

**Comment by mr-simba** [comment]
I am missing Feeds Tamper also. I use it in most of my projects.

**Comment by laryn** [comment]
Latest version under development is now under the contrib space and available for testing, feedback and PRs:

 - https://github.com/backdrop-contrib/feeds_tamper/

(Thanks to @herbdool for picking it up and helping move it forward)
