### ISSUE TITLE
Working on google tag manager

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#357]
@kthull and I are working on a port of GoogleTagManager module
https://github.com/kthull/google_tag

Drupal project
https://www.drupal.org/project/google_tag

Looks like we still need a d.o issue...
https://www.drupal.org/project/issues/google_tag?text=backdrop

**Comment by kthull** [comment]
d.o issue created: https://www.drupal.org/project/google_tag/issues/3081660

**Comment by jenlampton** [comment]
GTM module posted to contrib: https://github.com/backdrop-contrib/google_tag
