### ISSUE TITLE
Working on a port of ImageMagick

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#358]
@kthull and I are working on a port of ImageMagick module
https://github.com/kthull/imagemagick

Drupal project:
https://www.drupal.org/project/imagemagick

Looks like we still need to create a d.o issue:
https://www.drupal.org/project/issues/imagemagick?text=backdrop&status=All

**Comment by kthull** [comment]
d.o issue created here: https://www.drupal.org/project/imagemagick/issues/3081661

**Comment by korontari** [comment]
I was about to post a port request for ImageMagick module and found that it is already being worked on. Awesome! I very much anticipate it. :+1:

**Comment by jenlampton** [comment]
ImageMagick is available at https://github.com/backdrop-contrib/imagemagick, closing this issue!
