### ISSUE TITLE
Application to join Backdrop contrib

### ISSUE THREAD

**Issue by kthull** [backdrop-ops/contrib#359]
I'm working with @jenlampton on two module ports so I should officially apply here as well.

- [ImageMagick](https://github.com/kthull/imagemagick) - https://github.com/backdrop-ops/contrib/issues/358 
- [Google Tag](https://github.com/kthull/google_tag) - https://github.com/backdrop-ops/contrib/issues/357. 

I'll submit the d.o issues shortly.

**Comment by kthull** [comment]
d.o issues have been filed as noted on each of the above tickets

**Comment by kthull** [comment]
It's been a while...anything else I need to do on my end?

**Comment by jenlampton** [comment]
@kthull we'll need you to agree to the https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement (a written statement here that you do is sufficient).

I'll also check your contrib projects for the following...

ImageMagick - #358
- [ ] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [ ] Include a README.md file that includes license and maintainer information.
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in rare cases GPL-3.0)

Google Tag - #357.
- [ ] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [ ] Include a README.md file that includes license and maintainer information.
- [ ] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0 (or in

**Comment by kthull** [comment]
@jenlampton I agree to the terms!

**Comment by klonos** [comment]
Thanks and welcome to the Backdrop Contrib group @kthull 🎉 🙂 

. You've invited Kevin Thull to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by klonos** [comment]
...you can now move the projects under https://github.com/orgs/backdrop-contrib and create releases for them when you think they're ready for public consumption 😉 

See here for details on how to do that: https://github.com/backdrop-ops/contrib#what-to-do-after-your-application-is-accepted
