### ISSUE TITLE
I'm making a global climate strike module.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#360]
It should be up in 5 mins or so.

**Comment by jenlampton** [comment]
Module is up https://github.com/backdrop-contrib/globalclimatestrike/releases/tag/1.x-1.0.0

**Comment by stpaultim** [comment]
FYI  - I assume this just implements the Javascript available on this page. 
https://digital.globalclimatestrike.net

**Comment by jenlampton** [comment]
Yep, and it has a settings page so you can choose whether you want the X so people can get around it or not :)
