### ISSUE TITLE
Backdrop Contributed Project Group Application

### ISSUE THREAD

**Issue by AlexShapka** [backdrop-ops/contrib#362]
I agree to the Backdrop Contributed Project Agreement. As stated on https://github.com/backdrop-ops/contrib/issues/361 I'd like to port my first Drupal 7 module. In fact, I already have working code ported, but don't know where to push it to.

**Comment by klonos** [comment]
Thanks @AlexShapka 👍 ...please push it to your own GitHub repo, and then post a link to it here. We will then review it and provide feedback. If everything checks out, you will be invited to the https://github.com/backdrop-contrib group, and will be able to transfer the project there 😉 

Please let us know either here or on Gitter if you need any help.

**Comment by AlexShapka** [comment]
It's ready on https://github.com/AlexShapka/search_krumo

**Comment by klonos** [comment]
Hello @AlexShapka 👋 I have checked the repo, and it meets the minimum requirements:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7
- [x] Include a README.md file that includes license and maintainer information
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

Invite is underway:

> You've invited Sasha to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Welcome to the Backdrop Contrib group! 🎉 ...I hope you have fun in the community ❤️

**Comment by klonos** [comment]
...you can now move the repo under https://github.com/orgs/backdrop-contrib (see https://github.com/backdrop-ops/contrib#what-to-do-after-your-application-is-accepted). Once you have done that, and have created a release, it will show up in backdropcms.org + also be available in the Project Browser for people to install it 😉

**Comment by AlexShapka** [comment]
Thanks a lot Greg! I will start reading how to get it moved to contribs.

**Comment by AlexShapka** [comment]
Done https://github.com/backdrop-contrib/search_krumo I believe we can now close this issue. Again thank you very much, Greg!
