### ISSUE TITLE
'Trash' module

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#363]
I had an idea for a 'trash' module for Backdrop. It would provide a 'soft delete' ability for content so that deleting something isn't permanent (until it's removed from trash). Basically the same as the trash can on your computer. Here're some thoughts:

It would provide a way of marking nodes, comments and terms (not sure about other entities like layouts, users, etc.) as 'trashed'. 'Trashed' entities would not appear publicly anywhere, only listed in a new 'Trash' view. From there they could be permanently deleted or 'restored'.

It would have to hook into the current delete hooks, possibly overriding them to provide a middle-ground between a regular node and deleting one altogether.

I looked for Drupal modules, and while there are a few, none really seem to be current or designed quite the way I'm thinking.

Just putting this out there for now as I'm not sure I have the time to build this myself yet, and I'd like to get an idea of the interest first too. Also, would it be better to develop straight in core, or in contrib initially?

Thoughts?

**Comment by docwilmot** [comment]
Ideally we need [revision states](https://www.drupal.org/project/drupal/issues/218755) in core. That would allow Draft, Live, Trashed, Moderated, Waiting Moderation, etc etc; all kinds of configurable states for (Node) Entities.

**Comment by BWPanda** [comment]
@docwilmot Is there a Backdrop core issue for that?

**Comment by docwilmot** [comment]
Not that I know of

**Comment by klonos** [comment]
>@docwilmot Is there a Backdrop core issue for that?

Why are you asking @docwilmot man? 😛 ...you know I'm the man 😅 ...of course there is: https://github.com/backdrop/backdrop-issues/issues/2498 😉

**Comment by BWPanda** [comment]
Ha, well there you go. Guess we can close this in favour of that core issue then.

**Comment by docwilmot** [comment]
But!
There isn't really an issue for [revision states](https://www.drupal.org/project/drupal/issues/218755) in core though. That issue is about trash 😄 
Do we have an issue specifically for revisions @klonos? or is that issue re-purposable?
