### ISSUE TITLE
Port of the Tocbot module

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/contrib#365]
There is a quite new Drupal 7 module called [Tocbot](https://www.drupal.org/project/tocbot). It provides a wrapper around the Tocbot library which builds an table of contents (TOC) with navigation links from HTML headings.

I like the module, and there is no Table-of-content-module for Backdrop so far. I'll try to port it to Backdrop.

Issue on drupal.org: https://www.drupal.org/project/tocbot/issues/3088630

**Comment by alfabuster** [comment]
+1. It is very useful module for info web sites, with massive articles. I will wait for this module.

**Comment by alfabuster** [comment]
> There is a quite new Drupal 7 module called [Tocbot](https://www.drupal.org/project/tocbot). It provides a wrapper around the Tocbot library which builds an table of contents (TOC) with navigation links from HTML headings.
> 
> I like the module, and there is no Table-of-content-module for Backdrop so far. I'll try to port it to Backdrop.
> 
> Issue on drupal.org: https://www.drupal.org/project/tocbot/issues/3088630

Hi olafgrabienski, how is your progress with porting Tocbot module to backdrop cms?

**Comment by olafgrabienski** [comment]
@alfabuster I haven't started so far but I hope I'll find some time next week.

**Comment by olafgrabienski** [comment]
I've started the port but it's not ready to use. Any help is appreciated.

https://github.com/backdrop-contrib/tocbot

**Comment by findlabnet** [comment]
I have working port of this module with some small fixes (I do not use Coder Upgrade):
https://github.com/findlabnet/tocbot
Only need to update README.md and tocbot.install for variables migration (haven't time for it at this time). 
You can use anything from this repo, hope it help you to release.

**Comment by olafgrabienski** [comment]
@findlabnet Thanks a lot, I'll have a look at your repo! May need some time, though.

For curiosity: Did you port from the [new 7.x-1.1 release](https://www.drupal.org/project/tocbot/releases/7.x-1.1)? It was released today.

**Comment by findlabnet** [comment]
No, from 7.x-1.0, as marked in .info, with my small changes, for example you can disable CDN, library already within module.

**Comment by olafgrabienski** [comment]
I've made an initial release of Tocbot for Backdrop:

- https://github.com/backdrop-contrib/tocbot/releases/tag/1.x-1.1.0

Project page:

- https://backdropcms.org/project/tocbot

Thanks for helping me @findlabnet, @BWPanda, and @stpaultim!
