### ISSUE TITLE
Contrib Group Application - Views Selective Filters

### ISSUE THREAD

**Issue by bobchristenson** [backdrop-ops/contrib#368]
Hiya!  Looking to become an official Backdrop contributor.  I run [Mustardseed Media](http://mustardseedmedia.com) full time and I'm currently in the transition for my clients from D7 over to Backdrop.  Apparently [I've been using Drupal (as Rob_Feature) for 13 years and 10 months](https://www.drupal.org/u/rob_feature).  I've tried to contribute there as much as possible, but my contributions come more in the way of training and testing (although I've contributed a few things).

Anyway...I'm in the process of launching some new sites on Backdrop and finally had the opportunity of porting my first module: [Views Selective Filters](https://github.com/bobchristenson/views_selective_filters) (hopefully the first of many).

I'm not a hardcore developer, but certainly I know my way around the ecosystem (still learning differences between D7 and Backdrop).  So, I'm always looking for help/advice for any projects I may port/develop in the future.

Let me know where we go from here!

**Comment by klonos** [comment]
Hello @bobchristenson and sorry for the late responce.

a) Huge fun; some of your videos have helped me during my first steps into Drupal-land, so your face and voice feels familiar, and b) it's really great to have you on-board 👍 

For each application to join the Backdrop Contrib, we ask the following criteria to be met:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0.

You have ticked all these boxes, so last thing is to have you state that you agree with https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement

A couple of recommendations:

- When starting a port of an existing D7 module, out of courtesy, we open an issue in the d.org issue queue of that module, to inform its maintainers of our intention to port it to Backdrop and ask if they were planning to port it themselves. Even if not, we invite them to join and co-maintain at any time in the future, if they change their minds. It would be nice if you did that now retrospectively. If you do, please tag the d.org issue as `backdrop-port`

- Besides the `package = Views` entry in the module .info file, you may want to add a `tags = ` one as well. See https://api.backdropcms.org/documentation/module-packages-and-tags 😉

**Comment by bobchristenson** [comment]
Yup, the contributed project agreement looks good...I agree!  

A note that I tend to usually only maintain my own projects (private repos for my own clients) so I'll have a learning curve about how to maintain a more public module like this one.  I've never had to deal with pull requests, merges, etc....so I may need some mentoring on how to actually maintain, but I'm looking forward to learning a bit about that!

I'll look to add an issue in the drupal.org module queue and I'll read up on those tags as well.  Thanks, let me know what I need to do next!

**Comment by bobchristenson** [comment]
Backdrop port message posted on d.o. https://www.drupal.org/project/views_selective_filters/issues/3090953

**Comment by klonos** [comment]
Thanks @bobchristenson and sorry for the late response 😓 ...I hope that this delay has not been blocking you from doing further work.

Also thanks for filing that issue in the d.org queue 👍 

Well, without further ado, officially welcome to the Backdrop Contrib group 🎉:

> You've invited Bob Christenson to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

**Comment by klonos** [comment]
> I'll have a learning curve about how to maintain a more public module like this one. ...so I may need some mentoring on how to actually maintain...

Sure, we're here to help 🙂 ...the "" section here should be able to provide some guidance as to what the next steps are in order to move the project repo under https://github.com/backdrop-contrib, but if you have additional questions, feel free to ask away; I personally lurk around the Gitter chat 😉 

Please see https://backdropcms.org/contribute/join/welcome for next steps (that page has recently been moved from the GitHub README to b.org, so if you happen to spot anything out of order or missing steps, please let us know).

**Comment by bobchristenson** [comment]
@klonos Hmm...I fear I did something wrong.  I'm stuck on the "update who gets access" step because after transferring the repository, I dont see a 'settings' tab at all: https://github.com/backdrop-contrib/views_selective_filters

Did things change or am I missing something?

**Comment by klonos** [comment]
Hey @bobchristenson 👋 ...sorry, this seems to have slipped under my radar.

You were added to that repo with "maintain" permissions; I have now elevated that to admin for you. Can you please give it another go now?

**Comment by bobchristenson** [comment]
Sorry...back to this after so long away and I seem to be lost (again).  I now see the settings tab (thanks!) and it looks like the 3 teams have appropriate permission (or I should say 'reasonable' permissions, since I dont know exactly what those permissions should be)....but not sure what to do next?  I can't find what to do in order to get this project 'active' and then added over on the backdropcms project list?

Sorry, I'm so in and out of Backdrop currently that I forgot this was pending...next steps here?

**Comment by bobchristenson** [comment]
@klonos Just another 'ping' here....want to get this project active for everyone but I got stuck a while back and couldn't proceed...

**Comment by klonos** [comment]
FTR, this has been done: https://github.com/backdrop-contrib/views_selective_filters/releases ...sorry for not being as active in this queue as I used to be; keeping up with "all things" in life is hard 😓
