### ISSUE TITLE
Please add me as a maintainer for Simplenews project

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#373]
Per the following explanation of @BWPanda on Gitter:

> @alanmels @stpaultim @herbdool @laryn There's no need to wait 2 weeks to take over maintainership of Simplenews. https://backdropcms.org/user-guide/adopt-project says: > File an issue with the current project requesting to help maintain the project. > If the project does not have a listed maintainer, or if a current maintainer does not respond within 2 weeks, create a separate issue asking to be added as a maintainer. I.e. the "2 weeks" part only applies if there's an existing maintainer. The README at https://github.com/backdrop-contrib/simplenews says it's seeking maintainers and that it was ported by @biolithic. TL;DR: If there's no maintainer listed for a project, it's considered abandoned and you can file an issue requesting to take over maintainership (without waiting 2 weeks for a (non-existent) maintainer to respond).

I am requesting to add myself as a maintainer for Simplenews project. However, if possible best course for me would be completely deleting the current project on https://github.com/backdrop-contrib/simplenews, because we started porting Simplenews not by forking the project on GitHub, but cloning it from 7.x version on Drupal.org. Code changes on https://github.com/backdrop-contrib/simplenews are minimal and were done 5 years ago. So starting from clean slate would be preferable.

I've filed an issue on https://github.com/backdrop-contrib/simplenews/issues/1, but was told on Gitter that the current maintainer would not be responding as he did not respond for other projects he maintained.

**Comment by herbdool** [comment]
If there's a way you can replace without deleting this that would be ideal. So long as the d7 git history remains.

**Comment by BWPanda** [comment]
What about making a (large) PR to merge AltaGrade's repo into the contrib one...?

**Comment by herbdool** [comment]
Yeah, might work

**Comment by alanmels** [comment]
I could try. Should proceed creating such a PR or should I wait until this is decided? Will anyone add me as the maintainer or it doesn't matter if I just do PR and merge?

**Comment by quicksketch** [comment]
@alanmels Sure that would be great. To follow protocol, also file a separate PR that just adds yourself to the README.md as a maintainer. The instructions include:

> File an issue with the current project requesting to help maintain the project.
> If written permission is granted by a current maintainer, create a PR that adds your name to the README.md file in the list of maintainers.

In lieu of the maintainer being present, a contrib maintainer will merge your PR instead.

**Comment by alanmels** [comment]
And since I was added as a maintainer, I've proceeded to merging and creating a release for working version.
