### ISSUE TITLE
Port of Image Field Caption

### ISSUE THREAD

**Issue by sternhagel** [backdrop-ops/contrib#380]
**Name of the module, theme, or layout you are working on**
Image Field Caption

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/image_field_caption

**(Optional) Link to the drupal.org issue where you notified the maintainer(s) of this port**
https://www.drupal.org/project/image_field_caption/issues/3097151

**Do you need assistance with this port?**
No, not at the moment - but anyone interested in (co-)maintaining, feel free to contact me!

**Comment by sternhagel** [comment]
The repository is online now:
https://github.com/sternhagel/image_field_caption

Seems to work in Backdrop so far...

Is this the place where I can apply for joining the contrib team?

**Comment by klonos** [comment]
Hello @sternhagel 👋 ...yes, you are at the right place 😄 

So here's the checklist for all new projects:

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

You seem to be ticking all the checkboxes, so welcome to the Backdrop Contrib group! 🎉 

> You've invited sternhagel to Backdrop CMS contributed projects! They'll be receiving an email shortly. They can also visit https://github.com/backdrop-contrib to accept the invitation.

Please refer to https://backdropcms.org/contribute/join/welcome for next steps, like moving your project to the backdrop-conrib repo.

PS: you should **remove the version line from the .info file**, as the packager script will take care of that when you create a release 😉 

You may also want to add `tags[]` to the .info file and/or `package` as well. Please see https://github.com/backdrop-contrib/devel/blob/1.x-1.x/devel.info as an example, and refer to this page for tags/packages that Backdrop supports: https://api.backdropcms.org/documentation/module-packages-and-tags

**Comment by klonos** [comment]
...FTR, may also please have you agree to this?: https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement (please add a comment here to state that you do).

**Comment by sternhagel** [comment]
@klonos Thanks for the warm welcome and your helpful suggestions! :-)
I'll try to move the project to the contrib repo as a next step.

FTR: I hereby declare that I agree to the Backdrop Contributed Project Agreement: https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement

**Comment by sternhagel** [comment]
The repo seems to be in backdrop-contrib now:
https://github.com/backdrop-contrib/image_field_caption

However I can't access the repo settings anymore after the transfer - seems like I don't have the necessary permissions...

**Comment by klonos** [comment]
Hello @sternhagel 👋 ...sorry for the really late response here. I see that you have already been added to the project with maintainer access. Is this still an issue for you?

**Comment by sternhagel** [comment]
@klonos Thanks, it's working now - so I think we can close this issue.
