### ISSUE TITLE
Port of Invite module

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#381]
**Name of the module, theme, or layout you are working on**
Invite

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/invite

**Link to the drupal.org issue where you notified the maintainer(s) of this port**
https://www.drupal.org/project/invite/issues/3097223

**Link to the Backdrop version**
https://github.com/altagrade/invite

**Do you need assistance with this port?**
Maybe

**Comment by rositis** [comment]
Did you start on this port? It seems to have stalled and I'd like to help.

**Do you agree to the Backdrop Contributed Project Agreement?**
Yes.

**Post a link to your new Backdrop project under your own GitHub account.**
https://github.com/rositis/invite

**Comment by rositis** [comment]
The port is pretty close to complete and ready for review. There is one roadblock, however. There is a bug in the Entity module in Backdrop core that needs to be addressed before the Invite By Email submodule will work. See more here:
https://github.com/backdrop/backdrop-issues/issues/4379

**Comment by alanmels** [comment]
Hi Ryan,

I'd love if you could help with getting it work and then to co-maintain the module. Please PR on https://github.com/altagrade/invite

**Comment by rositis** [comment]
Alan,
Thanks!  Which version should we use? It appears that we have both done much of the work to port the module, but it looks like you used the 7.x-2.x branch and I did the 7.x-4.x branch! Thoughts on how we should proceed?

**Comment by alanmels** [comment]
Not sure. I'd rather support your choice on this, because I'll be quite busy for about one more month. So if you pursue to finish this sooner, then I'll just stick with your choice. Just run both version and see which one is more ready.

**Comment by rositis** [comment]
The 7.x-2.x branch is no longer supported, so it makes sense to use the port of 7.x-4.x going forward.  I'm almost done with it at this point, with most of the major hurdles dealt with. That Entity module bug is the biggest roadblock I'm facing right now.

**Comment by alanmels** [comment]
> The 7.x-2.x branch is no longer supported, so it makes sense to use the port of 7.x-4.x going forward. I'm almost done with it at this point, with most of the major hurdles dealt with. That Entity module bug is the biggest roadblock I'm facing right now.

I don't insist on anything, but just so you know it will take some time to get changes in the core and therefore you could give a try to 7.x-2.x branch. It's almost done, there are only few bug fixes left. Also it does not have the entity dependency.

Also you don't have to stick with the versions supported for Drupal 7, because D7 will EOL soon anyway, and then Backdrop contributed modules will have to go their own life paths in that respect that they could be completely different.

**Comment by rositis** [comment]
That's a fair point. We need a working port up and running first and then we can adjust as needed.  

How about this idea? We get the 7.x-2.x port done and release it as our Backdrop 1.x-1.x  release. We can then use the 7.x-4.x port  as the basis for our Backdrop 1.x-2.x-dev version, which we can release once the Entity bug in Issue #4379 is resolved.

**Comment by alanmels** [comment]
Good idea! We need a working module for now. At the same time we could see the progress of https://github.com/backdrop/backdrop-issues/issues/4379 and then act accordingly.

**Comment by alanmels** [comment]
Please find the working version of the module on https://github.com/backdrop-contrib/invite/releases/tag/1.x-1.0.0

**Comment by rositis** [comment]
Yay! Thanks for kicking that out!
