### ISSUE TITLE
Profile Switcher module has been ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#387]
Hello everybody! This is just to let you know another module has been ported:

**Name of the module, theme, or layout you are working on**
Profile Switcher (https://github.com/backdrop-contrib/profile_switcher)

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/profile_switcher

**Link to the drupal.org issue on this port**
https://www.drupal.org/project/profile_switcher/issues/3106434

**Comment by alanmels** [comment]
I was supposed to change the label to "Port complete", but don't know how. Checkbox on the instructions on https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests seems not be available to me.

**Comment by stpaultim** [comment]
@alanmels - Thanks! 
I think that only a few people have label privileges on this repo. I'm not one of them. :-)
Someone will get to it.

**Comment by klonos** [comment]
All done. Thanks once again @alanmels 👍
