### ISSUE TITLE
Archive Request - AYAH project

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#391]
The maintainer just posted a request to "archive" this project which connects to a service that no longer exists. 

What needs to happen?

https://github.com/backdrop-contrib/ayah/issues/1

**Comment by jenlampton** [comment]
I have archived the project. 

As a general rule I think we should have the maintainer (or a bug squad member?) update the README to state why the project was archived before we archive it.

This should probably be added to https://backdropcms.org/user-guide/maintaining-your-project

**Comment by jenlampton** [comment]
I've added a section https://backdropcms.org/user-guide/maintaining-your-project
Feedback (or edits!) welcome :)

**Comment by sillygwailo** [comment]
@jenlampton One thing I would add to Maintaining Your Project page is how to get a project archived, i.e. post an issue in the backdrop-ops/contrib project. I couldn't archive AYAH myself, so I thank @stpaultim for connecting the dots here.
