### ISSUE TITLE
Application to join: argiepiano (and port of HMS Field)

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#393]
**The name of your module, theme, or layout**
HMS Field

**(Optional) Post a link here to an issue in the drupal.org queue notifying Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/hms_field/issues/3108556

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Post a link to your new Backdrop project under your own GitHub account**
https://github.com/argiepiano/hms_field

Once we have a chance to review your project, we may provide feedback that's meant to be helpful. If everything checks out, you will be invited to the @backdrop-contrib group, and will be able to transfer the project  😉

**Comment by jenlampton** [comment]
Hi @argiepiano and thank you for applying to join the contrib group :) 

All projects must meet these minimum requirements.

- [x] If porting a Drupal project, Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0
    (or in rare cases GPL-3.0 -- please see below).

This project looks great! An invite to join the contrib group is on the way to your inbox! :)

**Comment by jenlampton** [comment]
I read through all the module's code too and it looks spot-on. There is only one tiny little thing I saw that is different between how things were done in Drupal and how we like them in Backdrop: In Backdrop we prefer to have all CSS in a `css` directory and all JavaScript in a `js` directory. 

In this case, the module only has one file so it may not seem necessary to move it into a directory (it is entirely up to you) but the general reasons are 1) everyone would be able to find all JS files in all modules if we do this consistently across all projects, and 2) you won't need to add the directory later on if you ever decide to add an additional JS file. Again, it is not necessary to make any changes to your project. I am only leaving this note here to help point out a difference you may not have already been aware of.

Thanks for the module port, we're happy to have you!

**Comment by argiepiano** [comment]
Thank you! I've moved the js file to a new directory and committed the change. 

Forgive my ignorance, what's the next step? Should I import the repositories (currently living in my github account) to backdrop-contrib? Please let me know

**Comment by argiepiano** [comment]
OK, nevermind. I found the Backdrop [directions](https://backdropcms.org/contribute/join/welcome)

**Comment by argiepiano** [comment]
Hi again. I followed the [directions here](https://backdropcms.org/contribute/join/welcome) and transferred the repository to backdrop-contrib. However, I'm not able to complete step number 3, "Update who gets access".  I cannot see "Settings" in this project. Did I miss something?

**Comment by jenlampton** [comment]
> I'm not able to complete step number 3, "Update who gets access". I cannot see "Settings" in this project. Did I miss something?

I've updated the access on this project. I think we need to revisit the instructions and make sure they are accurate - you've done everything correctly!

**Comment by laryn** [comment]
I have invited @argiepiano to the "Documentation and Organization" team.
