### ISSUE TITLE
Port status: Views Aggregator Plus

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#395]
The name of your module, theme, or layout
Views Aggregator Plus

(Optional) Post a link here to an issue in the drupal.org queue notifying Drupal 7 maintainers that you are working on a Backdrop port of their project
https://www.drupal.org/project/views_aggregator/issues/3109116

If you have chosen option #2 or #1 above, do you agree to the Backdrop Contributed Project Agreement
YES

Post a link to your new Backdrop project under your own GitHub account
https://github.com/argiepiano/views_aggregator

**Comment by stpaultim** [comment]
@argiepiano - You only have to open one maintainer application, even if you have multiple modules. We have a developer meeting tomorrow and I'll bring up your application if no one has responded before then.

**Comment by jenlampton** [comment]
@argiepiano welcome and thanks for applying to join Backdrop contrib! Someone will get to your applicaiton shortly :) I'm going to change this issue from a maintainer application to a port status issue, since the application will be addressed in the other issue.

So sorry for the delay!
