### ISSUE TITLE
Backdrop Token

### ISSUE THREAD

**Issue by enzolutions** [backdrop-ops/contrib#4]
I did a migration of Token to Backdrop

- Cache
- Configuration Management
- Tests
- backdrop_drupal_compatibility = FALSE

Some test are failing I don't know why

Git project: https://github.com/enzolutions/backdrop_token

**Comment by quicksketch** [comment]
Hi Enzo! Thanks and sorry for the delay! I didn't even realize I hadn't turned on notifications for this repo. :(

Great job on the initial port. Thanks for adding a LICENSE.txt and README.md file. Do you think you could do a Git checkout from drupal.org then use that as the starting point? That would maintain the project history.

**Comment by quicksketch** [comment]
We drafted up a [contrib author agreement](https://github.com/backdrop-ops/contrib/blob/master/README.md#backdrop-contributed-project-author-agreement) to clarify expectations of the Contrib module group. Would you agree to the following?

---

Backdrop Contributed Project Group Application
==============================================

This project allows you to apply to join the [contributed project developer team](https://github.com/backdrop-contrib/).

To apply simply create a request as an issue at https://github.com/backdrop-ops/contrib/issues/new

If you have already written or ported a project to Backdrop, please include a link to the module or theme you have written, hosted either on Github under a personal account or elsewhere. After joining the Backdrop Contributed Project Group, you will be able to transfer the entire repository to live under `https://github.com/backdrop-contrib/[your_project_name]`

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

Process for Abandoned Projects
-----------------------------

If you feel a project in the Backdrop Contrib group has been abandoned, you may apply to adopt that project. To do so:

1. Join the Backdrop Contrib group by submitting an application (see above).

1. File an issue with the current project, requesting to help maintain the project. If written permission is granted by a current maintainer, add your name to the README.md file in the list of maintainers.

1. If the current maintainers do not respond within 2 weeks. [Create an issue in this repository](https://github.com/backdrop-ops/contrib/issues/new) to take over the project, including a link to the issue you filed with the abandoned project.

1. After confirming the project has been abandoned, a Backdrop Contrib administrator will add your name to the list of maintainers in that project's README.md file.

1. You may now maintain the project directly as though given permission by the project maintainers and likewise now grant permission to others to maintain the project.

**Comment by enzolutions** [comment]
Hi @quicksketch ok I will checkout the git version of token and do again the migration process.

I will ping you next week or as soon I finish.

**Comment by enzolutions** [comment]
I did a new version with git files as you request, check at https://github.com/enzolutions/backdrop_token

**Comment by quicksketch** [comment]
Looks like the history still isn't there though: https://github.com/enzolutions/backdrop_token/commits/master/token.module

You should be able to see the entire commit history from when Token was first written.

```
git clone --branch 7.x-1.x http://git.drupal.org/project/token.git
git checkout -b 1.x-1.x
git remote remove origin
git remote add origin git@github.com:enzolutions/backdrop_token.git
git push origin
```

You'll probably need to make a new repository to start fresh, since you won't be able to push over the existing repository. Then just copy all your changes over the top of the D7 files, commit and push again. :)

**Comment by enzolutions** [comment]
Hi @quicksketch check now at https://github.com/enzolutions/backdrop_token

**Comment by quicksketch** [comment]
Perfect now! Full history at https://github.com/enzolutions/backdrop_token/commits/1.x-1.x/token.module

To be official about it, could you state that you agree to the "Backdrop Contributed Project Author Agreement"?

**Comment by enzolutions** [comment]
I'm totally agree with "Backdrop Contributed Project Author Agreement" specially with the "Process for Abandoned Projects"

Is enough ?

**Comment by quicksketch** [comment]
Yep! Invite sent. You should now be able to create and move your repository over to the Backdrop Contrib group. Welcome! You're contrib member `#`5 :smile:

**Comment by quicksketch** [comment]
Please reopen if you have any trouble getting started.
