### ISSUE TITLE
 Application to join contrib team - for User Cancel Password Confirm

### ISSUE THREAD

**Issue by DavidRothstein** [backdrop-ops/contrib#40]
I would like to apply to join the Backdrop contrib team.

Here is a module I ported: https://github.com/DavidRothstein/user_cancel_password_confirm

It's a relatively small module that I wrote for a Drupal client a long time ago.  Mostly I picked it because I'm writing a blog post (hopefully will be published on Drupal Watchdog soon) about the mechanics of getting a Backdrop contrib project up-and-running on GitHub as well as how to link it up with the Drupal version of the project (to make it easy to simultaneously maintain both of them).

Bottom line, feel free to be extra-picky if you want to review what I did, so I can make sure there are no mistakes in the blog post :)

**Comment by quicksketch** [comment]
Hi @DavidRothstein! That's great.

This module looks really simple, with no configuration at all. I see you adjusted the change for `password_inc` from `variable_get()` to `settings_get()`, that's just about the only real difference I could spot in the code, other than the obvious `drupal` to `backdrop` changes.

Anyway, for an application, our policy is just to check a few items, which are all covered in your port:

- [x] README.md file that lists maintainers and license
- [x] LICENSE.txt file
- [x] Maintain the Git history from Drupal 7

So you're all good! Would you confirm you agree to the following?

----

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by DavidRothstein** [comment]
Great, thanks.  Yeah, I deliberately picked a simpler module since the blog post is going to focus mostly on the Git-related mechanics of the process (though I'll talk about the actual Backdrop-related changes a bit too).

I have read the Backdrop Contributed Project Agreement and confirm that I agree to it.

**Comment by quicksketch** [comment]
Excellent. Thanks @DavidRothstein! Invite is now on its way. Thanks for doing this comparison! Personally, I'm curious what you'll find as well. :smile: Thanks!
