### ISSUE TITLE
Menu Per Role module port

### ISSUE THREAD

**Issue by ericfg** [backdrop-ops/contrib#402]
**Name of the module, theme, or layout you are working on**
Menu Per Role

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/menu_per_role

**(Optional) Link to the drupal.org issue where you notified the maintainer(s) of this port**
https://www.drupal.org/project/menu_per_role/issues/3117866

**Do you need assistance with this port?**
No

# Please return to this issue when complete, and change the label to "Port complete".

**Comment by robertgarrigos** [comment]
I'm working on porting Menu Item Visibility (https://github.com/backdrop-ops/contrib/issues/415) and almost done. You might want to try it out.

**Comment by stpaultim** [comment]
https://backdropcms.org/project/menu_per_role
