### ISSUE TITLE
Application to join:  dBonde (cacheexclude module)

### ISSUE THREAD

**Issue by SorenBonde** [backdrop-ops/contrib#412]
I have ported the Drupal 7 Cache Exclude module and just wanted to contribute it somehow but I am unsure how.
I have attached the zipped module file.
[cacheexclude.zip](https://github.com/backdrop-ops/contrib/files/4803082/cacheexclude.zip)

**Comment by jenlampton** [comment]
Hi @dBonde, welcome to the Backdrop community, and thanks for working on a port of the Drupal 7 Cache Exclude module!

In order to contribute this module to the Backdrop community, it will need to be in a GitHub repository. You can create one here: https://github.com/new

Once you have the repository, you can push the module code into it. We can review it there, and then grant you permission to move the repository into the Backdrop Contrib space.

We're happy to help you through the process -- feel free to ask in Zulip for faster replies :) 
https://backdrop.zulipchat.com/

**Comment by dBonde** [comment]
Hi @jenlampton, thanks for your reply. :-)

I have added the repository: https://github.com/dBonde/cacheexclude

**Comment by jenlampton** [comment]
Thanks @dBonde!

All projects must meet these minimum requirements.

- [ ] If porting a Drupal project, Maintain the Git history from Drupal 7. 
- [x] Include a README.md file 
- [x] Include a LICENSE.txt file

It looks like [this project does not maintain the commit history](https://github.com/dBonde/cacheexclude/commits/master) from the Drupal project. Keeping the commit history will not only enable us to tell exactly when it was forked and what Drupal patches have already been added, but also retains credit for all the commit authors.

When I forget to maintain the history (it happens to all of us!) I usually do the following:
1) get a fresh checkout from Drupal, 
2) delete all the tags (using `git tag | xargs git tag -d`) 
3) checkout a new branch named `1.x-1.x`, 
4) then repeat all my port changes, if there weren't that many, and make the initial commit again.
4b) If there were a lot of changes, then I'd copy over all the Drupal files with my Backdrop files.
5) delete all the Drupal branches
6) force-push back up to Github

**Comment by jenlampton** [comment]
@dBonde I was recently thinking there must be an easier way to get back the Git history, so I ran a quick experiment and it worked! 

[I wrote up a blog post](https://www.jenlampton.com/blog/how-add-back-git-history-when-you-forgot-clone) on how I did it. It is pretty common that the Git history is not included and I want to have a good resource for the next time :)

**Comment by jenlampton** [comment]
Hi again @dBonde! 
The cacheexclude module recently came up on a list of projects that I'll need to have ported for one of my next Drupal to Backdrop upgrades. I'd love to help push this over the finish line and get it into contrib. :)

If I were to create a new project with the Drupal history, and try to merge in the changes from your repository, would you still be interested in being listed as a maintainer of that project once it lands in Backdrop contrib?

If so, we'll need you to agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

**Comment by klonos** [comment]
Hey @SorenBonde 👋🏼 ...we haven't heard from you in a while, so I will go ahead and close this issue here.

Please feel free to reopen if you are still interested.
