### ISSUE TITLE
Maintainer change request - Content Access

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/contrib#418]
Content Access is abandoned. I'm willing to take it over for now and try to get a full release:
https://github.com/backdrop-contrib/content_access/issues/5

**Comment by jenlampton** [comment]
You're now the new maintainer: https://github.com/backdrop-contrib/content_access

**Comment by laryn** [comment]
@jenlampton Do you need to do something special to allow me to adjust branches in that repo? I was going to change the default branch from `1.x` to `1.x-1.x` but don't think I have access.

**Comment by jenlampton** [comment]
Yeah, I think you need to be an admin for that. Adjusting now!

**Comment by jenlampton** [comment]
can you try now?

**Comment by laryn** [comment]
@jenlampton Yes, that works. Thanks again!
