### ISSUE TITLE
Backup_migrate porting complete - please test

### ISSUE THREAD

**Issue by quackers8me** [backdrop-ops/contrib#42]
I have completed the porting for the backup_migrate module now and run some basic tests of installing and running a backup to the manual directory successfully. 
Please test and file issues. 
There may be issues in the nodesquirrel fuctionality due to a major change to system_setting_form there.
https://github.com/backdrop-contrib/backup_migrate
Thanks in advance.

**Comment by biolithic** [comment]
Hi, I have developed http://www.andymartha.com/backdrop on my localhost and then used your port to migrate to the live server successfully.  I have done a config save and change between the localhost and the live server as well.  I didn't have any issues but I didn't use nodesquirrel.

**Comment by quackers8me** [comment]
Thank-you for the feedback.

**Comment by quicksketch** [comment]
Awesome, great job!
