### ISSUE TITLE
Port request for Organic groups (OG)

### ISSUE THREAD

**Issue by VasasA** [backdrop-ops/contrib#420]
**Name of the module, theme, or layout**
Organic groups

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/og

It is a very useful module, but I couldn't convert it:
https://github.com/VasasA/og
It uses some functions and classes of the dependency modules (e.g. CTools, Entity), what aren't implemented in the Backdrop.
I think this requires in-depth expertise in core programming also. We should find an expert who can port this module.

For example: my commits:
Missing CTools and Entity functions: https://github.com/VasasA/og/commit/27893da5e126aa872f7c0eec9cea56278d83f51a
Missing Entity class: https://github.com/VasasA/og/commit/6deb80bfc30e4cfcb5bfcca018ffbe2f7b374bfe

**Comment by laryn** [comment]
I looked into this relatively recently and was thinking the Entity views class/folder might be good to add into Entity Plus and then use that as a dependency:
https://github.com/backdrop-contrib/entity_plus/issues/32

**Comment by laryn** [comment]
With the latest release of Entity Plus I've gotten this OG port further along. Testing and filing issues can be helpful at this point.

https://github.com/laryn/og

**Comment by olafgrabienski** [comment]
Great to hear! I’m using OG on two D7 sites, will have a look at the port hopefully soon.  Are there particular things that need testing?

**Comment by stpaultim** [comment]
I started testing last night and already identified a problem. However, I'm new to using OG so I'm not the best tester, because I don't know how it's supposed to work. But, I'm learning. I need some group functionality on sites.

**Comment by VasasA** [comment]
It is a very useful video tutorial: http://modulesunraveled.com/organic-groups

**Comment by stpaultim** [comment]
I opened a ticket in the OG repo to help coordinate progress: https://github.com/backdrop-contrib/og/issues/30

**Comment by yorkshire-pudding** [comment]
I believe now this in beta, this issue can be closed:
https://github.com/backdrop-contrib/og

**Comment by olafgrabienski** [comment]
> I believe now this in beta, this issue can be closed

Indeed, was a fantastic team work.

- https://backdropcms.org/project/og
- https://github.com/backdrop-contrib/og
