### ISSUE TITLE
Porting Real Name module

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/contrib#424]
**Name of the module, theme, or layout you are working on**
Real Name

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/realname

There are at least two stalled attempts to port this module:

- https://github.com/bizmarkdev/backdrop-realname
- https://github.com/backdrop-contrib/realname

The latter blocked me from moving my port (which does contain the full git history) to backdrop-contrib, that's why it's parked here:

- https://github.com/indigoxela/realname

**Do you need assistance with this port?**
No

Note: I'll wait some time for a response on https://github.com/backdrop-contrib/realname/issues/2
If I get no response, I'll need assistance of the contrib team.

**Comment by indigoxela** [comment]
Hi team,

after a week I belief that the user didn't even get a notification on [my request](https://github.com/backdrop-contrib/realname/issues/2).

And considering the info in the chat:

> ...stopped all work on Backdrop about a year ago. He switched jobs and is no longer involved with Drupal either.

I guess, it's time to delete the stub repo.

**Comment by docwilmot** [comment]
What happens if you just force push your code?

**Comment by indigoxela** [comment]
> What happens if you just force push your code?

I don't belief anything gets easier then, because it still needs someone of the contrib team to make me admin of that repo. Currently I could only provide pull requests.

**Comment by indigoxela** [comment]
Do I really ask for something that uncommon or complicated?

**Comment by docwilmot** [comment]
Trying to help. I'll leave you to it.

**Comment by stpaultim** [comment]
Let's tag @jenlampton - because I think she needs to see this and tagging her is a good way to get her attention (I think).

**Comment by jenlampton** [comment]
@indigoxela I have deleted the old realname module, feel free to push yours to backdrop-contrib. 

Most of our maintainers are not actually admins of their repos, they are all part of the `authors` team that has commit / push / edit / release permissions on every repo. Some additionally have the `maintainer` role (but only if their repo was created after that role was added to GitHub.)

Only if someone needs to change the default branch do we specifically make them an admin. If someone leaves themselves an admin when a repo is transferred, we also do not remove their access, so you may be an admin on several of your own repos, and that's fine too :)

**Comment by indigoxela** [comment]
> Most of our maintainers are not actually admins of their repos

That's a problem on its own. Maybe worth an Issue (maintainers can't even change the description of their repo - how silly is that?)

Anyway. Problem solved. Now someone could change the label - something I don't have permission to here (also silly btw.).

**Comment by jenlampton** [comment]
> That's a problem on its own. Maybe worth an Issue (maintainers can't even change the description of their repo - how silly is that?)

Unfortunately we don't have control of which permissions are associated with each role here on GitHub, so we're stuck with some limitations. Our current work-around is to grant people admin access to their repos when requested (or if they self-assign it) so they can perform actions like changing branch or description. So far it's been working okay.

> Now someone could change the label - something I don't have permission to here (also silly btw.).

Yep, another GitHub limitation we've been struggling with :( This is why we have a separate queue for core issues and can't do them on the backdrop core repository itself.
