### ISSUE TITLE
Port request for CKEditor Accordion

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#425]
**Name of the module, theme, or layout**
CKEditor Accordion

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/ckeditor_accordion

It looks like a small module but I have not enough skill to port it myself.

There are a few other modules for CKEditor which would be useful for Backdrop, e. g. CKEditor Abbreviation, CKEditor Tabber.

**Comment by indigoxela** [comment]
Does that help?
https://github.com/backdrop-contrib/ckeditor_accordion

**Comment by djzwerg** [comment]
@indigoxela definitely! Thanks a lot - tested and it works!

**Comment by djzwerg** [comment]
I don't know how to change the label :(

**Comment by indigoxela** [comment]
I don't have permission to change it either...

**Comment by stpaultim** [comment]
This one I can handle. :-)
