### ISSUE TITLE
Port request for TwentyTwenty

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#432]
**Name of the module, theme, or layout**
Zurb TwentyTwenty

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/zurb_twentytwenty

**Comment by olafgrabienski** [comment]
I've had a quick look at the [Drupal repository](https://git.drupalcode.org/project/zurb_twentytwenty/-/tree/7.x-1.x). At first sight, the module doesn't look very complex.

@djzwerg Are you interested to port the module yourself? In case you need help, I'll try to give some support.

**Comment by djzwerg** [comment]
@olafgrabienski sounds interesting. If I have enough time the next week I will try it.

**Comment by olafgrabienski** [comment]
Great! I'm listing some resources below, hope that helps to get started.

Generally, there are two approaches to port a module:

1. Convert the module manually, following the documentation and other resources.
2. Convert the module with *Coder Upgrade* (see below), test the result and continue from there.

While the latter might be less work, the first approach should be a good way to learn the differences between Drupal and Backdrop.

In case of TwentyTwenty of interest: In Backdrop, 3rd party libraries should be bundled into modules. I'm not sure if the exact way is documented somewhere but you could have a look how other modules bundle the library, e.g. [Flexslider](url) or [Tocbot](https://github.com/backdrop-contrib/tocbot).

Further resources:

- [Backdrop Contributed Project Group Application](https://github.com/backdrop-ops/contrib)
- https://api.backdropcms.org/converting-modules-from-drupal
- https://www.lullabot.com/articles/porting-drupal-7-modules-to-backdrop
- https://backdropcms.org/project/coder_upgrade

**Comment by djzwerg** [comment]
Drupal port issue:
https://www.drupal.org/project/zurb_twentytwenty/issues/3171892

Port is in progress.

**Comment by djzwerg** [comment]
@olafgrabienski at the step
`# Push to the new repository.
git push origin 1.x-1.x`

I'm getting an error message:
`git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

The port is manually done. But I don't know how to upload.

**Comment by olafgrabienski** [comment]
(For reference, the mentioned step is from https://api.backdropcms.org/converting-modules-from-drupal.)

@djzwerg Let's see, I guess the "Permission denied" is because you're not yet a member of the Backdrop Contrib Group. You find information about requirements and a link to join on the page [Backdrop Contributed Project Group Application](https://github.com/backdrop-ops/contrib).

The way to go is probably: first upload the project to your own GitHub account, then apply for contrib group membership. Finally, someone will review the module and let you know what else is to be done. When all that is done, you'll be able to push your next project directly to Backdrop.

**Comment by djzwerg** [comment]
@olafgrabienski thanks for your help! I will try.

The repository is ready to test: https://github.com/djzwerg/zurb_twentytwenty.

**Comment by djzwerg** [comment]
@olafgrabienski because the port was already done I think we can close this issue ;-)

**Comment by olafgrabienski** [comment]
Oh yes, I guess it's this one: https://github.com/backdrop-contrib/zurb_twentytwenty
