### ISSUE TITLE
Port for SpamSpan Filter

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#434]
**Name of the module, theme, or layout**
SpamSpan Filter

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/spamspan

**Comment by olafgrabienski** [comment]
@djzwerg Would one of the existing modules to hide email addresses do the job, or do you need necessarily SpamSpan?

- https://github.com/backdrop-contrib/invisimail
- https://github.com/backdrop-contrib/maildisguise

**Comment by djzwerg** [comment]
@olafgrabienski I have to check these modules. My wish would be Cypher Link but this ist only available für Drupal 8/9.

**Comment by bugfolder** [comment]
I have started working on porting Spamspan filter to Backdrop. I'll post more when I have a working version.

**Comment by bugfolder** [comment]
A first release is in Backdrop modules:

https://backdropcms.org/project/spamspan

Testing/feedback would be most appreciated.
