### ISSUE TITLE
Porting Comment Hide Subject

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#440]
**Name of the module, theme, or layout you are working on**
Comment Hide Subject

**Link to the drupal.org module, theme, or layout**
https://drupal.org/project/comment_hide_subject

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/comment_hide_subject/issues/3173482

**Do you need assistance with this port?**
No

**Comment by stpaultim** [comment]
I assume that this is a contrib module that would accomplish this goal. 
https://github.com/backdrop/backdrop-issues/issues/4569

**Comment by bugfolder** [comment]
Yes. I should have an alpha release of the ported module in the repository within a few days.

**Comment by bugfolder** [comment]
First release is now in Backdrop modules.

https://backdropcms.org/project/comment_hide_subject
