### ISSUE TITLE
Change the default branch for the Shortcut module to 1.x-1.x and delete the master branch

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#445]
It's real shame contributors can not manage the branches for their projects. Once I had such an option, but then, for some reason, was deprived of such a right. I would love to get that right back.

If it's not possible, then please someone with enough powers go to https://github.com/backdrop-contrib/shortcut/branches and make 1.x-1.x the default branch and delete the master branch.

**Comment by alanmels** [comment]
Also I would really appreciate if Backdrop gods give me privileges to set labels for the issues. This one, for example, should be marked differently as the port has been finished, but unfortunately, I can't change the labels.

**Comment by stpaultim** [comment]
@jenlampton - can you help here?

**Comment by jenlampton** [comment]
I switched the default branch to 1.x-1.x

**Comment by jenlampton** [comment]
> Also I would really appreciate if Backdrop gods give me privileges to set labels for the issues. 

I also find this frustrating. For some reason `Base permissions` for a repository can only be `Read`, `Write`, or `Admin`, and not `Triage` which is what would allow issue management.  :(

**Comment by alanmels** [comment]
@jenlampton, thanks for your attention to this. 

I know we're dealing with GitHub permissions here, however I thought you, guys, could've just elevate my account to some other group that has more privileges than `Base permissions`. This is not the first time I had to ask for interference of someone with higher privileges. 

I sometimes feel not to transfer ownership of the modules we port and keep managing them under https://github.com/altagrade, which would definitely make you sorry. But then the current state and referring to GitHub limitations also do not address the problem.

**Comment by alanmels** [comment]
And once again: I clearly remember I had all the privileges when I had just joined. But then without any kind of explanation was deprived of them. I understand that you, guys, are worried about possible harm users with higher privileges could cause. However, I can assure you won't see that kind of troubles from myself or other AltaGrade staff-members. If I had somehow dog  my ways into undesired areas in the very beginning, it was completely out of curiosity and willing to learn my ways on how to navigate here and properly manage the projects. So I do believe you could start re-instating deprived privileges to those contributors who have multiple projects and loyal care and attitude for Backdrop project. Otherwise, you, guys, are really pushing us to keep our projects' ownership at our own hands.

**Comment by jenlampton** [comment]
> I thought you, guys, could've just elevate my account to some other group that has more privileges than `Base permissions`

In this repository (https://github.com/backdrop-ops/contrib) there are only three groups: 1) those who review and approve contrib applications, 2) the security team, and 3) everyone else (who have `Base permissions`). The `backdrop-ops` group is different from the `backdrop-contrib` group, so it doesn't have the same teams or options. In order to add labels to these issues you would need to be part of the application approval team. Everyone who's not on that team will need to ask for interference from someone who is in order to change a label. It's definitely not ideal. :(

>  I clearly remember I had all the privileges when I had just joined. But then without any kind of explanation was deprived of them.

When you create a repository in your own github account, you are automatically an `Admin` and have all permissions. When you transfer a repository to the `backdrop-contrib` group, the permissions on the project change. Perhaps this is what you are experiencing? 

> If I had somehow dog my ways into undesired areas in the very beginning, it was completely out of curiosity and willing to learn my ways on how to navigate here and properly manage the projects.

All `Authors` in the `backdrop-contrib` group get exactly the same permissions, I can assure you that you are not being treated any differently from anyone else. :)

**Comment by alanmels** [comment]
@jenlampton, thanks for the update.

> In this repository (https://github.com/backdrop-ops/contrib) there are only three groups: 1) those who review and approve contrib applications, 2) the security team, and 3) everyone else (who have `Base permissions`). The `backdrop-ops` group is different from the `backdrop-contrib` group, so it doesn't have the same teams or options.

I was referring to `backdrop-contrib` as that's where I'm mostly active (compared to `backdrop-ops). 

> When you create a repository in your own github account, you are automatically an `Admin` and have all permissions. When you transfer a repository to the `backdrop-contrib` group, the permissions on the project change. Perhaps this is what you are experiencing?

No, I clearly remember I could manage projects under the `backdrop-contrib` group, but at some point got lost most of permissions.
 
> All `Authors` in the `backdrop-contrib` group get exactly the same permissions, I can assure you that you are not being treated any differently from anyone else. :)

Jen, I was actually hoping to get more privilages than `Authors` have. I am not seeking more privileges for anything else, but efficiently manage projects. It's not fun to request someone else to perform simple branch actions every single time a project was created with wrong branch name.

> I switched the default branch to 1.x-1.x. You should be able to delete the master branch now.

BTW, the `master` branch is still the default one and I can't do anything with the fact, but to request you to take another look. I hate taking your time and this is exactly why you, guys, really need to start being little bit more flexible with giving more privileges to contributors. At least to those who are managing multiple projects.

![Screen Shot 2020-10-12 at 3 16 35 PM](https://user-images.githubusercontent.com/56604405/95791207-1c0e5700-0c9e-11eb-9905-fe5b552d849e.png)

**Comment by alanmels** [comment]
Checked the https://github.com/backdrop-contrib/shortcut/branches once again and was finally able to remove the `master` branch. Thanks a lot, @jenlampton.

Still, my request for more privileges holds as I don't want to take anybody else's time for simple tasks.

**Comment by jenlampton** [comment]
> I was referring to backdrop-contrib as that's where I'm mostly active (compared to backdrop-ops).

Ah, sorry. You had also asked about labels for this issue.

> Jen, I was actually hoping to get more privileges than Authors have. 

You are already a `Maintainer` for your own project `shortcut` which is more privileges than Authors have. My point was only that all Authors are facing the same challenges.

> I am not seeking more privileges for anything else, but to be able to efficiently manage projects. It's not fun to request someone else to perform simple branch actions every single time a project was created with wrong branch name.

I still 100% agree with you. Would you please help me find the GitHub issue where we can ask to have this problem fixed for everyone? 

> BTW, the master branch is still the default one

Bah. Okay, I tried again to fix it... would you please check again now?

**Comment by stpaultim** [comment]
Let's write a blog post or some documentation somewhere that makes clear how this works and the limitations that we have. This issue comes up from time to time and I know it's frustrating to module maintainers. I don't even know where to point someone with information about this issue and I believe that there have been some changes in how we handle "ownership" of contrib projects, but I don't remember what the change was. 

I think at one point, all contrib maintainers had the same permissions for all contrib projects. Wasn't there complaints about that which required scaling back permissions somewhat for all contrib authors/maintainers?

**Comment by jenlampton** [comment]
> I think at one point, all contrib maintainers had the same permissions for all contrib projects. Wasn't there complaints about that which required scaling back permissions somewhat for all contrib authors/maintainers?

When we started there wasn't the `Triage` role or the `Maintainer` role. 

Now that we have those, all members of the `Authors` group (which is everyone) get `Triage` access to all projects (less than `Write` which is what they had before) and maintainers get `Maintain` permissions (more permissions than `Write` which is what they had before).

**Comment by alanmels** [comment]
I wish the maintainers had more permissions, however have to face the reality and not to further cause ado about this, and since the subject matter of this issue has been addressed by @jenlampton, I am marking this as closed.

@jenlampton and @stpaultim, thank you for your time and attention to this.

**Comment by jenlampton** [comment]
Thanks @alanmels, sorry again about needing to ask here to do things you should be able to do yourself :(

**Comment by alanmels** [comment]
Another annoying issue that is unnecessarily taking everyone's time: https://github.com/backdrop-contrib/bueditor/issues/12 And that's because you, guys, are too cautious about giving active contributors enough privileges. If you are restricted with GitHub's limitations for certain roles (groups), then why don't you just move my account to another group with higher privileges?
