### ISSUE TITLE
GitHub problem: why don't maintainers get permission to manage branches?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#446]
There is a huge limitation in GitHub permissions: maintainers don't have permission to change the default branch on their own projects. 

If a maintainer would like the default branch changed, they need to ask here for an organization admin to make the change for them. This is silly -- and needs to be addressed with GitHub.

So far, I have been unable to locate the "correct" place to complain about this to GitHub. I have posted some negative feedback on the documentation pages, but I'm sure that's not the right way to get the problem resolved.

I would love some help locating the GitHub issue (?) or place where we should voice our dissatisfaction with this decision.

**Comment by jenlampton** [comment]
Update: the PMC is reviewing our polices around contrib maintainers and hope to have a solution for this shortly.

**Comment by quackers8me** [comment]
I have a PR on the contrib module I maintain but I no longer have write access to merge it. It this related to this Github problem? I was last able to merge last September.
https://github.com/backdrop-contrib/backup_migrate/pull/61

**Comment by jenlampton** [comment]
@quackers8me yes, I bet that's the problem. Granting you admin access now!

**Comment by quackers8me** [comment]
Great! Thank-you, it's working. Now to push a critical release due to some
obsolete code flushed out from the BD 1.19 release :-)

**Comment by jenlampton** [comment]
> from the BD 1.19 release :-)

Since Backdrop is one word, we usually abbreviate it B. "the B 1.19 release" :)

**Comment by jenlampton** [comment]
@quackers8me I'm going to close this issue, but if you find you need more access on any other projects  you maintain, please open another issue. Hopefully the fixing of permissions will be automated soon :)
