### ISSUE TITLE
Maintainer permissions change request: Voting API

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/contrib#447]
I'd like to request admin access on the `voting_api` project. It looks like I am the maintainer and I was going to merge a PR but it says I don't have access:

![Screen Shot 2020-10-14 at 9 16 22 PM](https://user-images.githubusercontent.com/871421/96068835-896ae500-0e62-11eb-999a-c4b9d81bafd3.jpg)

https://github.com/backdrop-contrib/votingapi

**Comment by jenlampton** [comment]
I've added you as a maintainer, it looks like @whiteph was the only maintainer before.

**Comment by laryn** [comment]
Thanks!
