### ISSUE TITLE
Webform Autocomplete port

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#448]
**Name of the module, theme, or layout you are working on**
Webform Autocomplete

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/webform_autocomplete

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/webform_autocomplete/issues/3177433

**Do you need assistance with this port?**
No

**Comment by bugfolder** [comment]
First release is now in Backdrop Modules.

https://backdropcms.org/project/webform_autocomplete

@oadaeh, would you please change the label on this issue to Port Complete.

**Comment by olafgrabienski** [comment]
@bugfolder I've changed the label to "Port complete". Thanks for porting the module!
