### ISSUE TITLE
Porting Webform Countdown

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#453]
**Name of the module, theme, or layout you are working on**
Webform Countdown

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/webform_countdown

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/webform_countdown/issues/3177854

**Do you need assistance with this port?**
No

**Comment by bugfolder** [comment]
A first release is now in Backdrop modules:

https://backdropcms.org/project/webform_countdown

@stpaultim, @oadaeh: However, I inadvertantly gave the release the wrong version number (to match the Drupal version). Although I deleted the old release and tag in GitHub and created a new properly numbered release, the Backdrop packager had already generated from the wrong release, so now the download link is bad. 

Here's the current release page: https://backdropcms.org/node/3115/releases

Can you wipe out the 1.x-2.2.0-alpha1 release, leaving the (correct) 1.x-2.1.0-alpha1 release?

Thanks, sorry for the bother.

**Comment by stpaultim** [comment]
I'm sorry, I'm not entirely sure what the correct way to resolve this is. Going to flag @jenlampton. 

You try deleting the release again and waiting a short time before creating a replacement. But, it might help if we simply delete the node for this project first. 

I'm hesitant to delete the node myself, because I don't know if that might make things worse. @jenlampton, @quicksketch, or @klonos have a better idea of how the process works.

**Comment by bugfolder** [comment]
Yeah, I'm sorry to have created a problem. The problem is that I did delete the bogus release (2.2.0), but the download link still wants to point to the now-missing release.

Will await further word.

**Comment by stpaultim** [comment]
Don't worry about it. I don't this is hard to fix for the people who understand the process. I'm just not the right person to fix it this time. But, I'll watch how it is fixed and next time I can help.

**Comment by jenlampton** [comment]
> Can you wipe out the 1.x-2.2.0-alpha1 release, leaving the (correct) 1.x-2.1.0-alpha1 release?

I have deleted the release node for `1.x-2.2.0-alpha1`. You should be all set now, but please let us know if not :)

**Comment by bugfolder** [comment]
Thanks, @jenlampton, all looks good. Closing this issue. Would you (or another listener) please change the label to "Port complete."

**Comment by stpaultim** [comment]
I see. I didn't notice that Project Releases were nodes separate from the project nodes. Makes sense.
