### ISSUE TITLE
Port of protected_pages module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#455]
**Name of the module, theme, or layout you are working on**
Protected Pages

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/protected_pages

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/protected_pages/issues/3023129

**Do you need assistance with this port?**
I welcome co-maintainers and help with testing!

**Comment by jenlampton** [comment]
@robertgarrigos if you've been working on this project already, I'd love to collaborate.

**Comment by robertgarrigos** [comment]
Hi @jenlampton I see I wanted to work on it, but I actually forgot about it. Most provably I was planning to use it and finally, I didn't. You are free to work on it. I've not having much time lately.

**Comment by jenlampton** [comment]
Protected pages port is up: https://github.com/backdrop-ops/contrib/issues/455

**Comment by olafgrabienski** [comment]
Link to the module page: https://github.com/backdrop-contrib/protected_pages
