### ISSUE TITLE
Language Icons module has been ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#457]
**Name of the module, theme, or layout you are working on**
Language Icons

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/languageicons

**Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/languageicons/issues/3180598

**Status**
The module has been ported and is available at https://github.com/backdrop-contrib/languageicons

**Comment by olafgrabienski** [comment]
Great! I'll change the label to "Port complete".
