### ISSUE TITLE
Insert View

### ISSUE THREAD

**Issue by vtad** [backdrop-ops/contrib#46]
A simple Port of the Insert View Module (I needed it because there is no php Filter in backdrop).

See https://github.com/vtad/insert-view

**Comment by quicksketch** [comment]
Hi @vtad! Excellent! I looked over the code and it looks like you've got both a README.md and a LICENSE file, great!

We like to maintain the complete history in Git from the original Drupal project. Could you do a git checkout of the original module, then push that into your repository?

```
git clone --branch 7.x-2.x http://git.drupal.org/project/insert_view.git

# Rename branch to indicate it is for Backdrop 1.x.
git branch -m 7.x-2.x 1.x-2.x

# Push to GitHub.
git remote add github git@github.com:vtad/insert-view.git
git push github 1.x-2.x

# Delete the existing master branch on Github.
git push github :master
```

Then you can copy your ported version over the top and commit that.

It'd also be great if you could rename `LICENSE` to `LICENSE.txt` to be consistent with the license files of other contrib projects. Thanks!

**Comment by vtad** [comment]
Hi Nate,
it didn't work, now I have 2 Branches at https://github.com/vtad/insert-view
- master (the ported and modified code)
- 7.x-2.x  (with the original drupal Insert_view code)

  My git knowledge is nearly 0
regards


Am 04.02.2015 um 04:36 schrieb Nate Haug:

**Comment by quicksketch** [comment]
Hi @vtad! Closer!

So the renaming of the branch didn't seem to work. Try this in your repository.

```
# Rename the branch from 7.x-2.x to 1.x-2.x.
git branch -m 7.x-2.x 1.x-2.x
git push origin 1.x-2.x

# Delete the remote 7.x-2.x branch.
git push origin :7.x-2.x
```

Additionally, we'd like to get rid of the "master" branch and copy your ported version into the 7.x-2.x branch. Please make a backup of your ported version in the event that this doesn't go correctly! I'd hate to loose your work.

- Copy your entire working directory of "insert_view".
- Switch the copied directory to the "master" branch (`git checkout master`).
- Switch the original directory to the "7.x-2.x" branch (`git checkout 7.x-2.x`).
- Copy the entire contents of the "master" directory version over the top of the "7.x-2.x" directory version.
- `git commit -m "Initial port to Backdrop."`
- `git push origin 1.x-2.x` (push the port to the 1.x-2.x branch on GitHub).
- `git push origin :master` (delete the "master" branch on GitHub).

You should end up with a single branch, 1.x-2.x, that includes your port as the last commit, on top of the entire history of the Drupal version.

**Comment by vtad** [comment]
Hi Nate,
there seems to be a bug in github for Windows, it always pushes with the 
original branch name, even after renaming it locally.

But, playing a little with github I managed to create the desired 
|1.x-2.x.| branch.
Hope its OK now:
https://github.com/vtad/insert-view

Thanks for your help.

Am 05.02.2015 um 03:33 schrieb Nate Haug:

**Comment by quicksketch** [comment]
It looks great now! Thanks! I think it's ready to transfer to the contrib repository. Would you agree to this for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by vtad** [comment]
I agree!
Joerg Kienitz

Am 06.02.2015 um 03:23 schrieb Nate Haug:

**Comment by quicksketch** [comment]
Excellent, thanks! The invite is sent. Thanks for doing this port and we can't wait to see what you do with Backdrop!
