### ISSUE TITLE
Porting View Unpublished

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#463]
**Name of the module, theme, or layout you are working on**
View Unpublished

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/view_unpublished

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/view_unpublished/issues/3182638

**Do you need assistance with this port?**
No

**Comment by olafgrabienski** [comment]
@bugfolder In case you missed it: The permissions to view "own" and "all" unpublished content are part of Backdrop core as of version 1.5 (see [issue thread](https://github.com/backdrop/backdrop-issues/issues/897)). Or do you have a more specific use-case which isn't possible with core?

**Comment by bugfolder** [comment]
Thanks for pointing out the issue thread. I'd noticed that "view own unpublished" and "view all unpublished" were now in core (and planned to remove "view all" from the port as being superfluous). On my D7 site, I use the content-specific "view any unpublished $content_type content", which doesn't appear to be in core (and is my motivation for starting the port).

**Comment by olafgrabienski** [comment]
> the content-specific "view any unpublished $content_type content", which doesn't appear to be in core

I see! Thanks for the feedback.

**Comment by bugfolder** [comment]
The module is now [in Backdrop Contrib](https://backdropcms.org/project/view_unpublished). @jenlampton @klonos, would you please mark this issue "Port Complete".

**Comment by olafgrabienski** [comment]
Hey @bugfolder, I've set it to "Port complete". Thanks for porting the module!
