### ISSUE TITLE
Permissions change request: Search API

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/contrib#464]
Can someone with appropriate permissions adjust the Github settings for `search_api`? @earlyburg is listed as a maintainer at this point but does not have write access. See:

https://github.com/backdrop-contrib/search_api/pull/11#issuecomment-727858612

Also, less urgently, he is not a maintainer on Entity Plus but indicates he does have write access there.

**Comment by klonos** [comment]
Thanks @laryn for bringing this to my attention. All done 👍

**Comment by klonos** [comment]
@earlyburg can you please respond here, to let us know if things are fixed for you now? Thanks.

**Comment by earlyburg** [comment]
@klonos Hello, I have been able to merge my pull requests for this project, and in addition, I was able to push and pull from my remote repo to this one. Thank you very much for your assistance, I appreciate it.
