### ISSUE TITLE
Porting Webform2PDF

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#465]
**Name of the module, theme, or layout you are working on**
Webform2PDF

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/webform2pdf

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/webform2pdf/issues/3183068

**Do you need assistance with this port?**
No

**Comment by bugfolder** [comment]
This is now up at Backdrop modules:

https://backdropcms.org/project/webform2pdf

@klonos or @olafgrabienski, would you please mark this issues as "port complete." Thanks!

**Comment by olafgrabienski** [comment]
Done! (And thanks for porting the module, sounds very useful.)
