### ISSUE TITLE
Paragraphs jQuery UI Accordion module has been ported to Backdrop

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#471]
Paragraphs jQuery UI Accordion module has been ported to Backdrop and is now available on https://github.com/backdrop-contrib/paragraphs_jquery_ui_accordion. 

Issue on DO: https://www.drupal.org/project/paragraphs_jquery_ui_accordion/issues/3189300

Please mark this as port complete.

**Comment by olafgrabienski** [comment]
Thanks for porting the module, @alanmels!
