### ISSUE TITLE
Maintainer change request

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#472]
Thank you for adopting an abandoned Backdrop project. 

<snip>

**Please include a link to the issue you filed for the abandoned project.**
https://github.com/backdrop-ops/contrib/issues/113

After confirming the project has been abandoned, a Backdrop Contrib administrator will add your name to the list of maintainers in that project's README.md file.  Once your name is listed in the README.md, you may act as the current maintainer.

_Note that my plan is to create a new branch 1.x-2.x (because I am upgrading the Backdrop module from the Drupal 1.x-1.4 branch to the Drupal 7.x-2.0 branch); I will update the README.md file in the new branch to include my own role as maintainer and include Graham's role as porter of the original 1.x-1.x version._

**Comment by jenlampton** [comment]
Thanks @bugfolder! 
I have made you an admin for the gauth project. :)
