### ISSUE TITLE
Porting Ubercart Discounts (Alternative)

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#473]
**Name of the module, theme, or layout you are working on**
Ubercart Discounts (Alternative)

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/uc_discounts_alt

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/uc_discounts_alt

**Do you need assistance with this port?**
No

Note: there are three similarly named "Ubercart Discount" modules in Drupal:
* [UC Discount Framework](https://www.drupal.org/project/uc_discounts) [`uc_discount`] - 16 sites
* [UC Discounts](https://www.drupal.org/project/uc_discounts) [`uc_discounts`] - 7 sites
* [Ubercart Discounts (Alternative)](https://www.drupal.org/project/uc_discounts_alt) [module machine name is `uc_discounts`, but project name is `uc_discounts_alt`] - 2314 sites

I'm porting the last one, which has by far the most installs, and plan to take `uc_discounts` as both the machine name (as now) and project name (rather than `uc_discounts_alt`). And to call it "Ubercart Discounts," to follow the most common naming scheme being used for Ubercart modules on Backdrop. I'll put some explanation (like this) in the README.

**Comment by bugfolder** [comment]
Ported module is now up on Backdrop Modules.

https://backdropcms.org/project/uc_discounts

@olafgrabienski, would you please mark this "Port complete."

**Comment by olafgrabienski** [comment]
Marked as "Port complete", thanks for the port, @bugfolder!
