### ISSUE TITLE
Porting Grid Field Formatter

### ISSUE THREAD

**Issue by Retsell** [backdrop-ops/contrib#485]
**Name of the module, theme, or layout you are working on**
Grid Field Formatter 

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/grid_field_formatter

**Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/grid_field_formatter/issues/3092046

**Do you need assistance with this port?**
Yes, any assistance is welcome!
I have been using this module with no issues under Drupal Compatability mode.  Would now like to finish porting it so it can be added to the contrib modules.

**Comment by olafgrabienski** [comment]
@Retsell I'm curious: Have you finished the port?

**Comment by Retsell** [comment]
@olafgrabienski Yes, the port is complete.

**Comment by olafgrabienski** [comment]
Great, thanks for porting the module!

For reference, here's the link: https://backdropcms.org/project/grid_field_formatter

(Changing the label to `Port complete`.)
