### ISSUE TITLE
Porting User Merge

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#486]
**Name of the module, theme, or layout you are working on**
User Merge

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/usermerge

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/usermerge/issues/3191690

**Do you need assistance with this port?**
No

**Comment by bugfolder** [comment]
Module is now in Backdrop Modules: [User Merge](https://backdropcms.org/project/usermerge)

@klonos or @olafgrabienski , would you mark this issue "Port complete"? Thx!

**Comment by olafgrabienski** [comment]
> would you mark this issue "Port complete"?

Sure! And thanks for the port!
