### ISSUE TITLE
Porting Node authorize link

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/contrib#487]
**Name of the module, theme, or layout you are working on**

Node authorize link

**Link to the drupal.org module, theme, or layout**

https://www.drupal.org/project/node_authlink

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**

https://www.drupal.org/project/node_authlink/issues/3191706

**Do you need assistance with this port?**

No, almost done.

**Comment by indigoxela** [comment]
Hi team,

done.

https://github.com/backdrop-contrib/node_authlink/releases

**Comment by olafgrabienski** [comment]
Thanks for porting this module, @indigoxela !
