### ISSUE TITLE
Contrib application: Aggregator module

### ISSUE THREAD

**Issue by sillygwailo** [backdrop-ops/contrib#49]
I'm willing to maintain a port of the core Aggregator module, tracking with the development of the core module only but using configuration management instead. https://github.com/sillygwailo/backdrop-aggregator I didn't maintain the history of the core module because that would have meant forking the entire Drupal project. If there are instructions on how to port a core module (that was removed from Backdrop) and keeping the Drupal.org development history in Git, I'm willing to retrace my steps.

**Comment by quicksketch** [comment]
Hi @sillygwailo, that's excellent! We needed a similar workflow to maintain the history for Forum module. Could you try the approach mentioned in https://github.com/backdrop-ops/contrib/issues/8?

You've already got a LICENSE.txt file (excellent!) but we need to include a list of maintainers in the README.md file. Could you update it to match [our example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md)?

**Comment by sillygwailo** [comment]
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/ looks like what you're talking about. I'll do that. Expect the repository to maybe disappear for a short time in the next couple of days but it should be back at the same location.

10-4 on adding maintainers to the REAMDE.me.

**Comment by quicksketch** [comment]
> Expect the repository to maybe disappear for a short time in the next couple of days but it should be back at the same location.

Super! Just let us know when it's updated and I'll give it another spot-check.

**Comment by sillygwailo** [comment]
OK, it's ready to take a look at now. https://github.com/sillygwailo/backdrop-aggregator

**Comment by quicksketch** [comment]
Excellent! Nice one. You could delete the 7.x branch at your leisure if you like. Our branch naming convention is `1.x-1.x` (indicating compatibility with Backdrop 1.x, and version 1.x of the module), same as a Drupal project.

This looks great to me. Would you agree to the following for the record? Thanks!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by sillygwailo** [comment]
I agree to everything in that document. I'll rename the branch shortly.

**Comment by quicksketch** [comment]
Excellent, thanks again! Invite is now on its way. :)
