### ISSUE TITLE
Take over as maintainer of Token Filter module

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#492]
[Per this issue](https://github.com/backdrop-contrib/token_filter/issues/3), I would like to take over as maintainer of the Token Filter module.

[Here's the associated PR.](https://github.com/backdrop-contrib/token_filter/pull/4)

**Comment by jenlampton** [comment]
@bugfolder  can you file a new PR with only the README commit? I don't want to merge the bug-fix commit at the same time.

**Comment by bugfolder** [comment]
Sure. I'll have to figure out how to do that (still new to this PR stuff).

While I'm at it, once I'm maintainer, would it be appropriate to commit the bugfix directly, or via another PR?

**Comment by jenlampton** [comment]
@bugfolder  as maintainer, you can do whatever you like :) I usually like to have  PR up if I want review or testing, but I merge things like typos directly.

**Comment by bugfolder** [comment]
Thanks for the suggestion, I'll do that (new branch, cherry-pick). To come shortly...

**Comment by bugfolder** [comment]
New PR done: https://github.com/backdrop-contrib/token_filter/pull/5

**Comment by bugfolder** [comment]
Transfer completed.
