### ISSUE TITLE
Port of IP Anonymization

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#493]
**Name of the module, theme, or layout you are working on**
IP Anonymization

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/ip_anon

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/ip_anon/issues/3196175

**Do you need assistance with this port?**
No

**Comment by djzwerg** [comment]
Port is done and tested // see https://github.com/backdrop-ops/contrib/issues/494

**Comment by djzwerg** [comment]
@klonos @jenlampton can you please change the label to "Port complete" so we can close this issue? :)

**Comment by jenlampton** [comment]
Sure!

**Comment by djzwerg** [comment]
@jenlampton thanx 👍
