### ISSUE TITLE
Application to join: IP Anonymize

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#494]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
IP Anonymization

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/ip_anon/issues/3196175

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/djzwerg/ip_anon

**OR (option #2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**

**OR (option #3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**
@jenlampton @klonos 

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**If you have chosen option #3 above, do you agree to undergo this same maintainer application process again, should you decide to contribute code in the future?**
YES

**Comment by jenlampton** [comment]
Hi @djzwerg and thanks for applying to join the Backdrop contrib group!  We're happy to have you :)

I reviewed your project at `https://github.com/djzwerg/ip_anon` and it looks like you have included the license and readme files, but the previous Git history has not been maintained. I see only one commit [in your project's history](https://github.com/djzwerg/ip_anon/commits/1.x-1.x/README.md) and we should be seeing [all the Drupal commits](https://git.drupalcode.org/project/ip_anon/-/commits/7.x-1.x/) there too. 

Not including the Drupal Git history is very common, so I wrote a blog post on how I add it back when I forget it :) https://www.jenlampton.com/blog/how-add-back-git-history-when-you-forgot-clone

If you can include the history, we can send an invite off to you right away :)

**Comment by djzwerg** [comment]
> Hi @djzwerg and thanks for applying to join the Backdrop contrib group! We're happy to have you :)
> 
> I reviewed your project at `https://github.com/djzwerg/ip_anon` and it looks like you have included the license and readme files, but the previous Git history has not been maintained. I see only one commit [in your project's history](https://github.com/djzwerg/ip_anon/commits/1.x-1.x/README.md) and we should be seeing [all the Drupal commits](https://git.drupalcode.org/project/ip_anon/-/commits/7.x-1.x/) there too.
> 
> Not including the Drupal Git history is very common, it happens to many of us. I wrote a blog post on how I add it back when I forget it! https://www.jenlampton.com/blog/how-add-back-git-history-when-you-forgot-clone
> 
> If you can include the history, we can send an invite off to you right away :)
> 
> (I'm also happy to post a recommendation for you to help with the issue queues and documentation, but since you have also provided code, I'd prefer that you become a maintainer)

Sorry for the delay @jenlampton but because of the pandemic there are lots of projects at work and no time for "backdropping"... I'm goint to restart the port these days. I don't know why the previous history was deleted after I changed the branch from master to 1.-x. Sorry for that.

**Comment by jenlampton** [comment]
> Sorry for the delay... I don't know why the previous history was deleted after I changed the branch from master to 1.-x. Sorry for that.

No need to be sorry for anything, we understand that life happens. We're happy to have you in the time you have available. :)

**Comment by djzwerg** [comment]
@jenlampton please have a look at https://github.com/djzwerg/ip_anon/commits/1.x-1.x - there is the full Drupal Git repository. Is there anything to do by myself?

**Comment by djzwerg** [comment]
Transfer is done :-)
