### ISSUE TITLE
Application to join: [larsdesigns]

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-ops/contrib#496]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**The name of your module, theme, or layout**
Node Noindex

**(Optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

https://www.drupal.org/project/node_noindex/issues/3197373

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/larsdesigns/backdrop-contrib-node_noindex

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**If you have chosen option #3 above, do you agree to undergo this same maintainer application process again, should you decide to contribute code in the future?**
YES

**Comment by jenlampton** [comment]
Hi @larsdesigns  and thanks for working on the Node Noindex module!

In order for a project to be moved to backdrop contrib, the three basic requirements above need to be met. Thank you for maintaining the git history from Drupal. Would you please address the other to requirements, below?

> Include a README.md file containing license and maintainer information.

Can you please add the maintainer and license sections as demonstrated in [the example file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md)?

> Include a LICENSE.txt file.

Can you please add a LICENCE file? you can use [the example file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt) provided.

**Comment by larsdesigns** [comment]
1. Added maintainer information to the README.txt file and improved its content.
1. Added the license text file. 

@jenlampton

**Comment by jenlampton** [comment]
Fantastic! An invite to join the contrib group is on the way :)

I'm also going to drop a list of recommendations below. These comments are only intended to be helpul, and I hope, will help highlight some of the differences between Backdrop and Drupal!

In the README...
* The "Requirements" section that includes "The node core module must be enabled." The node module is required in Backdrop, and in fact, does not even appear on the modules page. This instruction might be confusing to some people, so I would recommend replacing this instruction with something like `No requirements`.
* The configuration section begins "To enable the noindex option for a node content type navigate to the edit the node type's setting." In Backdrop, only content is "edited", all settings and configuration is "configured". I would recommend changing `edit the node type's setting.` to `configure the node type`.
* The configuration section goes on to refer to an "Article" content type, but in Backdrop this type has been renamed `Post`.
* The configuration instructions state "click the edit link" but this link has been renamed `Configure` in backdrop.
* The Credits section has a typo: "Ccurrent Drupal project maintainer" begins with an extra C.

**Comment by larsdesigns** [comment]
@jenlampton, Do I need to add the config/node_noindex.node_noindex.settings.json to the Git repository?

**Comment by jenlampton** [comment]
> Do I need to add the config/node_noindex.node_noindex.settings.json to the Git repository?

Yes, you should add `config/node_noindex.settings.json` (module name only needed once, sorry) to the Git repository because that file will contain all the default values for a fresh install of the module. If all the defaults are NULL then it's not strictly necessary, but most variables usually have defaults so it's a good habit to get into.

**Comment by larsdesigns** [comment]
@jenlampton, I have completed the changes requested in the list. Thank you so much for working through this with me.

**Comment by jenlampton** [comment]
It's my pleasure :) Feel free to transfer the project into the contrib group when ready, I'll close this ticket now :)

Welcome to the family!!!
