### ISSUE TITLE
Port request for CKEditor Blocks

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-ops/contrib#497]
**Name of the module, theme, or layout**
CKEditor Blocks 

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/ckeditor_blocks

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
Some discussion and background https://github.com/backdrop/backdrop-issues/issues/4916

**(Optional) Bounty**
Name your price.

**Comment by mikesoltis** [comment]
Similar functionality (interleaving text, images, views) can be obtained using Paragraphs and Viewfield.

**Comment by stpaultim** [comment]
We are working on this one as well.
