### ISSUE TITLE
Rename group

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#5]
This is called the 'Backdrop Contributed module group' (as per the README), however since this will, I imagine, eventually contain themes and possibly layouts, distributions, etc., I think we should rename it to the 'Backdrop Contributed *project* group' instead.

**Comment by quicksketch** [comment]
Thanks! You probably noticed we just drafted the README.md :wink: great suggestion.

**Comment by BWPanda** [comment]
That's ok, it looks good!

**Comment by quicksketch** [comment]
Fixed up now! https://github.com/backdrop-ops/contrib/blob/master/README.md

We went over the verbiage a couple of times. If you think a change here or there might help, just file a PR. :)
