### ISSUE TITLE
Permission to join group

### ISSUE THREAD

**Issue by biolithic** [backdrop-ops/contrib#50]
Hi, I request permission to add modules or have them forked to the Backdrop repository and I agree to this.

Backdrop Contributed Project Agreement

By joining the Backdrop Contributed Project Group (Backdrop Contrib, for short) you agree to the following:

You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

You must agree to license your code contributions as GPLv2 or later.

Any project you create or maintain must include a copy of the GPL v2 LICENSE.txt file in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later. See for the Backdrop License FAQ for a more detailed explanation.

You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

Any project you create or maintain must include a README.md file containing at the least the following:

A description of the project
Basic documentation
License information for the project (GPL v2)
License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
A list of the current maintainers for the Backdrop project
Credits acknowledging past maintainers for the Backdrop or Drupal projects
You may use this example README.md to get started.

You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

__________________________________________________

Here are some modules I found to be working:
https://github.com/biolithic/backdrop_simple_paypal_donate
https://github.com/biolithic/backdrop_link
https://github.com/biolithic/backdrop_instagram_block

Here are some modules with PHP errors in the conversion I will try to hunt down the differences between Drupal and Backdrop and fix them.
https://github.com/biolithic/backdrop_basic_cart_braintree
https://github.com/biolithic/backdrop_basic_cart_stripe
https://github.com/biolithic/backdrop_paywallbraintree
https://github.com/biolithic/backdrop_paywallstripe
https://github.com/biolithic/backdrop_redirect
https://github.com/biolithic/backdrop_twitter_block
https://github.com/biolithic/backdrop_basic_cart

If someone else already has these, great -- use them.  I need to practice on the conversions before providing Backdrop services.  I spend most of my time at work in HTML5, Javascript and CSS and mentoring or communicating so I definitely could use a hand in the PHP aspect, although not necessary.  Other than the cart modules, I don't care if I am the maintainer of the other modules or not.    You may delay until I fully fix the modules if needed -- just thought I would apply tonight.
Thanks!

**Comment by quicksketch** [comment]
Hi @biolithic! Great to hear from you!

Wow, looks like you've been busy! We like to make sure that you've done these things with each port:

- [x] Included a README.md that lists the license and maintainers.
- [x] Include a LICENSE.txt that indicates the project is GPL v2.
- [ ] Maintain the project history from Drupal 7 if possible.

Looks like for all of these ports, you've got the first 2 down. Could you try and update one of the projects to keep the entire project history from the Drupal 7 port? That will help maintain attribution of all the previous authors and explain why changes were made when looking through the history.

This set of steps should work for most projects:
```
git clone --branch 7.x-1.x http://git.drupal.org/project/[project_name].git

# Rename branch to indicate it is for Backdrop 1.x.
git branch -m 7.x-1.x 1.x-1.x

# COPY YOUR PORT OVER THE FILES HERE.

# Push the new project to Github.
git push origin 1.x-1.x
```

It looks like you may have gotten Link module working. @docwilmont has been trying to get a port working as well. If it looks like your version is completely working, it'd be great to get a copy into the contrib repository, so let's try to get the history in place and get these projects transferred. Thanks!

**Comment by docwilmot** [comment]
Wow, @biolithic should be renamed prolific.

**Comment by biolithic** [comment]
Not really -- lots of those modules have not working yet due to php errors
in a difference in porting, but the config management stuff is working.
Also, some of those are my modules or ideas so I'm not stepping in blind :)

**Comment by quicksketch** [comment]
Hi @biolithic! I'd love to get your completed/working modules into the contrib group to prevent duplicate work. I took a look at https://github.com/biolithic/backdrop_colorbox and it meets the last requirement (maintaining the history from Drupal 7). Now that we've met all the requirements, I'd love to get some of these modules moved into the official repository.

Would you agree to the following for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by biolithic** [comment]
Yes, I (Andy) do consent to this agreement.

**Comment by quicksketch** [comment]
Yay! Invite sent your way. You can now transfer any of the ported projects to the Backdrop Contrib group when you're ready. Thanks!
