### ISSUE TITLE
Porting Views Auto-Refresh

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/contrib#501]
**Name of the module, theme, or layout you are working on**

Views Auto-Refresh

**Link to the drupal.org module, theme, or layout**

https://www.drupal.org/project/views_autorefresh

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**

https://www.drupal.org/project/views_autorefresh/issues/3198118

**Do you need assistance with this port?**

No :wink:

**Comment by indigoxela** [comment]
A [beta release](https://backdropcms.org/project/views_autorefresh) is out, this issue can get closed (I can do that) and the label could get changed (I can't).

**Comment by olafgrabienski** [comment]
> and the label could get changed

Done!
