### ISSUE TITLE
Multiple E-mail Addresses ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#502]
**Name of the module**
Multiple E-mail Addresses
https://github.com/backdrop-contrib/multiple_email

**Link to the drupal.org module**
https://www.drupal.org/project/multiple_email

**Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/multiple_email/issues/3200796

**Comment by alanmels** [comment]
Please change the status to Ported.

**Comment by klonos** [comment]
Thanks @alanmels 🙏
