### ISSUE TITLE
Gravatar has been ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#503]
**Name of the module**
Gravatar has been ported and is now available on https://github.com/backdrop-contrib/gravatar

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/gravatar

**Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/gravatar/issues/3201165

**Comment by alanmels** [comment]
Please change the status to Ported.

**Comment by olafgrabienski** [comment]
> Please change the status to Port complete.

Done. Thanks for porting the module!
