### ISSUE TITLE
Take over as maintainer of abandoned project: Layout Wildcard

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#505]
I would like to take over as maintainer of the Layout Wildcard module.

[Here's the issue (16 days old) offering to become a co-maintainer.](https://github.com/backdrop-contrib/layout_wildcard/issues/8)

**Comment by jenlampton** [comment]
@bugfolder thank you for offering to maintain Layout Wildcard, I reviewed the issue you linked to, but could not find a PR that adds your name to the README. If you can make one for me I would be happy to merge it and make you a maintainer :)

**Comment by bugfolder** [comment]
Thanks, I have done so. 

[PR 13](https://github.com/backdrop-contrib/layout_wildcard/pull/13)

The [instructions for abandoned projects](https://docs.backdropcms.org/documentation/contrib-application-process) say to file a PR if written permission is granted, but if not granted, says:

* If a current maintainer does not respond within 2 weeks create an issue in this repository to take over the project. Please include a link to the issue you filed with the abandoned project.
* After confirming the project has been abandoned, a Backdrop Contrib administrator will add your name to the list of maintainers in that project's README.md file.

I interpreted that to mean that the Backdrop Contrib administration would make the change. Perhaps the instructions to "create a PR" should apply to both cases in the instructions?

**Comment by jenlampton** [comment]
@bugfolder the PR not a requirement, but you just saved me some time - so thank you :)

**Comment by bugfolder** [comment]
Thanks!
