### ISSUE TITLE
Port of BG Image Formatter

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/contrib#507]
**Name of the module, theme, or layout you are working on**

BG Image Formatter

**Link to the drupal.org module, theme, or layout**

https://www.drupal.org/project/bg_image_formatter

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**

https://www.drupal.org/project/bg_image_formatter/issues/3038326

**Do you need assistance with this port?**

No

Note that this port has a longer story. It's currently stuck here: https://github.com/drupol/bg_image_formatter
But no more responses: https://github.com/drupol/bg_image_formatter/issues/1

So it seemed easier to start fresh, I only had to apply my own patch to the current dev.

**Comment by olafgrabienski** [comment]
Thanks @indigoxela for https://github.com/backdrop-contrib/bg_image_formatter. The port does have a release now, so closing.
