### ISSUE TITLE
Port request for Leaflet Widget for Geofield

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#508]
**Name of the module, theme, or layout**
Leaflet Widget for Geofield

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/leaflet_widget

See also https://github.com/backdrop-contrib/leaflet/issues/9.

**Comment by indigoxela** [comment]
@djzwerg I started to work on this port, but it seems a bit tricky, because the widget library seems incompatible with a more recent Leaflet version. Stay tuned, though.

**Comment by indigoxela** [comment]
Here we go: https://github.com/backdrop-contrib/leaflet_widget

The port isn't finished yet, but the widget is working. Testing (not on production sites) and feedback is welcome.

BTW: could someone with proper permissions change the issue label to "port in progress", please? :smiley:

**Comment by olafgrabienski** [comment]
> could someone with proper permissions change the issue label to "port in progress", please?

Sure, done!

**Comment by indigoxela** [comment]
Here we go, port is complete: https://backdropcms.org/project/leaflet_widget :leafy_green:

**Comment by olafgrabienski** [comment]
Great, thank you for doing the port! I've adapted the label to `Port complete`.
