### ISSUE TITLE
Sticky Note has been ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#509]
**Name of the module**
Sticky Note 

**Link to the drupal.org module**
https://www.drupal.org/project/stickynote

**Link to the drupal.org issue**
The module is maintained by AltaGrade, but I've created the issue on https://www.drupal.org/project/stickynote/issues/3208885 for all interested parties.

Please set the status to Port Complete.

**Comment by olafgrabienski** [comment]
Hey Alan, thanks for porting the module! I've set the issue to `Port complete`.
