### ISSUE TITLE
Superfish module has been ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#511]
**Name of the module**
Superfish

**Link to the drupal.org module**
https://www.drupal.org/project/superfish

**Link to the drupal.org issue**
https://www.drupal.org/project/superfish/issues/3211069

Port is done and the module is available at https://github.com/backdrop-contrib/superfish Please change the status accordingly.

**Comment by olafgrabienski** [comment]
Great, thanks for porting another important module!
