### ISSUE TITLE
Menu Attach Block has been ported

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/contrib#512]
**Name of the module, theme, or layout you are working on**
Menu Attach Block

**Link to the drupal.org module**
https://www.drupal.org/project/menu_attach_block

**Link to the drupal.org issue**
https://www.drupal.org/project/menu_attach_block/issues/3211074

The port is available on https://github.com/backdrop-contrib/menu_attach_block. Please change the status accordingly.

**Comment by olafgrabienski** [comment]
Thanks! Changed label to `Port complete`.
