### ISSUE TITLE
Port request for Read Time

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#515]
**Name of the module, theme, or layout**
Read Time

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/read_time

**Comment by olafgrabienski** [comment]
Nice, originally from @BWPanda !

**Comment by keiserjb** [comment]
It is here.  https://github.com/backdrop-contrib/read_time

**Comment by djzwerg** [comment]
Thanks a lot @keiserjb. Happy holidays!
