### ISSUE TITLE
Ubercart Feed Mappers

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-ops/contrib#523]
**Name of the module, theme, or layout**
Ubercart Feed Mappers

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/uc_feeds

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
https://www.drupal.org/project/uc_feeds/issues/3214581

I've already converted the module for my own usage.  I converted it with Coder_upgrade and it worked for my usage.

**Comment by stpaultim** [comment]
Well, I need it as well. I can't find any Github projects, so I'll start over.

**Comment by stpaultim** [comment]
No official release yet. But, I ran it through Coder Upgrade and it works as is. 

https://github.com/backdrop-contrib/uc_feeds

**Comment by albanycomputers** [comment]
Sorry @stpaultim I never got around to posting it :(
