### ISSUE TITLE
Porting viewport

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#525]
**Name of the module, theme, or layout you are working on**
Viewport

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/Viewport

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/viewport/issues/3216093

**Do you need assistance with this port?**
Yes, I would love a co-maintainer, or help with testing

**Comment by larsdesigns** [comment]
I am assisting @jenlampton with the module port and cross posted on Drupal.org: https://www.drupal.org/project/viewport/issues/3216093#comment-14141839

**Comment by larsdesigns** [comment]
Completed the following:

1. Ported the module using Coder Upgrade. 
1. Tested the module and replaced the template_preprocess_html() with hook_html_head_alter() to add the view port. Rewrote the building of the viewpoint content string.
1. Created a help page to replace the Drupal hook_help() implementation. 
1. Cleaned up the code to be PHPCS Drupal standards compliant. 
1. Created the README.md file using the recommended template and content from the README.txt drupal file.

@jenlampton, Posted the viewport module to https://github.com/backdrop-contrib/viewport. This is ready for review.

**Comment by larsdesigns** [comment]
@jenlampton, The release was created on July 1st. Can we close this one?

**Comment by jenlampton** [comment]
yep!
