### ISSUE TITLE
Porting of CKeditor

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#53]
From my perspective, getting a first-rate WYSIWYG editor available in Backdrop is a high priority and something that is essential before I hand over a website for use by a client. I am hoping that this will be in May, with the release of 1.1.x
However, just in case this (full WYSIWYG editing) isn't going to make it into core, I have started having a look at the possibility of porting the CKeditor D7 contributed module into Backdrop, perhaps just using it in compatibility mode. I was pleasantly surprised to find that it is largely functioning just 'out-of-the-box' but there are some problems.
The first one I am tackling is problems with the calls to admin menu functions [e.g. function ckeditor_admin_profile_form()] where the parameters are showing up differently in Backdrop compared with D7. So my next task is to learn enough about the workings of form.inc in core and why it is different in Backdrop. This I fear is a bit of a needle in a haystack job!

**Comment by Graham-72** [comment]
An interesting development in my hunt for the problem with the calls to the admin menu functions - I installed the devel module and the problem disappeared. Deactivate the devel module and the problem reappears. I was hoping to use devel to find out what has happened to the 'page arguments' which seem to go missing.

**Comment by Graham-72** [comment]
Advice please - I have found a problem but I don't yet know enough about the inner workings of Backdrop or Drupal to know how to solve it. 'form.inc' in Backdrop core contains some code changes compared with the current Drupal 7 version and a result is that some admin functions in the ckeditor module are producing errors.

ckeditor.admin.inc declares functions such as
function ckeditor_admin_profile_form($form, $form_state, $task, $profile = NULL)
and the parameters '$task, $profile = NULL' do not seem to be registering in Backdrop's form.inc though they do in D7.

Looking through the Drupal APIs I see a similar construct for the D6 version of drupal_rebuild_form, namely
drupal_rebuild_form($form_id, &$form_state, $args, $form_build_id = NULL)
but the D7 and Backdrop APIs have
backdrop_rebuild_form($form_id, &$form_state, $old_form = NULL) i.e. without the $args

So maybe ckeditor.admin.inc is in error and only works with D7's form.inc because there is a hangover from D6.

My question is, should I be solving these issues by making changes to ckeditor.admin.inc or is there something wrong in Backdrop's form.inc ?

**Comment by docwilmot** [comment]
Hi Graham,
If you look in ckeditor.module, in hook_menu, you find this:
```
$items['admin/config/content/ckeditor/edit/%ckeditor_profile'] = array(
...
    'page callback' => 'drupal_get_form',
    'page arguments' => array('**ckeditor_admin_profile_form**', 'edit', 5),
...
  );
```
The way I understand it drupal_get_form() passes the 'edit' and '%ckeditor_profile' to ckeditor_admin_profile_form() as $task and $profile respectively. So thats where those come from.

**Comment by Graham-72** [comment]
Yes, thanks docwilmot, but my problem is that the two parameters do not seem to be getting through to their required destination, unless I happen to have the devel module installed - this last bit being an odd situation. So I fear that something may be wrong with form.inc in core. As I said, it works OK in D7 and I can see that they get through to the form OK.

**Comment by Graham-72** [comment]
I have completed an initial full port to Backdrop, changing functions calls from drupal to backdrop and replacing variable_ with config_ . There are some remaining issues that I am investigating.

**Comment by Graham-72** [comment]
One issue now solved thanks to advice (and solution) from Wiktor Walc - a maintainer of the Drupal module. Many thanks Wiktor.

**Comment by Graham-72** [comment]
Current status is that this port of ckeditor is working in Backdrop but with one remaining problem. The function ckeditor_preprocess_page(&$page) in ckeditor.module needs modifying to work in Backdrop. I hope to solve this one soon.

**Comment by Graham-72** [comment]
I have learnt that the $page variable has been removed in Backdrop so I have tried replacing it with $variables but this is still not getting the ckeditor.css rendered into the foot of the page. I am now wondering if this is something to do with what is described in this issue  "No hook exists to extract the complete list of messages on a page #615" but this is way above my current level of expertise. @quicksketch please can you spare a moment to advise me? Thanks.

**Comment by quicksketch** [comment]
Using `hook_preprocess_page()` should still work fine for adding CSS. Do you have any idea why CKEditor needs to add CSS to the bottom of the page? If using a normal backdrop_add_css() works, you might consider using that. If it absolutely needs to be attached to the bottom of the page, you can append HTML to include the CSS to the `$variables['page_bottom']` variable.

**Comment by Graham-72** [comment]
Thanks @quicksketch . Your suggestion to use backdrop_add_css() seems to work fine. I am not sure why CKEditor uses the bottom of the page, except perhaps to make it clearer that it has added it - I read something about this somewhere. I have been trying to include it in $variables['page_bottom'] with 
$variables['page_bottom']['#attached']['css'] = array(backdrop_get_path('module', 'ckeditor') . '/css/ckeditor.css' => array('every_page' => TRUE,)
but this woudln't work, perhaps because it wasn't producing HTML?

Now that backdrop_add_css() is doing what is needed my port is complete, At the weekend I will transfer it to backdrop-contrib. Perhaps others will also find it useful as a stop-gap until CKEditor is in core.

**Comment by Graham-72** [comment]
Port now at https://github.com/backdrop-contrib/ckeditor
