### ISSUE TITLE
Porting Field default token

### ISSUE THREAD

**Issue by indigoxela** [backdrop-ops/contrib#531]
**Name of the module, theme, or layout you are working on**

Field default token

**Link to the drupal.org module, theme, or layout**

https://www.drupal.org/project/field_default_token

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**

https://www.drupal.org/project/field_default_token/issues/3216699

**Do you need assistance with this port?**
No

https://github.com/backdrop-contrib/field_default_token

**Comment by indigoxela** [comment]
Module has a stable release, this issue could get closed. https://backdropcms.org/project/field_default_token

**Comment by olafgrabienski** [comment]
Great! Thanks for porting this module!
