### ISSUE TITLE
Porting (or attempting to) Tawk.to module

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/contrib#532]
**Name of the module, theme, or layout you are working on**
Tawk.to

Tawk.to is a free chat service providing widgets that sit on your page.  There are possible paid add-ons, but the free service is pretty good. 

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/tawktodrupal7

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/tawktodrupal7/issues/3217539

**Do you need assistance with this port?**
Yes
I followed the guidance for changing to Backdrop and the module is now showing the config page without any errors and saving the options to a config file.  However, the widget is not appearing on pages and I'm not sure why.  I would appreciate some pointers as to what I should be looking at.

Note - I tried Coder Upgrade, but that caused lots of PHP syntax errors that was tricky to diagnose, so I went back to the drupal 7 original and worked through the changes that seemed applicable from here (https://docs.backdropcms.org/converting-modules-from-drupal)

https://github.com/yorkshire-pudding/tawkto

**Comment by jenlampton** [comment]
Hi @yorkshire-pudding and welcome! 

Thanks for working on this module :) The reason your widget isn't appearing on the page is becasue the Drupal 7 module used [`hook_page_build()`](https://github.com/yorkshire-pudding/tawkto/blob/280e3839c58526e981a33380db2ee842f645c566/tawkto.module#L27) which has been removed from Backdrop. 

You can read all the boring details about the change in [the change record](https://docs.backdropcms.org/change-records/new-layout-module-implements-a-drag-drop-model-for-building-layouts), but the short answer is that you probably need to change this into `hook_preprocess_page()` instead. 

Here's [an example of how we did the same thing when admin_menu was moved into Backdrop core as admin_bar](https://github.com/backdrop/backdrop/commit/6490d6bfd7bf813e71266d128a66cbaf71284a1a#diff-76a37b8cdf08471bdcb862b66c903d2975eda8cf54c52627c21f2dbd06ed83f5L103)

**Comment by yorkshire-pudding** [comment]
Hi @jenlampton 
Thank you.  I had started wondering along the lines of whether the function had changed and had started trawling the API for likely candidates.  What you've provided there gives me a solid idea of where to start digging.

The suppliers of the service are interested in helping as well, so I'm optimistic I can get there with the odd pointer here and there from the Backdrop experts like yourself.

I have been around for a bit, some more than others, but have been trying to build up my confidence to tackle a module, having let my PHP skills get very rusty.

**Comment by yorkshire-pudding** [comment]
Thanks @jenlampton . Your tip has helped us get it showing up.
The chat supplier is taking on the ownership and have created #534 .  I am working with @alvinjohnsonso on the tawk repository.
