### ISSUE TITLE
Porting Tawk.to Module

### ISSUE THREAD

**Issue by alvinjohnsonso** [backdrop-ops/contrib#534]
**Name of the module, theme, or layout you are working on**
tawk.to

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/tawktodrupal7

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
I'm one of the Drupal maintainers of this module and will collaborate with https://github.com/yorkshire-pudding, who was porting this module.

Related issue: https://github.com/backdrop-ops/contrib/issues/532

**Do you need assistance with this port?**
As of now, no. But will post here if something comes up that we cannot handle.

https://github.com/tawk/tawk-backdrop

**Comment by alvinjohnsonso** [comment]
Hi @jenlampton, would you happen to know if I can do this scenario that I thought of. To start, I saw in Backdrop's Administation > Configuration > Development > Performance page that there's an option to `Cache pages for anonymous users`. Now if that's enabled, that would pose an issue to our plugin. If the admin user changed/removes the widget from the plugin, the cached pages won't be updated until it reaches the expiration time.

I was wondering if there's a way to have something similar to Drupal 8's cache tags where we `tag` the cache from the `hook_preprocess_page` and manually invalidate it from other parts of the plugin using that `tag`.

**Comment by jenlampton** [comment]
See https://github.com/backdrop/backdrop-issues/issues/4127

**Comment by alvinjohnsonso** [comment]
Just noting down this comment here

https://github.com/backdrop-ops/contrib/issues/555#issuecomment-909784915

**Comment by stpaultim** [comment]
This one seems complete. 

https://backdropcms.org/project/tawk_to
