### ISSUE TITLE
Ported link module

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/contrib#54]
I've ported link: https://github.com/herbdool/link but I recall that someone else might have also been working on it. There wasn't much work to do so either port is fine by me.

**Comment by docwilmot** [comment]
@herbdool I tried to port Link, but it wasnt working so I gave up, so please feel free to move to the Backdrop contrib repo as the official port.

**Comment by herbdool** [comment]
Okay, I've moved it. It worked for me, though I hadn't tested it extensively so perhaps you could give it a try.

**Comment by quicksketch** [comment]
Thanks @herbdool! We'll certainly give it a spin when we convert backdropcms.org to Backdrop. That should be in the next couple of weeks.
