### ISSUE TITLE
Port request for node_limit

### ISSUE THREAD

**Issue by padprint** [backdrop-ops/contrib#542]
**Name of the module, theme, or layout**
Node Limit

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/node_limit

if anyone is up for this, it'd be great! I tried running it through coder_upgrade but the module ls looking for the role table, which no longer exists.

**Comment by jenlampton** [comment]
> if anyone is up for this, it'd be great! I tried running it through coder_upgrade but the module ls looking for the role table, which no longer exists.

This should be a relatively straightforward fix. Do you have the module in a github repository, so we can help diagnose and fix the issue?

**Comment by padprint** [comment]
Hi Jen,

Here's what I have set up. 
https://github.com/padprint/backdrop_node_limit

I'm not particularly clever so I rarely use Git.  Or GitHub.  Or brain cells. If you would prefer something different, please let me know and I'll see what I can sort out.

**Comment by rositis** [comment]
I'll take this one as part of my participation in OpenForce 2022.  My current WIP version is [here](https://github.com/rositis/node_limit/tree/1.x-1.x). 

The notable challenges in this module conversion are both the aforementioned role table issue as well as converting to using Config when the original D7 version used dynamic variable names. There also seems to be an unresolved architectural issue for when a new content type gets created.

**Comment by rositis** [comment]
The initial port is complete and I am preparing a release. It is now available on the [backdrop-contrib GitHub repository.](https://github.com/backdrop-contrib/node_limit)

**Comment by olafgrabienski** [comment]
@rositis Thank you very much for porting the module!

The module page on backdropcms.org https://backdropcms.org/project/node_limit
