### ISSUE TITLE
Porting IP Address Manager

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#549]
**Name of the module, theme, or layout you are working on**
IP Address Manager

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/ip

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/ip/issues/3228421

**Do you need assistance with this port?**
No

**Comment by bugfolder** [comment]
Port completed.

https://backdropcms.org/project/ip

**Comment by olafgrabienski** [comment]
Great, thanks for porting the module! (Adjusted the labels, closing issue.)
