### ISSUE TITLE
pax_global_header file packaged along with contrib module releases.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#55]
What is that file used for? Is there any reason to ship it with the .tar.gz archives? Can we get rid of it?

**Comment by quicksketch** [comment]
I got this file as well, but only when opening the file with the default Mac OS X application for expanding archives (Archive Utility). If I open the archive with The Unarchiver, the command line, or tell Firefox to open the file instead of save it, then the archive is fine and only includes the expected files. I think this may be an issue with the way GitHub generates all .tar.gz files.

**Comment by klonos** [comment]
https://marc.info/?l=linux-kernel&m=111909182607985&w=2

> Kernel tar-archives created by git contain an extended header with the git
> commit ID that was used to generate the tar-tree. If your tar is older
> than 1.14 then this extended header will be extracted as a regular file
> called pax_global_header. Patches should never be generated against this
> file, so it should be listed in dontdiff.

https://forum.dokuwiki.org/thread/11842

> > The pax_global_headers are internal to the tar file (pax=POSIX).  Linux tar ignores them and unpacks the tarred contents only.  But I see that in Windows, Winrar extracts pax_global_header as a file.  

> Dokuwiki's tar also produces a pax_global_header.  The posix format has to be specified, it seems, but it is ignored on Centos and produces an error in Ubuntu.

http://comments.gmane.org/gmane.comp.version-control.git/140254

> git-archive adds a special entry to the archives it creates, pax_global_header, containing the SHA1 of the exported commit.

Hope this info helps.

**Comment by quicksketch** [comment]
So... I don't think there's anything for us to do here. Depending on your unzipping application, it may or may not show this file. And of course you can use the .zip file as an alternative, which doesn't include this information.

**Comment by klonos** [comment]
Yep.
