### ISSUE TITLE
Porting Views Photo Grid

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#552]
**Name of the module, theme, or layout you are working on**
Views Photo Grid

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/views_photo_grid/

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/views_photo_grid/issues/3229257

**Do you need assistance with this port?**
No

The port is done at https.//www.github.com/backdrop-contrib/views_photo_grid

**Comment by djzwerg** [comment]
Port is done, is it ok to close this issue @jenlampton @klonos ?

**Comment by klonos** [comment]
Yup, lets close it. Thanks for porting the module over @djzwerg 🙏🏼
