### ISSUE TITLE
Hero Video Module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#554]
I was just asked if a hero block can support videos, did a quick search, and found that there's not a module for this yet! I was going to create one, but wanted to post here incase anyone else was working on the same thing. 

I was thinking about doing something [along these lines](https://howtogetonline.com/how-to-embed-a-hero-background-video.php) for a Background video.

We could also provide direct integration with YouTube, Vimeo, or other providers.

**Comment by Steve-A-Orr** [comment]
I think it a great idea. I'm not working on any similar idea.

**Comment by jenlampton** [comment]
First release is out! https://github.com/backdrop-contrib/video_hero/releases/tag/1.x-1.0.0
