### ISSUE TITLE
Application to join: a8w4

### ISSUE THREAD

**Issue by a8w4** [backdrop-ops/contrib#557]
Hello and welcome to the contrib application process! We're happy to have you :)

## Please note these 3 requirements for new contrib projects:

- [x] N/A Include a README.md file containing license and maintainer information. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] N/A Include a LICENSE.txt file. 
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] N/A If porting a Drupal 7 project, Maintain the Git history from Drupal.

## Please provide the following information:

**If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
- https://github.com/backdrop-contrib/pdf_to_image/pull/7
- https://github.com/backdrop-contrib/pdf_to_image/pull/5
- https://github.com/backdrop-contrib/pdf_to_image/pull/6

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by a8w4** [comment]
here is one PR for the abandoned project I would like to maintain:
https://github.com/backdrop-contrib/pdf_to_image/pull/1

**Comment by jenlampton** [comment]
Hello @a8w4 and thank you for your application to join the Backdrop Contrib group!  

Based on your previous contributions, I have sent you an invitation to join Backdrop Contrib!

I aslo noticed that you have been doing a lot of work on the pdf_to_image module, which does not currently have a maintainer. Are you interested in becoming a maintainer for that module? If so you would be able to merge your open pull requests, and create a new release. If yes, please create a pull request adding your name to the README.md file in the maintainer's section, and we would be happy to grant you access to that project as well :)

**Comment by jenlampton** [comment]
I'm going to close this ussue, but @a8w4 if you have any questions feel free to ask here :)
