### ISSUE TITLE
Port request for Localization client module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#559]
**Name of the module, theme, or layout**
Localization client

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/l10n_client

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
@todo 

**(Optional) Bounty**
<!-- example: I would be willing to pay $500 towards having this project ported. <!-- example:

**Comment by olafgrabienski** [comment]
FYI https://github.com/backdrop-contrib/l10n_client :-)

**Comment by jenlampton** [comment]
what? How did I miss that! Thank you @olafgrabienski
