### ISSUE TITLE
Module releases have no version in .info file

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#56]
Just installed the newly released Token 1.x-1.7.0 and Pathauto 1.x-1.2.1. None of them has a ```version``` property defined in their .info file:

![backdrop-pathauto_token-no_version](https://cloud.githubusercontent.com/assets/2423362/6127734/78b83336-b182-11e4-9dca-8028e975514b.png)

Perhaps we'll need to automate this.

**Comment by quicksketch** [comment]
Very similar to https://github.com/backdrop/backdrop-issues/issues/700. I filed a new issue detailing how we need to set up the GitHub web hook to automate this at https://github.com/backdrop-ops/backdropcms.org/issues/51.

**Comment by klonos** [comment]
Fair enough. The same concern about people already having installed some version and not being notified of any new ones applies here. In this case, people are not able to tell which version they already have installed if they want to "manually" compared to a future one.

If the auto-generated info script solution is implemented soon(ish) that won't be much of an issue given the fact that till today we only have just a couple of extensions with actual releases. And I guess only a few people (that know what they are doing) using them.

**Comment by quicksketch** [comment]
> If the auto-generated info script solution is implemented soon(ish), that won't be much of an issue

I don't think the GitHub integration is going to be difficult, but we'll need to get BackdropCMS.org updated to Backdrop first (https://github.com/backdrop-ops/backdropcms.org/issues/38).
