### ISSUE TITLE
Port request for Leaflet Markercluster

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#561]
**Name of the module, theme, or layout**
Leaflet Markercluster
**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/leaflet_markercluster

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**

**(Optional) Bounty**
<!-- example: I would be willing to pay $500 towards having this project ported. <!-- example:

**Comment by olafgrabienski** [comment]
There's a [Markercluster submodule](https://github.com/backdrop-contrib/leaflet/tree/1.x-1.x/modules/leaflet_markercluster) in the [Leaflet module](https://github.com/backdrop-contrib/leaflet). (The submodule doesn't expose any settings, as far as I know.)

**Comment by jenlampton** [comment]
Hm, I wonder if that is the same as the Drupal leaflet_markercluster module? @indigoxela do you know? If so I can close this issue too :)

**Comment by indigoxela** [comment]
> Hm, I wonder if that is the same as the Drupal leaflet_markercluster module?

Yes, that's the same. Leaflet Markercluster now ships with Leaflet, so it's already ported.

**Comment by jenlampton** [comment]
Fantastic, thank you!
