### ISSUE TITLE
Initial port Complete: simpleSAMLphp Authentication (simplesamlphp_auth)

### ISSUE THREAD

**Issue by joelsteidl** [backdrop-ops/contrib#567]
**Name of the module, theme, or layout you are working on**
simpleSAMLphp Authentication (simplesamlphp_auth)

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/simplesamlphp_auth

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/simplesamlphp_auth/issues/3243089

**Do you need assistance with this port?**
The initial port is complete. Additional testing outside the features I'm using would be helpful. I did create https://github.com/backdrop-contrib/authmap that replaces some functions removed from Drupal 8.x and inherited by Backdrop.

**Comment by joelsteidl** [comment]
Here is the ported module https://github.com/backdrop-contrib/simplesamlphp_auth

**Comment by jenlampton** [comment]
I'm going to close this issue since there is a release out:
https://github.com/backdrop-contrib/simplesamlphp_auth/releases/tag/1.x-2.0.0-alpha2
