### ISSUE TITLE
Create .md file containing friendly Backdrop invite (for d.o project maintainers)

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/contrib#57]
Can/should we create a wiki page here that has a copy of a typical message people can post to a module's D.o issue queue offering for the maintainer(s) to port their module to Backdrop? (e.g. https://www.drupal.org/node/2411297)

**Comment by quicksketch** [comment]
Maybe we should throw in a new .md in https://github.com/backdrop-ops/contrib/tree/master/examples? Or we could just include the example directly in https://api.backdropcms.org/converting-modules-from-drupal.

**Comment by BWPanda** [comment]
I think https://api.backdropcms.org/converting-modules-from-drupal is primarily for the person who ends up porting the module (maybe after reading the invite). I personally wouldn't think to go there when I'm wanting to ask someone else to port a module.

Adding a new .md file would be fine though.

**Comment by BWPanda** [comment]
Don't think this is needed anymore... Reopen if you disagree.
