### ISSUE TITLE
Port status: turn.js

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#576]
**Name of the module, theme, or layout you are working on**
Turn.js

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/turnjs

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/turnjs/issues/3225917

**Do you need assistance with this port?**
I'm hoping to use this module on 2 different projects, but could certainly use help with adding the JS settings.

**Comment by keiserjb** [comment]
Does this work?  I only get the first page displaying and it doesn't open the flip book.

**Comment by keiserjb** [comment]
I see the flip effect in Firefox but not chrome.

**Comment by jenlampton** [comment]
I ran into that in an early version. Let me check that the current release
is up to date!

**Comment by jenlampton** [comment]
I pushed my recent updates and tagged it as -beta. I'm running this right now on https://commonerscatalog.org/books/the-commoners-catalog-for-changemaking?page=-3 and it seems to be working in Chrome. I'm going to close this issue, but if you still have any problems please open issues in the queue :)

**Comment by keiserjb** [comment]
Thank you, I will give this a try again soon.  I thought it would be great for magazine websites.
