### ISSUE TITLE
Port request: Text Resize Module

### ISSUE THREAD

**Issue by Wylbur** [backdrop-ops/contrib#584]
**Name of the module, theme, or layout**
Text Resize module

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/text_resize

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
None yet.

**(Optional) Bounty**
I would like to find a few projects to help learn to port modules.  Perhaps we can do this as part of regular office hours.

**Comment by keiserjb** [comment]
I couldn't resist, and well I wanted to use it after I knew it existed.  https://github.com/keiserjb/text_resize

**Comment by djzwerg** [comment]
I think this could be closed because you had complete the port? https://github.com/backdrop-contrib/text_resize

**Comment by Wylbur** [comment]
Closed!
