### ISSUE TITLE
Port request: Quicktabs

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-ops/contrib#586]
**Name of the module, theme, or layout**

Quicktabs

**Link to the drupal.org module, theme, or layout**

https://www.drupal.org/project/quicktabs

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**

Some discussion here...
https://forum.backdropcms.org/forum/there-out-box-tabbed-block

**(Optional) Bounty**

**Comment by olafgrabienski** [comment]
I just read [in the forum](https://forum.backdropcms.org/forum/quick-tabs-or-method-simulate?page=0%2C0#comment-6358) that Quicktabs is now available, and indeed: https://github.com/backdrop-contrib/quicktabs
