### ISSUE TITLE
Join Backdrop-contrib (port cbb) 

### ISSUE THREAD

**Issue by Wylbur** [backdrop-ops/contrib#589]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option #1: I would like to contribute a project
* Option #2: I would like to maintain a project, but have nothing to contribute at this time
* Option #3: I would like to update documentation and/or triage issue queues

Option 1

### Based on your selection above, please provide the following information:

**(option #1) The name of your module, theme, or layout**
cbb

### (option #1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**(option #1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

@todo?

**Post a link to your new Backdrop project under your own GitHub account (option #1)**
https://github.com/Wylbur/cbb

**If you have chosen option #2 or #1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**

--- Original Issue ---

I'm porting a module - cbb
https://github.com/backdrop-ops/contrib/issues/585

Here's the module page on drupal.org
https://www.drupal.org/project/cbb

Here's the request to port the module
https://www.drupal.org/project/cbb

I have created a project folder on my own account for now
https://github.com/Wylbur/cbb

**Comment by Wylbur** [comment]
Sorry I missed this.

YES, I agree to the Backdrop Contributed Project Agreement.

**Comment by Wylbur** [comment]
I've also added the LICENSE.txt and README.md files to the project.

**Comment by Wylbur** [comment]
@jenlampton Is there anything else that needs to be done for this?

**Comment by jenlampton** [comment]
Sorry for the delay @Wylbur, I had forgotten to add the correct label so missed this issue a few times in my weekly reviews.  

There should be an invitation in your inbox! - Once it arrives, feel free to transfer the repository into the backdrop-contrib group at any time. Ask here if you have questions, and if you don't feel free to close this issue!

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have an questions @Wylbur feel free to keep asking them here :)
