### ISSUE TITLE
Becoming maintainer for entity_token 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#593]
I'd like to offer my help to maintain `entity_token` (https://github.com/backdrop-contrib/entity_token). 

Currently the project does not list any maintainer in the readme file. I'm following the steps outline [here](https://docs.backdropcms.org/documentation/adopt-a-project) and have created an issue: backdrop-contrib/entity_token#8  - and a PR in the project: backdrop-contrib/entity_token#9 . Thanks

**Comment by jenlampton** [comment]
Thank you @argiepiano for offering to maintain, and @klonos  for taking care of the change!  Closing this issue :D
