### ISSUE TITLE
Field Permissions: Become a maintainer for this project

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#597]
I would like to become the maintainer for the Field Permissions project (which currently is "looking for maintainers").

Issue in that project: https://github.com/backdrop-contrib/field_permissions/issues/7

PR to update the README file: https://github.com/backdrop-contrib/field_permissions/pull/8

**Comment by jenlampton** [comment]
@bugfolder  I see you are listed as the maintainer now 🎉 , closing issue.
