### ISSUE TITLE
please add me to the contrib repo

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/contrib#60]
I'm porting `redirect` module:
https://github.com/serundeputy/redirect

i think it is stable enough to use.

**Comment by quicksketch** [comment]
That's great! I thought you were in the group already!

We generally require 3 things in the first module port:

- [x] Include a LICENSE.txt file.
- [x] Include a README.md with a list of maintainers and license info.
- [x] Maintain the history from Drupal 7

Your port includes all 3 already. Nice! The only thing I'd suggest is making the README.md line up a bit more with the example, using the raw version might make it easier to match the formatting: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md

All technical requirements are met however, so let's not hold things up. Would you agree to the following for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by serundeputy** [comment]
@quicksketch yes I agree.

**Comment by quicksketch** [comment]
Great! Invite is on its way! You can transfer the repository from your account under the repo's "Settings" page. Be sure to grant the "Authors" group access, otherwise you won't be able to push after its been transferred.

**Comment by serundeputy** [comment]
@quicksketch who do I transfer the repo to?
