### ISSUE TITLE
Port request: Tracking Code

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/contrib#604]
**Name of the module, theme, or layout**
Tracking Code

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/tracking_code

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**

https://www.drupal.org/project/tracking_code/issues/3257012

I am interested in a module like this because I am having trouble getting Google Analytics 4 to work with Backdrop. A module like this would allow me to add the code directly to the header (using UI settings) and test it out. I have had to use this module to include other misc tracking codes in Drupal 7 sites. 

I think it would be a good module to have available for Backdrop CMS users. I would think it would be pretty easy port.

**Comment by stpaultim** [comment]
Should we follow the path of Drupal 8/9 and merge the functionality of this module with the functionality of CSS injector. 

https://www.drupal.org/project/asset_injector

**Comment by olafgrabienski** [comment]
> Other contrib modules with similar functionality?

Have you seen [JS Injector](https://www.drupal.org/project/js_injector)? As far as I know, this is the module which in D8 was combined with CSS Injector.

**Comment by stpaultim** [comment]
@olafgrabienski - Thanks. I've not looked closely at JS Injector, because I have experience with Tracking Code and it has met me needs nicely in the past. We've got a Backdrop version of this module working already and will be moving to Contrib soon. We may take a look at JS injector soon. I'm curious.
