### ISSUE TITLE
Port request: views_calc_distinct

### ISSUE THREAD

**Issue by LucianoGit-x6zeta** [backdrop-ops/contrib#607]
**Name of the module, theme, or layout**
views_calc_distinct

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/views_calc_distinct

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
This module solves a problem in "view calcs" that expose content with multivalued fields. In fact, if you want to add up the numeric values of a certain field and the contents contain another multivalued field (even non-numeric - for example 3 attached files), the sum of the field returns triple the real value.
I tried the conversion with coder upgrade but the module does not work and I am not doing more as I am not a programmer. Thank you and sorry for my bad English.

**Comment by argiepiano** [comment]
Hi again Luciano.

Have you tried [Views Aggregator](https://github.com/backdrop-contrib/views_aggregator)? I believe it may be able to do what this other project does. I maintain that module. Take a look and let me know.

**Comment by argiepiano** [comment]
Ciao Luciano.

I took a look at Views Calc Distinct - it should be fairly simple to port. I'll take care of it in the next few days. I'll let you know once it's done.

**Comment by argiepiano** [comment]
Luciano, I have ported the module and it seems to be working, but since I'm not super familiar with what it does, I'm not sure how to go about testing it. Can you please download, install and test, and then add a comment here? If it works for you, then I'll create a first release.

https://github.com/backdrop-contrib/views_calc_distinct

**Comment by LucianoGit-x6zeta** [comment]
Dear Hi Argiepiano, I try to explain by attaching 2 files. I specify that in both views I chose the "Query Settings: Distinct" option. Note that with the view calc view the total sums are multiplied by the number of multiple values of the two columns 'test distinct taxonomy' and 'test distinct file'. This does not happen in the calc distinct view. It's a great module and I thank you again for bringing it to backdrop. I use this CMS mainly as a database and it is really very useful to me
![Test_view_calc](https://user-images.githubusercontent.com/77635069/148980340-46044e26-bb3d-4181-a32e-9a5dceb4abed.jpg)
![Test_view_calc_distinct](https://user-images.githubusercontent.com/77635069/148980347-bdded2cd-f31c-439f-8796-44569f173802.jpg)
.

**Comment by LucianoGit-x6zeta** [comment]
I add that it works perfectly so, at least in my opinion, you can easily create the first version. Many greetings dear Argiepiano

**Comment by argiepiano** [comment]
Grazie mille for the explanation and screenshots. I'll create the first release tonight.

**Comment by LucianoGit-x6zeta** [comment]
I peeked a bit at the new code of the module and the changes you made are not easy at all ... you have been really good Argiepiano and you have solved a huge problem for me. Thanks again

**Comment by argiepiano** [comment]
Sure! I've created the first release. The module should available through the Install new modules tab in Backdrop very soon, after it's picked up by the module portal.
