### ISSUE TITLE
Port completed: Node Title Length

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#618]
**Name of the module, theme, or layout you are working on**
Node Title Length

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/title_length

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/title_length/issues/3263014

**Do you need assistance with this port?**
No, it is tested and it works.

**Comment by djzwerg** [comment]
The module can be found here: https://github.com/backdrop-contrib/title_length. Can sb pls change the label to "Port completed"?

**Comment by olafgrabienski** [comment]
> Can sb pls change the label to "Port completed"?

Sure, done! And, thanks for porting the module.
