### ISSUE TITLE
Port completed: Active Tags

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#619]
**Name of the module, theme, or layout you are working on**
Active Tags

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/active_tags

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/active_tags/issues/3263242

**Do you need assistance with this port?**
No

**Comment by djzwerg** [comment]
Port is done - can somebody please change the label?

**Comment by olafgrabienski** [comment]
Thanks for the port, I've changed the label to `Port complete`.

Link: https://github.com/backdrop-contrib/active_tags
