### ISSUE TITLE
Port request: Smartmenus.js

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#622]
@jenlampton made this nice module :-)

**Name of the module, theme, or layout**
Smartmenus.js

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/smartmenus

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**

**(Optional) Bounty**

**Comment by jenlampton** [comment]
@djzwerg the Drupal module was based off what's already in Backdrop core. If there are features you need that are not already in Backdrop, can you list them here? The module itself shouldn't be necessary :)

**Comment by djzwerg** [comment]
Hi @jenlampton and thanks for your fast reply. I'm looking for a flexible and [mega-menu ready module](https://www.smartmenus.org/about/themes/#demos-6). I don't know whether it is better or maybe lighter than [TB Mega Menu](https://github.com/backdrop-ops/contrib/issues/615).

**Comment by jenlampton** [comment]
> I'm looking for a flexible and [mega-menu ready module](https://www.smartmenus.org/about/themes/#demos-6) 

Why are you looking for a module? 

> I don't know whether it is better or maybe lighter than https://github.com/backdrop-ops/contrib/issues/615.

Smartmenus is already in backdrop core, so anything you could do with the Drupal 7 smartmenus module you can do in Backdrop, without any module. "no module" is definitely lighter than any module.

**Comment by djzwerg** [comment]
I'm looking for a mega-menu module because In have to migrate 10 websites using one (TB Mega Menu). I'm not able to figure that out with core modules only 😔 And I'm sorry I didn't find the smartmenus.js library in core to extend the block menu functionality.

**Comment by jenlampton** [comment]
> And I'm sorry I didn't find the smartmenus.js library in core to extend the block menu functionality.

It's right here: https://github.com/backdrop/backdrop/tree/1.x/core/misc/smartmenus

**Comment by djzwerg** [comment]
Nice, thanks! But sorry I'm not a coder - can you please explain how to use the library to create custom mega menus? The library won't be loaded in my case and I don't know how to add the CSS classes.

**Comment by olafgrabienski** [comment]
FYI, here's a related core thread with some info and a workaround: https://github.com/backdrop/backdrop-issues/issues/5071

**Comment by djzwerg** [comment]
Thanks @olafgrabienski that helps a bit. I miss the [UI of TB Mega Menu](https://github.com/backdrop/backdrop-issues/issues/2208#issuecomment-492399527) which made it very easy to build menus. Because I started a [port request](https://github.com/backdrop-ops/contrib/issues/615) I think we can close this issue for now.

**Comment by jenlampton** [comment]
@djzwerg If your sites are using TB Mega Menu already, the upgrade path will be easier if you use that for backdrop as well. I'll close this issue now - but if anyone else was using the smartmenus module for Drupal and finds that they can't get the same exact functionality from backdrop core -- please re-open this issue and let me know what's missing :)
