### ISSUE TITLE
Port completed: Advanced Text Formatter

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#623]
**Name of the module, theme, or layout you are working on**
Advanced Text Formatter

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/advanced_text_formatter

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/advanced_text_formatter/issues/3263597

Done: https://github.com/backdrop-contrib/advanced_text_formatter

**Comment by djzwerg** [comment]
Port is done, can somebody please change the label?

**Comment by olafgrabienski** [comment]
Thanks for the port, label changed!
