### ISSUE TITLE
Port request: Image effect kit

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#627]
**Name of the module, theme, or layout**
Image effect kit

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/iek/

**Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
https://www.drupal.org/project/iek/issues/3265657

Maybe as a submodule of https://github.com/backdrop-contrib/image_effects?

**Comment by laryn** [comment]
@djzwerg At a glance it seems many of those effects are already in the Image Effects modules. Which ones are missing, if any?

**Comment by djzwerg** [comment]
Hi @laryn as [we discussed here](https://github.com/backdrop-contrib/image_effects/issues/12#issuecomment-1230482666) I'm looking for dynamic watermarks. Maybe there is no need to port the module while adding this feature to [Image Effects](https://github.com/backdrop-contrib/image_effects)?

**Comment by laryn** [comment]
Does this kit include the ability to add tokens to text overlays?

**Comment by djzwerg** [comment]
I'm not sure anymore. After re-trying it seems that it doesn't work. So I'm going to close this issue here.
