### ISSUE TITLE
Port status: Token Embed Views

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#629]
**Name of the module, theme, or layout you are working on**
Module: Token Embed Views

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/token_embed_views

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/token_embed_views/issues/3266232

**Comment by argiepiano** [comment]
This port is now completed - but I can't change the label!

**Comment by olafgrabienski** [comment]
Changed the label, thanks for porting the module!

Links:

- https://backdropcms.org/project/token_embed_views
- https://github.com/backdrop-contrib/token_embed_views
