### ISSUE TITLE
Port ready: Rules Throttle

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/contrib#631]
I'd like to apply to join backdrop-contrib.  Please note, I already co-ported [Tawk.to](https://github.com/backdrop-contrib/tawk_to) and am down as collaborator on that project.

**Name of the module, theme, or layout**
Rules Throttle

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/sandbox/jweirather/2603990

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
https://www.drupal.org/project/2603990/issues/3266874

**Link to repo**
https://github.com/yorkshire-pudding/rules_throttle

**Reason**
I was experimenting with Rules and found that the actions didn't seem to work after saving a node, so wanted to test by adding a delay.  I found this and thought others may benefit.

I'm thinking of changing to milliseconds for improved usability, but porting as is for now.

See also, [this issue](https://www.drupal.org/project/rules/issues/2604008)

**Comment by klonos** [comment]
I'm having a look now @yorkshire-pudding 👀

**Comment by klonos** [comment]
All projects must meet these minimum requirements:
- [ ] Maintain the Git history from Drupal 7.
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

Re the first item, it seems that the original author of the module only attached a .zip file in https://www.drupal.org/sandbox/jweirather/2603990. The repo for the drupal sandbox project is empty (see https://git.drupalcode.org/sandbox/jweirather-2603990), so not possible/applicable to retain any commit history 🤷🏼 

As such, and given a) @yorkshire-pudding's activity in the community over the past months, a) the prior history of co-maintainership of the Tawk.to module, I'll approve this.

@yorkshire-pudding for the record, can you please state that you agree with the terms in the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)?

**Comment by yorkshire-pudding** [comment]
@klonos - Yes I agree with the Backdrop Contributed Project Agreement

**Comment by klonos** [comment]
I will go ahead and close this issue, but please feel free to reopen if you happen to have any trouble with transferring the project to conntirb.

**Comment by yorkshire-pudding** [comment]
@klonos - I didn't get shown the 'Team Access' screen when I followed this step:

https://docs.backdropcms.org/documentation/after-your-application-is-accepted
> Transfer the project to backdrop-contrib following the steps mentioned in [this post](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization).
After clicking 'I understand, transfer this repository', you'll be shown the 'Team Access' screen.
Tick 'Authors', 'Bug squad', and 'Security', then click 'Transfer'.

I can't see any permissions screens from the repo either.

**Comment by klonos** [comment]
No worries @yorkshire-pudding ...I've fixed all permissions for that project 😉 

![image](https://user-images.githubusercontent.com/2423362/156419552-fe9b8007-4b4b-4660-b01c-1879f95a9aaf.png)

**Comment by yorkshire-pudding** [comment]
Thanks @klonos
