### ISSUE TITLE
Port request: Entityreference Prepopulate

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/contrib#632]
**Name of the module**
Entityreference Prepopulate

**Link to the drupal.org module**
https://www.drupal.org/project/entityreference_prepopulate

**Link to an issue in the drupal.org queue**
To do

**Motivation**
The module is needed for Organic Groups, see https://github.com/backdrop-contrib/og/issues/45#issuecomment-1058239851.

**Comment by argiepiano** [comment]
Port has been completed. It's already functional, but a couple of automated OG-related tests need to be fixed.

https://github.com/backdrop-contrib/entityreference_prepopulate

I don't have a way to change the status of this issue to "completed".

**Comment by argiepiano** [comment]
Link to issue in drupal.org queue:
https://www.drupal.org/project/entityreference_prepopulate/issues/3276876

**Comment by olafgrabienski** [comment]
@argiepiano Thank you **very** much for porting this module!
