### ISSUE TITLE
Should Backdrop contrib use semantic versioning or not?

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/contrib#64]
Most ported from d.org have a [backdrop_major].x-[module_major].x (for example 1.x-2.x) but their developers created a 1.x-2.0.0 once they tagged a release while others created a 1.x-2.0.

What is our policy on this? What happens to the already created releases?

**Comment by quicksketch** [comment]
I've been working on making our packaging script the past week (part of https://github.com/backdrop-ops/backdropcms.org/issues/51) and the only requirement that's in there so far is that some kind of version number is used at all. So these would all be valid:

```
1.0
v1.0
1.0.2
1.x-1.0.2
v1.x-1.02
```

You could even just use numbers like `v23`, `v24`, etc. Just so long as they keep incrementing.

Unlike on drupal.org, I don't think that we have the ability to restrict the allowed tags for releases. We *can* prevent the packaging script from auto-creating a release zip, but without a way to provide an explanation to the developer, I think being more liberal should reduce confusion as to why the package may not be generated.

**Comment by klonos** [comment]
So the packaging script does not have a way to communicate why if fails? Can't we output something like "Packaging failed: No valid version number [http://link.to.docs]"?

**Comment by klonos** [comment]
...BTW I had a dream that someday both d.org and GitHub/Backdrop would have some solution like coder running before packaging. That would save us a lot of time since we would not have to "manually" spot coding standard deviations for example.

**Comment by quicksketch** [comment]
> So the packaging script does not have a way to communicate why if fails? Can't we output something like "Packaging failed: No valid version number [http://link.to.docs]"?

Well the return response will say that, and we'll log it on the main site. But the response goes back to GitHub, not to the user who made the release. The only thing we can do to a release is add a release asset. So I suppose we could attach an error report to the release page. Here's what a release package looks like when it's done packaging: https://github.com/quicksketch/hooktest/releases/tag/v1.x-1.0.5

So I suppose we could actually attach the error log to the release itself if your tag did not match the expected tagging pattern.

**Comment by quicksketch** [comment]
> ...BTW I had a dream that someday both d.org and GitHub/Backdrop would have some solution like coder running before packaging.

Yeah, I know. https://github.com/backdrop/backdrop-issues/issues/659 :wink:

**Comment by klonos** [comment]
Yep, forgot to link that issue. Thanx :wink: 

> So I suppose we could actually attach the error log to the release itself if your tag did not match the expected tagging pattern.

...and (if supported) prevent the packaging from creating the .zip/.tar.gz

**Comment by quicksketch** [comment]
> ...and (if supported) prevent the packaging from creating the .zip/.tar.gz

Unfortunately we can't stop GitHub from creating the "Source Code (zip)" and "Source Code (tar.gz)" files on a release page. We can only add additional files to the release page. But I do like the idea of attaching an error log if the tag name doesn't match convention. GitHub still allows the user to delete the finished packages, so in theory it'd be easy for a maintainer to delete the error log if they didn't care that their package failed.

**Comment by klonos** [comment]
Fair enough.

**Comment by stpaultim** [comment]
@klonos - we are now using semantic versioning in contrib, aren't we. 

Can we close this old issue?

**Comment by jenlampton** [comment]
I think so.
