### ISSUE TITLE
Contrib Group Application: eric2pin (rolereference)

### ISSUE THREAD

**Issue by eric2pin** [backdrop-ops/contrib#640]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

Option 1

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**

Role reference (rolereference)

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

https://www.drupal.org/project/rolereference/issues/3244440

**Post a link to your new Backdrop project under your own GitHub account (option 1)**

https://github.com/eric2pin/rolereference

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES/no

**Comment by jenlampton** [comment]
Hi Eric, thanks for the application!  

I'm going to use the checklist below against the [rolereference module in your personal repo](https://github.com/eric2pin/rolereference): 

- [ ] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Unfortunately, the `README.md` file included in the repository doesn't contain the required information yet. 

The example `README.md` contains everything that's required, along with some of the other most commonly included sections. This is useful for projects coming over from Drupal as they often have very different information per project.

If you can get those two sections added to the README (and maybe also remove the heading "WHAT IT DOES:" -- but I'll get to that in a more detailed code review) then we can approve your application and you can transfer the project into the contrib group!

**Comment by eric2pin** [comment]
Hi Jen!

Thanks for the response and detailed requirements follow-up. The README.md should be good to go now.

Best,

**Comment by jenlampton** [comment]
That looks perfect! **An invitation to join the Backdrop Contrib group is on the way!** Feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

**Comment by quicksketch** [comment]
Repo is transferred and this can be closed. Welcome @eric2pin!

https://github.com/backdrop-contrib/rolereference
