### ISSUE TITLE
Port request: admin_menu_source - Port complete

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-ops/contrib#641]
**Name of the module, theme, or layout**
Admin Menu Source

**Link to the drupal.org module, theme, or layout**
(http://drupal.org/project/admin_menu_source)

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
https://www.drupal.org/project/admin_menu_source/issues/3270827

**Comment by albanycomputers** [comment]
The module is now ported.

**Comment by olafgrabienski** [comment]
Thanks for porting the module!

Link: https://github.com/backdrop-contrib/admin_menu_source
