### ISSUE TITLE
Port request: Barcodes

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#647]
**Name of the module, theme, or layout**
Barcodes

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/barcodes

**Comment by yorkshire-pudding** [comment]
@djzwerg - This looked interesting so I've done a first pass at this.  Tested on a few types (QRCODE, PDF417, DATAMATRIX) and works well.  A bit of tidying up to do later.  Are there any particular types of barcode you are interested in?  There are so many that testing may be a longer term aim.

**Comment by yorkshire-pudding** [comment]
I've now ported it and transferred to https://github.com/backdrop-contrib/barcodes

Added issue on Drupal queue - https://www.drupal.org/project/barcodes/issues/3282401

**Comment by olafgrabienski** [comment]
Thanks for porting the module, @yorkshire-pudding !
