### ISSUE TITLE
What is the animal?

### ISSUE THREAD

**Issue by andytruong** [backdrop-ops/contrib#65]
Hi, I am curious what animal is [this](https://avatars3.githubusercontent.com/u/8452564?v=3&s=200)? Is it anything related to "Backdrop"? Thanks

**Comment by docwilmot** [comment]
:-)
I understand your confusion. See https://backdropcms.org/presskit.

**Comment by andytruong** [comment]
Thank you. I think this will stop Christians to contribute to the project

> " He seized the dragon, that ancient serpent, who is the devil, or Satan, and bound him for a thousand years." Revelation 20:2

**Comment by quicksketch** [comment]
There is a long history of friendly and generally helpful dragons as well: http://io9.com/the-12-least-threatening-dragons-of-all-time-978171260 I think Drop falls into that category. :smile:
