### ISSUE TITLE
Backdrop Contrib Group Application: Daniel J. R. May (danieljrmay)

### ISSUE THREAD

**Issue by danieljrmay** [backdrop-ops/contrib#650]
Hello,

I would like to join the Backdrop contrib group. 

I would like to transfer my port of the `securitytxt` module to `backdrop-contrib` and maintain it there. Here is the relevant links & information:

- My current [backdrop port of the `securitytxt` module](https://github.com/danieljrmay/securitytxt) with Drupal 7 git history, `README.md` & GPL-2.0 `LICENSE.txt` files.
- The [drupal 7 securitytxt project page](https://www.drupal.org/project/securitytxt).
- My original [notification that I was porting this module](https://github.com/backdrop-ops/contrib/issues/636).
- I agree with the "Backdrop Contributed Project Agreement".

Please let me know if there is any other information that you require. :smile:

**Comment by herbdool** [comment]
Overall it looks like almost everything is in order. Really thorough for a first time Backdrop module!

I suggest these minor changes:

* Remove the VERSION line in securitytxt.info (will be added by packaging script when creating a release in github)
* Delete old git tags

Optional changes:

* Should `securitytxt/htaccess/drupal7.htaccess` be `securitytxt/htaccess/backdrop.htaccess`?
* Where there are multiple `config_get(` or `config_set(` in a function, it would be a bit more efficient to use `$config = config('securitytxt.settings');` and `$config->get('enabled')`.

**Comment by danieljrmay** [comment]
> I suggest these minor changes:
> 
>     * Remove the VERSION line in securitytxt.info (will be added by packaging script when creating a release in github)
> 
>     * Delete old git tags

Will do. 

> Optional changes:
> 
>     * Should `securitytxt/htaccess/drupal7.htaccess` be `securitytxt/htaccess/backdrop.htaccess`?

Actually no, `htaccess/drupal7.htaccess` is the current drupal 7 `.htaccess` file. There is no reason for it to be there now. It was there for comparison purposes, while I was trying to debug [backdrop issue 5583](https://github.com/backdrop/backdrop-issues/issues/5583). I suggest I delete it. 

The useful files are:
-  `htaccess/original.htaccess` the backdrop v 1.21.4 `.htaccess` file.
-  `htaccess/modified.htaccess` the "patched" version of the file which fixes [backdrop issue 5583](https://github.com/backdrop/backdrop-issues/issues/5583).

I will add a bit more documentation to explain this.

>     * Where there are multiple `config_get(` or `config_set(` in a function, it would be a bit more efficient to use `$config = config('securitytxt.settings');` and `$config->get('enabled')`.

I will make this change too — I have high hopes of being efficient one day, something which has eluded me so far in life… :wink:

**Comment by danieljrmay** [comment]
> I don't have permission to set up your access to the backdrop-contrib group but @jenlampton or @klonos can do it based on my review.

That's great. Thank you @herbdool :smile:

**Comment by danieljrmay** [comment]
> I don't have permission to set up your access to the backdrop-contrib group but @jenlampton or @klonos can do it based on my review.

I have now made all the changes suggested by @herbdool in his review. :smile:

**Comment by herbdool** [comment]
All looks good to me now!

**Comment by jenlampton** [comment]
Thanks for the review @herbdool! 

@danieljrmay an invite to join the contrib group is in your inbox :)  

Just to be official about it...

## 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Welcome to Backdrop contrib!

**Comment by danieljrmay** [comment]
Wonderful! Thank you very much @jenlampton & @herbdool :partying_face:
