### ISSUE TITLE
Port request: Subgroups for Organic Groups

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/contrib#652]
**Name of the module, theme, or layout**
Subgroups for Organic Groups

**Link to the drupal.org module, theme, or layout**
[https://www.drupal.org/project/og_subgroups](https://www.drupal.org/project/og_subgroups)

**(Optional) Link to an issue in the drupal.org queue asking the Drupal community if anyone is working on a Backdrop port of this project**
Not yet

I don't know how feasible this is as it contains ctools plugins

**Comment by argiepiano** [comment]
The plugin is an entityreference selection, which is simple to port (through a hook implementation). This should be a fairly quick port.

**Comment by argiepiano** [comment]
Port has been completed. Testing will be appreciated. https://github.com/backdrop-contrib/og_subgroups

Drupal post: https://www.drupal.org/project/og_subgroups/issues/3283239

**Comment by olafgrabienski** [comment]
Thanks for porting the module, @argiepiano!
