### ISSUE TITLE
Contrib Group Application: Rob Squires (port of uc_gc_client)

### ISSUE THREAD

**Issue by roblog** [backdrop-ops/contrib#653]
**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

Option 1

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**

Ubercart GoCardless Client

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

I have not finished porting the module yet, but will add the README and LICENSE files as required. 

I followed the instructions at https://docs.backdropcms.org/converting-modules-from-drupal for "Creating the Repository" in my personal github space. There are 3 branches in the Drupal repository (7.x-1.x, 7.x-2.x, and 8.x-1.x). However when I applied the "git remote remove origin" command as shown in the instructions, the 7.x-1.x and 8.x-1.x branches were removed from the clone. Did I do something wrong here?

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

I have omitted this step as I am the sole maintainer of the project on Drupal, and am not looking for any assistance in maintaining it at this point. The project can be seen on Drupal at https://www.drupal.org/project/uc_gc_client. 

**Post a link to your new Backdrop project under your own GitHub account (option 1)**

https://github.com/roblog/uc_gc_client/tree/1.x-2.x

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment]
Yes, everything seems to be in order -- **you should have an invite to join the contrib group in your inbox!** Welcome, and thanks again :) 

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**Comment by roblog** [comment]
Excellent thank you, I have joined the group.

**Comment by roblog** [comment]
I've copied the project to a new repository at https://github.com/backdrop-contrib/Ubercart-GoCardless-Client. Unfortunately I did not read the instructions about transferring the project here: https://github.com/backdrop-ops/contrib. 

Instead I manually created the new repository using the button at https://github.com/backdrop-contrib and pushed the code up to this. As a result I don't think that the access and team settings are correct for the repository. Please can someone take a look and check them over for me.

I have created a tag for the project and am ready to release it, but wanted to make sure the access settings are correct first.

**Comment by jenlampton** [comment]
Both ways to create projects are correct, you can do whatever you prefer :) I have added the Backdrop teams and all permissions appear to be correct now.

**Comment by roblog** [comment]
Great thanks. I think it is all set up then :-)
