### ISSUE TITLE
Becoming maintainer of commentsblock

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#656]
I believe  commentsblock is abandoned, but I may be wrong. It's not clear if Graham Oliver is a current maintainer, of if he was just the person who ported it from Drupal. I've filed an issue 
- https://github.com/backdrop-contrib/commentsblock/issues/6

and a pr
- https://github.com/backdrop-contrib/commentsblock/pull/7

**Comment by stpaultim** [comment]
@argiepiano - It seems that you have been approved as maintainer, so I think we can close this issue.
