### ISSUE TITLE
Port status: Completed. Views Raw SQL

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#663]
**Name of the module, theme, or layout you are working on**
Views Raw SQL

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/views_raw_sql

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/views_raw_sql/issues/3302667

**Do you need assistance with this port?**
Completed.

**Comment by olafgrabienski** [comment]
Link: https://backdropcms.org/project/views_raw_sql
