### ISSUE TITLE
Free licensing for use of JetBrains PhpStorm

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#67]
I recently applied for a free Open Source License to use PhpStorm for development of contributed modules for Backdrop CMS. This has now been sent to me and I am pleasantly surprised to find that it is valid for any genuine member of the team, I just have to let you have the licence key that JetBrains has sent me.

Is there somewhere I can post the key so that it is accessible for all backdrop-contrib members but not to others?

**Comment by quicksketch** [comment]
> and I am pleasantly surprised to find that it is valid for any genuine member of the team

Wow! That would be great. I'd like to double-check with JetBrains that they'd be okay with sharing this license with all members of the group. I know in the past, licenses for Drupal contrib modules were limited to 2 maintainers per project. But perhaps given our smaller community, JetBrains would not require such limitations. Could you forward the e-mail to info at backdropcms dot org?

**Comment by Graham-72** [comment]
Emails now forwarded.
