### ISSUE TITLE
Contrib Group Application: markabur (port of emptyparagraphkiller)

### ISSUE THREAD

**Issue by markabur** [backdrop-ops/contrib#672]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
Option 1: I would like to contribute a project

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**
Empty paragraph killer

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

https://www.drupal.org/project/emptyparagraphkiller/issues/3312732

**Post a link to your new Backdrop project under your own GitHub account (option 1)**

https://github.com/markabur/emptyparagraphkiller

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by jenlampton** [comment]
Hello @markabur and thank you for your application!

For starters, I'm very sorry that our example files were not available when you needed them. It appears as though [someone deleted those files](https://github.com/backdrop-ops/contrib/issues/657) without consulting anyone, and did not realize that they were important.

I noticed that there is a problem with the README in this project, and I believe that we could have saved some of your time had that resource been available. 

- [ ] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md

Would you please rename the `README.txt` file to `README.md`, and adjust the formatting to match the [markdown example provided](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).  Most importantly, we need a section labeled "Current Maintainers". This file is parsed by backdropcms.org to create the project pages, so using correct markdown syntax is also important. 

Once that is done, we can send you an invitation to join the contrib group!

**Comment by markabur** [comment]
Thanks @jenlampton! I have updated the README:

https://github.com/markabur/emptyparagraphkiller/blob/1.x-1.x/README.md

**Comment by jenlampton** [comment]
Looks beautiful! An invite should be on the way :)

**Comment by markabur** [comment]
Got it, thank you!
