### ISSUE TITLE
Port request: Views Exposed Form Fieldset

### ISSUE THREAD

**Issue by PepeMty** [backdrop-ops/contrib#675]
**Name of the module, theme, or layout**
Views Exposed Form Fieldset

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/views_ef_fieldset

**Comment by robertgarrigos** [comment]
I liked this module and believe I will use it, so made the port: https://github.com/backdrop-contrib/views_ef_fieldset

BTW; I have no permissions to tag this request as ported...

**Comment by olafgrabienski** [comment]
Added the "Port complete" label.

https://backdropcms.org/project/views_ef_fieldset
