### ISSUE TITLE
RUA ported to Backdrop

### ISSUE THREAD

**Issue by bserem** [backdrop-ops/contrib#68]
RUA is one of my simplest modules, but it is very valuable to the greek community.
It uses a JS file to remove accents from uppercase text (which is not allowed in the greek language but no browser understands this...).

Project is here:
https://github.com/bserem/rua (v1.x-3.x)

Since it was dead is to port, I started with it. I hope to have some more modules soon :)

**Comment by quicksketch** [comment]
Great! Same feedback as https://github.com/backdrop-ops/contrib/issues/69. We need the README.md to be updated, otherwise it looks great!

I didn't know you could have a module without a .module file! Interesting. :smile:

**Comment by bserem** [comment]
Should be ready too. I never thought it was possible either, but with Backdrop it turns out you don't necessarily need a .module file.

Now let's get the greek community into Backdrop

**Comment by quicksketch** [comment]
> Now let's get the greek community into Backdrop

:smile: 

Thanks, we definitely need more international involvement in the project. These modules make a good start.

I granted you access in https://github.com/backdrop-ops/contrib/issues/69, so we're good in this issue I think!

**Comment by klonos** [comment]
> Now let's get the greek community into Backdrop

Some of us were here already ...almost since the fork was announced back in September 2013 :stuck_out_tongue_winking_eye:

**Comment by bserem** [comment]
Great! In case you are close to Patras I'm buying the beers!

**Comment by klonos** [comment]
I usually am close to Larisa, but for the past year (and most likely the next 4-5 years) I am close to Melbourne, Australia. So, taking a rain check for those beers.
