### ISSUE TITLE
Maintainer change request: Add klonos to Diff project

### ISSUE THREAD

**Issue by quicksketch** [backdrop-ops/contrib#680]
I'm filing this on behalf of @klonos to get Diff module maintained again. He applied for maintainership over a year ago with no response.

Please note the procedure to add a new maintainer to a project:

1. Please join the Backdrop Contrib group (if you have not already) by
   submitting an application **done**
2. File an issue in the current project's issue queue offering to help maintain
   that project. **done**
3. Create a PR for that project that adds your name to the README.md file in
   the list of maintainers. **done**
4. If the project does not have a listed maintainer, or if a current maintainer
   does not respond within 2 weeks, create *this issue* to take over the project.  **Over 1 year with no response**

**Please include a link to the issue you filed for the project.**
https://github.com/backdrop-contrib/diff/issues/18

**Please include a link to the PR that adds your name to the README.md file.**
https://github.com/backdrop-contrib/diff/pull/22

**Comment by herbdool** [comment]
I've merged the PR since @klonos met all the criteria.
