### ISSUE TITLE
Port status: completed. Registration Confirm Email Address

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/contrib#684]
**Name of the module, theme, or layout you are working on**
Registration Confirm Email Address

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/reg_confirm_email

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/reg_confirm_email/issues/3320891

**Do you need assistance with this port?**
No

**Comment by robertgarrigos** [comment]
First released https://backdropcms.org/project/reg_confirm_email

BTW I cannot add the port completed tag. Is that normal?

**Comment by olafgrabienski** [comment]
> I cannot add the port completed tag. Is that normal?

Not sure about tagging permission. I *am* however able to add tags, so I've added `Port complete`.
