### ISSUE TITLE
PACE ported to Backdrop.

### ISSUE THREAD

**Issue by bserem** [backdrop-ops/contrib#69]
PACE module (https://www.drupal.org/project/pace) has been ported to backdrop:

https://github.com/bserem/pace (v1.x-1.x)

Hope you like it ;)

**Comment by quicksketch** [comment]
Hi @bserem! Thanks for porting this module to Backdrop! We generally have the following requirements for modules in the Backdrop contrib group (which I'm hoping you'll move this module into):

- [x] Include a LICENSE.txt file
- [ ] Include a README.md file that includes license and maintainer info (see [this example](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md))
- [x] Maintains the Drupal 7 project Git history

We're looking good on most fronts, but because of GitHub's loose permissions system, we really need module owners to specify maintainers in the README.md file as the canonical source of who should be able to push to the repository. If you can update the README.md, this looks good to go and we'd love to include it in the Backdrop Contrib Group.

**Comment by bserem** [comment]
It should be ready now :)

**Comment by quicksketch** [comment]
woot woot! You'll be able to move in this project after confirming the Backdrop Contrib Group agreement. Please do the same steps for all future modules you port as well.

Would you agree to this for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by bserem** [comment]
**I hereby accept the project aggrement above this reply.**

I would like to express however that 2 weeks (bullet 9) might be a bit short sometimes of the year.

**Comment by quicksketch** [comment]
> I would like to express however that 2 weeks (bullet 9) might be a bit short sometimes of the year.

Noted, it's just that short based on Drupal's existing paradigm. As with all things, there is "on-paper" and there is reality. :)

Invite sent your way! Thanks for porting your module(s) and I'm looking forward to working to make things together.

**Comment by bserem** [comment]
I'm happy to be on the team, hope I can help
