### ISSUE TITLE
Port status: Resource Conflict 

### ISSUE THREAD

**Issue by slackstone** [backdrop-ops/contrib#691]
**Name of the module, theme, or layout you are working on**
Resource Conflict (resource_conflict)

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/resource_conflict

**Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/resource_conflict/issues/3319580

**Progress to this point**
https://github.com/slackstone/resource_conflict

**Do you need assistance with this port?**
Yes. I need some help converting database variables to a config file. 
I've created a repository, where I've pushed the module code after my first pass through the Code Updater module. There are TODO comments withing the code highlighting the final pieces to get this module ported.   I will try to work through the needed syntax to replace variables, but I could really use a few minutes from someone with a bit more skill. This module is really helpful in creating reservation/booking systems. Any help would be greatly appreciated, thanks!

**Comment by argiepiano** [comment]
@slackstone took a look. This is what I suggest:

- Implement `hook_config_info()` to define configuration files for `resource_conflict`. I suggest something like `resource_conflict.NOTE_TYPE.json`. 
- All the D7 DB variables need to be stored as key/value pairs within each of the configuration files, dependent on node type. So, for example, you would do things like `config_get("resource_conflict.{$node_type}", 'rc_date_field');` to replace all the variable_get and variable_set. 
- You may also need to implement `hook_node_type_insert(){}` to create/initialize the corresponding `resource_conflict` config file for the new node type being created
- And, you probably need to create default config files for the three node types provided by core, `post`, `page` and `card`. Those files should be in the `config` folder of the module, and will be moved to the `files/config` folder when the module is enabled. 

Additionally, I see that the D7 code uses `DateObject`, which doesn't exist in Backdrop. Instead, use `BackdropDateTime`

If you need additional help I could fork your repo and create a PR...

**Comment by argiepiano** [comment]
Additionally, 

- in `resource_conflict.rules_defaults.inc` you should use `entity_plus_import()` instead of `entity_import`. 
- in the info file, create a dependency to entity_plus, not entity (although depending on rules is sufficient)
- The install file removes variables. You can safely remove that code, as the config file will be removed automatically when you uninstall

All the rules info looks fine.

**Comment by argiepiano** [comment]
A few additional details about `hook_config_info()` needed here.

This is a sample implementation:

```php
function resource_conflict_config_info() {
  $prefixes['resource_conflict'] = array(
    'name_key' => 'type',
    'label_key' => 'type',
    'group' => t('Resource conflict'),
  );
}
```

Then, inside of your default config files (e.g. `resource_conflict.page.json`) you'll need to have a key/pair `"type" : "page"` for example.

**Comment by argiepiano** [comment]
There are other quirks. The node type form in D7 automatically saved all the form settings added by resource_conflict as variables. This is not the case with BAckdrop. Those need to be saved manually to the config file. 

I think it's easiest if I provide a PR against your repo - I'll do that tomorrow. The module is pretty straightforward and I am very close to making it work...

**Comment by slackstone** [comment]
Alejandro - thanks so much for taking the time to review and post helpful comments. I really appreciate the energy. This is a great learning experience for me, It'll take me a bit of time to read through and process your comments. A PR would be an amazing help.  If we can get this working, I'll match your energy by doing a write-up and video on how to do Resource Reservations using Backdrop.  For documentation, I'm thinking something similar to this document would be helpful but updated for Backdrop; https://www.drupal.org/node/2090487.

**Comment by argiepiano** [comment]
@slackstone I have a working version, but there are some issues with your fork of the D7 repo: it did not save the commit history. One of the policies of Backdrop ports is that we need to keep the commit history of the D7 module.

I could start a new repo in my own git, and then move that to backdrop-contrib and make you a co-maintainer. Would that work for you? Otherwise I suggest you delete your repo, and start it again following the directions under "Creating the Repository" [in this page](https://docs.backdropcms.org/converting-modules-from-drupal). Once you do that let me know and I'll fork your new repo and send a PR.

**Comment by slackstone** [comment]
Commit histories are extremely important, I love this policy by the way. I pushed this repo real fast, just to start working in a public space. Please, go for it on making a repo in your git, whatever it takes.  That would be a tremendous help. On my side, I need to go through the steps of applying for backdrop-contrib access. Which I'll do today.  @argiepiano Again, I really appreciate your energy, thanks!

**Comment by argiepiano** [comment]
Hi @slackstone. The ported versions is now available on backdrop-contrib: 
https://github.com/backdrop-contrib/resource_conflict

I've done some light testing. Please do more testing before we do a release.

I added you as admin to the project as well.

**Comment by argiepiano** [comment]
If someone could mark this as "port completed" that'd be great!

**Comment by slackstone** [comment]
Big thanks for @argiepiano for helping to push this one over the finish line! Stay tuned, I'll be writing up some additional documentation with a slant on building Room Reservation systems.
