### ISSUE TITLE
Maintainer change request: Markdown Filter

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/contrib#692]
I would like to take over as maintainer for the Markdown Filter module.

[Here is my request in the module issue queue to become a maintainer.](https://github.com/backdrop-contrib/markdown/issues/9) It has aged the required 2-week period (during which it has developed a complex, full-bodied bouquet with hints of chocolate, currants, and green pepper.)

[Here is the PR that updates the README file.](https://github.com/backdrop-contrib/markdown/pull/11)

Please give me admin privileges for the module (and then I will merge the PR, plus the several other outstanding PRs).

Thanks!

**Comment by herbdool** [comment]
Done: https://github.com/backdrop-contrib/markdown/commit/15ccb1a4c454daf5f5866294a142ffed79b656a4
