### ISSUE TITLE
Port request: Simplenews Content Selection

### ISSUE THREAD

**Issue by djzwerg** [backdrop-ops/contrib#698]
**Name of the module, theme, or layout**
Simplenews Content Selection

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/simplenews_content_selection

**Comment by argiepiano** [comment]
Ported version: https://github.com/backdrop-contrib/simplenews_content_selection

@djzwerg, please test. If the testing looks OK I'll do a first release. 

The Backdrop version includes the stuff in D7's `simplenews_content_selection_views` submodule. Backdrop's version combines both modules into one. 

To use, go to Content and then click the tab "Newsletter Creation" to access the View that contains the Operation.

**Comment by argiepiano** [comment]
First release is out.

**Comment by djzwerg** [comment]
Hi @argiepiano thanks! But I'm not able to install this module:
![grafik](https://user-images.githubusercontent.com/49948628/213809209-4dd7b0f2-6b9d-4c57-9d7b-af95feed34aa.png)

**Comment by argiepiano** [comment]
OK, thanks for reporting. I think the problem is that the git repository (simplenews_content_selection) uses a different name from the module itself (scs). 

I'll check on that and will post here when it's fixed.

**Comment by djzwerg** [comment]
The module works but it looks that there is an issue with fieldsets. The legend is shown but the content is missing. Should I open an issue within the module page?

**Comment by argiepiano** [comment]
Yes please.

**Comment by djzwerg** [comment]
I think this issue label could be changed to "port completed". Is it possible to do so @klonos @jenlampton @olafgrabienski ?

**Comment by djzwerg** [comment]
Thanks :-)
