### ISSUE TITLE
I would like to contribute to Backdrop CMS

### ISSUE THREAD

**Issue by Lowell20** [backdrop-ops/contrib#7]
Hello,

I have one small project in a drupal.org sandbox that I will move to my github account with all of the required documentation and settings that you have outlined in the Backdrop Contributed Project Author Agreement.

My intention is to begin porting other simple modules from drupal.org as needed and as my skills increase.

Lowell Johnson

**Comment by quicksketch** [comment]
Hi @Lowell20! Could you provide the link to sandbox project to help us review? We don't an official review process at this time, but we'd still like to help guide contributors in the right direction before we start populating the contrib repository. Thanks!

**Comment by Lowell20** [comment]
https://github.com/Lowell20/profile_picture_plus

I am moving code there now. Ahem, well, 2 functions. Very small module.

**Comment by quicksketch** [comment]
Wow, nice! It looks good to me. The code is clean, APIs leveraged correctly. Thanks for adding in a LICENSE and README.md as well!

Could you post that you agree (for the record) to the contributed module repository guidelines?

---

Backdrop Contributed Project Author Agreement
---------------------------------------------

By publishing a project in the [Backdrop Contributed project group](https://github.com/backdrop-contrib) (Backdrop Contrib for short), you must agree to the following:

1. You will not push changes to a repository for which you are not a maintainer; even though joining the Backdrop Contrib group will grant you technical permission to push to any project within.

1. You must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository.

1. You must include a `README.md` with all projects, including at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information (GPL v2)
  1. A list of the current maintainers for the project

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.
1. You will work with the Backdrop Security Team to address any vulnerabilities in your code if necessary.

1. You will enable the GitHub issue tracker for official communication.

1. If you fail to do any of the above, your access to the Backdrop Contrib group -- including all projects including those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by Lowell20** [comment]
I agree to the contributed module repository guidelines

**Comment by quicksketch** [comment]
Super! Invite sent. Thanks for your contributions you've made already and welcome!!
