### ISSUE TITLE
Localization Server. Port status: Completed (need help testing)

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#705]
**Name of the module, theme, or layout you are working on**
Localization Server

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/l10n_server

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/l10n_server/issues/3351989

**Do you need assistance with this port?**
The port is mostly completed, but I'll appreciate some help testing. This module is needed so that we can run https://localize.backdropcms.org on Backdrop rather than Drupal 7 (as it currently runs).

**Comment by olafgrabienski** [comment]
Thanks for porting this important module, this is great news! I've started to test the module, works quite good at first sight. Will have another look soon.

**Comment by olafgrabienski** [comment]
In the meantime, there is an alpha release of the module, thanks again for the port!

- https://backdropcms.org/project/l10n_server
- https://github.com/backdrop-contrib/l10n_server
