### ISSUE TITLE
Contrib Group Application: ericfoy

### ISSUE THREAD

**Issue by ericfoy** [backdrop-ops/contrib#707]
Hello and welcome to the contrib application process! We're happy to have you :)

* Option 1: I would like to contribute a project

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**

I have a theme. Its name is Modoc, and it's pretty sweet. I think it is, anyway...

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.

Yep. Got that

- [x] Include a LICENSE.txt file.

It's in there.

- [x] N/A If porting a Drupal 7 project, Maintain the Git history from Drupal.

Nope. It's all Backdrop.

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

**Post a link to your new Backdrop project under your own GitHub account (option 1)**

https://github.com/ericfoy/modoc

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**

YES

**Comment by jenlampton** [comment]
Hello @ericfoy and welcome to Backdrop contrib! 
There should be an invitation to join the GitHub group in your inbox. 

I reviewed your theme code and it looks great -- thank you so much for contributing it. 

I noticed that the first commits have the message "Initial port from monochrome" which makes me think that we should be including the commit history from monochrome, so that we don't loose that history. We don't have an official requirement for this, but would you be open to adding the monochrome history here?

**Comment by ericfoy** [comment]
I would not object to that, but I don't know if it would be at all useful, due to the fact that I don't think I forked it from Monochrome. I think I started this repo from scratch, using files that bore little resemblance to those of the Monochrome code base. I started by hacking the Monochrome theme (over a year ago) while not changing its name. Then I changed its name; three times, over the development process, all before it ever went into github. When I started, I had never used git nor github, and just kept all my various versions spread across several websites, spaghetti-style.

Now, I could be wrong on all that. It's possible that the early diffs would actually provide useful info... I just don't know.

I leave the determination to you...

Cheers,
—Eric

**Comment by ericfoy** [comment]
... Actually, now I remember: I'm pretty sure I stuck that note in there on one or more initial commits, mostly because I was learning how git works, and I didn't have a clue just what those notes meant, or where they would be read or useful. (Using github-desktop), the program required me to enter something. At that time "Monochrome" was an ID that I could track, but it was already a long way from the actual Monochrome code.

**Comment by ericfoy** [comment]
Okay, now here's a thing...

I have successfully transferred my repository "modoc" to backdrop-contrib. However, during the transfer process the system never showed me the 'Team Access' screen described in 

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

Thus I was not able to "Tick 'Authors' and 'Security' and 'Bug Squad' then click 'Transfer'," as suggested. I think this might be why there is no settings button shown to me when I visit the repository in backdrop-contrib/modoc. I am therefore unable to 

ii. [Visit the repository's new page], and go to 'Settings'.
iii. Click 'Collaborators & teams' in the left menu.
iv. Under 'Teams', set 'Authors' to Triage, 'Security' to Admin and 'Bug Squad' to Write.

Can someone fix this for me, or let me know what I can do about it? Is this even a problem? Please advise.

Thanks!

**Comment by ericfoy** [comment]
Okay... I'm  G R A D U A L L Y  getting the hang of this whole system... So FYI: I have posted the above comment as a new issue in backdrop-ops, in order to capture a larger audience. Was this the right thing to do? I hope I'm being well-behaved...

**Comment by oadaeh** [comment]
Those Teams access settings are already set as described. Maybe someone already did it.

**Comment by ericfoy** [comment]
Yes. @klonos handled it for me!

Thanks.

**Comment by jenlampton** [comment]
We should really update the documentation, as that step throws everyone off
these days. Thank you @klonos for cleaning up the permissions!

@ericfoy if the code was ever monochrome I think it would be nice to have
the history (even if by the time you first committed, it was entirely
different). That said, it may be very difficult, and thus not worth the
effort. Let me run a quick test and I'll open an issue in the peoject queue
if it seems feasible :)

**Comment by jenlampton** [comment]
I'm going to close this issue since @ericfoy is a part of the contrib group now, but I will open an issue in the [modoc](https://github.com/backdrop-contrib/modoc) queue about the `monochrome` git history since that's not urgent :)
