### ISSUE TITLE
Port status: Completed. Field Readonly

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#709]
**Name of the module, theme, or layout you are working on**
Field Readonly

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/field_readonly

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/field_readonly/issues/3354662

**Do you need assistance with this port?**
Port completed.

**Comment by olafgrabienski** [comment]
Tnanks for the port! (Closing the issue.)
