### ISSUE TITLE
Port Complete: Other View Filter

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/contrib#711]
**Name of the module, theme, or layout you are working on**
Other View Filter

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/other_view_filter

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/other_view_filter/issues/3356256

**Do you need assistance with this port?**
No

**Comment by yorkshire-pudding** [comment]
See https://backdropcms.org/project/other_view_filter and https://github.com/backdrop-contrib/other_view_filter

**Comment by olafgrabienski** [comment]
Thank you for porting the module!
