### ISSUE TITLE
Contrib Group Application: @saschaeggi

### ISSUE THREAD

**Issue by saschaeggi** [backdrop-ops/contrib#718]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project 
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

Option 1.

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**

[Gin Admin Theme](https://github.com/backdrop-contrib/gin)

## (option 1) Please note these 3 requirements for new contrib projects:

- [X] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [X] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [X] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**

Not needed as Gin is only available for Drupal 8, 9 & 10. But it’s being ported over to Backdrop now 🎉 

**Post a link to your new Backdrop project under your own GitHub account (option 1)**

It’s already in the contrib space: https://github.com/backdrop-contrib/gin

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
https://github.com/backdrop/backdrop/pulls?q=is%3Apr+author%3Ahimanshu007-creator+is%

I’m a Drupal Core maintainer (Claro, Drupal Design System) and the creator of the Gin Admin Theme.
Contribution towards the Gin fork for Backdrop: 

**(option 3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**

YES

**If you have chosen option 3 above, do you agree to undergo this same maintainer application process again, should you decide to contribute code in the future?**

–

**Comment by klonos** [comment]
Hello @saschaeggi 👋🏼 ...really awesome to see you in our community!

Based on discussions with @laryn over Zulip and also https://github.com/backdrop-contrib/gin/issues/26 + the fact that you are the maintainer of the Drupal version of the theme, and the fact that you have agreed to our [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement), I am approving this request.

cc'ing @jenlampton and @stpaultim for visibility ^^

**Comment by saschaeggi** [comment]
@klonos I accepted the invite, thanks a lot 🙌

**Comment by jenlampton** [comment]
Welcome!
