### ISSUE TITLE
Request to contribute

### ISSUE THREAD

**Issue by jromine** [backdrop-ops/contrib#72]
Hi, I would like to contribute to Backdrop CMS.  

I'm working on Reference module backport from Drupal https://github.com/jromine/references

**Comment by quicksketch** [comment]
Hi @jromine! Awesome! That's a very important module to get ported. We require 3 things on initial ports:

- [x] Update the README.md to include a list of maintainers and license info
- [x] Include a LICENSE.txt file
- [x] Maintain the Drupal 7 history of the project

You got all 3 right off the bat. Nice! There is still some work to be done on the module I see, like there are a lot of "drupal_*" functions in the code still, so it requires the backwards-compatibility mode. That's fine for the initial port and it will work for most sites.

Anyway, all that comes in time. This is great and we'd love to see it in the contrib group. Would you agree to this for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by jromine** [comment]
Yes, the code has basic functionality now, but still needs more work.

I agree to the Backdrop Contributed Project Agreement terms.

**Comment by quicksketch** [comment]
Thanks! SO EXCITED to have you contributing! I've sent you the invite.

You can now transfer your project to the 'backdrop-contrib' organization. Make sure you check the "Authors" box when you transfer, otherwise you won't be able to modify it after it's transferred! I don't know why GitHub even makes that an option. See David Rothstein's post for more info: http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2

**Comment by jromine** [comment]
The https://github.com/backdrop-contrib/references project has been transferred.

**Comment by quicksketch** [comment]
Thanks @jromine!
