### ISSUE TITLE
Port COMPLETE: Enforce revlog (renamed to Enforce Revision Logs)

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/contrib#722]
**Name of the module, theme, or layout you are working on**
Enforce revlog
now called:
Enforce Revision Logs

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/enforce_revlog

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/enforce_revlog/issues/3378703

**Do you need assistance with this port?**
No - it is complete

See:
https://backdropcms.org/project/enforce_revlog
https://github.com/backdrop-contrib/enforce_revlog

**Comment by olafgrabienski** [comment]
Thank you for porting this module!
