### ISSUE TITLE
Cannot access new module port content_lock

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/contrib#724]
Just created a new port, handed the repository to backdrop-contrib and, for some reason, I have no access to it:

1. could someone give me access to https://github.com/backdrop-contrib/content_lock ??
2. is there something wrong I'm doing when changing ownership of the repository?
Thanks!

**Comment by herbdool** [comment]
I'm not sure. I've updated your permissions. I can't recall how it worked before but I noticed I had to change the permissions on the repos I recently created too. I've got admin role for contrib so I didn't notice at first. @jenlampton @klonos are permissions supposed to be added automatically?

**Comment by jenlampton** [comment]
@herbdool We have an issue in the b.org queue to add permissions automatically using the GitHub API. Right now, I add them manually every time I get an email that a new repository is transferred in. 

Sorry @robertgarrigos  that I didn't respond quickly - I was traveling over the weekend.

**Comment by robertgarrigos** [comment]
Thanks, @jenlampton and @herbdool.

Just to let you know, what I did to keep all permissions for a new tiny module is forking my personal repo to backdrop-contrib, then delete my personal repo and fork back from backdrop-contrib. This way, all permissions on the backdrop-contrib repo are kept. I hope don't have to bother you any more.
