### ISSUE TITLE
Port complete: Agreement

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#725]
**Name of the module, theme, or layout you are working on**
Agreement

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/agreement

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/agreement/issues/3383022

**Do you need assistance with this port?**
Port is complete:
https://github.com/backdrop-contrib/agreement

**Comment by olafgrabienski** [comment]
Thanks for porting this module!
