### ISSUE TITLE
How best to remove old release tags

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#73]
Is there a quick way of removing the releases inherited when one copies a repo from Drupal? I have one with 64 releases and it is going to be rather a chore to remove them one by one!

**Comment by quicksketch** [comment]
Something like this would do the trick: https://gist.github.com/okunishinishi/9424779

**Comment by Graham-72** [comment]
Sadly his proposal will not work for me, perhaps because I am working from a Windows PC? So I am looking out for something else, but it's not a priority just at the moment.

**Comment by Graham-72** [comment]
I have found out how to do this using Git Bash on my PC, and have added a comment to https://gist.github.com/okunishinishi/9424779

**Comment by quicksketch** [comment]
Excellent, nice one @Graham-72
