### ISSUE TITLE
Contrib Group Application: Eric Aitala + name module

### ISSUE THREAD

**Issue by aitala** [backdrop-ops/contrib#738]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project

## Based on your selection above, please provide the following information:

Name Field

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/name/issues/3357173

**Post a link to your new Backdrop project under your own GitHub account (option 1)**
https://github.com/aitala/name

##Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by herbdool** [comment]
@aitala the module is looking pretty good. I did some spot checks and looks like a most things are in order. Nothing that would block becoming an official maintainer.

Some small things:

- You have the example names in the config file. Do they need to be there? They're also in https://github.com/aitala/name/blob/8641680857da2f492d97418bca3818aae149c6cb/name.admin.inc#L186.
- I recommend moving `name.tests.info` to the tests folder and update paths in it. Take a look at how core does it. Do the tests even run like that?

That's all I've got from my spot checks.

**Comment by jenlampton** [comment]
As @herbdool  mentioned you've met the requirements for contributed projects - so an invitation is on the way! :tada 

##Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (you can ask here if you have questions).

**Comment by aitala** [comment]
@jenlampton Could you resend the invite to join the @backdrop-contrib organization?

I got pulled into something else and didn't get back to the invite in time.

Thanks.

**Comment by klonos** [comment]
@aitala sorry we missed your previous comment here. I see you already in the contrib group and no pending/failed invitations. Do you still need help with this request, or can we close the issue?

**Comment by aitala** [comment]
You can close it
