### ISSUE TITLE
Port complete: Colectomy

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/contrib#739]
**Name of the module, theme, or layout you are working on**
Colectomy

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/colectomy

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/colectomy/issues/3410232

**Do you need assistance with this port?**
No - Complete unless someone can be bothered to fix the tests.

**Comment by olafgrabienski** [comment]
Sounds very useful! Link to the Backdrop version: https://backdropcms.org/project/colectomy
