### ISSUE TITLE
Contrib Group Membership

### ISSUE THREAD

**Issue by hgutknecht** [backdrop-ops/contrib#74]
I received a request to co-maintain the Custom Meta module https://github.com/backdrop-contrib/custom_meta that @sirkitree ported to Backdrop

https://github.com/backdrop-contrib/custom_meta/issues/2

I'd be happy to help port, fix other ports as well

**Comment by sirkitree** [comment]
:+1: w00t!

**Comment by quicksketch** [comment]
Hi @hgutknecht! Awesome!

For a co-maintainer like this, we just grant access right away (after the agreement). But in the future if you submit a new module, you need to have that module go through a basic review to spot-check it for consistency.

So for the time being, all we need is for you to agree to the contrib group conditions. Would you accept the following for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by hgutknecht** [comment]
@quicksketch I agree

**Comment by quicksketch** [comment]
Excellent! I've sent an organization invite your way. You or @sirkitree should add your name to the list of maintainers for https://github.com/backdrop-contrib/custom_meta.

Thanks so much for reaching out @hgutknecht! I'm always especially thrilled to see original module authors collaborating with Backdrop. I'm looking forward to working together to make great things. Let me know if you have any issues with access. Cheers!
