### ISSUE TITLE
Contrib Group Application: Eli Lisseck + Views Block Area

### ISSUE THREAD

**Issue by elisseck** [backdrop-ops/contrib#745]
Hello! We (Giant Rabbit) will be porting several modules to Backdrop this year and would like to contribute them back as we go, starting with this one. I have responded based on the application template below:

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project

## Based on your selection above, please provide the following information:

Module w/link to our github repo: [Views Block Area](https://github.com/giant-rabbit/views_block_area)
D.O. notification: [https://www.drupal.org/project/views_block_area/issues/3417056](https://www.drupal.org/project/views_block_area/issues/3417056)

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

I believe the three new project requirements have been met, but let me know if I've missed anything here. Thanks for your time!

**Comment by klonos** [comment]
Hello @elisseck sorry for the delay here and thank you for offering to contribute to the Backdrop community. I'll take a look at this and get back to you shortly...

**Comment by klonos** [comment]
Things check out 👍🏼 :
- [x] Maintain the Git history from Drupal 7 : https://github.com/giant-rabbit/views_block_area/commits/main (although I'd rename the branch to 1.x, but that can be done after the project is transferred to the Backdrop contrib repo too)
- [x] Include a README.md file that includes license and maintainer information (although can you please add the rest of the maintainers listed in the d.org project?: https://www.drupal.org/project/views_block_area).
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

Finally, can I please get you to state that you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)?

**Comment by klonos** [comment]
...if you reply here and we happen to not be responsive after a few days, then please ping us over at our official chat in Zulip: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Contrib.20Application

**Comment by elisseck** [comment]
Hi @klonos,

Yes, I agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement

Thanks for your notes, I have changed the branch name and added the rest of the listed maintainers in [this commit](https://github.com/giant-rabbit/views_block_area/commit/6bf885a433fc055c513792088b210b6c775c7762)

**Comment by jenlampton** [comment]
Welcome @elisseck !!  

I've sent you an invite to the contrib group, once you accept you should be able to transfer your project into backdrop-contrib! We're happy to have you :) 

Feel free to [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) into the backdrop-contrib group at any time (ask here if you have questions).

@klonos the contributor agreement question has been included in the issue template, so you can look for that now in the original issue :) 

> If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)
> YES

**Comment by herbdool** [comment]
Hi @elisseck! Do you feel like being a co-maintainer on https://github.com/backdrop-contrib/civicrm_afform_block as well?

**Comment by herbdool** [comment]
One change iI suggest: adding you'rer name @elisseck, and any coworkers, as maintainers, with the company name at the end. This allows people send you direct messages in GitHub, including other maintainers.

**Comment by elisseck** [comment]
@herbdool Thanks for the comments! I'm happy to help with maintenance of the civicrm_afform_block module. I've just realized the drupal version also needs some attention and i'm not sure why that wasn't sending me emails, so i'll be looking at that one as well.

**Comment by elisseck** [comment]
https://github.com/backdrop-contrib/views_block_area should be all transferred and set! Let me know if you need anything else from me to close this issue.

**Comment by herbdool** [comment]
@elisseck thanks! I've added you as maintainer to the other module.

I think we can close this one now. Looks like you met the requirements.
