### ISSUE TITLE
Contrib Group Application: new theme

### ISSUE THREAD

**Issue by ininfoveritas** [backdrop-ops/contrib#746]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project : Theme

## Based on your selection above, please provide the following information:

**(option 1) The name of your theme**
Theme name : IIV

https://github.com/ininfoveritas/iiv

**Comment by jenlampton** [comment]
Welcome @ininfoveritas and thanks for offering to contribute your theme!  

Your theme does meet these 3 minimum requirements:

- [x] N/A Maintain the Git history from Drupal 7. 
- [x] Include a README.md file that includes license and maintainer information.
- [x] Include a LICENSE.txt file that indicates the contributed code is GPL-2.0

We also need you to agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement) by stating YES in your next comment :)

**Comment by jenlampton** [comment]
I've also done a quick code review of your theme, and it looks great! I only have two minor recommendations (and you can safely ignore these if you'd like, it is not a requirement to make any of these changes.)

1) In the comment template file, the code comment still indicates that it belongs to Bartik `Bartik's theme implementation for comments.`
2) There is some commented out code in the template.php file, I'd recommend removing this code if it's not in use, or uncommenting before the first official release.

That's it! everything else looks great!

**Comment by ininfoveritas** [comment]
YES

**Comment by jenlampton** [comment]
Thank you! Please check your inbox as **an invitation to join the Backdrop Contrib group is on the way!** Feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

**Comment by ininfoveritas** [comment]
Thank you very much. I am very happy to be able to work with you

**Comment by jenlampton** [comment]
I see the theme has been transferred, I'm going to close this issue as complete 🎉
