### ISSUE TITLE
Port request: Ubercart Affiliate v2

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/contrib#750]
**Name of the module, theme, or layout you are working on**
Ubercart Affiliate v2 (completed)

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/uc_affiliate2

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/uc_affiliate2/issues/3294960#comment-15437029

**Do you need assistance with this port?**
This port is completed.

**Comment by argiepiano** [comment]
I don't have enough privileges to change this to "completed".

**Comment by olafgrabienski** [comment]
I've changed the label to "Port complete" (and removed the port status from the title).

Link to the module: https://github.com/backdrop-contrib/uc_affiliate2
