### ISSUE TITLE
Contrib Group Application: Anthony Nemirovsky (@anemirovsky)

### ISSUE THREAD

**Issue by anemirovsky** [backdrop-ops/contrib#752]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
Option 2: I would like to maintain a project, but have nothing to contribute at this time

## Based on your selection above, please provide the following information:

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
I am part of the team at Giant Rabbit currently porting Drupal 7 modules to Backdrop. @elisseck is handling some of the porting and contribution back to Backdrop and I'm doing internal code reviews in our private repositories before we contribute code back. So far, these are the modules we've contributed, with more on the way: 

- https://github.com/backdrop-contrib/termstatus
- https://github.com/backdrop-contrib/views_filters_populate
- https://github.com/backdrop-contrib/views_block_area

**(option 3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**
@elisseck

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by elisseck** [comment]
Confirmed I recommend @anemirovsky! Please let me know if there is anything else I need to do here.

**Comment by stpaultim** [comment]
Someone should officially reply to this within a day or two.

**Comment by jenlampton** [comment]
Welcome to the team @anemirovsky :) I have sent you an invite to join the contrib group 🎉 

As an "author" you will have permission to triage any issue in any queue for any project. If you would like to contribute directly to any of the GR projects, you should request co-maintainership from @elisseck to get your name added to the README.md file, and so he can grant you more access. We're so happy to have your code-review skills here either way!

**Comment by anemirovsky** [comment]
Thank you!
