### ISSUE TITLE
Port request: Facets Pretty Path

### ISSUE THREAD

**Issue by samgreco** [backdrop-ops/contrib#753]
**Facets Pretty Path**

**[Link to the the Drupal version of Facets Pretty Paths](https://www.drupal.org/project/facets_pretty_paths)**

Would really love to have this module.  I have an Ubercart store with 200o+ products using Search API and Facets as the catalog.  I wanted to be able to link the Brands vocabulary/terms to those search pages so our brands pages would take the user back to the catalog, filtered by the selected brand.  I did this in Drupal 7 using the Facets Pretty Paths.

**Comment by nattywebdev** [comment]
I would like to see this too - my current path for product search looks as bad as Amazon's, for example:
/list-products?f%5B0%5D=taxonomy_catalog%253Aname%3Abooks

This looks like a percent encoding of
/list-products?f[0]=taxonomy_catalog%253Aname:books

when it would be wonderful to have:
/list-products?catalog=books

**Comment by samgreco** [comment]
Actually, we paid someone to migrate this module.  I does work, but we really need Entity Paths as well to make it work fully.  I have not found anyone to migrate that one yet without open-ended time/charges.  I am trying to find someone to migrate that one with a "do not exceed" amount, so we don't end up paying a fortune on a never ending project.

I haven't shared that module, nor the other 3 we did because we can't support them.  But if someone wanted to maintain them, I would certainly "donate" them.

We did:
Facets API Pretty Paths
Search Autocompete
Search Live Results
Ubercart Disable Product/Call for Price

Unfortunately, Facets Pretty Paths is not completely helpful  without Entity Paths.

**Comment by laryn** [comment]
> I haven't shared that module, nor the other 3 we did because we can't support them. But if someone wanted to maintain them, I would certainly "donate" them.

I believe you can move these into contrib without maintainers, and indicate they are looking for maintainers.

**Comment by samgreco** [comment]
I look into that.  I would love to see these getting used and improved.  I still think Ubercart with Search API and Facets is a pretty powerful setup.

**Comment by nattywebdev** [comment]
I agree with that and would be most grateful to see these modules made available. Thank you @samgreco !

**Comment by nattywebdev** [comment]
Any progress on this @samgreco ? Anything I can do to help?

**Comment by samgreco** [comment]
Sorry, no.  My real life has been quite hectic.  And I have never done anything on Github other than the issue queues.  So no idea where to start when I do have a moment.

**Comment by nattywebdev** [comment]
Maybe @laryn could advise? I'm a novice in that regard too so not much help, I'm afraid.

**Comment by samgreco** [comment]
I won't be able to answer until later.  At work now and will need to get into my test sites when I have some time to give you examples.  Hang in there...

**Comment by nattywebdev** [comment]
Great - thank you for replying @samgreco

**Comment by rudy880719** [comment]
@samgreco Do you still need help migrating the module? specifically which module it is?

**Comment by samgreco** [comment]
Actually, what I need now is the [Entity Paths](https://www.drupal.org/project/entity_path) module.

**Comment by samgreco** [comment]
Sorry I haven't followed up on this.  Life has been hectic.  Turns out, I don't need Entity Paths at all.  Just good URL paths in my taxonomy and views pages.  @nattywebdev If you want to see how this formats now, check out https://audiosupply.com/products
That should give you an idea.  It's not perfect, but it is pretty good.  Then look at the brands page.  Since I got the taxonomy stuff formatted correctly, I was able to set that page up to go back to the products pages, filtered by the Brands facet.

I'd love to upload these modules, but don't have a Github developers account really setup.  I only created this account so I could post issues and follow stuff.  Don't have the first clue how to proceed with this.  I also had the Search API Auto Complete and Live Results modules done, as well as the Ubercart Disable Product which allows the add-to-cart form to be disabled and a Call for Price button option.

**Comment by samgreco** [comment]
Also, I would be fine with sending these files to someone that could upload, etc.

**Comment by nattywebdev** [comment]
Thanks for that @samgreco - nice to see it in action. As I wasn't able to get a fix for the urls using facets I went with a Views solution. It had other benefits so I'm fairly happy with the result. Still would like to see Facets Pretty Path in Backdrop though - I will likely need it in future.
I'm not particularly skilled in github either so am not volunteering to take this forward. Maybe @laryn might?

**Comment by herbdool** [comment]
Ported: https://github.com/backdrop-contrib/facetapi_pretty_paths
