### ISSUE TITLE
Port of Date

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#76]
I have made a port of Date available at backdrop-contrib/date. It should be possible to install and test it, and I would be grateful for any reports of issues.

**Comment by quicksketch** [comment]
Awesome! I'll probably need this module on a site in the near future. Looking forward to trying it out. :smile:

**Comment by Graham-72** [comment]
It looks as though I need to sort out an Ajax-related issue - it may take a day or so to get my head around this!

**Comment by Graham-72** [comment]
Well, it doesn't seem to be related to Ajax, but rather to hook_field_schema() which isn't allowing for a field of type 'datetime', but the port of Date will accept ISO and Unix dates, which are stored in fields of type 'varchar' and 'integer' respectively. I'm still searching for a solution.

**Comment by jromine** [comment]
datetime column type was removed from Drupal 7. See https://www.drupal.org/node/866340

**Comment by quicksketch** [comment]
Thanks @jromine! It looks like Date module has been hacking around this limitation in core for the entire D7 cycle (which I had not realized). I made a dedicate core issue to restore support for date, time, and datetime column types at https://github.com/backdrop/backdrop-issues/issues/838. Backdrop *only* supports MySQL, so the justification for removing support in Drupal 7 do not stand for Backdrop.

**Comment by jromine** [comment]
@quicksketch that sounds like a good plan. I've had to work-around this in Drupal myself.

**Comment by jdanthinne** [comment]
PR for this here: https://github.com/backdrop/backdrop/pull/805

**Comment by klonos** [comment]
If there's any reason to keep this issue open, then please feel free to re-open. Otherwise lets move to https://github.com/backdrop-contrib/date/issues

**Comment by klonos** [comment]
If there's any reason to keep this issue open, then please feel free to re-open. Otherwise lets move to https://github.com/backdrop-contrib/date/issues
