### ISSUE TITLE
Contrib Group Application: Anna Heath (@aheathgr)

### ISSUE THREAD

**Issue by aheathgr** [backdrop-ops/contrib#773]
Hi, and thank you for all your incredible work!

**Please indicate how you intend to help the Backdrop community by joining this group**
Options 2 and 3!

## Based on your selection above, please provide the following information:

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
I am part of the team at Giant Rabbit currently porting Drupal 7 modules to Backdrop. @elisseck is handling some of the porting and contribution back to Backdrop and @anemirovsky is doing internal code reviews in our private repositories before we contribute code back. So far, these are the modules we've contributed, with more on the way:

https://github.com/backdrop-contrib/termstatus
https://github.com/backdrop-contrib/views_filters_populate
https://github.com/backdrop-contrib/views_block_area

**(option 3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**
@elisseck

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**Comment by elisseck** [comment]
Confirmed I recommend @aheathgr! Please let me know if there is anything else I need to do here.

**Comment by jenlampton** [comment]
Hello @aheathgr and welcome! Thanks to the recommendation rom @elisseck I have sent you an invite, please check your inbox. 

As an "author" you will have permission to triage any issue in any queue for any project. If you would like to contribute directly to any of the GR projects, you should request co-maintainership for that project to get your name added to the `README.md` file before making any direct commits. 

Thank you so much for your previous contributions, and we look forward seeing you in the contrib queues :)

**Comment by aheathgr** [comment]
Woo hoo! Thank you, @jenlampton!

**Comment by jenlampton** [comment]
I'm closing this issue but if you have any questions feel free to open a new one, ask in the forum, or ask in live chat.
