### ISSUE TITLE
Maintainer change request: Auto Logout

### ISSUE THREAD

**Issue by herbdool** [backdrop-ops/contrib#786]
I've just created a request in the project yesterday, so still need to wait for a response by June 12th.

**Please include a link to the issue you filed for the project.**
https://github.com/backdrop-contrib/autologout/issues/18

**Please include a link to the PR that adds your name to the README.md file.**
https://github.com/backdrop-contrib/autologout/pull/29

**Comment by herbdool** [comment]
@klonos @jenlampton I could use a second admin to confirm that I've met the criteria for being added as a maintainer for this module.

**Comment by jenlampton** [comment]
Yes, two weeks and no reply means that you can be added as co-maintainer :) thank you for helping with this project :)
