### ISSUE TITLE
Static class map documentation

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#79]
I have tried looking for more information on hook_autoload_info and,at the moment, the most helpful piece is in the Change Records article 'The class registry has been replaced with a static class map' which has got me thus far.

But now I am trying to create a view that needs a Contextual Filter and this produces an error because it needs to find the class 'views_handler_argument_node_created_year_month' which is not in 'views' but is in core module 'node'. Can I add this to hook_autoload_info in core/modules/views/view.module ?

I will carry on searching for something that will give me the answer, maybe hook_autoload_info for one of the other modules will give me an example to follow.

**Comment by Graham-72** [comment]
I could not find any other examples and resorted to an intelligent (?) guess. Adding this to views/views.module's views.autoload.info works

'views_handler_argument_node_created_year_month' => '../node/views/views_handler_argument_dates_various.inc',

There are no doubt several other classes to add.

**Comment by quicksketch** [comment]
The lack of documentation is a bug in core, there's an issue for it at https://github.com/backdrop/backdrop-issues/issues/712.

This missing class should be added to `node_autoload_info()`: https://api.backdropcms.org/api/backdrop/core!modules!node!node.module/function/node_autoload_info/1

Could you file an issue for this in the Backdrop core issue queue? https://github.com/backdrop/backdrop-issues/issues

**Comment by Graham-72** [comment]
Added as backdrop/backdrop-issues#824

**Comment by quicksketch** [comment]
Thanks @Graham-72!
