### ISSUE TITLE
Contrib Group Application: drybro 

### ISSUE THREAD

**Issue by drybro** [backdrop-ops/contrib#791]
I would like to become a maintainer for the adaptive_image module. I have recently sent a push request that fixes a 500 internal server error. The maintainer of this module has been inactive for 8 years so it is unlikely this request will be applied.
https://github.com/backdrop-contrib/adaptive_image

**Comment by jenlampton** [comment]
Hi @drybro and welcome to Backdrop contrib!  We have an application for joining the group, so I'll copy the questions from that below, and we can help get you through this process :) 

> **Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

It sounds like you are Option 2, wanting to take-over as maintainer of an existing project. 

> **(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**

I found your existing PR for adaptive_image: https://github.com/backdrop-contrib/adaptive_image/pull/7 so I expect that's the link you would like to provide. If you have others, feel free to add some of them (we do not need more than 3).

> **If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**

(we will need a yes or no from you on this)


And unrelated to this issue but as part of your quest to maintain adaptive_image, you will also want to:
- [x] File an issue in the current project's issue queue [offering to help maintain that project](https://github.com/backdrop-contrib/adaptive_image/issues/8). (I see you have already done this ✅ )
- [ ] Create a PR for that project that adds your name to the `README.md` file in the list of maintainers.
- [ ]  And then, once the above PR has been up for 2 weeks, open another issue to [take over as maintainer](https://github.com/backdrop-ops/contrib/issues/new?assignees=&labels=Maintainer+change+request&projects=&template=maintainer-change.md&title=Maintainer+change+request%3A).

**Comment by drybro** [comment]
Option 2 to maintain a project is what I'm applying for except that I do currently have something to contribute to a specific project.
I agree to the terms as listed at [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

**Comment by jenlampton** [comment]
> Option 2 to maintain a project is what I'm applying for except that I do currently have something to contribute to a specific project.

@drybro  if you also have another project you would like to transfer into the contrib group, please provide a link to your personal repository here, and we can switch you to Option 1. But if your "something to contribute" is the PR linked above, we can continue with Option 2 :) 

> I agree to the terms

Great! Please check your inbox, an invitation to join the contrib group is on the way :)

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have any questions feel free to re-open this one or a open a new one.
