### ISSUE TITLE
Port of Libraries

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#80]
I am working on a port of Libraries with the initial aim of getting Views Slideshow ported to Backdrop

**Comment by docwilmot** [comment]
See https://github.com/backdrop/backdrop-issues/issues/159. 
I think the plan is to have something like libraries in core. I re raised the issue but don't have the technical skill to build that, so waiting.

**Comment by Graham-72** [comment]
Thanks @docwilmot for pointing out that discussion. I look forward to having the facilities we need in core. In the mean time, I want to try and get Views Slideshow ported, but I am a bit stuck on that at the moment - backdrop-ops/contrib/issues/81

**Comment by Graham-72** [comment]
Libraries would now seem to work and I have moved the repository to backdrop-contrib/libraries
