### ISSUE TITLE
Port of Views Slideshow

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#81]
I am working on a port of Views Slideshow.

At the moment I have a problem in that it is giving an error report "Class 'views_plugin_style' not found" and yet this is provided by Views in core and listed there in function views_autoload_info()

**Comment by Graham-72** [comment]
My port of Views is now working after a lot of searching for problems. The final one was that it was using hook_library and this needed to be hook_library_info. Perhaps this needs to be mentioned in Backdrop's Change Records?

**Comment by Graham-72** [comment]
Views Slideshow would now seem to work and I have moved the repository to backdrop-contrib/views_slideshow

**Comment by docwilmot** [comment]
Good work. You need to replace all instances of `print $classes` in all the slideshow template files with `print print implode(' ', $classes)`. I get a bunch of errors if I attempt to show text controls on slideshows. See the change records re removal of the process layer.
Also, the slideshow controls dont work.

**Comment by Graham-72** [comment]
Thanks. I confess that at the moment that document (Removed the theme process layer) is a lot like a foreign language to me! But I shall persevere. Did you reall mean 'print print implode(' ', $classes)' with two prints?

**Comment by docwilmot** [comment]
Nope, one print. Sorry.

**Comment by Graham-72** [comment]
That's a relief :smiley: No worries!

**Comment by Graham-72** [comment]
I have now got the slideshow controls working on my trial site and will push an edit to the repository soon.

**Comment by jenlampton** [comment]
Closing this issue since https://github.com/backdrop-contrib/views_slideshow exists now.  Please continue all discussion about views_slideshow in the queue for that module.
