### ISSUE TITLE
Contrib Group Application: bennybobw

### ISSUE THREAD

**Issue by bennybobw** [backdrop-ops/contrib#811]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

Option 2

## Based on your selection above, please provide the following information:

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
https://github.com/backdrop-contrib/title/pull/16

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

Re: references
@elisseck works at Giant Rabbit with me along with @wesruv

**Comment by bennybobw** [comment]
Oh, I didn't write this, I'd like to co-maintain the title module, see 
https://github.com/backdrop-contrib/title/issues/15

**Comment by herbdool** [comment]
This looks ok to me.

**Comment by elisseck** [comment]
Confirm I can vouch for @bennybobw - Please let me know if there is anything else I need to do here!

**Comment by jenlampton** [comment]
@bennybobw Please check your email, an invite should have arrived from GitHub 🎉 

@elisseck thank you for the vouch, and @herbdool thanks for the review and the ping.

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have any questions feel free to re-open this one or a open a new one.

**Comment by bennybobw** [comment]
Thank you, I got the email. I think we're good! I will start merging some commits.
