### ISSUE TITLE
Contrib Group Application: sudipto68

### ISSUE THREAD

**Issue by sudipto68** [backdrop-ops/contrib#816]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**

* Option 2: I would like to maintain a project, but have nothing to contribute at this time

I helped port several modules currently being maintained by Tim Erickson (@stpaultim)

* UC Variable Price
* Domain
* Opera

## Based on your selection above, please provide the following information:

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**
https://github.com/backdrop-contrib/domain/commit/a2366234c6f689fb469f780b800255ddca51dfb5
https://github.com/backdrop-contrib/uc_varprice/pull/3
https://github.com/backdrop-contrib/opera/pull/26

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**

YES

**Comment by stpaultim** [comment]
@sudipto68 and @bdalomgir both work on the Triplo team and have extensive background with BackdropCMS. 
https://github.com/backdrop-ops/contrib/issues/815

They are both applying to the contrib group so that they can become official co-maintainers of projects that they already ported themselves and I maintain or projects that I've created/maintain.

**Comment by jenlampton** [comment]
Welcome @sudipto68! Please check your inbox for an invite to join the contrib group. Once you accept, you will be able to triage all issues in all queues, and any maintainer will be able to add you to co-maintain their projects. You can open issues in the queues, and create PRs to add your name to the README. Looking forward your assistance.

Thank you @stpaultim  for the recommendation.

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have any questions feel free to re-open this one or a open a new one.
