### ISSUE TITLE
Maintainer change request: node_clone

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/contrib#820]
**Please include a link to the issue you filed for the project.**
https://github.com/backdrop-contrib/node_clone/issues/16

**Please include a link to the PR that adds your name to the README.md file.**
https://github.com/backdrop-contrib/node_clone/pull/17

**Comment by robertgarrigos** [comment]
Is there anything else I need to do to have this maintenance transferred?

**Comment by stpaultim** [comment]
This seems to have been fixed!

Thanks @robertgarrigos for taking care of the node clone module. I use it on several sites.
