### ISSUE TITLE
Contrib Group Application: sjnorton-aa + Textile module

### ISSUE THREAD

**Issue by sjnorton-aa** [backdrop-ops/contrib#821]
Hello and welcome to the contrib application process! We're happy to have you :)

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project
* Option 2: I would like to maintain a project, but have nothing to contribute at this time
* Option 3: I would like to update documentation and/or triage issue queues

For now, Option 1, though I might be able to help with the others at some point.

See my previous posting here: https://github.com/backdrop-ops/contrib/issues/812

## Based on your selection above, please provide the following information:

**(option 1) The name of your module, theme, or layout**
Textile (a markup text filter for input formats)

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
- [x] Include a LICENSE.txt file.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

**(option 1 -- optional) Post a link here to an issue in the drupal.org queue notifying the Drupal 7 maintainers that you are working on a Backdrop port of their project**
https://www.drupal.org/project/textile/issues/3467041

**Post a link to your new Backdrop project under your own GitHub account (option 1)**
https://github.com/sjnorton-aa/textile

**(option 2) If you have already contributed code to Backdrop core or contrib projects, please provide 1-3 links to pull requests or commits**

**(option 3) If you do not intend to contribute code, but would like to update documentation, manage issue queues, etc, please tag an existing contrib group member so they can post their recommendation**

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**
YES

**If you have chosen option 3 above, do you agree to undergo this same maintainer application process again, should you decide to contribute code in the future?**

**Comment by jenlampton** [comment]
Hi @sjnorton-aa and thanks for applying to join the contrib group!

> If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)
> YES

Thank you for agreeing :)

A quick review of the three requirements for your project:

- [x] Include a README.md file containing license and maintainer information.
- [ ] Include a LICENSE.txt file.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

There's one very minor issue with the license file, and that's that it's a markdown file and not a text file. GitHub seems to have no issues with this, and I expect people won't either. I'd like to officially clarify if this is allowed for the future, but until then, would you be willing to replace this file with https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt?

**Comment by sjnorton-aa** [comment]
No problem, just uploaded a plain text version. The FSF site offers versions of the text in a number of different formats, and since the README files were in Markdown, I just went ahead and got the md version of the license. It seems very retro to have a pure ASCII file :-) Thanks!

**Comment by jenlampton** [comment]
> It seems very retro to have a pure ASCII file :-) Thanks!

💯  agree! Thank you for making the change anyway: 

- [x] Include a README.md file containing license and maintainer information.
- [x] Include a LICENSE.txt file.
- [x] If porting a Drupal 7 project, Maintain the Git history from Drupal.

Since this project meets all 3 requirements now, **an invitation to join the Backdrop Contrib group is on the way!** Please check your inbox.

Once you have accepted the invitation, feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

**Comment by jenlampton** [comment]
I'm going to close this issue, but feel free to open another if you need any assistance with anything.
