### ISSUE TITLE
Contrib Group Application: Layout Body Class

### ISSUE THREAD

**Issue by catorghans** [backdrop-ops/contrib#822]
Hi,

I created a simple module which does something I wanted to have since my first backdrop project:
Layout Body Class, it simply adds the name of the active layout to the body classes.
https://github.com/catorghans/layout_body_class

Probably can be solved in other ways too, but this is easy to understand for anyone who needs something like this.

It has a Readme and a Licence file. So have a look.

---

**Please indicate how you intend to help the Backdrop community by joining this group**
* Option 1: I would like to contribute a project

**(option 1) The name of your module, theme, or layout**
Layout Body Class

## (option 1) Please note these 3 requirements for new contrib projects:

- [x] Include a README.md file containing license and maintainer information.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md
- [x] Include a LICENSE.txt file.
      You can use this example: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt.
- [x] N/A If porting a Drupal 7 project, Maintain the Git history from Drupal.

**If you have chosen option 2 or 1 above, do you agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)**

**Comment by jenlampton** [comment]
Hi @catorghans  and welcome to backdrop contrib! 

I have verified this project meets the requirements :) 

In order to send you an invite, we need you to agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)

Can you please reply YES or NO?

**Comment by jenlampton** [comment]
I have reviewed the code in your project, and everything looks great! 

I have two small recommendations (that you can choose to ignore if you like)

1) The blank line (line 2) in `layout_body_class.module` can be removed (this was necessary in Drupal back when it used the CVS version control system, and became start of the standard -- not needed here anymore)
2) There should be a blank line as the last line (line 16) in `layout_body_class.module` (This is recommended for Git projects, to prevent unnecessary diffs)

**Comment by catorghans** [comment]
> Hi @catorghans and welcome to backdrop contrib!
> 
> I have verified this project meets the requirements :)
> 
> In order to send you an invite, we need you to agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement)
> 
> Can you please reply YES or NO?

YES

**Comment by catorghans** [comment]
> recommendations

Done

**Comment by jenlampton** [comment]
**An invitation to join the Backdrop Contrib group is on the way!**  🎉 

Once you have accepted the invitation, feel free to [transfer the repository](https://docs.backdropcms.org/documentation/after-your-application-is-accepted) into the backdrop-contrib group at any time (ask here if you have questions).

**Comment by jenlampton** [comment]
I'm going to close this issue, but if you have any questions feel free to re-open it or start a new one.
