### ISSUE TITLE
Access Unpublished ported to Backdrop CMS

### ISSUE THREAD

**Issue by martin-klima** [backdrop-ops/contrib#83]
I have made a port of Access Unpublished module. It is ready for testing by community.
Repository link: https://github.com/martin-klima/access_unpublished

**Comment by quicksketch** [comment]
Hi @martin-klima! Thank you for porting this module!

It would be great if you could transfer it into the official backdrop-contrib group, but we always need to check for a few minor things for consistency with other projects and to help manage things here on GitHub.

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

You've got the hardest part done! We just need to a md files for consistency and to keep track of who's maintaining the project.

Other things I noticed just looking over it, there are still a lot of "drupal_" functions in place. Doing a global find/replace would be a good idea so you could run this module with compatibility mode turned off.

**Comment by martin-klima** [comment]
Thank you for quick review and help.

1) Licence: I used the right file
2) Readme: I updated contents and renamed file
3) Git history: There is whole Git history in branch 1.x-1.x
4) No more "drupal_" functions. Module was tested without backdrop_drupal_compatibility.

**Comment by quicksketch** [comment]
Ah! Sorry I missed the LICENSE.txt file. This looks great! Nice job.

Would you agree to the following for the record so we can give you access to the official contrib group?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by martin-klima** [comment]
Yes, I agree.
Dne 30. 3. 2015 3:17 "Nate Haug" <notifications@github.com> napsal(a):

**Comment by quicksketch** [comment]
Excellent, thanks and welcome! Invite to the group should be in your e-mail.
