### ISSUE TITLE
Port status: email verify

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/contrib#843]
**Name of the module, theme, or layout you are working on**
Email Verify

**Link to the drupal.org module, theme, or layout**
https://www.drupal.org/project/email_verify

**(Optional) Link to the drupal.org issue where you notified the Drupal maintainer(s) of this port**
https://www.drupal.org/project/email_verify/issues/3487649

**Comment by jenlampton** [comment]
I believe the port is complete, this module is now located at https://github.com/backdrop-contrib/email_verify.

**Comment by olafgrabienski** [comment]
@jenlampton I just saw a typo in the title on the [module page](https://github.com/backdrop-contrib/email_verify): **Ea**mil Verify
