### ISSUE TITLE
Application to join: Egmund

### ISSUE THREAD

**Issue by Egmund** [backdrop-ops/contrib#844]
I did not get any response last time - a month or so ago - I tried to join, so - - - 

I have created several layouts for BackdropCMS inspired by and confused by the recipe 'Digital Agency'. One is posted on GitHub: https://github.com/Egmund/BackdropLayouts
StPauliTim suggested I join.

Egmund

**Comment by stpaultim** [comment]
@Egmund Let's close this issue in favor of your earlier application. Sorry that we did not respond sooner.
