### ISSUE TITLE
Problem porting commentsmodule

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/contrib#86]
I have hit a problem trying to port this module to Backdrop. It tries to make use of hook_node_view_alter which is implemented in core/modules/node/node.api.php, but on what I have experienced so far it is as though this function (also hook_node_view) is invisible to Backdrop. 

Is there some way I can do a simple check to satisfy myself that these hooks will work? I cannot find another module that makes use of them and gives me an example to follow. I may well be doing something stupid! Any advice would be appreciated.,

**Comment by quicksketch** [comment]
Hi @Graham-72! `hook_node_view()` and `hook_node_view_alter()` should be unchanged. I'm using them as well in the Project module port, and I know Webform uses them as well. First I'd check if you can get debugging messages just to show up by putting them at the very top of your hook functions. If that doesn't work, I usually start working backwards through the code to where the hooks are invoked (`node_build_content()` and `node_view()` in this case). I can't see any reason why these wouldn't be getting called. Check for typos and clear the cache?

**Comment by Graham-72** [comment]
Thanks @quicksketch for your advice on this. I have managed to resolve the issues and have now put my port of commentsblock at backdrop-contrib/commentsblock

**Comment by quicksketch** [comment]
:+1:
