### ISSUE TITLE
Port of Facebook OAuth (FBOAuth)

### ISSUE THREAD

**Issue by alex-kirienko** [backdrop-ops/contrib#89]
Hi there.

I recently became maintainer of FBOAuth module, thanks to Nate. I want to port it to Backdrop.

**Comment by quicksketch** [comment]
Awesome @alex-kirienko! Welcome! Our process for porting is usually:

- Make start on your port in your personal GitHub account.
- We give it a review to make sure you meet the checklist.
- You access the contrib group agreement.
- We grant you access and you transfer the project to the backdrop-contrib group.

Here's the checklist we review once you've done the initial port:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Thanks and looking forward to working together on Backdrop!

**Comment by klonos** [comment]
Hello @alex-kirienko 👋 ...it's been quite a while without your response here, so I will go ahead and close this one. Please feel free to reopen if you decide to work on this again.
