### ISSUE TITLE
EfqHelper Contrib Module Port

### ISSUE THREAD

**Issue by kerasai** [backdrop-ops/contrib#90]
Hello, I've ported efq_helper to Backdrop. This is a developer tool to make it easier to execute EFQ, and has tools built in to deal with an EFQ's results.

https://github.com/kerasai/efq_helper

I agree to the terms & contained in https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement.

Let me know if anything further is needed.

**Comment by quicksketch** [comment]
Hi @kerasai! Great!

You've done everything we normally require, looks like you've done your homework!

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Even though you've already agreed to the contrib group rules, I'm going to post them again here for posterity:

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by quicksketch** [comment]
An invite has been sent your way! Thanks for porting this module. :smile:

As a final follow-up, it would be great if you could add one line to your .info file:

```
type = module
```

And then tag a release. This will get the project registered on BackdropCMS.org. The project repository listings are coming soon and this will help get ready to increase the visibility of available projects. See https://github.com/backdrop-ops/backdropcms.org/issues/8#issuecomment-93949278.

Thanks and welcome to the Backdrop community. :)

**Comment by kerasai** [comment]
Hi, quick question. Do I need to create a repo in https://github.com/backdrop-contrib and push the code there, or is there an automated process to do this?

**Comment by quicksketch** [comment]
You can transfer the repository directly from the "Settings" tab on the project, it's probably the easiest thing to do. See http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2.
