### ISSUE TITLE
Unable to Push Changes - Write Access

### ISSUE THREAD

**Issue by kerasai** [backdrop-ops/contrib#92]
Hello, I'm not able to push changes to https://github.com/backdrop-contrib/efq_helper. I've pushing directly to that repo and tried forking and creating a PR, but to no avail. Can you check that my account is a proper member of the backdrop-contrib group and that the backdrop-contrib can write to the backdrop-contrib/efq_helper repository?

Thanks.

**Comment by quicksketch** [comment]
Hi @kerasai! Thanks for letting us know about this problem. It appears that the efq_helper module didn't allow access to the "authors" group (of which you are a member). Apparently it's possible when you transfer a repository to not include your own group in the new organization. I fixed this so you should now be able to push. Thanks!
