### ISSUE TITLE
Application to join contrib team - for AutoFloat

### ISSUE THREAD

**Issue by lolandese** [backdrop-ops/contrib#93]
I would like to apply to join the Backdrop contrib team.

My port: https://github.com/lolandese/autofloat
My original module: https://www.drupal.org/project/autofloat (N.B. ported is version 7.x-2.x)

It is a helper module mainly used by sites that have the [Flickr](https://www.drupal.org/project/flickr) Filter module enabled (not completely ported yet).

- It has been tested and resulted working as expected.
- Also with the compatibility mode turned off.
- I agree to the [Backdrop Contributed Project Agreement](https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement).
- A Drupal to Backdrop update hook has been provided.

I would appreciate if you could have a look to find any issues. Test with a node body consisting of some text with some images inside.

Thanks in advance.

**Comment by quicksketch** [comment]
Awesome! Great job!

- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

For the record, here's the current agreement as being agreed-to.

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by quicksketch** [comment]
Invite is on the way! Remember when you transfer the project to make sure the "Authors" group is allowed access.

This looks like a great port (you even added the almost brand-new `type = module` to the .info file. Nice job! I'm excited to work with you on making Backdrop. Cheers!

p.s. The only thing I found was you might drop the README.txt file.
