### ISSUE TITLE
Request to join the Backdrop contributor community.

### ISSUE THREAD

**Issue by spot-the-cat** [backdrop-ops/contrib#94]
HI Folks -

I was interested in joining the growing Backdrop contributor community.

As an exercise while testing Backdrop I ported the Drupal contrib module fences, (not mine).

I've let the folks on Drupal know and was going to wait a few days before proceeding.

The ported version is currently located: https://github.com/spot-the-cat/fences

Have Fun - Bill

**Comment by quicksketch** [comment]
Hi @spot-the-cat! Welcome! We're really excited to have your help expanding the functionality of Backdrop! This port looks great! You did all the main items, including our checklist for new projects:


- [x] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [x] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [x] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Just doing a cursory review, I found a few small issues. In https://github.com/spot-the-cat/fences/blob/1.1.1/config/fences.settings.json#L4, the JSON is not properly formatted (missing a comma on line 3 and the comma on line 4 is not valid).

For efficiency, I'd also recommend putting 
```
"_config_static": true,
```

after `_config_name`. That will make it so Backdrop isn't reading that file from disk every time you call config_get() (by default there's no caching).

It's looking great though! If you would agree to the following for the record, we'll get your access to the group set up. Thanks!

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by spot-the-cat** [comment]
Hi @quicksketch -

I officially agree to the Backdrop Contributed Project Agreement.

I'll fix those issues in the config file, (I'm an idiot, I sorted alphabetically and didn't edit the commas).

Thanks for the help.

Have Fun - Bill

**Comment by quicksketch** [comment]
Great! Invitation sent.
