### ISSUE TITLE
Request to join backdrop contrib

### ISSUE THREAD

**Issue by btopro** [backdrop-ops/contrib#96]
I posted this PR to add support for a Vagrant instance for Backdrop
https://github.com/backdrop/backdrop-issues/issues/971

It was suggested I add this to contrib instead (which makes sense) hence this issue here.  I've got close to 100 d.o. D7 modules, many of which I'm probably game for porting since the one that I ported recently was pretty easy.

**Comment by quicksketch** [comment]
Hi @btopro! Excellent, thanks for posting a request here. This request is a little different than most, as it's not a port of an existing project but a new stand-alone thing. Normally, we do a small review of new projects to make sure they meet our basic requirements:

- [ ] Include a LICENSE.txt file that indicates the code is GPL v2. You can use [this copy](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/LICENSE.txt).
- [ ] Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).
- [ ] Maintain the Git history from Drupal 7. See [this article](http://tag1consulting.com/blog/how-maintain-contrib-modules-drupal-and-backdrop-same-time-part-2).

Could you put your work in your personal repository and include the first two items here? If maintaining history from D7 also applies, then it'd be great to get that done also, but as I understand it, this work has not been in a public repository in the past. Once we get the checklist knocked off, I'll grant you access and you can transfer the repository to the backdrop-contrib group.

**Comment by btopro** [comment]
https://github.com/btopro/backdrop-vagrant

**Comment by quicksketch** [comment]
Hah, we need a bit more (https://github.com/btopro/backdrop-vagrant/blob/482359fee3c8b6a8f318683c3c20e4414e77c397/README.md)! Because group access gives you permission to commit to *any* project, we keep track of which people *should* be allowed to commit to specific projects by listing them in the README.md file. Could you copy/paste and fill in the details from https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md?

**Comment by btopro** [comment]
It's in the 1.x branch -- https://github.com/btopro/backdrop-vagrant/blob/1.x/README.md or is the convention to work from master?

**Comment by quicksketch** [comment]
Doh! I didn't see that! Maybe you could delete the master branch if it's not being used.

Normally, Backdrop projects are versioned exactly like Drupal, e.g. `1.x-1.x` (Backdrop 1.x and version 1.x of the module). But as your project may not need to include the major version number, I don't think that's necessary in your case.

This looks great. Would you agree to the following for the record?

---

Backdrop Contributed Project Agreement
--------------------------------------

By joining the [Backdrop Contributed Project Group](https://github.com/backdrop-contrib) (Backdrop Contrib, for short) you agree to the following:

1. You will not push changes to a repository for which you are not a current maintainer (even though joining the Backdrop Contrib group will grant you access to push to any project within).

1. You must agree to license your code contributions as GPLv2 or later.

1. Any project you create or maintain must include a copy of the [GPL v2 `LICENSE.txt` file](https://github.com/backdrop-ops/contrib/blob/master/examples/LICENSE.txt) in the root of your repository. The GPLv2 license applies to all code that directly interacts with parts of Backdrop licensed as GPLv2 or later.  See for the [Backdrop License FAQ](https://backdropcms.org/license) for a more detailed explanation.

1. You must confirm that you have the right to distribute any additional code, libraries, images, fonts or other assets written or created by any third party with code licensed as GPLv2 or later.

1. Any project you create or maintain must include a `README.md` file containing at the least the following:
  1. A description of the project
  1. Basic documentation
  1. License information for the project (GPL v2)
  1. License information for any additional assets (SIL OFL fonts, CC-SA images, etc)
  1. A list of the current maintainers for the Backdrop project
  1. Credits acknowledging past maintainers for the Backdrop or Drupal projects

  You may use this [example README.md](https://github.com/backdrop-ops/contrib/blob/master/examples/README.md) to get started.

1. You will work with the Backdrop Security Team to address any vulnerabilities in any project you create or maintain, if necessary.

1. Any project you create or maintain will have the GitHub issue tracker enabled for official communication.

1. If any of the above requirements are not met, your access to the Backdrop Contrib group -- including all projects and even those that you may have originally authored -- may be revoked.

1. If your project becomes abandoned and you do not respond to requests in the issue tracker within 2 weeks, your project may be modified by a Backdrop Contrib administrator without your explicit consent.

**Comment by btopro** [comment]
Yes I agree to the above. is there an easy way to delete master branch tags on github? It's rejected me issuing that in the past once the branch was there.

**Comment by quicksketch** [comment]
Yeah, you have to set a different branch as the default under the settings of the repository. Then you'll be able to delete the remote master branch like you would any other `git push origin :master`.

I've sent an invite your way. Thanks so much for your contribution and I'm looking forward to working together!!
